### ISSUE TITLE
Comparing broken lnk-files (windows shortcuts) freezes WinMerge

### ISSUE THREAD

**Issue by JP95Git** [WinMerge/winmerge#1007]
I compared 2 folders and noticed that WinMerge freezes, if it compares 2 invalid lnk-files (windows shortcuts). Both (equal) shortcuts points to a network-share which is no longer available.

This is not a problem in windows, since fc (in cmd) can compare these files.

It happens if you compare a folder with these files and if you compare only both lnk-files.

Version: 2.16.14 (x64) with Windows 10.

**Comment by sdottaka** [comment]
Thank you for the information. I think I misunderstood the reproduction conditions. Now I am able to reproduce the problem. I don't know if it's possible to fix the problem of the message box being hidden behind at the moment.

This problem can be prevented by selecting the "Manual Unpacking" menu item in the Plugin menu.

![image](https://user-images.githubusercontent.com/98126/137145163-06f6f7f9-1e20-42e6-a05e-f40e6a5252ae.png)
![image](https://user-images.githubusercontent.com/98126/137145416-92488682-62c5-4f4d-a002-6fd4dcc89404.png)
