### ISSUE TITLE
Vertical shifting needed when some lines do not match

### ISSUE THREAD

**Issue by san-r** [WinMerge/winmerge#1013]
Suppose file1 is:
```
                      NAME        DOB     ID    PIN
               B ANNAPURNA 12-12-1962 502877 500084
               B ANNAPURNA 12-12-1962 502878 500084
                B V RAMANA 15-01-1960 502902 500032
                B V RAMANA 15-01-1960 502910 500033
              DARBAR ASHOK 03-01-1950 502548 500084
              DARBAR ASHOK 03-01-1950 502639 500032
           KOTLA CHENNAMMA 15-07-1958 502466 500032
           KOTLA CHENNAMMA 15-07-1958 502467 500032
           MARIAM SUDHAKAR 24-01-1954 502047 500032
           MARIAM SUDHAKAR 24-01-1954 502475 500032
   VELPURI LAKSHMI SUJATHA 28-06-1971 502251 500032
   VELPURI LAKSHMI SUJATHA 28-06-1971 502267 500084
VENKATESHWARAN PONNAMBALAM 14-04-1969 502272 500032
VENKATESHWARAN PONNAMBALAM 14-04-1969 502290 500032
```
and file2 is:
```
                       NAME          DOB       ID      PIN
 --------------------------   ----------   ------   ------
                B ANNAPURNA   12-12-1962   502877   500084
                B ANNAPURNA   12-12-1962   502878   500084
                 B V RAMANA   15-01-1960   502902   500032
                 B V RAMANA   15-01-1960   502910   500033
               DARBAR ASHOK   03-01-1950   502548   500084
               DARBAR ASHOK   03-01-1950   502639   500032
                  K KRISHNA   01-05-1964   502737   500050
            KOTLA CHENNAMMA   15-07-1958   502466   500032
            KOTLA CHENNAMMA   15-07-1958   502467   500032
            MARIAM SUDHAKAR   24-01-1954   502047   500032
            MARIAM SUDHAKAR   24-01-1954   502475   500032
    VELPURI LAKSHMI SUJATHA   28-06-1971   502251   500032
    VELPURI LAKSHMI SUJATHA   28-06-1971   502267   500084
 VENKATESHWARAN PONNAMBALAM   14-04-1969   502272   500032
 VENKATESHWARAN PONNAMBALAM   14-04-1969   502290   500032
```
Then WinMerge compares them as:
![image](https://user-images.githubusercontent.com/45727825/137583490-3b306527-11b9-4853-9d36-4b849d281b29.png)

Whereas Notepad++ with Compare plugin shows them as:
![image](https://user-images.githubusercontent.com/45727825/137583526-7718ffbc-8304-4bf4-851d-4a8eba7a2401.png)

which is a much better view. Please modify.

**Comment by san-r** [comment]
Ignoring whitespaces gave me exactly what I wanted. Thanks.

![image](https://user-images.githubusercontent.com/45727825/137618586-356f75a7-657a-45fc-a210-20d5a8f203bf.png)

I think this should be the default behavior.

**Comment by sdottaka** [comment]
The fix in commit 4ddcac2 6da30cd 98cc2c2 gives similar results to the Notepad++ compare plugin when the 'Match similar lines' option is enabled.

**Comment by Gitoffthelawn** [comment]
> WinMerge has an option "Match similar lines" that does this kind of vertical adjustment. Unfortunately, if there are more than 15 lines in a diff block, the option is ignored for performance reasons, so it will not work for files in this issue.

Would it be reasonable to expose that value (15 by default) so the user can tweak it to match their preferred performance/functionality tradeoff?

**Comment by sdottaka** [comment]
The current implementation has changed to a 4096 character limit instead of a 15 line limit.
I'm not thinking about being able to change this limit so far. Pull Requests are welcome.

**Comment by Gitoffthelawn** [comment]
> The current implementation has changed to a 4096 character limit instead of a 15 line limit. I'm not thinking about being able to change this limit so far. Pull Requests are welcome.

Is there anything besides the hardcoded value creating that limit?

**Comment by sdottaka** [comment]
I think I can make this limitation larger by running the "Match similar lines" function in a background thread for areas that are not yet visible, but it is not easy.

**Comment by Gitoffthelawn** [comment]
> I think I can make this limitation larger by running the "Match similar lines" function in a background thread for areas that are not yet visible, but it is not easy.

That sounds like a great idea... whenever you have time.

I think, overall, WinMerge is great.  With a touch of irony, I feel the one area it could use improvement is in comparison quality.  Of course, that's WinMerge's primary task, but also the most difficult because, ideally, it would use AI to generate the comparison... and that's *a lot* of work to implement at a level to get consistently good results (but would be a fun challenge!).
