### ISSUE TITLE
Release 2.16.16 crashes when comparing large files - likely a regression

### ISSUE THREAD

**Issue by Gitoffthelawn** [WinMerge/winmerge#1036]
When comparing 2 200MB files, WinMerge 2.16.16 x64 crashes every time.  The new message box appears asking if only the contents should be compared without the differences displayed.  If I select "Yes", WinMerge immediately crashes with this error (Win7 x64):

```
Problem signature:
  Problem Event Name: APPCRASH
  Application Name: WinMergeU.exe
  Application Version: 2.16.16.0
  Application Timestamp: 61795870
  Fault Module Name: WinMergeU.exe
  Fault Module Version: 2.16.16.0
  Fault Module Timestamp: 61795870
  Exception Code: c0000005
  Exception Offset: 00000000000bc690
```

Ironically, if I answer "No" to the message box asking to show differences, WinMerge does not crash.  But it takes so long to compare the files that WinMerge becomes nonresponsive for several minutes.  With the answer of "No", eventually WinMerge will come back to life and tell me the files are identical.

I think this is likely a regression because I don't think I've ever had WinMerge crash in this situation.

I found #325, but I think this is actually a different issue.

**Comment by sdottaka** [comment]
This crash has been fixed with commit 205fa6d.

Thank you for the report.

**Comment by Gitoffthelawn** [comment]
> This crash has been fixed with commit [205fa6d](https://github.com/WinMerge/winmerge/commit/205fa6dc16a035ecb452b9e812cf453882b8743f).
> 
> Thank you for the report.

You're welcome, and wow! Thank you for the quick fix!

I know it will just be a guesstimate, but do you have an idea when v2.16.17 will be released?

**Comment by sdottaka** [comment]
It is scheduled for mid-December, but it may be delayed.

You can always download the latest binaries from the URL below. 

https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts

**Comment by Gitoffthelawn** [comment]
> It is scheduled for mid-December, but it may be delayed.
> 
> You can always download the latest binaries from the URL below.
> 
> https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts

Thanks.  Is there any good way to know when nightlies are likely to be relatively stable vs have a serious regression?  Given that WinMerge is used for important tasks, it would be hazardous to use a nightly that might not generate accurate results.

I suppose one idea would be to release alphas or betas that are believed to be stable but just don't have sufficient testing to release to the masses.

**Comment by sdottaka** [comment]
Unfortunately, there is no way to do that.
Basically, we try to keep the master branch clean by doing relatively major development on a separate branch.
The URL I showed earlier is a build of the master branch.

It may be unstable when we finish a relatively large development and merge it into the master branch.

**Comment by Gitoffthelawn** [comment]
> Unfortunately, there is no way to do that. Basically, we try to keep the master branch clean by doing relatively major development on a separate branch. The URL I showed earlier is a build of the master branch.
> 
> It may be unstable when we finish a relatively large development and merge it into the master branch.

Thanks.  Glad I wasn't missing anything in my understanding.  Also good to learn that the link you shared is for master branch builds.  I look forward to the new version whenever it happens.  Personally, I prefer more frequent releases when crashes are fixed, but you're the boss. :)

**Comment by AFract** [comment]
Hello, 
I was about to report the same crash (happening while attempt to compare two 90MB .SQL files), and I found this ticket.
So I have just tried with build WinMerge-2.16.17-a4f4ccb8c-x64-Setup.exe and it seems to fix the issue. 
The file is quite fast (regarding its size) to open.
Thank you for your great work !
