### ISSUE TITLE
Moving the caret (left/right, up/down) without pressing the Alt-key not possible

### ISSUE THREAD

**Issue by baka0815** [WinMerge/winmerge#1037]
When I press the left or right arrow key without the Alt-key the content is still copied over from one side to the other (instead of just moving the caret in the current line).
The hint says the key would be Alt+left/right.
![grafik](https://user-images.githubusercontent.com/15894566/139861546-78021fd4-4977-47eb-8b63-959b43a27561.png)

It's the same with the up and down arrow keys which are not just moving the caret a line up/down but jump straight to the next/previous difference which should only be the case when I press the Alt key.

**Comment by sdottaka** [comment]
Merge Mode is enabled.
Please see below to disable Merge Mode.

https://github.com/WinMerge/winmerge/issues/787#issuecomment-841217012

**Comment by baka0815** [comment]
That was the issue. Thanks for the fast answer!
