### ISSUE TITLE
"Automatically expand all subfolders" not working in v2.16.16

### ISSUE THREAD

**Issue by Gitoffthelawn** [WinMerge/winmerge#1041]
I have "Automatically expand all subfolders" selected in the settings UI of v2.16.16, but when comparing folders, none of the subfolders are expanded. :(

Also, is there a keyboard shortcut, like in many applications, to expand all subfolders?  Most applications use the asterisk (*) to expand all, and some use forward-slash (/) to reverse the operation.  If there are no keyboard shortcuts for these functions, could they be added?

**Comment by sdottaka** [comment]
I have not been able to reproduce this problem.
Do you have the 'Include subfolders' option or 'Tree mode' disabled?

![image](https://user-images.githubusercontent.com/98126/140750763-efd6a2db-4767-43c3-aea5-775a99bfab62.png)
![image](https://user-images.githubusercontent.com/98126/140750654-d504520e-71cb-4a01-8f18-92c1cc19af78.png)

**Comment by Gitoffthelawn** [comment]
> Do you have the 'Include subfolders' option or 'Tree mode' disabled?

I have 'Include subfolders' enabled, but 'Tree mode' is dimmed.  I'm thinking that is the problem, but why is it dimmed?

**Comment by sdottaka** [comment]
I tried reinstalling version 2.16.16, but Tree mode was still enabled.

If you know how to reproduce this, please let me know.

**Comment by Gitoffthelawn** [comment]
> I tried reinstalling version 2.16.16, but Tree mode was still enabled.
> 
> If you know how to reproduce this, please let me know.

Hmmm... is there another setting that could cause it to be dimmed?

I'm using the portable version, could that be the issue?

FYI, I use binary compare when comparing folders.

**Comment by Gitoffthelawn** [comment]
@sdottaka I'm not at a Windows box right now, but I am thinking about this issue... I always compare folders using the command line.  Could that have an impact?

**Comment by Gitoffthelawn** [comment]
Oh sheesh... `/r`.  Sorry for wasting your time.  Closing.
