### ISSUE TITLE
The current pane switches without me asking it to.

### ISSUE THREAD

**Issue by Arthanzar** [WinMerge/winmerge#1050]
Steps to re-produce: 
1. Start with the left pane having focus. 
2. Update a file outside of Wm. This file is shown in the r.h. pane in Wm. 
3. Switch back to Wm, and the r.h. pane now has focus. 
Very annoying, I didn't ask for that, and I can't find an option to revert the behaviour.

**Comment by sdottaka** [comment]
This issue has been fixed by commit d165aa7.

Thank you for reporting this.

**Comment by Arthanzar** [comment]
Awesome, thank you.
