### ISSUE TITLE
Issue with closing WinMerge with Esc keyboard key

### ISSUE THREAD

**Issue by Gitoffthelawn** [WinMerge/winmerge#1052]
I believe I may have stumbled on a little issue with v2.16.16.0:

Since it was made available, I've always used the WinMerge setting:
`Options > General > Close windows with Esc > MDI child window or main window`
to allow closing WinMerge with a single click of the `Esc` keyboard key.

Recently, I started using the `/r` command line option when calling WinMerge from another application (let's call that `App A`).

Without making other changes, I noticed that when calling WinMerge from a *different* application (let's call it `App B`), the `Esc` key no longer exits WinMerge (even though I have not changed the WinMerge settings, and the Settings page still indicates `MDI child window or main window`).

I had to add the following command line parameters to the WinMerge call from `App B` as a workaround to this issue: `/e /x`

**Comment by sdottaka** [comment]
First, the setting "Options > General > Close windows with Esc > MDI child window or main window" allows WinMerge to be closed with the Esc key. However, WinMerge can only be closed with the Esc key if there is no MDI child window, such as a file comparison window or folder comparison window.

If a file or folder comparison window is displayed, WinMerge will not close with a single click of the Esc key. Under these conditions, you will need to press the Esc key at least twice to close WinMerge.

Is your problem that WinMerge no longer closes with a single click of the Esc key? Or is it that WinMerge no longer closes no matter how many times you press the Esc key?

**Comment by Gitoffthelawn** [comment]
> 
> 
> First, the setting "Options > General > Close windows with Esc > MDI child window or main window" allows WinMerge to be closed with the Esc key. However, WinMerge can only be closed with the Esc key if there is no MDI child window, such as a file comparison window or folder comparison window.

Hmmm... for years I've been able to close WinMerge with a single click of the `Esc` key when I'm just comparing 2 files (which is ~95% of the time).
 
> If a file or folder comparison window is displayed, WinMerge will not close with a single click of the Esc key. Under these conditions, you will need to press the Esc key at least twice to close WinMerge.

I seem to recall having to do that a long, long time ago, but I happily haven't had to do that in years.

> Is your problem that WinMerge no longer closes with a single click of the Esc key? Or is it that WinMerge no longer closes no matter how many times you press the Esc key?

The former.

**Comment by sdottaka** [comment]
>>    Is your problem that WinMerge no longer closes with a single click of the Esc key? Or is it that WinMerge no longer closes no matter how many times you press the Esc key?

> The former.

If /e is not specified as a command line option, then it is correct behavior that WinMerge will not close after a single Esc key press.

Various crash bugs have been fixed in WinMerge 2.16.16.
It may be that WinMerge used to crash on a single Esc keystroke in previous versions. This may have caused WinMerge to appear to exit with a single Esc keystroke.

It might be better to allow the option dialog to specify settings equivalent to the /e command line options.

**Comment by Gitoffthelawn** [comment]
> Various crash bugs have been fixed in WinMerge 2.16.16. It may be that WinMerge used to crash on a single Esc keystroke in previous versions. This may have caused WinMerge to appear to exit with a single Esc keystroke.

Certainly a possibility. Thanks.

> It might be better to allow the option dialog to specify settings equivalent to the /e command line options.

I think that's an excellent idea.

**Comment by sdottaka** [comment]
in commit 88e8c07, I've added a new option that behaves the same as the /e command line option.

![image](https://user-images.githubusercontent.com/98126/143768783-ff9fd417-002f-4cc0-9840-3e4e7283bf8c.png)

**Comment by Gitoffthelawn** [comment]
@sdottaka Wonderful! Thank you!
