### ISSUE TITLE
Suboptimal diff

### ISSUE THREAD

**Issue by mbtools** [WinMerge/winmerge#1053]
If the end of an inserted block matches the end of the block preceding the insert, then the diff is "not quite right". While technically ok, it simply does not match what was changed.

![WinMergeU_579](https://user-images.githubusercontent.com/59966492/142479179-9f67844d-653a-4c0e-81e9-468cf94aa462.png)

[original.txt](https://github.com/WinMerge/winmerge/files/7565343/original.txt)
[after_change.txt](https://github.com/WinMerge/winmerge/files/7565344/after_change.txt)

For comparison, here's the example as seen by VSCode, GitHub, and other diff tools:

![image](https://user-images.githubusercontent.com/59966492/142479275-ca6a86a0-d320-4fe9-8d86-e4c6a3212c5b.png)

https://github.com/mbtools/TEST-SAP-Diff/commit/5faacd42e41f2e53f65a0b503e4a4fac0f950dbf#

https://editor.mergely.com/ohTSI2tK/

GNU diff3 output:

```
> diff3 original.txt original.txt after_change.txt
====3
1:6a
2:6a
3:7c
      METHODS test_3.
====3
1:21a
2:21a
3:23,31c


    METHOD test_3.
      "method 3
      IF 1 = 2.
        BREAK-POINT.
      ENDIF.
    ENDMETHOD.

```

WinMerge is a bit off here.

**Comment by sdottaka** [comment]
In the "Options" dialog, set the "Compare/General" category → "Diff Algorithm" to something other than "Default" to get the expected results.

![image](https://user-images.githubusercontent.com/98126/142505707-7d06ed57-a3d2-40a7-b928-72dc8243db84.png)

**Comment by mbtools** [comment]
Thanks!
