### ISSUE TITLE
Could you please compile arm32 binaries for unlocked Windows 8.1 and 8.0 arm32 RT?

### ISSUE THREAD

**Issue by easyentry** [WinMerge/winmerge#1076]
Hello,
I am very glad, that you did compile arm64 bins. They work great under both W10 arm64 and W11 arm64.
But arm64 bins don't work on unlocked arm32 MS OSes like my Windows 8.1 and 8.0 arm32 (RT).
Could you please compile arm32 bins too?
Thanks.
It would be worth for the nice donation. :P

**Comment by sdottaka** [comment]
I'm attaching the binary I built for ARM here.
I don't have an ARM32 PC, so I haven't been able to check if it works properly.

[winmerge-2.16.16-f75947e86-ARM-exe.zip](https://github.com/WinMerge/winmerge/files/7696400/winmerge-2.16.16-f75947e86-ARM-exe.zip)

**Comment by easyentry** [comment]
After a testing in arm32 OS there were no problems detected. Please note that ARM32 bins can be also tested on W11 and W10 arm64 OSes, as those have full ARM32 WOW.
![WinMerge](https://user-images.githubusercontent.com/56564697/145674220-0685fd6a-7fcf-4683-98b5-071c0d4c0940.jpg)
Please include ARM32 platform at download page also for the future releases: https://winmerge.org/downloads/?lang=en
Donation of 10 USD was made:
![PayPal](https://user-images.githubusercontent.com/56564697/145674341-3d9a3bb5-b9da-448e-bf2a-2d81917c647b.jpg)
Thanks.

**Comment by sdottaka** [comment]
Thank you for the donation.
There are no plans to put the ARM32 binaries on the winmerge.org download page at this time, as there is probably almost no demand for them and they are still incomplete in terms of plugins.
However, if I haven't forgotten, I may upload it to https://sourceforge.net/projects/winmerge/files/ in a future release.

**Comment by easyentry** [comment]
Hello Takashi,

Thanks again for your arm32 port. It works well.
Could you please compile also WinMergeContentMenu.dll file as arm32 and also x32? In ShellExtension-1.18.7.0.zip there are only arm64 and x64 versions. Thanks.

Saturday, December 11, 2021, 2:19:59 PM, you wrote:

Thank you for the donation.There are no plans to put the ARM32 binaries on the winmerge.org download page at this time, as there is probably almost no demand for them and they are still incomplete in terms of plugins.However, if I haven't forgotten, I may upload it to https://sourceforge.net/projects/winmerge/files/ in a future release.
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. 


-- Best regards,Milan Benes

**Comment by sdottaka** [comment]
The WinMergeContentMenu.dll is a shell extension for Windows 11. Since there is no 32-bit version for Windows 11, building it for x86 or ARM32 would be of no use. (I tried launching the 32-bit version of Explorer on Windows11, but WinMergeContextMenu.dll runs as a separate process from Explorer.exe, so the 64-bit version of WinMergeContextMenu.dll was used instead.)
