### ISSUE TITLE
wm 2.16.16.0 crashes with file attached

### ISSUE THREAD

**Issue by seejayr** [WinMerge/winmerge#1101]
hi there.

i've got two file[s] which crashing wm when i trying to execute two files comparsion (with doubleclick) from folder comparsion tab,

and there's the same behavior on latest 2.16.16.0 x64 and unknown older 32-bit version (i've killed it with upgrade). guess it's not necessesary to specify version numbers etc when my bad file[s] are available.

now i've find which file is 'bad' for wm. it's 'left' file in archive. when i drag it alone in wm window and pressing 'compare', nothing happens, and wm still working. but if i drag any other file the comparsion window appears at least. and when i drag two files into window, then nothing happens too.

have a nice [anything]. and thanks for awesome tool, i luv it so ohh.

p.s. and maybe you like the song attached. :-)

[winmerge_crashes_on_it.zip](https://github.com/WinMerge/winmerge/files/7765494/winmerge_crashes_on_it.zip)

**Comment by sdottaka** [comment]
Thank you for the report!

This issue has been fixed in commit ab42398f7da66276dedd8cc9cf3910674de6dbe2.

The latest binaries can be downloaded from

https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts
