### ISSUE TITLE
Enable advanced menu for windows 11

### ISSUE THREAD

**Issue by phoxtail** [WinMerge/winmerge#1107]
Issue version: 2.16.16.0 X64
No advanced menu when 'enable advanced menu' option is checked
![advanced menu 2](https://user-images.githubusercontent.com/564951/147799707-1e30fa1f-3e2f-4be5-8e48-3e92424e2bd3.png)
![advanced menu 1](https://user-images.githubusercontent.com/564951/147799709-ba085244-9f94-4c2e-96c4-4183110e8316.png)

**Comment by sdottaka** [comment]
The Advanced menu is enabled in 2.16.17 beta. 

https://github.com/WinMerge/winmerge/releases/tag/v2.16.17
