### ISSUE TITLE
Updated Translations\WinMerge\ChineseSimplified.po in 

### ISSUE THREAD

**Issue by CharlesMengCA** [WinMerge/winmerge#1109]
Hi,

I have updated the ChineseSimplified.po. Please merge if the file is OK.

Thanks,

[ChineseSimplified.zip](https://github.com/WinMerge/winmerge/files/7795540/ChineseSimplified.zip)

**Comment by sdottaka** [comment]
Merged at 0add01e Thank you!

**Comment by CharlesMengCA** [comment]
Here is a updated version after reviewing the merge.

Better wording and consistency.

Thanks a lot,

[ChineseSimplified.zip](https://github.com/WinMerge/winmerge/files/7796525/ChineseSimplified.zip)
.

**Comment by sdottaka** [comment]
Would you please create a Pull Request?
You'll probably see a "Compare & pull request" button at https://github.com/winmerge/winmerge that you can press to create a Pull Request.

https://archaeogeek.github.io/gettingstartedwithgit/github/pullrequest.html#submitting-pull-request-on-github
