### ISSUE TITLE
Winmerge hangs when i try to compare files.

### ISSUE THREAD

**Issue by kotenok2000** [WinMerge/winmerge#1111]
Winmerge hangs when i try to compare files.
version 2.16.16 x64
Microsoft Windows [Version 10.0.22000.376]
i attached the  files in zip archive
[compare files.zip](https://github.com/WinMerge/winmerge/files/7797191/compare.files.zip)

**Comment by sdottaka** [comment]
Thank you for your report.
I was able to reproduce this issue by enabling the View> Wrap Lines menu item.

**Comment by sdottaka** [comment]
It's so slow that it looks like it's hung.

Commit 4004541 improves this problem a bit.
