### ISSUE TITLE
Colors -> Differences -> Word Difference : Text color ignored

### ISSUE THREAD

**Issue by robert-andrzejuk** [WinMerge/winmerge#1116]
When in options :
- Editor -> General -> Line Difference Coloring -> "View line differences" and "Word-level" are set,
- Colors -> Differences -> "Word Difference" and "Selected Word diff" :  Text color is ENABLED and set to some unexpected color
- Colors -> Differences -> All options from "Difference" to "Same as the Next (Selected)" : Text color is DISABLED

Then: 
- Colors -> Differences -> Word Difference : Text color is not used in a difference.

Diff to test:
1) unsigned char * f(unsigned char *) PROC                             ; f, COMDAT
2) unsigned char * g(unsigned char *) PROC                             ; g, COMDAT

Expected result:
The text color of `f` and `g` should have the "unexpected" color from the settings above.

**Comment by sdottaka** [comment]
I could not reproduce this problem.
What version of WinMerge are you using?
Are there any other conditions under which you can reproduce this problem?

![image](https://user-images.githubusercontent.com/98126/148307585-4fa80738-2917-4802-9ff7-bc712fa9fc41.png)
![image](https://user-images.githubusercontent.com/98126/148307624-85627005-e909-49a4-95bd-2d050724d4dd.png)

**Comment by robert-andrzejuk** [comment]
You have incorrectly set:
- Colors -> Differences -> All options from "Difference" to "Same as the Next (Selected)" : Text color is DISABLED

**Comment by sdottaka** [comment]
Sorry, I missed the part about 'All options from "Difference" to'.
I've been able to reproduce this issue and fixed it in commit 408ab0f .
Thank you for the report.

![image](https://user-images.githubusercontent.com/98126/148384585-3009a9ea-fa80-441f-acc3-e371c860ae19.png)
