### ISSUE TITLE
Incorrect link to "Quick Start" guide at WM installation end

### ISSUE THREAD

**Issue by grajewski** [WinMerge/winmerge#1127]
After installing WinMerge for the first time, the link to the web-based Quick Start guide is incorrect.

The installer points to:
 https://manual.winmerge.org/en/QuickStart.html

when it should be:
 https://manual.winmerge.org/en/Quick_start.html

**Comment by sdottaka** [comment]
Fixed in d31d6fe
Thank you for the report.
