### ISSUE TITLE
Trojan.Malware.300983.susgen identified by VirusTotal in winmerge-2.16.16-exe.zip from the website

### ISSUE THREAD

**Issue by eladkarako** [WinMerge/winmerge#1132]
<details><summary>previously discussed</summary>

###Discussed in https://github.com/WinMerge/winmerge/discussions/973

<div type='discussions-op-text'>

<sup>Originally posted by **incircolo** September 14, 2021</sup>
Hi
Virustotal has detected malware " MaxSecure - Trojan.Malware.300983.susgen " in your winmerge-2.16.14-x64-exe.zip
Is it a false positive from this AV vendor? 
</div>

</details>

<hr/>

https://www.virustotal.com/gui/file/bdcee04511eda4a8cb356336171354c34cac4dc402177d8bcf51ed5c39d1a8e5  

<img width="880" alt="2022-01-15_043026" src="https://user-images.githubusercontent.com/415238/149605738-0cb9831d-315a-49e6-8906-c59ac08b26fd.png">  

https://www.virustotal.com/gui/file/bdcee04511eda4a8cb356336171354c34cac4dc402177d8bcf51ed5c39d1a8e5/relations  

<img width="732" alt="2022-01-15_043239" src="https://user-images.githubusercontent.com/415238/149605742-12dd738e-7550-4df4-b55e-048dbf095e4f.png">  

<hr/>

it is weird since the binaries downloaded by me from each of the repositories:  

https://github.com/stedolan/jq/releases/latest  

https://github.com/htacg/tidy-html5/releases/latest  

https://github.com/harelba/q/releases/latest  

does not trigger VirusTotal.

have you been re-compiling stuff? or maybe your server got hacked?

Ps. 
https://github.com/WinMerge/winmerge/discussions/973 hasn't been closed.

**Comment by sdottaka** [comment]
> have you been re-compiling stuff? or maybe your server got hacked?

These files are not recompiled. jq and tidy-html5 are downloaded from the following URL.


https://github.com/htacg/tidy-html5/releases/download/5.4.0/tidy-5.4.0-w32-mt-XP.zip
https://github.com/stedolan/jq/releases/download/jq-1.4/jq-win32.exe

I just submitted a False Positive report at the following URL

https://www.maxsecureantivirus.com/submit_aFalse_Positive.htm

**Comment by eladkarako** [comment]
Ps. my norton also gone bezerk on them. but not the ones that I recently got from GitHub. can't even add screenshot - it purged them so violently you would think it was a Mexican food :|

**Comment by sdottaka** [comment]
Currently, False Positives are gone.

https://www.virustotal.com/gui/file/02072cff71079b7b3122b887d5083bf2cf6b173de066aa5044acf1762f845ef6/detection/f-02072cff71079b7b3122b887d5083bf2cf6b173de066aa5044acf1762f845ef6-1642578796
https://www.virustotal.com/gui/file/9e803a5a2c11fd3e2b63b3616d0da071b456b5759ad7f5b9b9ea1b84ca9c5e70/detection/f-9e803a5a2c11fd3e2b63b3616d0da071b456b5759ad7f5b9b9ea1b84ca9c5e70-1642593544
