### ISSUE TITLE
 failed to do a comparison of .zip or .tar.gz files.

### ISSUE THREAD

**Issue by 9demaio1964** [WinMerge/winmerge#1135]
I failed to do a comparison of .zip or .tar.gz files.
I encountered this issue with WinMerege 2.16.14.0 and 2.16.16.0.

Error
%1!s!7z.dll:
The specified module cannot be found.
![Error_dialogobox](https://user-images.githubusercontent.com/6443194/149652178-40ba266d-22ec-47a9-9dcd-9f2ee7174bf8.png)

I got Alert dialog box with an alert saying
Both the context menu and File -> Open will result in the same situation.

Case 1: .zip files
Press OK, then the same box appears again and again.
6 times repeats after, The following main window was opened.
![window](https://user-images.githubusercontent.com/6443194/149652187-7df022a4-b0a1-4099-9045-64fb3e337530.png)

Case 2: .tar.gz files
Press OK, then the same box appears again and again.
I gave up after 30 times tries, and killed WinMerge from the Task Manager.

Case 3: another binary files (e.g. .exe files)
No problem.

I searched for 7z.dll in my My Computer

"C:\\Users\shige\AppData\Local\Programs\WinMerge\Merge7z\7z.dll" <-- v19.0.0.0
"C:\Program Files\7-Zip\7z.dll" <-- v21.7.0.0
"C:\Program Files\Trend Micro\AMSP\update\iAU_SDK_Backup\iaucore\7z.dll" <-- v18.5.0.0
"C:\Program Files\Trend Micro\AMSP\update\iau_sdk\iaucore\7z.dll" <-- v18.5.0.0
"C:\Program Files (x86)\Leawo\Blu-ray Player\7z.dll" <-- v4.65.0.0
"C:\Program Files (x86)\XnView\Addon\7z.dll" <-- Unknown

[WinMerge.txt](https://github.com/WinMerge/winmerge/files/7876571/WinMerge.txt)

**Comment by sdottaka** [comment]
WinMerge.txt shows that 7z.dll does exist.
Maybe there is a different 7z.dll installed with a different architecture.

Could you please tell me the file size of the 7z.dll file in C:\Users\shige\AppData\Local\Programs\WinMerge\Merge7z\7z.dll?
 
The file size of the 32-bit version of 7z.dll is 1.08 MB (1,141,248 bytes)
The file size of the 64-bit version of 7z.dll is 1.60 MB (1,679,360 bytes)

If you have the 32-bit version of 7z.dll installed, copy 7z.dll from https://github.com/WinMerge/winmerge/releases/download/v2.16.16/winmerge-2.16.16-x64-exe.zip Try to overwrite that file with 7z.dll.

**Comment by 9demaio1964** [comment]
7z.dll that I found is 
7z.dll 2019/02/22 01:00 1,141,248 bytes !!

I tried to overwrite 64 bit version and It's working fine.

It appears that I installed old 32-bit version and then updated new 64-bit version...
I clean-installed both version and 64-bit version.

Thanks your advise.

**Comment by sdottaka** [comment]
With the fix in commit 10861553b22e2e86f4cdf0595c4717e4e8a5437c, from version 2.16.18, installing the 64-bit version after installing the 32-bit version should replace 7z.dll.
