### ISSUE TITLE
WinMerge crashes with specific regex search

### ISSUE THREAD

**Issue by mdell-seradex** [WinMerge/winmerge#1160]
When searching for the following regex in the subsequent text, WinMerge crashes are the first or second search.  In addition, if it cannot be found and you have attempted the search 2x (I didn't try it 1x), WinMerge crashes after simply adding the that subsequent text.
Regex:
```
(TabIndex        =   )\b0(?!9+~)|([0-9])(?=9*~[0-9]*?\2([0-9]))|~[0-9]+x
```

Text:
```
TabIndex        =   0175~01234567890x
TabIndex        =   42
TabIndex        =   053~01234567890x
```

Note that by crashes, I mean that the process immediately exits.  All information is lost.

**Comment by sdottaka** [comment]
This crash has been fixed in commit f1da8c2.
Thank you for the report.
