### ISSUE TITLE
WinMerge installer require admin rights

### ISSUE THREAD

**Issue by TheJustMoose** [WinMerge/winmerge#1173]
Hi!
I use windows and today I try to install WinMerge.
And I can't. Because WinMerge installer require admin rights
This is very strange.
Usually windows installers can install into LOCALAPPDATA and don't require any admin rights.

**Comment by sdottaka** [comment]
Which installer did you use?
If you do not have admin rights, please use the following installer.

https://github.com/WinMerge/winmerge/releases/download/v2.16.18/WinMerge-2.16.18-x64-PerUser-Setup.exe

**Comment by TheJustMoose** [comment]
First in the list on download page.
https://github.com/WinMerge/winmerge/releases/download/v2.16.18/WinMerge-2.16.18-x64-Setup.exe

Sorry. I didn't see second installer ;)

**Comment by TheJustMoose** [comment]
not reproduced
