### ISSUE TITLE
Wrong links for ShellExtension on Translations page

### ISSUE THREAD

**Issue by Patriccollu** [WinMerge/winmerge#1185]
Hello,

The [ShellExtension Status section on Translations page](https://winmerge.org/translations/?lang=en#shellextension) shows two links for English and both refer to Dutch translation:
	`English`		>	https://github.com/WinMerge/winmerge/blob/master/Translations/ShellExtension/Dutch.po

Additionally, the link for the Template is incorrect:
	`(Template)`	>	https://github.com/WinMerge/winmerge/blob/master/Translations/ShellExtension/

Thanks,
Patriccollu.

**Comment by sdottaka** [comment]
The line "X-Poedit-Language: English\n" in Dutch.po was causing this problem, so I removed it.

@gerundt Could you please update the https://winmerge.org/translations page when you have time?

**Comment by gerundt** [comment]
The removing from `X-Poedit-Language: English\n` fixed the problem. I uploaded a new version to the website.
