### ISSUE TITLE
[Bug Report] WinMerge does not recognize Win 11

### ISSUE THREAD

**Issue by MuhammetEminCakir** [WinMerge/winmerge#1192]
![Ekran görüntüsü 2022-02-13 193813](https://user-images.githubusercontent.com/64583157/153763773-e77b24ca-5b3a-4da5-9a4e-e507bc90fdcb.png)

**Comment by sdottaka** [comment]
The above string is obtained from the registry key Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProductName, which gives "Windows 10" even if the OS is Windows 11. Windows 10" even if the OS is Windows 11.

Pull requests are welcome

**Comment by jrathlev** [comment]
As I know there is only this workaround to identify Windows 11: The build number (key "CurrentBuild") is >= 22000.

**Comment by Temepest74** [comment]
> The above string is obtained from the registry key Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProductName, which gives "Windows 10" even if the OS is Windows 11.
> 
> Pull requests are welcome

I don't this is a fixable problem. Almost all games/programs have the same problem.

**Comment by MuhammetEminCakir** [comment]
I don't know if this information will help. I noticed Notepad++ and MPC-HC can recognize Windows 11.
<img width="868" alt="Ekran görüntüsü 2022-06-06 190558" src="https://user-images.githubusercontent.com/64583157/172200569-7ac89856-35c5-4e7d-9253-4e08d50152d4.png">
