### ISSUE TITLE
Winmerge does not set ERRORLEVEL

### ISSUE THREAD

**Issue by Bluesman74** [WinMerge/winmerge#1193]
I am finding that Winmerge always returns the ERRORLEVEL of 0 whether the files matched or whether they were different.

According to the old SourceForge site https://sourceforge.net/p/winmerge/patches/1272/ should mean that the exit code is returned properly, but that doesn't seem to be the case with Version 2.16.14.0 X64.

The manual doesn't seem to discuss it.  Does anyone know of any command line option to get Winmerge to return a non zero error code on files differing?

**Comment by sdottaka** [comment]
A command line option /enableexitcode has been added in WinMerge version 2.16.15 to enable the exit code.

For usage, please see the following:

https://github.com/WinMerge/winmerge/discussions/743#discussioncomment-1353328

**Comment by Gitoffthelawn** [comment]
> A command line option /enableexitcode has been added in WinMerge version 2.16.15 to enable the exit code.
> 
> For usage, please see the following:
> 
> [#743 (comment)](https://github.com/WinMerge/winmerge/discussions/743#discussioncomment-1353328)

Would there be any harm in always enabling that feature instead of requiring a command line option?

**Comment by sdottaka** [comment]
I don't remember the details, but I gave up on always enabling this feature because it caused problems with git and other commands.
