### ISSUE TITLE
Match similar lines breaks with Ignore whitespace change

### ISSUE THREAD

**Issue by stanio** [WinMerge/winmerge#1209]
I have the [Match similar lines](https://manual.winmerge.org/en/Configuration.html#id625354) option checked and I've often been noticing weird diff alignment.  I tried the exact [Similar lines](https://manual.winmerge.org/en/Compare_files.html#id609976) example (Comparing and merging text files – Difference highlighting):

| file1 | file2 |
|-|-|
| Three | Three |
| blind | mice and a |
| mice | blone |

but I didn't see a difference (as shown in the documentation) with or without "Match similar lines" enabled.  I've then tried various configuration options and found out the "Whitespaces: Ignore change" option I also had checked is interfering with the result of "Match similar lines" (the same happens with "Ignore all whitespace").  Is it possible the two options could play nicer together?

**Comment by sdottaka** [comment]
Thank you for the report.

**Comment by stanio** [comment]
Fixed for me using [v2.16.19](/WinMerge/winmerge/releases/tag/v2.16.19) – thank you very much.
