### ISSUE TITLE
Help text is truncated

### ISSUE THREAD

**Issue by Mr-Update** [WinMerge/winmerge#1210]
- In the settings window, the help text of the too long messages is truncated before the first "\n".

```
msgid "%1\nis marked read-only. Would you like to override the read-only item?"
msgstr "%1 \nist als schreibgeschützt markiert. Möchten Sie das schreibgeschützte Objekt überschreiben?"

```
In the help text only appears: "%1 ".

![Meldungen 1](https://user-images.githubusercontent.com/37781396/155417689-17b9fc5c-5092-4a10-b933-53c2adac2f43.png)

- The message text truncated if there is enough space (probably after 263 characters):

```
msgid "These files use different carriage return types.\n\nDo you want to treat all carriage return types as equivalent for this comparison?\n\nNote: If you always want to treat all carriage return types as equivalent, set the option 'Ignore carriage return differences (Windows/Unix/Mac)' in the Compare tab of the options dialog (available under Edit/Options)."
msgstr "Die Dateien haben ein unterschiedliches Zeilenumbruchformat. \n\nMöchten Sie alle Zeilenumbrüche für diesen Vergleich als gleichwertig behandeln? \n\nHinweis: Wenn Sie immer alle Zeilenumbruchformate als gleichwertig behandeln wollen, aktivieren Sie die Option 'Zeilenumbruchunterschiede (Windows/Unix/Mac) ignorieren' unter Einstellungen/Vergleichen/Allgemein."

```
![Meldungen 2](https://user-images.githubusercontent.com/37781396/155417915-897dd655-1208-493d-938c-73538e72c338.png)

- The same problem exists in the Plugin Settings window. Before the first "\r", the help text is cut off.

```
msgid "Apply filter command. \r\nUsage: ExecFilterCommand COMMAND\r\n  COMMAND - command to execute. %1 in the command is replaced with the filename."
msgstr "Filterbefehl anwenden. \r\nVerwendung: ExecFilterCommand COMMAND\r\n  COMMAND - auszuführender Befehl. %1 im Befehl wird durch den Dateinamen ersetzt."

```
![Plugins](https://user-images.githubusercontent.com/37781396/155417940-3095b9be-6065-49d6-a939-7932707b0f21.png)

**Comment by Gitoffthelawn** [comment]
Ah... German... The language that brought us *wunderbar* words like *rindfleischetikettierungsüberwachungsaufgabenübertragungsgesetz*.

I'm convinced German was invented by a time traveler with a unique sense of humour who created it to break tech user interfaces in the future.

**Comment by sdottaka** [comment]
Ideally, the tooltip should be displayed as a multiline, but for now, I have replaced `\n` with a space character to display it.

Also, the text displayed in the ListView is limited to 259 characters, as shown below.

https://docs.microsoft.com/en-us/windows/win32/api/commctrl/ns-commctrl-lvitema

~~~
Note that although the list-view control allows any length string to be stored as item text, only the first 259 TCHARs are displayed.
~~~
