### ISSUE TITLE
Different exit procedure required for small vs. large files

### ISSUE THREAD

**Issue by Gitoffthelawn** [WinMerge/winmerge#1218]
Users can configure WinMerge to exit with a single press of the `Esc` key after comparing files.  Especially when comparing identical files, this is especially useful.

Currently, there is an inconsistency of this behaviour when comparing very large files.  If you set WinMerge to only show results of very large files, instead of showing the contents, you can no longer use a single press of the `Esc` key to exit WinMerge.

**Comment by sdottaka** [comment]
Thank you for the report.

**Comment by Gitoffthelawn** [comment]
You're most welcome.  Thank *you* for the fix.
