### ISSUE TITLE
Winmerge hangs when opening Google Docs files

### ISSUE THREAD

**Issue by jhgarrison** [WinMerge/winmerge#1249]
Winmerge 2.16.6.0 on Win 10 x64 21H2

When doing a folder compare where one or both folders are on a "Google Drive for Desktop" mirrored drive, when Winmerge encounters a Google Docs file (.gdoc, .gsheet, etc) the comparison hangs.  There is no CPU or Disk I/O activity at this point.  The program is still responsive, but the "Stop" button has no effect, and attempting to close the program hangs hard, at which point the only solution is Task Manager kill.

I suspect that the virtual driver for Google Drive is trying to handle opening a .g* file in a way that Winmerge doesn't like, because of the following observed behavior:

- When double-clicking on a Docs file in Windows Explorer it automatically launches a tab in your default browser instead of using a program to open it
- If you right-click on a Docs file in Windows Explorer and try to open it with a different program (i.e. notepad++ or Wordpad) you get an error dialog similar to "An unexpected error occurred while reading G:\[Google Docs file name]"
- Attempting something really simple like "type filename" in the command prompt gives "Incorrect function"

All this leads me to believe Winmerge is getting an error return from "open" that it doesn't know how to handle.

**Comment by sdottaka** [comment]
I believe this problem has been fixed in the latest version 2.16.18. Could you please try the latest version?

Note that Google Docs files cannot be opened by common applications, so the latest version of WinMerge will give an error instead of hanging.

**Comment by jhgarrison** [comment]
This appears fixed in 2.16.18.  Instead of hanging the comparison result is "Unable to compare files"

Thanks
