### ISSUE TITLE
csv data not recognized in table mode

### ISSUE THREAD

**Issue by a-attanasio** [WinMerge/winmerge#1253]
Hi, in table compare mode, the data of a simple csv are recognized  as a single column instead of being splitted

![Immagine 2022-03-17 001934](https://user-images.githubusercontent.com/87855740/158707066-b0cca1dc-45af-4a3c-a918-34722db5d12e.png)

**Comment by sdottaka** [comment]
I think CSV stands for Comma-Separated Values, but your csv data seems to be separated by semicolons.
Unfortunately, WinMerge can't handle this situation well.
If all your CSV files are in this format, set them in the Options dialog as shown below and compare again.

![image](https://user-images.githubusercontent.com/98126/158709827-dadfe288-7445-4243-a141-9a2b5663a760.png)

**Comment by sdottaka** [comment]
In the upcoming version 2.16.19, after opening files with the file extension csv but not actually CSV, the data will be displayed as in the previous version. However, you will be able to specify ';' as a separator in the "Recompare As → Table" menu item.

![image](https://user-images.githubusercontent.com/98126/158911843-50d7527a-fd49-4838-8cb1-3f6b82d4bd65.png)
