### ISSUE TITLE
Updated Slovenian translation for WinMerge 2.16.19 20220319

### ISSUE THREAD

**Issue by JadranR** [WinMerge/winmerge#1261]
Hi, 
I send you now updated Slovenian translation for WinMerge 2.16.19 20220319
[WinMerge 2.16.19 Slovenian.zip](https://github.com/WinMerge/winmerge/files/8309977/WinMerge.2.16.19.Slovenian.zip)

Best Regards,
Jadran Rudec

**Comment by sdottaka** [comment]
Thank you!

**Comment by JadranR** [comment]
Slovenian translation for Frhed (WinMerge 2.16.19 20220320 BETA)

Best Regards,
Jadran
[Uploading Frhed_Slovenian.zip…]()

**Comment by sdottaka** [comment]
> Uploading Frhed_Slovenian.zip…

The link doesn't point to the zip file and seems to point to this issue itself.

**Comment by JadranR** [comment]
HI,
Here is atached file
BR
Jadran
[Frhed_Slovenian.zip](https://github.com/WinMerge/winmerge/files/8313146/Frhed_Slovenian.zip)

**Comment by sdottaka** [comment]
Thank you!
You seem to have changed `\0` to `\\0`, but that's not correct, so I fixed it as follows: 

~~~
"Datoteke predlog (*.tpl)\\0*.tpl\\0\\0"
~~~
↓
~~~
"Datoteke predlog (*.tpl)\0*.tpl\0\0"
~~~

**Comment by JadranR** [comment]
Hi,
Updated Slovenian translation for WinMerge 2.16.30-e9df6169a per Today
Best Regards,
Jadran
[Slovenian_winmerge-2.16.30-e9df6169a.zip](https://github.com/WinMerge/winmerge/files/11610102/Slovenian_winmerge-2.16.30-e9df6169a.zip)

**Comment by JadranR** [comment]
Hi,

I send you now all updated Slovenian translations for WinMerge 2.16.32.

With respect,

Jadran

V V sre., 31. maj 2023 ob 15:30 je oseba Takashi Sawanaka <
***@***.***> napisala:

**Comment by sdottaka** [comment]
There don't seem to be any files attached here.

**Comment by JadranR** [comment]
Attazhed  ZIP file Slovenian 2.16.32.zip with all  files  inside folders.

Best regards,
Jadran

V V čet., 27. jul. 2023 ob 23:15 je oseba Takashi Sawanaka <
***@***.***> napisala:

**Comment by JadranR** [comment]
A ZIP file was also attached yesterday.

Best Regards,
Jadran



V V pet., 28. jul. 2023 ob 08:53 je oseba Jadran Rudec ***@***.***>
napisala:

**Comment by sdottaka** [comment]
Oh, you probably thought you were emailing me directly, but the email wasn't sent directly to me. I see your message via https://github.com/WinMerge/winmerge/issues/1261. If you look here, you'll notice that no attachments are attached.

**Comment by JadranR** [comment]
[Slovenian 2.16.32_20230811.zip](https://github.com/WinMerge/winmerge/files/12324052/Slovenian.2.16.32_20230811.zip)


Updated Slovenian translation WinMerge-2.16.32-dfcaf93a8-20230811

Best regards,
Jadran

**Comment by sdottaka** [comment]
Thank you!

**Comment by JadranR** [comment]
Hi, 
I send you now updated Slovenian translation for  WinMerge v2.16.34 per Today
[WinMerge-2.16.34 Slovenian.zip](https://github.com/WinMerge/winmerge/files/13190208/WinMerge-2.16.34.Slovenian.zip)


Best regards,
Jadran

**Comment by sdottaka** [comment]
Thank you!

**Comment by JadranR** [comment]
Hi, I send you attached, updated Slovenian translation for  WinMerge 2.16.35 Beta

With respect,
Jadran
[Slovenian-WinMerge-2.16.35 BETA.zip](https://github.com/WinMerge/winmerge/files/13418798/Slovenian-WinMerge-2.16.35.BETA.zip)

**Comment by sdottaka** [comment]
Thank you!
