### ISSUE TITLE
Allow resizing Options dialog box in both directions

### ISSUE THREAD

**Issue by Gitoffthelawn** [WinMerge/winmerge#1265]
Currently, the Options dialog box can only be resized horizontally.  How about allowing it to be resized vertically as well?  By allowing this, the user can make that dialog box sufficiently tall to avoid having to scroll the pane selector in the left side of the dialog box.

**Comment by sdottaka** [comment]
Implemented in commit [e57c5c3](https://github.com/WinMerge/winmerge/commit/e57c5c3e1e9d322020f3e18913be315421f0e629)

**Comment by Gitoffthelawn** [comment]
Thanks!
