### ISSUE TITLE
Wording of tool tips of Copy functions is confusing

### ISSUE THREAD

**Issue by SpeechScientist** [WinMerge/winmerge#1271]
![image](https://user-images.githubusercontent.com/44842385/160122565-88dc6588-44b2-4de9-88de-b4ee6232d392.png)

Very confusing for first-time users. Should read "Copy **to** Right". Same for other Copy functions. 
Version: 2.16.18.0 X64 under Windows 10

**Comment by sdottaka** [comment]
Thank you for the report. This has already been fixed in PR #1219 and applied to version 2.16.19 Beta.
![image](https://user-images.githubusercontent.com/98126/160124316-43eadeae-9e26-41a8-a9d8-31e60122fda0.png)

**Comment by SpeechScientist** [comment]
Good to know, thanks!
