### ISSUE TITLE
What is the real difference with respect to both tags ("identical" and "binary files are identical")

### ISSUE THREAD

**Issue by IlluminatiWave** [WinMerge/winmerge#1282]
![image](https://user-images.githubusercontent.com/42191299/161369417-625649e1-b4f9-4d18-8775-5e8ff7e912f1.png)

I did some tests with the pairs of files and apparently each pair has the same hash (MD5). They have the same information and even the same metadata.

Both "Identical binary files" and "Identical files" have the same file type

for example

file 1.mp4 > "Identical binary files"
file 2.mp4 > "Identical files"

So my question is, what is the difference between both types of identifiers?

Or maybe I'm missing something

In the documentation I also didn't find any information specifying this

**Comment by sdottaka** [comment]
The "Identical" will be displayed when the file size exceeds 64 MB.

If the "Full Contents" method is selected for folder comparisons, the file comparison method will automatically switch to the "Binary Contents" method for faster comparison when the file size exceeds 64 MB.
The "Binary Contents" method does not determine whether the file is a binary file or a text file, so if the files match, it simply displays "Identical".

**Comment by Gitoffthelawn** [comment]
@sdottaka I'm trying to remember... when comparing folders, why not compare everything as binary?  Doing so would eliminate this confusion, but I'm guessing there was a reason for the current behaviour.

**Comment by sdottaka** [comment]
"The "Binary Contents" method does not retrieve the text file encoding, EOL type, number of differences, etc., and therefore cannot display that information in the folder compare window column." Full Contents" method can retrieve that information. Full Contents" method is slower and WinMerge will switch to the Binary Contents method if the file size is large.

**Comment by Gitoffthelawn** [comment]
Thanks.  I wonder if we can find a good way to make this clear to the user via the UI.
