### ISSUE TITLE
Updated Slovenian translation for WinMerge 2.16.19 20220407

### ISSUE THREAD

**Issue by JadranR** [WinMerge/winmerge#1289]
I send you last Slovenian update.
Best regards,
Jadran
[Uploading WinMerge 2.16.19 20220407.zip…]()

**Comment by sdottaka** [comment]
The file does not seem to be attached correctly...

Pull Request can prevent this problem, but is there anything wrong with making a Pull Request?

**Comment by JadranR** [comment]
New attachment
Best Regards
Jadran
[WinMerge 2.16.19 20220407.zip](https://github.com/WinMerge/winmerge/files/8445204/WinMerge.2.16.19.20220407.zip)

**Comment by sdottaka** [comment]
Thank you!

**Comment by JadranR** [comment]
I send you last Slovenian update WinMerge 2.16.20-3745 20220509 per Date 09.05.2022
[Slovenian WinMerge 2.16.20-3745 20220509.zip](https://github.com/WinMerge/winmerge/files/8653349/Slovenian.WinMerge.2.16.20-3745.20220509.zip)

Best regards,
Jadran

**Comment by sdottaka** [comment]
Thank you!
