### ISSUE TITLE
Add "C++/WinRT" as a build requirement in README.md

### ISSUE THREAD

**Issue by Nutzzz** [WinMerge/winmerge#1295]

**Comment by sdottaka** [comment]
I thought C++/WinRT was included in the Windows 10 SDK, did you have to install any additional components?

I have installed the components listed below.

![image](https://user-images.githubusercontent.com/98126/163491322-f06f49ee-e02b-4601-a1e5-9cee0e183843.png)
![image](https://user-images.githubusercontent.com/98126/163491417-3dae439e-faa0-4471-b0fc-aaf37704ad57.png)
![image](https://user-images.githubusercontent.com/98126/163491435-f370c678-66a9-4ca3-845c-b27fee9a8f9e.png)

**Comment by Nutzzz** [comment]
I managed to have Win10 19041 and Win11 SDKs installed and working properly without it.  My installed workloads are .NET desktop development, Desktop development with C++, Universal Windows Platform development, Data storage and processing, and Linux and embedded development with C++.  I don't have any of the ARM tools installed.

I did install MFC and ATL from the left pane of Individual components rather than the right pane under "Desktop development with C++ > Optional".  Perhaps that affects the end result?

Here's what Installation details looks like for me at this point:
![image](https://user-images.githubusercontent.com/5732804/163497527-2a08b773-ba08-47bc-b919-d0ca9e7a38e3.png)
![image](https://user-images.githubusercontent.com/5732804/163497573-2ba631ef-e635-441a-8a2d-8917f13ceb71.png)
![image](https://user-images.githubusercontent.com/5732804/163497590-ceca795f-893a-4a26-a18c-619702d145da.png)

**Comment by sdottaka** [comment]
It seems that installing the "C++/WinRT" component of Visual Studio adds project templates and extensions as shown in the attached file.
However, WinMerge only uses the C++/WinRT header files included in the Windows 10 SDK, so the "C++/WinRT" component is not necessarily required to build WinMerge.
[diff.zip](https://github.com/WinMerge/winmerge/files/8495849/diff.zip)

**Comment by Nutzzz** [comment]
That's odd, as I was getting a number of errors like "unresolved external symbol WINRT_GetRestrictedErrorInfo."  As soon as I installed C++/WinRT the errors were resolved.

**Comment by sdottaka** [comment]
I have found that the above link error occurs when the Windows 10 SDK version is 10.0.19041.0 or lower.

Perhaps installing the C++/WinRT component also installs the latest Windows 10 SDK. (Not confirmed).

A fix has been made to prevent link errors when using Windows 10 SDK 10.0.19041.0 or lower. (2704875)

Thank you for the report.
