### ISSUE TITLE
Sugg: Increase the dialogue for Pluginns

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [WinMerge/winmerge#1308]
Please increase this dialogue:
![grafik](https://user-images.githubusercontent.com/13277944/165302780-ecc49229-11d5-4c48-9852-eda1acda368e.png)
And it would be great if the help and the parameters would be displayed also when the next dialogue appears (where I need the information ...)

**Comment by sdottaka** [comment]
Commit 45cf926 to make that dialog window resizable.
