### ISSUE TITLE
Copy left/right different behavior

### ISSUE THREAD

**Issue by twistah03** [WinMerge/winmerge#1334]
When compare 2 files, sometime is not clear what is copied.

![image](https://user-images.githubusercontent.com/104089154/168290383-1029a556-dc03-4f88-9c10-2635030cdec8.png)

Copy from left to right:
Case 1.
If I select "Folder compare" by click out of the text (on #15), the Copy to Right button is disabled (as in figure) (not as expected)
If I select "Folder compare" as select all text, the Copy to Right button is enabled but nothing happening (not as expected)
If I select "Folder compare" and the row below the Copy to Right button  (works as expected).

Case 2.
Select "Resource trees" will copy also "Extracted texts" (not as expected)

Copy right to left:
Select "Resource trees another" will delete also "Extracted texts" (not as expected)
Selecting "Folder compare again" works as expected

If I add a new line in the right (as shown below) everything work as expected.

![image](https://user-images.githubusercontent.com/104089154/168294074-556f7a08-94ab-4c6d-9ab1-9bf2999a3fca.png)

Attached the files:
[change.log](https://github.com/WinMerge/winmerge/files/8688191/change.log)
[change_1.log](https://github.com/WinMerge/winmerge/files/8688192/change_1.log)

**Comment by sdottaka** [comment]
Fixed in commit 467f8fb. Thank you for the report.
