### ISSUE TITLE
Alt/Shift key highlighting issue not resetting start point from move.

### ISSUE THREAD

**Issue by chrispikula** [WinMerge/winmerge#1335]
If you press and hold the alt key, and then use the up/down arrow key, you automatically jump to the next file or folder that has a merge conflict, this is well understood.

However, if, say, you have multiple issues on one side, such as the following:

![image](https://user-images.githubusercontent.com/22281606/168473300-17c9a6c7-2ef8-413c-8321-e62fbe3f4f6f.png)

And you wish to delete them all, well, you can first jump to the next one with alt+down arrow:

![image](https://user-images.githubusercontent.com/22281606/168473308-abd401c7-c8f4-4a57-bc35-55d4d1f92cc1.png)

Then if you hold shift, to start highlighting, and down arrow some more, you get the following:

![image](https://user-images.githubusercontent.com/22281606/168473325-c2d9e8a2-704e-4a22-ac3b-4a8c25146ed6.png)

Which... is not intended.  If you instead select the first conflict, and then hold shift and down arrow to select the following, a more appropriate selection is highlighted.

![image](https://user-images.githubusercontent.com/22281606/168473443-1625e8a2-c539-4c65-b171-197a234ce341.png)

I apologize if this issue is already tracked, but I just updated from minor version .8 to .20 to attempt to fix it, and it is still existent.

Windows 10/x64/2.16.20.0

**Comment by sdottaka** [comment]
Fixed in commit 9b7f7fc. Thank you for the report.
