### ISSUE TITLE
Add Match Points to files to help file comparison

### ISSUE THREAD

**Issue by FloatingCloud8964** [WinMerge/winmerge#1336]
Please add a new feature of Match Points, which will help compare files more accurately. 

For example, I have 2 big files, and with this feature, I set 2 match points in file1, which break file1 into 3 sections. I also set 2 match points in file2, which break file2 into 3 sections. Then Winmerge will compare section 1 in both files, and compare section 2 in both files, and compare section 2 in both files.

Both files need to have the same number of match points, and match points break the whole file into small sections, and we can compare corresponding sections across 2 files.

Thanks.

**Comment by sdottaka** [comment]
I think the Add Synchronization Point menu item already in WinMerge is close to what you want.

A demo of the Synchronization point can be found at the following URL:

https://github.com/WinMerge/winmerge/issues/1008#issuecomment-942796328
