### ISSUE TITLE
Version Control missing

### ISSUE THREAD

**Issue by kaiukdevelopment** [WinMerge/winmerge#134]
Prior to 2.16.0, in the options there is a section for Version Control. We used this to point to an application that we made which automatically checks out files from Visual Studio Source Control when you saved a file.

Can this feature be brought back?

**Comment by mlipok** [comment]
Why this is still open ?

**Comment by sdottaka** [comment]
Unfortunately, I've lost the environment where I can test the integration between VSS and WinMerge, so it's difficult to restore that functionality.
