### ISSUE TITLE
Request for updating code: a new language(ABAP) in "syntax highlighting"

### ISSUE THREAD

**Issue by yuanshouyan1823** [WinMerge/winmerge#1340]
Dears,

I would like to add a new language to syntax highlighting: ABAP,  a developing language for SAP. And i have written the core cpp file: abap.cpp and completed the adjustment for other related code. Finally it works in my local repository. I would like to know how can i upload my codes? May i send the core code to u directly or i can have an access for  branch?

Thx a lot!

BR.

**Comment by sdottaka** [comment]
Great!

Could you please create a pull request?
If you don't know how to make one, you can attach a compressed zip file of the source code here.

**Comment by yuanshouyan1823** [comment]
>

**Comment by yuanshouyan1823** [comment]
> Great!
> 
> Could you please create a pull request? If you don't know how to make one, you can attach a compressed zip file of the source code here.

Dear, 
I am so sorry to get your reply until today. I am so busy with the work in my company this week.

Since i am not quite familar with github, so i attach the the compressed zip of changed source code here,
[changed code.zip](https://github.com/WinMerge/winmerge/files/8749213/changed.code.zip)

If u meet any problem, just let me know.

**Comment by yuanshouyan1823** [comment]
> Great!
> 
> Could you please create a pull request? If you don't know how to make one, you can attach a compressed zip file of the source code here.

Dear, 
I am so sorry to get your reply until today. I am so busy with the work in my company this week.

Since i am not quite familar with github, so i attach the the compressed zip of changed source code here,
[changed code.zip](https://github.com/WinMerge/winmerge/files/8749272/changed.code.zip)

If u meet any problem, just let me know.

**Comment by sdottaka** [comment]
Thank you!

Merged in commit 260a23f.

I made the following fixes to abap.cpp

- Removed compiler warnings
- Sort keyword list
