### ISSUE TITLE
Enhancement Request - Option to directly view Windows Property of Left and Right file

### ISSUE THREAD

**Issue by 411thetime** [WinMerge/winmerge#1346]
Currently when I right click on a file, I have the following Open Left or Open Right options:

With Registered Application
With External Editor
With...
Open Parent Folder

I'm not sure if there is a way, but it would be nice if there was a way to open the Windows Properties of both the Left and Right File to more easily compare differences.

As an example, I have some JPG files that are slightly different in size and different in modified date, and WinMerge identifies them as different.  However when I use the "Compare", WinMerge says "The selected files are identical".  In my case I believe the Images are identical, however one file is an original, and the other slightly larger file has had some modifications to the EXIF/XMP/MWG meta data.

If someone could let me know if there is an easy way to see the actual difference in this case it would be helpful.

ORIGINAL
![NoName](https://user-images.githubusercontent.com/105978613/169654422-4527d958-b806-45c3-b4a3-b738adea1794.jpg)

WITH NAME EDIT
![WithName](https://user-images.githubusercontent.com/105978613/169654428-a079bd61-47ac-4b77-b652-199baf3abdf9.jpg)

**Comment by sdottaka** [comment]
Unfortunately, WinMerge does not have the ability to compare image metadata.

However, it is possible to add image properties to the columns of the folder comparison window, as shown below.

![image](https://user-images.githubusercontent.com/98126/169655004-ce47d249-19b6-405e-874e-86a81fc35dec.png)
![image](https://user-images.githubusercontent.com/98126/169655016-c8b35547-304f-4ef9-ba1a-88e7b2fd63be.png)
![image](https://user-images.githubusercontent.com/98126/169654976-de99edac-e6dd-4c2f-a555-ba29ffc302ce.png)
![image](https://user-images.githubusercontent.com/98126/169655550-d5f2b8a6-6256-4b93-adac-b185c84eecb2.png)

**Comment by 411thetime** [comment]
Thank you for the helpful and quick response.

I was wanting a way to easily see the differences and didn't see those Additional Property options before.  It took me a little bit to understand why the files were difference sizes when the images matched.

Understanding it was those meta data fields and now having a way to show them in the results display columns is good for what I needed.  I will close this request as I feel what you have directed me to gives me enough information for what I need to see the additional differences.

Thanks again!
