### ISSUE TITLE
Proposal: Single installer

### ISSUE THREAD

**Issue by Bill-Stewart** [WinMerge/winmerge#1348]
Inno Setup 6.x now supports building a single installer that can install the 32-bit and 64-bit in a single installer. It can also support installers that installer per-user or per-computer in a single installation. For reference, see the installer I built for the open-source Syncthing project:

[https://github.com/Bill-Stewart/SyncthingWindowsSetup](https://github.com/Bill-Stewart/SyncthingWindowsSetup)

Creating a single package would reduce confusion and simplify things as there would only need to be a single installer download. When you run the installer, it asks the user whether they want to install for the current user only or the entire computer, as well as automatically installing the appropriate "bitness" (i386 or amd64).

I'm willing to create a prototype installer for this project if you like and you can incorporate it into your build process, if you like.

**Comment by sdottaka** [comment]
In fact, WinMerge already has an installer script for InnoSetup 6 that allows you to choose between per-user and per-computer installation.
(https://github.com/WinMerge/winmerge/blob/master/Installer/InnoSetup/WinMergeX64.is6.iss).

The reason this is not currently in use is that in the past, installers created with InnoSetup 6 have been treated as malware by some virus scanning software.
(I have not tested how this is currently happening).

By putting both the 32-bit and 64-bit versions in one installer, I am concerned about two things

- The size of the installer will increase.
- The impact on users who have already installed the 32-bit version of WinMerge on a 64-bit version of Windows when they update to the next version.

**Comment by Bill-Stewart** [comment]
> WinMerge already has an installer script for InnoSetup 6

Great!

> The reason this is not currently in use is that in the past, installers created with InnoSetup 6 have been treated as malware by some virus scanning software

This was also an issue with older versions of Inno Setup. Since you are digitally signing your installers, these should be reported to AV vendors as false-positives.

> By putting both the 32-bit and 64-bit versions in one installer, I am concerned about two things
> * The size of the installer will increase.
> * The impact on users who have already installed the 32-bit version of WinMerge on a 64-bit version of Windows when they update to the next version.

Regarding size: Correct, the single installer will be larger, but it shouldn't be a huge amount, as only both pairs of binaries need to be included.

Regarding impact: If this is an issue, you can use a different AppID and automatically uninstall the old version if you detect it. I wrote a Windows DLL that makes this easier:

https://github.com/Bill-Stewart/UninsIS/

**Comment by sdottaka** [comment]
Thank you for your suggestion.

For now, I will keep the 32-bit and 64-bit versions separate, as I recall that the installer created by InnoSetup6 does not support Windows XP.
I will consider this again when I give up WindowsXP support.

**Comment by Bill-Stewart** [comment]
Sounds good, thanks!
