### ISSUE TITLE
Refresh Selected Marks Unscanned Folders as Identical

### ISSUE THREAD

**Issue by Jamestec** [WinMerge/winmerge#1349]
Reproduction steps:
1. Start a compare where there are folders.
2. Stop the scan before all the folders are compared (e.g. immediately stop it).
3. "Refresh Selected" anything.

**Comment by sdottaka** [comment]
Fixed in commit [0315bd6](https://github.com/WinMerge/winmerge/commit/0315bd6a99fc184693d2585742b8640e1019959d)
Thank you for the report.
