### ISSUE TITLE
[Feature Request] Selection Count on Status Bar

### ISSUE THREAD

**Issue by crazysurajit** [WinMerge/winmerge#135]
When comparing data files it's really useful to have the Selection Count displayed on the Status Bar, just like in Beyond Compare or Notepad++
![image](https://user-images.githubusercontent.com/12027492/54498832-e5584980-495f-11e9-8122-6deba9e43b2d.png)
https://github.com/WinMerge/winmerge-v2/blob/07755eab3b56d974dd1d38b3c1944f9510b0376c/Src/MergeStatusBar.cpp#L238-L239

**Comment by sdottaka** [comment]
This feature has been implemented in commit c3f876c.
Thank you for the feature request.
