### ISSUE TITLE
Syntax highlighting: SQL comments

### ISSUE THREAD

**Issue by Darkazas** [WinMerge/winmerge#1354]
### Discussed in https://github.com/WinMerge/winmerge/discussions/1353

<div type='discussions-op-text'>

<sup>Originally posted by **Darkazas** May 31, 2022</sup>
.sql file syntax highlighting

Just multiline comments /* */ supported - missing single line comments --</div>

**Comment by sdottaka** [comment]
Fixed in commit [671ca7f](https://github.com/WinMerge/winmerge/commit/671ca7f92b1795411786d011f5042bead7136fa5)

Thank you for the report.
