### ISSUE TITLE
Folder is listed as being different when all Files inside are identical. 

### ISSUE THREAD

**Issue by Zachruff** [WinMerge/winmerge#1359]
![image](https://user-images.githubusercontent.com/70397032/172005706-ee080c3d-8a69-41d9-ae6d-448652acca36.png)

As you can see it says the code folder is different but all the files within it are identical so I am not sure exactly why its saying its different. Looked on the Internet for info but I could not find anything.

**Comment by Zachruff** [comment]
![image](https://user-images.githubusercontent.com/70397032/172007817-6d901157-ebb5-40a1-a30b-5316a8134b89.png)
although I might just be using this program incorrectly in general... Here both directories im comparing have all of the StampXX.szs files despite this saying that the right only has 0-9 and left only has 10+

**Comment by Zachruff** [comment]
Ive also done another compare on just those two folders themselves and they still say all is identical so I dont know why its saying it isnt here.

**Comment by sdottaka** [comment]
Are any of the following menu items unchecked except for "Show Skipped Items"?

![image](https://user-images.githubusercontent.com/98126/172028271-09f74f85-e2d1-4a10-bac8-e85a4175fb87.png)

**Comment by Zachruff** [comment]
ah I had Show Different Items unchecked. Thank you lol sorry for this.
