### ISSUE TITLE
Line difference coloring in “Word-level” mode does not work correctly for Cyrillic-based languages

### ISSUE THREAD

**Issue by JentRys** [WinMerge/winmerge#1362]
Thank you for the program, which is the best among similar ones!

Line difference coloring in “**Word-level**” mode unfortunately does not ❌ work for **Cyrillic-based languages** (in particular, Russian).  Could you please fix this?

Text compare:

![Word-level](https://user-images.githubusercontent.com/14031889/172344278-dc52d8e1-69ee-4c34-8dc7-cb488015cf66.png)

Please note that the line difference coloring (**Word-level**: “Break at whitespace” or “Break at whitespace or punctuation”) works correctly ✔ in the old version (2.14.0).

![Word-level 2 14 0](https://user-images.githubusercontent.com/14031889/172350714-f0c14205-39bf-4926-bb26-553757bbddf4.png)

[WinMerge Configuration Log.txt](https://github.com/WinMerge/winmerge/files/8851937/WinMerge.Configuration.Log.txt)
[Compared files.zip](https://github.com/WinMerge/winmerge/files/8851938/Compared.files.zip)

**Comment by sdottaka** [comment]
Fixed in commit [8d819a8](https://github.com/WinMerge/winmerge/commit/8d819a8497cc4ed56a5cf98292d084b27beb9649)

Thank you for the report.
