### ISSUE TITLE
Crash on command line compare

### ISSUE THREAD

**Issue by psbitdev** [WinMerge/winmerge#1363]
My Winmerge version is 2.16.20.0 x64 on Windows 10 Enterprise 2016 LTSB (OS build 14393.2670).

I has been compare two text files with following command:
***"C:\Program Files\WinMerge\WinMergeU.exe" /f \*.txt /m full /u /l 4 /al testall.text .\fi\test.txt***
that cause Winmerge to crash.

I have file _"testall.text"_ in current folder (I change extension to "txt" just to be able to load it to Github)
[testall.txt](https://github.com/WinMerge/winmerge/files/8852067/testall.txt)
```
<skip1>
<skip2>
<skip3>
```
and file _"fi\test.txt"_ in "fi" subfolder
[test.txt](https://github.com/WinMerge/winmerge/files/8852073/test.txt)
```
<skip1>
<skip2>
<skip3>
<1>
<2>
<3>
<2>
<3>
<4>
<5>
<2>
<6>
<3>
```
If I remove the '/al' switch it work normal.

**Comment by sdottaka** [comment]
Thank you for the report.
I fixed the crash in commit [2faa6b3](https://github.com/WinMerge/winmerge/commit/2faa6b3907db59feb63b6679b9b2a0d9622cfbba).
However, the `/ al` command line option is an option for 3-way merge, so specifying two files has no effect.

If you want to force it to work, specify three files as shown below.
~~~
"C:\Program Files\WinMerge\WinMergeU.exe" /f *.txt /m full /u /l 4 /al testall.text .\fi\test.txt testall.text
~~~
