### ISSUE TITLE
"Replace All" doesn't work when Replace in "Selection" and the new string contains the old string.

### ISSUE THREAD

**Issue by www1800** [WinMerge/winmerge#1376]
Hi,

"Replace All" doesn't work when Replace in "Selection" and the new string contains the old string.

Steps to reproduce, consider the below C code:
`float foo(float a, float b) {
    return a * b * b;
}`

1. Select the code.
2. Replace in "Selection"
3. Find "float" and Replace with "Myfloat"
4. Click "Replace All", then it would behave like "Replace" (only the first string would be replaced).

![image](https://user-images.githubusercontent.com/61829207/174694270-eb45bd0f-3134-4d68-a35e-5af855457658.png)

Note:
1. Replace with "double" is fine.
2. Replace in "Whole file" is fine.
3. Only 2.16.20 version we saw this.

Thank you.

Best,
John

**Comment by sdottaka** [comment]
Fixed in commit [e594b8b](https://github.com/WinMerge/winmerge/commit/e594b8b02bd4c83058d19dd2e9f7f9909ac373e5)
Thank you for the report.
