### ISSUE TITLE
vertical editing for .h file is quite slow

### ISSUE THREAD

**Issue by www1800** [WinMerge/winmerge#1386]
[repro.zip](https://github.com/WinMerge/winmerge/files/9015671/repro.zip)

Hi,

Please see the repro.zip, the left.h has 0x7fc00000 padding for every lines, compare left.h and right.h, try to use vertical editing (Alt+Drag for column selection) to remove the padding from the left panel, it's quite slow.

The known workaround is change the file extension to .txt to avoid syntax detection/highlight.

Thanks.

Best,
John

**Comment by sdottaka** [comment]
Fixed in commit [ba0bc86](https://github.com/WinMerge/winmerge/commit/ba0bc86609e444fc9aeaf8cdcab16fcbcf713701)
Thank you for the report.
