### ISSUE TITLE
replace text using regular expressions﻿ behaves incorrectly if multiple matches on the same line

### ISSUE THREAD

**Issue by www1800** [WinMerge/winmerge#1387]
Hi,

Replace text using regular expressions﻿ behaves incorrectly if there are multiple matches on the same line.

`f0, f1, f2,

f0,
f1,
f2,
`
![image](https://user-images.githubusercontent.com/61829207/176619612-29bef16a-83a6-4f8f-9cc5-06f5c9b1c335.png)

Replace f(\d) with m\1, result:

`m0, m , m ,

m0,
m1,
m2,
`

The first line should be m0, m1, m2.

Thanks.

Best,
John

**Comment by www1800** [comment]
'Replace All' was used.

**Comment by sdottaka** [comment]
Fixed by PR #1388 
Thank you for the report.
