### ISSUE TITLE
[Feature request] Implement dark theme

### ISSUE THREAD

**Issue by MarcAnt01** [WinMerge/winmerge#139]

**Comment by i-would** [comment]
I just want to second this.

**Comment by dongbum** [comment]
:+1:

I need this.

**Comment by NeuCp** [comment]
Looking fordward for this enhancement. BR.

**Comment by PwrSrg** [comment]
+1

**Comment by mbanaszek88** [comment]
+1

**Comment by malamanteau** [comment]
+1

**Comment by cwinkler89** [comment]
+1

**Comment by rypo07** [comment]
plus oneeeeeeeeeee 1111111111111111111111111

**Comment by fantasyz** [comment]
I want this too.

**Comment by eltociear** [comment]
dark theme ini file
https://qiita.com/eltociear/items/bc7005a49272b8e25b3b

**Comment by sdottaka** [comment]
The Solarized Dark color scheme has been added in commit 1d238d6b318f8e4ccc5341591900a8197407f0b1.

If you would like another color scheme to be included in WinMerge, please submit a Pull Request.

**Comment by mikemma** [comment]
> The Solarized Dark color scheme has been added in commit [1d238d6](https://github.com/WinMerge/winmerge/commit/1d238d6b318f8e4ccc5341591900a8197407f0b1).
> 
> If you would like another color scheme to be included in WinMerge, please submit a Pull Request.

how can we activate the theme from the menu?

**Comment by sdottaka** [comment]
It can be set on the Edit-> Options menu item -> Color/Color schemes page.

![image](https://user-images.githubusercontent.com/98126/98607300-3e8ea100-232c-11eb-8744-945906dddcec.png)

**Comment by Pysis868** [comment]
Not in 2.16.6 though O_o.  Just updated to 2.16.14 and got it.

**Comment by FallenAvatar** [comment]
Just want to leave this comment for others. This is not a dark theme for the app itself, it only affects the lists and merge/edit windows.

Still a step in the right direction.

**Comment by rigiddesign** [comment]
> Just want to leave this comment for others. This is not a dark theme for the app itself, it only affects the lists and merge/edit windows.
> 
> Still a step in the right direction.

Yeah. I closed the app and restarted my PC, before opening a file to realise this doesn't change the app's UI, at all. As you said, it's a start, at least.

**Comment by yenic** [comment]
It doesn't look like this issue is even on the list for WinMerge. As what looks like an MFC application so the best option may be to override CMFCVisualManager and put in a menu option to switch WinMerge to the color palette of https://github.com/xatupal/KeeTheme. 

I'm sure if someone got it working that the WinMerge team would consider a pull request. And if not, a fork with this would be very popular. I can live without dark mode myself but there's an idea for anyone interested.

**Comment by emanueol** [comment]
As of 17-MAY-2022 with Winmerge 2.16.20 I only see 4 themes and none if typical "dark" them like Obsidian for example.
I only see  4 options with followingf look and feels:
default		
Modern 		- similiar to default but greenish
Solarized Dark	- dark green
Solarized Light - very similiar to Modern

So basically theres only 2 look and feels: normal and greenish

Can anyone please let me know where to get a proper dark team (like Obsidian) ?
Or how can I make my own by creating some configuration file ?

Thanks ~

**Comment by Gitoffthelawn** [comment]
@emanueol I'm quite busy for the next 10-20 hours, but ping this thread after that, and I'll post my custom dark theme settings for you and others to enjoy.

**Comment by srgloureiro** [comment]
For me there at least 4 different Color schemes which make sense and WinMerge does not have them yet:

- Visual Studio Light
- Visual Studio Dark
- Viasfora Light
- Viasfora Dark

**Comment by emanueol** [comment]
> @emanueol I'm quite busy for the next 10-20 hours, but ping this thread after that, and I'll post my custom dark theme settings for you and others to enjoy.

are you back ? are you back ? are you back ?  😄 

Personally I would love Obsidian style. I got it on all my tools, except winmerge 😢

**Comment by emanueol** [comment]
> It can be set on the Edit-> Options menu item -> Color/Color schemes page.
> 
> ![image](https://user-images.githubusercontent.com/98126/98607300-3e8ea100-232c-11eb-8744-945906dddcec.png)

that optin "Solarized Dark " is in reality greenish and not dark blackish as you can see from screenshot:
![image](https://user-images.githubusercontent.com/8422412/196983381-b5f7aa00-25c5-439b-9bec-653ee1be004f.png)

**Comment by Tamarindo94** [comment]
This is a much needed feature!

**Comment by oeloo** [comment]
What is this issue with status 'Closed' ?
It has not been implemented, and it is really an important feature for anyone using Dark Mode on their computers

**Comment by Feky** [comment]
Still nothing? 😱

**Comment by MkazemAkhgary** [comment]
Could you please consider making the borders black in the current dark theme? The white borders are quite sharp on my eyes, and having black borders would greatly enhance the usability. I understand that theme changes can take time, but I hope the developers can prioritize this issue. Overall, I think this app is great, and having the proper dark theme with black borders would make it even better.

**Comment by EmirLogas** [comment]
Obviously they're not going to add a nice dark mode. I switched to Beyond Compare. It looks pretty good.

**Comment by rkodey** [comment]
FWIW:
A quick search found this additional dark mode theme:  https://github.com/liqube/liqube-dark-winmerge
And then I created one of my own:  https://github.com/rkodey/winmerge-visual-studio-dark

WinMerge 2.16.44 added the ability to override some of the system colors.  Big improvement!

**Comment by rkodey** [comment]
New color scheme merged with completed PR #2634
