### ISSUE TITLE
Allow renaming of untitled pages

### ISSUE THREAD

**Issue by skyhirider** [WinMerge/winmerge#1395]
When creating a comparison by copy pasting text, the titles of the left and right pane shot untitled left and right and can not be renamed.

When a html diff report is created (Tools -> Generate Report) the comparison shows untitled which is not helpful and needs to be manually edited in the html.

Being able to double click the titles in WinMerge and change then before generating the report would be great.

![image](https://user-images.githubusercontent.com/1695005/177516376-c9b62785-91f9-4efb-b1f0-744c59848d50.png)

**Comment by sdottaka** [comment]
Unfortunately, it is not possible to change the title in the GUI at this time.

As an alternative, you can start WinMerge by specifying the title as a command line argument as follows.

"c:\Program Files\WinMerge\WinMergeU.exe" /new /dl "file1" /dr "file2"

**Comment by skyhirider** [comment]
Thank you sdottaka. Is this something that would make sense in adding to your roadmap if its feasible to implement?

**Comment by sdottaka** [comment]
I implemented this feature in commit [5f2db80](https://github.com/WinMerge/winmerge/commit/5f2db807f0aeaaf9f3a64192a4177e8beb6d0b70)
![image](https://user-images.githubusercontent.com/98126/178132517-74d732b2-16dd-46b6-a429-db2d0e6d62d0.png)
