### ISSUE TITLE
WinMerge lacks support for smartphone like portable devices?

### ISSUE THREAD

**Issue by Tinase-nau** [WinMerge/winmerge#1419]
I wanted to compare a folder on my phone's internal shared storage, but WinMerge keeps saying "Folder Selection. File not found." Then I tried copy-pasting the address of that folder into the input field, but WinMerge does not accept that.
WinMerge doesn't even add context menu actions to that device's directories.

I also have another comparison tool. And that one does have context menus even for that device and it does not complain about bad directory address. I checked how it deals with it: the application translates the device path from "PC\\..." into "mtp://..." address.

Is this a known issue?

**Comment by sdottaka** [comment]
Unfortunately, WinMerge does not support Windows Portable Devices.

**Comment by Tinase-nau** [comment]
Ahh, that is a shame. :(
