### ISSUE TITLE
 Slovenian translation for WinMerge 2.16.22-140940828

### ISSUE THREAD

**Issue by JadranR** [WinMerge/winmerge#1424]
Hi,
I send you now updated Slovenian translation for WinMerge 2.16.22-140940828
[winmerge-2.16.22_Slovenian.zip](https://github.com/WinMerge/winmerge/files/9195357/winmerge-2.16.22_Slovenian.zip)

Best Regards,
Jadran Rudec

**Comment by sdottaka** [comment]
Merged.
Thank you!

**Comment by JadranR** [comment]
Hi,
I send you now updated Slovenian translation for WinMerge 2.16.22-5c1e121e2
Best Regards,
Jadran
[Slovenian-winmerge-2.16.22-5c1e121e2.zip](https://github.com/WinMerge/winmerge/files/9569563/Slovenian-winmerge-2.16.22-5c1e121e2.zip)

**Comment by sdottaka** [comment]
Thank you!

**Comment by JadranR** [comment]
Hi,
I send you now updated Slovenian translation for WinMerge  2.16.23-3b82dd85a, per tonight.
[Slovenian.zip](https://github.com/WinMerge/winmerge/files/9742325/Slovenian.zip)

Best Regards,
Jadran

**Comment by sdottaka** [comment]
Thank you!

**Comment by JadranR** [comment]
Updated Slovenian translation WinMerge 2.16.24-cab8901f4
[Slovenian.zip](https://github.com/WinMerge/winmerge/files/10270706/Slovenian.zip)

**Comment by sdottaka** [comment]
Thank you!

**Comment by JadranR** [comment]
Updated Slovenian translation WinMerge 2.16.25-ec4d9f250
[Slovenian.zip](https://github.com/WinMerge/winmerge/files/10354308/Slovenian.zip)
Best Regards
Jadran

**Comment by sdottaka** [comment]
Thank you!

**Comment by JadranR** [comment]
Updated Slovenian translation Slovenian_2.16.29-decf135c9
[Slovenian_2.16.29-decf135c9.zip](https://github.com/WinMerge/winmerge/files/11026949/Slovenian_2.16.29-decf135c9.zip)


Best Regards
Jadran

**Comment by sdottaka** [comment]
Thank you!
