### ISSUE TITLE
Remember zoom level for all files

### ISSUE THREAD

**Issue by sdottaka** [WinMerge/winmerge#1433]
### Discussed in https://github.com/WinMerge/winmerge/discussions/1432

<div type='discussions-op-text'>

<sup>Originally posted by **Faguss** July 30, 2022</sup>
I find it inconvenient to zoom out every time I open a file. Could you save zoom value like in Notepad++?</div>

**Comment by Gitoffthelawn** [comment]
If I'm not mistaken, I think the OP is asking for a zoom level that gets applied to ***all*** files, not a zoom level stored ***per*** file (just trying to provide clarity).  If I'm mistaken, please advise.

**Comment by sdottaka** [comment]
I've implemented this feature in [e477205](https://github.com/WinMerge/winmerge/commit/e4772056fe149931a3a7b0ef2dbe604f801975fc)
In this implementation, the zoom level is not saved per file.
