### ISSUE TITLE
Line filters don't ignore differences if comparing three folders

### ISSUE THREAD

**Issue by Tom-Robinson** [WinMerge/winmerge#1435]
Comparing folder A to folder B, line filters work fine.
Comparing folder B to folder C, line filters work fine.
Comparing folders A to B to C, line filters are ignored.

**Comment by sdottaka** [comment]
I haven't been able to reproduce this issue.
What version of WinMerge are you using?
If you are using the latest version, could you please attach the files to reproduce the problem?

**Comment by Tom-Robinson** [comment]
It is fixed in the current version. Sorry I didn’t check that first.

Thanks,

…Tom
