### ISSUE TITLE
Non existing backup directory should be automatically created

### ISSUE THREAD

**Issue by WhiteChairFromIkea** [WinMerge/winmerge#1438]
1. Configure to make backups to non existing folder, like this:    
![5616w](https://user-images.githubusercontent.com/46539653/183042214-e5789a9c-4843-4945-ae3f-9c388aaf551e.png)
2. Error is thrown about failure to create a backup file:
![0307V](https://user-images.githubusercontent.com/46539653/183043139-f5374179-ad27-4ec8-9e9b-7a1727845a57.png)

This is because folder `_WinMerge_Backups`  is not existing inside my %tmp% dir. If I create `_WinMerge_Backups` inside my %tmp% folder, backup operation is successfully finished. WinMerge should automate that folder creation by itself.

![0559m](https://user-images.githubusercontent.com/46539653/183043494-5ec0ac14-5558-4ec7-a9ae-e2a719f7ff5c.png)

**Comment by sdottaka** [comment]
Fixed in commit [bfc2015](https://github.com/WinMerge/winmerge/commit/bfc20150e0120d149e3030391dadce9c5c88d1ba)

Thank you for the report.

**Comment by WhiteChairFromIkea** [comment]
Thank you for your work! 🙂
