### ISSUE TITLE
Windows 11 *Pro* - WinMerge NOT in Explorer's context menu

### ISSUE THREAD

**Issue by David-Maisonave** [WinMerge/winmerge#1442]
## Setup:
**OS:** Windows 11 Pro
**WinMerge Ver:** 2.16.22
WinMerge installed with [**Enable Explore context menu**] selected.

### Initial Workaround Attempt:
I found the following post, which help me fix the issue.
_Originally posted by @sdottaka in https://github.com/WinMerge/winmerge/discussions/1152#discussioncomment-2027043_
#### Fixing it wasn't straight forward, even with the available options. 
<img width="389" alt="OptionsMenuAfterInstallIntoWin11" src="https://user-images.githubusercontent.com/47364845/183267867-f64eb065-adeb-480c-99a9-8cf3378d7375.png">

#### I performed the following steps before getting it right.

- Clicked on **Register shell extension for Windows 11**. Before clicking this button, the "Enable advanced menu" option was greyed out, and could not be selected.
  - Results: 
    - Explorer did **NOT** display a WinMerge context menu.
    - **Enable advanced menu** option greyed out.
- Clicked on **Register shell extension**. 
  - Results: 
    - WinMerge listed in context menu option (by itself).
    - **Enable advanced menu** option available for selection.
- Selected **Enable advanced menu** option, and clicked on **Register shell extension for Windows 11**. 
  - Results: 
    - WinMerge listed in context menu option (by itself).
    - No advance context menu option listed.
- Selected **Enable advanced menu** option, clicked on **Unregister shell extension**, and clicked on **Register shell extension for Windows 11**. Do NOT click OK on the Options window.
  - Results: 
    - Explorer did **NOT** display a WinMerge context menu.
    - **Enable advanced menu** option greyed out.
    - **Add to context menu** option greyed out.
- After performing previous step, Click OK on Options window, to close it. 
  - Results: 
    - WinMerge listed in context menu option.
    - Advance WinMerge context menu option listed.

I listed the above steps to show how much work users may go through before getting the advance context menu option working.

## Workaround with Minimal Steps
1. Clicked on **Register shell extension**. 
2. Selected **Enable advanced menu** option.
3. Clicked on **Register shell extension for Windows 11**.
4. On the Options window, Click OK, to close the window.

## Summary
- The context menu if selected during setup, should get configured without having to go through extra steps to fix it.
- I believe this issue is unique to **Windows 11 Pro**. 
  - I've installed WinMerge on many Windows **10 Home** and Windows **10 Pro** computers, and I've never had this issue occur before.
  - I could **NOT** reproduce it on **Windows 11 Home** edition.
  - On Windows 11 Pro, it's easy to reproduce.
    - To reproduce it after applying the workaround, you have to fully uninstall WinMerge and then do a reinstall.
- The context menu is not the same on Windows 11 Pro compared to Windows 11 Home. On **11 Home**, the options are **correctly** consolidated under a sub menu, and on **11 Pro**, the options are incorrectly on the root menu.
  - Windows 11 Home
    - <img width="191" alt="ContextMenuWin11Home(smaller)" src="https://user-images.githubusercontent.com/47364845/183267693-09541980-927f-4ec4-acee-cb201413787d.png">
  - Windows 11 Pro
    - <img width="104" alt="ContextMenuOnWin11Pro_(256_x_256)" src="https://user-images.githubusercontent.com/47364845/183267597-7779854f-6d67-41b1-ada5-be70dfc2b064.png">

**Comment by David-Maisonave** [comment]
FYI:
On Windows 11 (Home or Pro) you can remove the need to click on [**Show More Options**] by modifying the registry via following command line:
````
reg.exe delete "HKCU\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}" /f
````
After making the registry key change, restart File Explorer or your computer for the changes to take effect.

That will allow WinMerge context menu to be available without having to click on [**Show More Options**] .

**Comment by sdottaka** [comment]
I was not able to reproduce this issue with WinMerge-2.16.22-x64-Setup.exe, but I was able to reproduce it with WinMerge-2.16.22-x64-PerUser-Setup.exe.
Was the installer you used WinMerge-2.16.22-x64-PerUser-Setup.exe?

**Comment by sdottaka** [comment]
I was able to reproduce it by installing WinMerge-2.16.22-x64-Setup.exe immediately after uninstalling WinMerge.

**Comment by David-Maisonave** [comment]
This issue has gotten worse. Now I can't get the context menu to show up at all.
Is there any update to address this issue?

**Comment by sdottaka** [comment]
Could you please try the following steps to see if this solves the problem?

1. Uninstall WinMerge 
2. Restart Windows
3. Install the latest version of WinMerge

**Comment by MuhammetEminCakir** [comment]
I have this issue too. But this issue only occurs when advanced menu is enabled and on desktop.
Like this:

Advanced Menu Disable-->Works as expected
![AdvancedMenuDisable](https://user-images.githubusercontent.com/64583157/217613090-8788d8c4-7f5d-4998-bef7-80f70016bc10.gif)

Advanced Menu Enable (Desktop right click)-->Does not work as expected
![AdvecedMenuEnable(Desktop)](https://user-images.githubusercontent.com/64583157/217613519-9a274dc2-796d-41be-ab20-5577f3e16fe9.gif)

Advanced Menu Enable (File right click)-->Works as expected
![AdvancedMenuEnable(File)](https://user-images.githubusercontent.com/64583157/217614171-464dc4f1-cbb7-478c-be9e-ef6652e8233f.gif)



> I was not able to reproduce this issue with WinMerge-2.16.22-x64-Setup.exe, but I was able to reproduce it with WinMerge-2.16.22-x64-PerUser-Setup.exe. Was the installer you used WinMerge-2.16.22-x64-PerUser-Setup.exe?

No, it was WinMerge-2.16.26-x64-Setup.exe



> Could you please try the following steps to see if this solves the problem?
> 
> 1. Uninstall WinMerge
> 2. Restart Windows
> 3. Install the latest version of WinMerge

I tried but this doesn't solve the problem

**Comment by sdottaka** [comment]
Oh, I used to have no problem right-clicking on the desktop background, but now it doesn't seem to be working properly. However, I could not reproduce this problem by right-clicking on any file or folder on the desktop.

**Comment by David-Maisonave** [comment]
> I could not reproduce this problem by right-clicking on any file or folder on the desktop.

Are you testing this on **Windows 11 x64**?
I can still reproduced this issue. I just installed WinMerge-2.16.26-x64 using file **WinMerge-2.16.26-x64-Setup.exe**, and the issue is still there.

### Setup: Windows 11 64-bit, [WinMerge-2.16.26-x64-Setup.exe](https://github.com/WinMerge/winmerge/releases/download/v2.16.26/WinMerge-2.16.26-x64-Setup.exe) 
- **Important:** Select the file in windows explore.
- The file should be fully highlighted.
    <img width="328" alt="FileFullySelected" src="https://user-images.githubusercontent.com/47364845/217962133-e7d0b23a-f116-48fe-b27b-3a30c397dadd.png">
- Right click the file.
- WinMerge does not appear on the context menu.
   <img width="189" alt="MissingContextMenuItem_ReducedSize" src="https://user-images.githubusercontent.com/47364845/217961760-2abe0716-8436-4601-aed2-096b5cf4b1df.png">
- Close the context menu.
- Click on an empty area in the right side (like right below the last file).
- The file should look like it's selected via an out line, instead of being fully highlighted.
   <img width="335" alt="FileWithAnOutlineSelection" src="https://user-images.githubusercontent.com/47364845/217961564-f2e36511-5f14-4b16-8245-829cc4a00aca.png">
- Right click on that same empty area.
- WinMerge is now in the context menu.
   <img width="264" alt="WinMergeInContextMenu" src="https://user-images.githubusercontent.com/47364845/217962816-73d8c2e3-3fbe-4f72-b056-05c828ec0780.png">
- However selecting compare on the WinMerge context menu item, will start up WinMerge with the folder selected instead of the file.

Side-Note: The WinMerge **About** window shows this as being version **2.16.22.0** instead of 2.16.26.

**Comment by David-Maisonave** [comment]
Hold the press!!! :-)

I finally figured out this issue, and I really should have figured it out when the version on the WinMerge About window did not match what I had just installed.
There was an old x86 version 2.16.22.0 installed on my computer, and it stayed there even when I updated WinMerge with [WinMerge-2.16.26-x64-Setup.exe](https://github.com/WinMerge/winmerge/releases/download/v2.16.26/WinMerge-2.16.26-x64-Setup.exe). 
The context menu was setup with this old x86 version.

#### For anyone who has this same problem, here's the steps to fix it:
1. Uninstall the old x86 version via Windows uninstall program.
2. Start the x64 version which is under _C:\Program Files\WinMerge_.
3. Select **Edit**->Options->[**Shell Integration**]
4. Enable [Add to context menu]
5. Enable [Enable advanced menu]
6. Select **Unregister** shell extension
7. Select **Register** shell extension
8. Select **Unregister** shell extension for Windows 11 or later
9. Select **Register** shell extension for Windows 11 or later

That resets it to the correct version with the correct context menu.

If this come up again, I would ask the user to look at their WinMerge About window and verify that they see the expected version and x64.

**Comment by sdottaka** [comment]
Thank you for the information.

**Comment by David-Maisonave** [comment]
I'm closing this issue since it's no longer reproducible with the old version fully uninstalled, and with [WinMerge-2.16.26-x64](https://github.com/WinMerge/winmerge/releases/download/v2.16.26/WinMerge-2.16.26-x64-Setup.exe) installed.
