### ISSUE TITLE
If possible add support for (or to) Winget

### ISSUE THREAD

**Issue by TommiPrami** [WinMerge/winmerge#1449]
Hello, 

Would be cool to update Winmerge with winget.

I think here is further information how to do that: https://github.com/microsoft/winget-cli

-Tee-

**Comment by sdottaka** [comment]
The latest version of WinMerge, 2.16.22, can be installed with winget.

https://github.com/microsoft/winget-pkgs/tree/master/manifests/w/WinMerge/WinMerge
