### ISSUE TITLE
W11 Taskbar, Winmerge 2.16.20.0 doesn't appear to have an icon when called from shell context menu

### ISSUE THREAD

**Issue by slestak** [WinMerge/winmerge#1450]
<img width="182" alt="image" src="https://user-images.githubusercontent.com/79189/184194938-b2409e7d-c6fc-4d09-9ee6-c40eb0ac722d.png">

I am using 2.16.20.0 x64 on WIndows 11 21H2

**Comment by slestak** [comment]
Okay, checked windows Light mode, it is the same.

<img width="193" alt="image" src="https://user-images.githubusercontent.com/79189/184196616-2b119c48-b676-4f79-b660-6d2b86ee769b.png">

**Comment by slestak** [comment]
This was called using the shell context menu to select left file and compare on the second file. The icon does show when you launch WinMerge from the start menu.

**Comment by sdottaka** [comment]
Thank you for your report.
This issue has been fixed in the latest version 2.16.22, so could you try it?

**Comment by jiteshsuthar** [comment]
Issue is fixed in the latest version 2.16.22, you can close this issue.
