### ISSUE TITLE
Bug: Can't copy selected text, if it has non-changed lines

### ISSUE THREAD

**Issue by mambax7** [WinMerge/winmerge#1507]
I used to be able to highlight text that included both changed and not-changed lines, right click on it, and copy it:

![image](https://user-images.githubusercontent.com/613686/194344103-6135c936-ee91-4666-8129-544780c5d5a7.png)

In the latest version 2.16.22, I can't do it anymore - the "Copy" icons are not active anymore:

![image](https://user-images.githubusercontent.com/613686/194344462-e604d3c2-7cbe-4e10-be8f-94332db5e530.png)

**Comment by sdottaka** [comment]
Thank you for your report.
This issue, which I forgot to mention in the release notes, is fixed in version 2.16.23 beta.

https://github.com/WinMerge/winmerge/releases/tag/v2.16.23

**Comment by mambax7** [comment]
That's fantastic! Thank you so much!!

**Comment by mdell-seradex** [comment]
I was just going to report this as it happens using the toolbar buttons as well.
Glad to hear it already seems to be fixed.
