### ISSUE TITLE
Digitally sign packages

### ISSUE THREAD

**Issue by dotMorten** [WinMerge/winmerge#152]
Please digitally sign WinMerge, so users aren't met with this:
![image](https://user-images.githubusercontent.com/1378165/59446328-22dd3f00-8db6-11e9-9426-b7397882577d.png)

This is especially problematic because you ship your binary download on SourceForge, a website known for injecting "extra stuff" into downloads, and without a digital signature, there's no way to know if this install has been tampered with by any 3rd party.

There's a few free options out there for open source projects.

**Comment by gerundt** [comment]
Have you links to the few free options?

I only found a form from "GlobalSign SSL" for open source projects:
<https://www.globalsign.com/en/ssl/ssl-open-source/>

But I don't find the info if this are a certificate for web or for code signing. :-(

**Comment by dotMorten** [comment]
That looks like it's for web.
This one is only €25: https://www.certum.eu/en/cert_offer_en_open_source_cs/
Blogpost: https://blog.aluxian.com/free-code-signing-certificate-for-open-source-software-d836270823a7

Does WinMerge have a donate option? I'd be more than happy to be part of donating to the certificate, and I'm sure many others would too.

**Comment by myokeeh** [comment]
Wouldn't submitting to the Microsoft Store also address this? I'd gladly pay for a Store version.

**Comment by 0Knowledge** [comment]
Maybe this could help.
_"SignPath Foundation provides reliable code signing for Open Source projects"_ (https://signpath.org/) _"through SignPath.io"_ (https://about.signpath.io/product/editions and https://about.signpath.io/open-source)

**Comment by sdottaka** [comment]
The installer and other files will be code-signed starting with version 2.16.15, as it is now required for the Shell Extension for Windows 11 Explorer.

**Comment by Gitoffthelawn** [comment]
@sdottaka Which service did you wind up using for code signing?

**Comment by sdottaka** [comment]
I am using https://www.certum.eu/en/simplysign/.

You can see it in the Digital Signatures tab of the exe file properties window.

Note: Files built with CI will not be signed. Version 2.16.16 and 2.16.17 exe files are signed.
