### ISSUE TITLE
Feature request: "Size Difference" column

### ISSUE THREAD

**Issue by SLDiggie** [WinMerge/winmerge#1520]
In folder compare you can add columns for "Left Size" and "Right Size". Often I don't care what the absolute values are, what I care about is if something is substantially different, so "Abs Size Difference" would be nice. This way I can easily see what are small differences vs large ones.

**Comment by sdottaka** [comment]
Although not absolute values, it is possible to display the difference between the file sizes as follows.

![file_size_diff](https://user-images.githubusercontent.com/98126/195730055-e95a3e98-746b-47c7-aeb0-85540295325e.gif)
