### ISSUE TITLE
Please apply "Ignore carriage return differences" to folder comparison

### ISSUE THREAD

**Issue by mrengineer7777** [WinMerge/winmerge#1522]
WinMerge 2.16.22.0

"Ignore carriage return differences" works great on individual file comparison, but when comparing folders the files are all marked as different.

Context:
   Cloned https://github.com/espressif/arduino-esp32 repository using GitHub Desktop on Win10 machine
   Comparing to C:\Users\USERNAME\.platformio\packages\framework-arduinoespressif32\

The first download sets text file line endings to CRLF.
PlatformIO downloads packages as ZIP archive.  The extracted files retain UNIX line ending LF.
Thus every file is different, and it makes it impossible to find actual differences in repository.  WinMerge currently shows 8519 file differences, but I'm sure less than 1% have changed.

**Comment by sdottaka** [comment]
The "Ignore carriage return differences" option should also work for folder comparisons if the Compare method is "Full contents" or "Quick contents".
What is the Compare method selected?

![image](https://user-images.githubusercontent.com/98126/195967620-89279998-4c53-4d59-b753-7e8690ae035c.png)

**Comment by mrengineer7777** [comment]
Oh wow.  Somehow the Folder compare method had been switched to "Binary".  Selecting "Full Contents" restores the expected behavior.  Thanks so much!!!
