### ISSUE TITLE
IPV6 Compatibility- WinMerge 2.16.22.0

### ISSUE THREAD

**Issue by jbracco1180** [WinMerge/winmerge#1539]
UCOR is under OMB mandate M-21-07 which requires us to transition to IPv6 only by 2025.
--
  
1. Does the software/version support running on a dual stacked O/S with IPv4 with IPv6? 
2. Does software/version support running on an IPv6 only O/S? 
3. If so, do you have any special configuration instructions? |   |   |   |  
4. If not, do you have a timeframe for upgrading the application to support IPv6? |   |  
  |   |   |   |   |   |   |   |   |  
https://www.whitehouse.gov/wp-content/uploads/2020/11/M-21-07.pdf

UCOR is under OMB mandate M-21-07 which requires us to transition to IPv6 only by 2025.
1. Does XXX support running on a dual stacked O/S with IPv4 with IPv6?
2. Does XXX support running on an IPv6 only O/S?
3. If so, do you have any special configuration instructions?
4. If not, do you have a timeframe for upgrading the application to support IPv6?
[https://www.whitehouse.gov/wp-content/uploads/2020/11/M-21-07.pdf](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.whitehouse.gov%2Fwp-content%2Fuploads%2F2020%2F11%2FM-21-07.pdf&data=05%7C01%7CJoseph.Bracco%40orcc.doe.gov%7Caa6786337ca84fe5ce8708daa7c2e816%7C608ac2ea8edf4f00b054370d08dfa72d%7C0%7C0%7C638006752798005969%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=o0Vwp%2Bdnn6qJ%2BEHmPLBj86bO2Fd%2F%2FdpqEKm44IAs88M%3D&reserved=0)

**Comment by sdottaka** [comment]
WinMerge is an application that compares files or folders, so it does not perform any IPv4/IPv6-aware communication processing.

Of course, WinMerge can also compare network shared folders, but whether access to these shared folders is done over IPv4 or IPv6 depends on the OS settings, not on WinMerge.
