### ISSUE TITLE
Crash 0xc0000409

### ISSUE THREAD

**Issue by norrisgc** [WinMerge/winmerge#1544]
Just started using WinMerge, so not entirely sure what I need to report, but this is what is in the event log:

Faulting application name: WinMergeU.exe, version: 2.16.24.0, time stamp: 0x63594b61
Faulting module name: WinMergeU.exe, version: 2.16.24.0, time stamp: 0x63594b61
Exception code: 0xc0000409
Fault offset: 0x002533c2
Faulting process ID: 0x2ca0
Faulting application start time: 0x01d8eb7843ee030e
Faulting application path: C:\Program Files (x86)\WinMerge\WinMergeU.exe
Faulting module path: C:\Program Files (x86)\WinMerge\WinMergeU.exe
Report ID: eff1a79b-a5a8-4354-b559-9c2ba4a5a0e6
Faulting package full name:
Faulting package-relative application ID:

I had a three-way network drive compare open, and I started a binary compare on two matching files (i.e. only present on 2 of the three drives) and WinMerge almost immediately quit. (This is repeatable.)

W10 Pro x64 21H2.

**Comment by sdottaka** [comment]
So far I have not been able to reproduce this issue.
Could you please attach the text file displayed in the Help→Configuration menu item?
(Note: If the text file contains personal information, please replace that part)

**Comment by norrisgc** [comment]
[WinMerge.txt](https://github.com/WinMerge/winmerge/files/9893841/WinMerge.txt)

I should probably note that the files in question are large: about 500GB, so you may need some substantial files to test this.

**Comment by sdottaka** [comment]
Thank you for the information. 
I was able to reproduce this issue.
The cause of this problem is that the binary editor (frhed) in WinMerge does not support file sizes larger than 2 GB.
This binary editor does not have the ability to read a partial file, but tries to read the entire file into memory. Thus, even if it did support file sizes larger than 2GB, a file size of 500GB would require 500GB of memory.
At the moment, I can only come up with a countermeasure that would simply prevent it from crashing.

**Comment by norrisgc** [comment]
Although not ideal, it would clearly be better for it to say "I can't do that" than to crash with no indication of what's wrong!

**Comment by sdottaka** [comment]
The following commit fixes this crash.

https://github.com/WinMerge/winmerge/commit/327290d06a1a406d9273af0e32d31e47ca1d30e5

Thank you for the report.

**Comment by mdell-seradex** [comment]
I do not know if this helps, but it appears that frhed added support for partially opening large files in stable release 1.6.0, although it appears that it was split off from the version that WinMerge uses years before that.
