### ISSUE TITLE
Selection in "Replace" by regular expression doesn't work with \n

### ISSUE THREAD

**Issue by www1800** [WinMerge/winmerge#1556]
Hi,

Let's say we have the below four lines:
```
1
2
3
4
```

Ctrl+A to select all, and Ctrl+H to do a replacement as follows:
![image](https://user-images.githubusercontent.com/61829207/199676215-2b141f9e-f00e-45df-8ad4-926fe700a43c.png)

Find (\w+) and replace with \1\n
click "Match case" and "Regular expression"
Replace in "Selection" then "Replace All"

![image](https://user-images.githubusercontent.com/61829207/199676482-f9c78222-5403-4178-bc4d-94ab44b3d073.png)

It becomes
```
1

2

3
4
```

Last two are missing to be replaced.
P.S. Replace in "Whole file" works fine.
Thanks.

**Comment by www1800** [comment]
Version: 2.16.24-x64 on Win11

**Comment by sdottaka** [comment]
Fixed in commit [7532ea4](https://github.com/WinMerge/winmerge/commit/7532ea478a74c5a3df6eca0805dc47556558d5fd)
Thank you for the report.
