### ISSUE TITLE
TreeView option grayed out, not working, but can be hackfixed

### ISSUE THREAD

**Issue by Domiii** [WinMerge/winmerge#1567]
* Windows: 10
* Winmerge: `2.16.14`

## Scenario

1. I set `winmerge` as a `difftool`: `git config --global diff.tool winmerge`
2. I want to diff directories, so I use the `--dir-diff` option, like so: `git difftool HEAD HEAD~4 --dir-diff`
3. Problem: It now opens in this weird mode, where it only shows one folder at a time for some reason, making it a pain to understand where you are as you navigate, and what all the files are etc.
4. Problem: `View` → `TreeView` is grayed out. (I made sure that `Include Subfolders` is enabled in options)

## Workaround

1. `Edit` → `Options` → `Ok` (change nothing, its just a necessary stupid step)
2. `Refresh` (F5)

→ It magically works now.

NOTE: You might also want to do `View` → `Expand All Subfolders` (or `ALT → V → C`)

**Comment by sdottaka** [comment]
Perhaps you are not using the WinMerge command line option `-r`. If you want to start WinMerge from the command line and compare folders recursively, use the `-r` option.

**Comment by Domiii** [comment]
> Perhaps you are not using the WinMerge command line option `-r`. If you want to start WinMerge from the command line and compare folders recursively, use the `-r` option.

hi @sdottaka and thank you for the fast reply!

I am not aware of any way to change winmerge's [`difftool`](https://stackoverflow.com/questions/1881594/use-winmerge-inside-of-git-to-file-diff) args, other than replacing the built-in `winmerge` with a custom `difftool`?

Would you say that `-r` should be default for [the `difftool` command](https://stackoverflow.com/questions/1881594/use-winmerge-inside-of-git-to-file-diff)? Or how do I go about doing it on my end. short of replacing standard `winmerge` with my own custom `difftool`?

**Comment by sdottaka** [comment]
I am not familiar with git, so the only way I know of to pass `-r` command line option to WinMerge is to define a custom difftool as described at https://stackoverflow.com/a/25982242.

**Comment by Domiii** [comment]
It still does not make much sense that that thing is grayed out, does it?

It makes even less sense for it to start working as intended after saving the settings once (without changing anything)?

**Comment by sdottaka** [comment]
> It still does not make much sense that that thing is grayed out, does it?

If the `Include Subfolders' option or the `-r` command line option is not enabled, recursive folder comparisons are not performed.
'Tree Mode' is grayed out because it makes no sense for non-recursive folder comparisons. (Note that the `Tree Mode' and `Include Subfolders' options mean different things.)

> It makes even less sense for it to start working as intended after saving the settings once (without changing anything)?

There is also an "Include Subfolders" checkbox in the Options dialog, but it is set to the global setting (checked), not the value of the current folder comparison window (unchecked).
When OK is pressed, it is reflected in the folder comparison window, so that if the comparison is performed again, a recursive comparison is performed.

I believe this needs some improvement, but there are no plans at this time.

**Comment by Domiii** [comment]
The program deciding to ignore global settings, and always expecting a local override makes little sense to me. Yes it definitely needs some improvement 😅

Either way, thanks for taking the time to clarify!

**Comment by ewerybody** [comment]
This thing is bugging me eeeeeeeeeeevery time. I mean I have different and sometimes new setups to maintain so I stumble over it again. NOW: It just happened again and here is how I fixed it this time:

* View > Tree Mode was greyed out
* **Include Subfolders** WAS already ticked!!
  > ![image](https://user-images.githubusercontent.com/218956/210286166-3b277ca9-7e38-4a87-a43e-3c1bc6240163.png)
* And so was the option on this toolbar options menu:
  > ![image](https://user-images.githubusercontent.com/218956/210286260-c268f752-0d76-44c4-b6af-c94fa968ea99.png)
* I just unchecked **Include Subfolders** in the the toolbar options menu
* ticked it again
* Voilà

So there must be something between showing the checked **Include Subfolders** option but not yet allowing Tree Mode.

**Comment by ewerybody** [comment]
I just figured this hack fix ^ setting is **not permanent**.
I have to do this **EACH TIME** I want to diff folders now 😞

**Comment by AlanMiltonETS** [comment]
The issue is a showstopper. It effectively disqualifies WinMerge from Git scenarios especially when KDiff3 is available.
I hope the developers fix it soon.

**Comment by sdottaka** [comment]
@AlanMiltonETS @ewerybody Are you running WinMerge from the command line? If so, have you tried the `-r` command line option?

**Comment by AlanMiltonETS** [comment]
Yes, I am running it from a command line like this:
```
git difftool -d
```
Obviously, adding -r is not working in this scenario. Of course, there is a way of configuring the difftool manually, ignoring the existing support for WinMerge in Git, but I did not find in the documentation instructions on how to do it.
Being an ordinary person I would prefer using simple solutions, like continuing using KDiff3, which does not have such problem, and waiting for the next version of WinMerge to give it a try, unlike working through the Git manuals and trying to learn how to make a difftool configuration and maybe a script for the existing version of WinMerge.
I hope you would understand why I am calling the issue a showstopper.

**Comment by sdottaka** [comment]
Try adding `-r` to the WinMerge command line in the .gitconfig file as follows.

%userprofile%\.gitconfig

~~~
[diff]
	guitool = winmerge
	tool = winmerge
[difftool "winmerge"]
	path = C:/Program Files/WinMerge/winmergeu.exe
	cmd = \"C:/Program Files/WinMerge/winmergeu.exe\" -r -e -u \"$LOCAL\" \"$REMOTE\"
~~~

If I changed WinMerge's behavior to recursively compare if the current 'Include subfolders' setting is ON even if `-r` is not specified, it would be incompatible. So I didn't want to change this behavior, however, maybe not too many people care...

**Comment by ewerybody** [comment]
Works with the added `-r`! 👍

But still:
![image](https://github.com/WinMerge/winmerge/assets/218956/ee7b3a23-6d10-495f-892e-7af827d9882e)
having that checked and not seeing the expandable folders,
then **ticking it off and on** again and then **F5** and it **works**.
Isn't there clearly something broken? 🤔

**Comment by sdottaka** [comment]
As of version 2.16.32, the option value of "Include subfolders" is respected if the command line option /r is not specified. Conversely, if you want a non-recursive comparison, specify the /r- command line option.
