### ISSUE TITLE
Redundant calls of CCrystalTextView::RecalcVertScrollBar and RecalcHorzScrollBar 

### ISSUE THREAD

**Issue by hordi** [WinMerge/winmerge#1573]
When load big files next two functions executed at least 12-16 times during loading data (without even touch any mouse/buttons etc).
If compare 2 files about 200-300MB each and if disable (return from top of the functions) these functions - I save at least 15 seconds.
Plus not needed to use smooth+redraw parameters if this window not visible - so need to refresh it one time only when all data loaded and processed.

https://github.com/WinMerge/winmerge/blob/10d7d0853823c47a165d15aba778496200a3fc10/Externals/crystaledit/editlib/ccrystaltextview.cpp#L4173

https://github.com/WinMerge/winmerge/blob/10d7d0853823c47a165d15aba778496200a3fc10/Externals/crystaledit/editlib/ccrystaltextview.cpp#L4082

**Comment by sdottaka** [comment]
Fixed by PR #1574
