### ISSUE TITLE
WinMerge hangs for a certain regex search & replace action for clearing all lines not containing '%'

### ISSUE THREAD

**Issue by orshwartz** [WinMerge/winmerge#1575]
1. Open WinMerge.
2. Click on the New Documents icon.
3. Type in the following document on the left side (the letter `d` followed by an empty line):
```
d

```
4. Click Ctrl+H to bring up the "Replace" window.
![image](https://user-images.githubusercontent.com/11471295/202347816-a698d5e0-9df9-490a-8724-f32db6cb2b36.png)
Fill in the following fields as follows:
Find what: `^[^%]*$`
Replace with:
and run a "Replace All" with regular expressions for the whole file.

The result is WinMerge hangs (unresponsive windows with a spinning blue circle cursor).

The purpose of this Search and Replace I was trying to do was to clear all lines not containing `%`.

_Using WinMerge 2.16.22.0, X64, Microsoft Windows [Version 10.0.22621.819]_

**Comment by sdottaka** [comment]
Fixed in commit [61e6dd3](https://github.com/WinMerge/winmerge/commit/61e6dd359218f4cdc0c0ba30cbdd48d0148e2074)
Thank you for the report.
