### ISSUE TITLE
Updating of Galician language

### ISSUE THREAD

**Issue by P0rsche-911** [WinMerge/winmerge#1581]
I provide the Galician language update.
Apologies if I do something wrong. I am new to these topics.

Aporto la actualización del idioma gallego.
Disculpas si hago algo mal. Soy nuevo en estos temas.

[WinMerge galician mo.zip](https://github.com/WinMerge/winmerge/files/10050453/WinMerge.galician.mo.zip)

[WinMerge galician po.zip](https://github.com/WinMerge/winmerge/files/10050454/WinMerge.galician.po.zip)

**Comment by sdottaka** [comment]
Merged in commit https://github.com/WinMerge/winmerge/commit/14f0e8f58067975fded40435c3fe9c19100fda0c

Thank you for the translation.
