### ISSUE TITLE
Syntax highlighting for SQL leaves many things out.

### ISSUE THREAD

**Issue by mdell-seradex** [WinMerge/winmerge#1583]
I noticed when attempting to apply syntax highlighting (i.e. font formatting) for SQL files that many things were left unformatted.
Examples: many keywords such as "DECLARE", "CURSOR", "WHILE", "BEGIN", variable names, data types, the alias qualifier keyword "AS".
I was hoping to alter a configuration file to get it to recognize those, but I could not find one.

Is there a way we can modify this?  Alternatively, can this be updated to support more keywords, etc?

Thank you

**Comment by mdell-seradex** [comment]
Cool.  Thanks for the update.
It is most appreciated.
I wasn't sure if I was missing something or not.
I notice that "DECLARE", "CURSOR", "FETCH", and "NEXT" weren't included.  Can they be added?
I get build a list of additional keywords, and possibly data types, if you think that would be useful.

**Comment by sdottaka** [comment]
Pull request is welcome

**Comment by sdottaka** [comment]
"DECLARE", "CURSOR", and "FETCH" were added by PR #1591.
