### ISSUE TITLE
Directory compare: files with leading dashes "-" are not handled correctly

### ISSUE THREAD

**Issue by tommaso-b** [WinMerge/winmerge#1600]
When comparing 2 directory trees recursiveley.
I have identical files in both trees, where the file names starts with a dash + space, example:   "- xxxxxfile.txt"
Altough identical files exist in in each tree, the compare report says:
"- xxxxxfile.txt"     Left only
....
"- xxxxxfile.txt"     Right only

Files without leading dash are being compared correctly. if space after dash has an impact is not known.
Using V 2.16.24.0 on win10

**Comment by sdottaka** [comment]
I could not reproduce this problem as shown in the attached image below.

![image](https://user-images.githubusercontent.com/98126/205933707-e91d3677-30c4-466a-9e38-961682a016d0.png)

Could it be that the characters in the filename on one side are not dash, but similar characters?

There are several characters similar to dash, as shown below.


~~~
–
−
–
—
~~~

**Comment by tommaso-b** [comment]
THX for looking into this.
I tried to collect data for a test case. When building several scenarios (and trying them out in winmerge) I noticed that the "left only" / "right only" reporting happens only, if I place the directory trees on 2 drives with different disk formats.
NTFS + FAT32 => left only / right only reporting
NTFS + NTFS => all matching
Seems that FAT32 is storing file names differently (although no FAT32 file name rules have been violated, length etc.)
Even more strange: As soon as I perform simple delete + restore operations in the FAT32 directoy, the comparison result switchs over to "all match". As if some missing attribute of the directory had been set by these dummy operations.
=> this is not a winmerge issue, please close
