### ISSUE TITLE
Mark files with filtered difference as "Identical" in folder differences

### ISSUE THREAD

**Issue by OshidaBCF** [WinMerge/winmerge#1603]
I have a lot of files that have a lot of difference each, and i need to make a report of "some" of those differences, a lot of useless difference are already filtered so when i open some file they already appear as "identical", but in the Folder view it doesn't show as identical, so it still count it as different. Could it be possible to make apply the filters "before" opening the file, even if it takes more time i frankly do not care.

It would save me a couple hours every time i have to do it.

**Comment by sdottaka** [comment]
If the folder comparison method is "Full contents", the comparison results of the files and the comparison results of the files in the folder comparison should match.

What is your folder comparison method of choice, and what line and substitution filters are you using?
If the folder comparison method is "Full contents", could you please attach the files in question so that we can reproduce them?
![image](https://user-images.githubusercontent.com/98126/206898439-1e2fd251-597d-4a6f-806e-5faf9f53d6e4.png)

**Comment by OshidaBCF** [comment]
[a_20g_30_ussr_right.txt](https://github.com/WinMerge/winmerge/files/10201929/a_20g_30_ussr_right.txt)
[a_20g_30_ussr_left.txt](https://github.com/WinMerge/winmerge/files/10201930/a_20g_30_ussr_left.txt)

",\r\n        "onKill": {\r\n          "nothing": 100\.0,\r\n          "cut": 0\.001\r\n        }" -> ""


Those are two exemple files, on line 1134 there is a difference that is ignored by the filter just above, but the file is still shown as "different" in folder comparaison, i am in "Full content" but it doesn't seem to remove "ignored" difference
![image](https://user-images.githubusercontent.com/61458287/206898804-cbafe4d3-abc4-41da-9720-992e63d5a8a7.png)
I cannot send you more files nor all the filters because i use roughly 30 and the files are a around 35k on each sides

**Comment by sdottaka** [comment]
Thank you for attaching the files.
I tried applying the Substitution filter above with those files, but the folder comparison also showed "Text files are identical".
Note: The above filter string didn't apply well, so I've modified it a bit.

![image](https://user-images.githubusercontent.com/98126/206900409-7af86760-9b22-490d-935a-507acbfd8b64.png)

**Comment by OshidaBCF** [comment]
Well that's weird... i guess

My version is 2.16.23.0 maybe you have another one ?

**Comment by sdottaka** [comment]
The latest version is 2.16.24. But 2.16.23 gave the same result.

In addition, as written above, the regular expression is changed as follows.
~~~
,\n\s+"onKill": {\n\s+"nothing": 100.0,\n\s+"cut": 0.001\n\s+}
~~~

**Comment by OshidaBCF** [comment]
It's not working anymore... it doesn't seem to be really stable, now even if i edit the filter it doesn't ask me if i want to refresh the folder difference.

it's very weird
