### ISSUE TITLE
double click selection bug

### ISSUE THREAD

**Issue by oleg620** [WinMerge/winmerge#1608]
In the text editor, move your cursor to a middle of a word and double click. The entire word is selected (good). 

![image](https://user-images.githubusercontent.com/3631882/207990210-1462461d-e718-4e2d-b9aa-0144241f7381.png)

Now try to expand the selection by pressing Shift and an arrow key (or by clicking your mouse further in the text).

**Expected**: Selection should expand.
**Actual**: The first part of the original word is no longer selected!

![image](https://user-images.githubusercontent.com/3631882/207990294-209f1931-95f4-456a-a2d7-e18a8f95995f.png)

This has been like this for many years. It's similar to https://github.com/WinMerge/winmerge/issues/109, but hasn't been fixed.

**Comment by sdottaka** [comment]
I was unable to reproduce this issue. It seems that you are using an old version of WinMerge. Could you please try using the latest version? https://github.com/WinMerge/winmerge/releases/tag/v2.16.24

**Comment by oleg620** [comment]
@sdottaka , indeed, I was on 2.14. I upgraded and the bug is gone. Thank you so much!
