### ISSUE TITLE
compare uses Create Date, want it to use Date

### ISSUE THREAD

**Issue by laurijh** [WinMerge/winmerge#1634]
I have copied some images to a separate folder but I don't know for sure that I copied, rather than moved them so I want to compare the folders. Since the files were copied, the create date is the copy date, but in both cases the "date" field has the original date which is the date field I want to compare against. Even comparing by file name would work but I don't see that option.

**Comment by sdottaka** [comment]
I think I may not have understood exactly what you want to do, but with WinMerge, you can compare only the modification date and time of the files as follows: 
![image](https://user-images.githubusercontent.com/98126/209666398-d5ff5ed6-f95d-4379-aa12-d8e9ab158579.png)

It is not possible to compare the creation date and time of the files, but you can add a column for the creation date and time of the files as follows:

![image](https://user-images.githubusercontent.com/98126/209666644-94d325af-28c1-4b6a-b838-956af4ec394d.png)

**Comment by laurijh** [comment]
It's the creation date I want to compare and I want to see the files that are identical. These are photos and I found another program that will do what I want (with a few modifications on my part). I have some documents that also need compare so I will try winmerge with those. Just trying to clean up my laptop. Thanks for the reply.
