### ISSUE TITLE
CSV don't get separated in columns

### ISSUE THREAD

**Issue by OshidaBCF** [WinMerge/winmerge#1637]
I have a couple CSV that refuse to separate each values into different columns

Here is one of them for exemple
[units.csv](https://github.com/WinMerge/winmerge/files/10308625/units.csv)

![image](https://user-images.githubusercontent.com/61458287/209678915-0f91a9ec-012f-4940-9883-30b61805d7c4.png)
Here's how my settings looks

**Comment by sdottaka** [comment]
The attached file has an extension of csv, but it seems to be separated by semicolons, not by commas.
To view the semicolon delimited file in table view, reopen it using the File->Recompare As menu item as shown below.

![image](https://user-images.githubusercontent.com/98126/209683762-1640d796-8032-4f62-9645-1b1a8c60cba4.png)

**Comment by OshidaBCF** [comment]
I seeeeeee

Any way to make this "permanent" ?

All my CSV are in this format and cannot be changed by me without breaking things

**Comment by OshidaBCF** [comment]
Also it is possible to look at differences only on the "nth" column

As those are lang files, i only need to check if the English column changed

**Comment by sdottaka** [comment]
> Any way to make this "permanent" ?

Please set as follows in the Options dialog

![image](https://user-images.githubusercontent.com/98126/209685794-6bdcc7fb-238c-4c1f-8520-42f7bcc43030.png)

> Also it is possible to look at differences only on the "nth" column

You can use the IgnoreCommaFields plugin to ignore columns for comma-separated files, but unfortunately semicolon-separated files are not supported.

**Comment by OshidaBCF** [comment]
Sweet, working perfectly
