### ISSUE TITLE
Some filters make every differences get ignored

### ISSUE THREAD

**Issue by OshidaBCF** [WinMerge/winmerge#1639]
I just updated my winmerge from .23 to .24, and for some reasons, some filters makes every difference break.

I use a lot of filters but i lost them when updating form 23 to 24.
While remaking them, it seems that some filters remove every differences in the file.

In the two .txt i given, and in the image, the "checked" filters remove all the differences, while the others works without real problem. but the two last sometime works

I thought at first the filter finished with an * but it doesn't, and before i updated it was working perfectly.

If you have any fix i'll take it
![image](https://user-images.githubusercontent.com/61458287/209718613-6209c711-82e8-4eae-a743-830e7ca98b47.png)

[wpcost.txt](https://github.com/WinMerge/winmerge/files/10310535/wpcost.txt)
[wpcost.txt](https://github.com/WinMerge/winmerge/files/10310537/wpcost.txt)

**Comment by OshidaBCF** [comment]
I just tested something and it's even weirder, i changed one of not working filter to " ," and while it's the only single filter selected, it still remove every differences


Where are differences "saved", i guess in the registry of the pc but i don't know where, maybe the old installation corrupted some part of the new one.

**Comment by sdottaka** [comment]
I have tried adding the above line filter and comparing the attached files, but so far have not been able to reproduce the issue of all differences being removed.

**Comment by OshidaBCF** [comment]
Well i just remade all the filters, and i don't have any problem anymore

I think that the previous installation didn't fully removed the previous filters, so the new installation probably had some error with some line numbers, it seem to be fixed now, and with the other issue that got fixed it shouldn't ever happen anymore
