### ISSUE TITLE
Files not appearing in Winmerge that do appear in the Windows folder

### ISSUE THREAD

**Issue by Vdarth200** [WinMerge/winmerge#1650]
I'm trying to compare to folders on my external HDD. The comparison results only shows folders and files on the right side. Yet the left folder contains some subfolders and a PDF file. My results is also showing a red exclamation mark. What does that mean? How would I find the explanation?
[Winmerge Issue 1-7-2023.docx](https://github.com/WinMerge/winmerge/files/10366709/Winmerge.Issue.1-7-2023.docx)

**Comment by sdottaka** [comment]
What is the status of the "Include unique subfolders contents" checkbox in the Compare/Folder category of the Options dialog and the View→Show Left Unique Items menu item? 

![image](https://user-images.githubusercontent.com/98126/211173759-5db1ead7-c853-4df8-85bf-c23ee7aadf5d.png)
![image](https://user-images.githubusercontent.com/98126/211173777-fb2c1eda-a4b0-46dd-a6c0-d94dabfc74af.png)

Please refer to the following for the meaning of the icons
https://manual.winmerge.org/en/Compare_dirs.html#Compare_dirs_window
