### ISSUE TITLE
Feature request: Allow pasting when editing caption of pages

### ISSUE THREAD

**Issue by Andrew-Staves-Activ** [WinMerge/winmerge#1651]
When editing the caption of pages, it is possible to copy the caption but it is not possible to paste a new value.
![image](https://user-images.githubusercontent.com/32958622/211161269-edc3b5ec-2a4d-4005-99fb-15cb0833fcf7.png)

(Keyboard shortcuts behave similarly - e.g., Ctrl + C copies but Ctrl + V does not paste.)

I would like to have the option to paste into the caption box.

Thanks!

**Comment by sdottaka** [comment]
Implemented in commit 54da23b.
