### ISSUE TITLE
Request: highlight the file after opening its parent folder

### ISSUE THREAD

**Issue by dimailer** [WinMerge/winmerge#1662]
any file > right mouse button > Open Left / Open Right > Open Parent Folder

once the parent folder opens, can we have the file highlighted so we don't have to look for it?

thank you

**Comment by sdottaka** [comment]
Commit dd3f583 implements this feature.

**Comment by dimailer** [comment]
> Commit [dd3f583](https://github.com/WinMerge/winmerge/commit/dd3f5836cb779670e4dc9b58c9da2a96e704ae17) implements this feature.

thank you very much
