### ISSUE TITLE
TypeInfo now saved in settings export files - intentional or a bug?

### ISSUE THREAD

**Issue by Gitoffthelawn** [WinMerge/winmerge#1691]
I noticed that the size of settings export files recently increased by about 100%.

The reason is that a new `TypeInfo` section is now saved, which contains the data type (bool, string, int, etc.) of each item.

Was this change intentional, or is it a bug?

**Comment by sdottaka** [comment]
This change is intentional to fix issue #1638.

**Comment by Gitoffthelawn** [comment]
Thanks Takashi.  That's good.  Closing.
