### ISSUE TITLE
3-way compare does not properly align identical lines when resolving conflicts, and show false highlights

### ISSUE THREAD

**Issue by mambax7** [WinMerge/winmerge#1696]
I'm using WinMerge to resolve conflicts between various commits on GitHub. 
Recently the identical lines don't align, e.g. in this picture, the "Base" and "HEAD" are the same, but they are shown in different lines, and they have false highlights. Is it because of being "multi-line" difference?
![image](https://user-images.githubusercontent.com/613686/215339704-2b4da251-65a0-4dc3-9554-e83acd7e4a98.png)

**Comment by sdottaka** [comment]
Disabling the Align similar lines option in the Options dialogue box, as shown below, should give the expected result.
This needs to be improved, but it can be difficult.
![image](https://user-images.githubusercontent.com/98126/215485109-56330552-ec65-4a87-a8f1-33c4cc4b09fc.png)

**Comment by sdottaka** [comment]
This issue has been fixed in commit 6816404.
Thank you for the report.

**Comment by mambax7** [comment]
Thank you so much! That's awesome!
