### ISSUE TITLE
may add new feature : show/hide  the same text content?

### ISSUE THREAD

**Issue by pyNpy** [WinMerge/winmerge#1697]
question: is there possible to add  1  button ,in order to show or hide  the same text content  ?
the reason  :
 in  the software of  Beyond Compare4 , have  the button which named  "Diffs" ,"Same" , it is  convenient to display different text ,  or  show  the same text .  I think it will be more nice to  have a look to compare the diff text .

![image](https://user-images.githubusercontent.com/19249459/215406576-8655ca16-0d34-4a74-bed5-2649db44fe49.png)

**Comment by pyNpy** [comment]
just a  small suggestion.

**Comment by sdottaka** [comment]
If you select the [View]→[Diff Context]→[0 Lines] menu item, does it display as you expect?

![image](https://user-images.githubusercontent.com/98126/215480821-0d811727-1197-491a-84bb-6b814f1ead89.png)

![image](https://user-images.githubusercontent.com/98126/215480675-2804cd65-aa15-4803-ae8a-667ea9ee8562.png)
