### ISSUE TITLE
Installer: components step unclear about "Patch GnuWin32"

### ISSUE THREAD

**Issue by Chealer** [WinMerge/winmerge#1698]
When installing WinMerge 2.16.26.0, the step offering to select components contains the option (in French):

> Patch GnuWin32 pour Windows/HTML Tidy/jq/md4c

While I know what HTML is and assume that "Windows" refers to Microsoft Windows, with this label and no description, I for one have no idea what this option provides, nor what are its drawbacks.

**Comment by sdottaka** [comment]
In English it looks like this:
GnuWin32 Patch for Windows/HTML Tidy/jq/md4c

Above are the commands to use with each plugin. The relationship between plugins and commands is as follows. Required to use the plugins below.

|Plugin name|Command|
|-------------------|----------------|
|ApplyPatch|GnuWin32 Patch for Windows|
|PrettifyHTML or PrettifyXML|HTML Tidy|
|PrettifyJSON or QueryJSON|jq|
|PreviewMarkdon|md4c|

**Comment by sdottaka** [comment]
In commit 444ecde, the GnuWin32 Patch for Windows/HTML Tidy/jq/md4c was removed from the Select Components page of the installer and changed to install them when Plugins is selected.

**Comment by Chealer** [comment]
> In English GnuWin32 Patch for Windows/HTML Tidy/jq/md4c
> 
> Above are the commands to use with each plugin. The relationship between plugins and commands is as follows. Required to use the plugins below.
> Plugin name 	Command
> ApplyPatch 	GnuWin32 Patch for Windows
> PrettifyHTML or PrettifyXML 	HTML Tidy
> PrettifyJSON or QueryJSON 	jq
> PreviewMarkdown 	md4c

Thank you very much for the clarification. The slash is not used to separate multi-word terms, so my understanding of the label was completely broken (I thought "Windows/HTML" was some component of Microsoft Windows).
