### ISSUE TITLE
"Folders are different" but do not expand

### ISSUE THREAD

**Issue by MrTobyDog** [WinMerge/winmerge#1705]
Version 2.16.26 (X64). Shows "folders are different" for folder mod_favslider in attached screen dump but it will not expand the folder to show the differences. A check in File Explorers shows at least one difference. I have set it to "expand all subfolders". 
[WinMerge.txt](https://github.com/WinMerge/winmerge/files/10609916/WinMerge.txt)
![Screenshot 2023-02-05 110357](https://user-images.githubusercontent.com/6834935/216794735-befb40d9-3dc9-4a05-b7d8-ff6ce37af8d7.png)

**Comment by sdottaka** [comment]
This may be because you are hiding binary files. What happens when you check the View → Show Binary Files menu item?

![image](https://user-images.githubusercontent.com/98126/216795127-6402de1c-fcb5-4a5f-9521-d1ebf5de6d1b.png)

**Comment by MrTobyDog** [comment]
Ah yes - that fixes it. Many thanks

**Comment by MrTobyDog** [comment]
This seems to have surfaced again for me - now on 2.16.40. The setting of Show Binary Files seems to make no difference,

**Comment by sdottaka** [comment]
Please tell me which menu items are unchecked in the View menu.
Also, could you post a screenshot of a folder comparison in WinMerge, and a screenshot of the Explorer folder containing files not displayed in WinMerge?

**Comment by MrTobyDog** [comment]
Thanks for that.
I attach a screenshot of WinMerge - as you can see language/overrides
folder is flagged as different and I can expand it, whereas
plugins/actionlogs is flagged but I can't expand.
I also show the View menu and a comparison of the two actionlogs folders.
Changing the View->Show Binary Files made no difference
Regards
Dave

**Comment by sdottaka** [comment]
GitHub supports replying to issues by email, but unfortunately, it doesn't seem to support attachments. This means I can't see the images you attached.
Could you attach the images to the GitHub issue?

**Comment by MrTobyDog** [comment]
As requested. Thanks
![Screenshot 2024-07-16 085329](https://github.com/user-attachments/assets/cb012194-5644-4347-8f0c-abd3b4f6f8ad)
![Screenshot 2024-07-16 085522](https://github.com/user-attachments/assets/0e65b8db-62a9-4af7-bc39-d0fa13468bd9)

I attach a screenshot of WinMerge - as you can see language/overrides folder is flagged as different and I can expand it, whereas plugins/actionlogs is flagged but I can't expand.
I also show the View menu and a comparison of the two actionlogs folders. Changing the View->Show Binary Files made no difference
![Screenshot 2024-07-16 085024](https://github.com/user-attachments/assets/3ba984c7-6bb9-47a3-bbef-fe2ae7186164)

**Comment by sdottaka** [comment]
Thank you for posting the screenshots.
I think the reason you can't expand the plugins/actionlogs folder is because the Show Left Unique Items and Show Right Unique Items menu items in the View menu are unchecked. If you check those menu items, you should be able to expand the folder.

**Comment by MrTobyDog** [comment]
Ah yes - that works fine. Thank you
