### ISSUE TITLE
Alarmingly bad translations implemented again for Swedish

### ISSUE THREAD

**Issue by timint** [WinMerge/winmerge#1706]
Some time ago I remember renovating the Swedish translations for this app. Work that took several days. I fixed gramatical errors, i corrected words by using the right terminology, and changed odd words to words that are more commonly recognizable.

Now there are several commits by a user @pgert that has managed to turn everything upside down. He is inventing new words no one has ever spoken. He uses some words that no one has used for the last 300 years. Inconsistent use of terminology. Gramatic errors. And mixed foreign gramatic standards (not swedish).

It is so bad I have to ask project maintainers to step in and take control. Stop accepting commits from this user. And if you can't take my word for it, try see if you can get this confirmed by proper translators.

Yes, it IS that bad!

**Comment by pgert** [comment]
You are free to make Pull Requests,
 through which you can be specific in your dislike.
I don't object.

**Comment by timint** [comment]
I will make another pull request. Please don't ruin it. It's one thing if you do it in your own blog. But distributing this nonsense is just wrong. Per definition nonsense means "spoken or written words that have no meaning or make no sense".

I will of course try to give you some feedback:

- What exactly is a "skriftläge" and what's wrong with the actual term "skiftläge"?

- "Skripter" (plural) there is no such thing. It's "ett skript, två skript" or generally just "skript".

- "HTML'ar" no we are not french, we don't use single quotes in our language. But even if you put it "HTMLar" that's not even a word. one traffic, two traffic - no just traffic. I know that the original translation was HTMLs, which is not a thing too. But HTML'ar is just tripple wrong.

- "Förhandsvisning" is when you get to see a movie in the cinemas before anyone else. The term is "Förhandsgranskning" to preview a result. There are many odd synonyms that you injected that is not accurate or simply is not better than the words you replaced.

- You replace "Gör om" with "Omgör" which is not a word I have heard anyone use. Your Office suite as well use "Gör om". The fact that you replaced it makes me wonder if this is some dialectal word locally used where you live?

- "All Profil" should be "Allprofil". "Skum tomte" or "skumtomte" different meaning. Read up on [skrivihop.nu](http://skrivihop.nu/).

- You changed "ändringsdatum" to "filtid" and that is one weird term. Is it of extraterrestial origin? 😁

- The pronoun "Ni" hasn't been used much for singularis in sweden for 300 years. And back then it wasn't very polite. Stop using "ni" or even worse "Ni". You are talking to the person at the screen, always put "du".
> Att nia anses oartigt i Sverige
https://sprakkonsulterna.se/tilltal-med-du-eller-ni/
 
You swapped out "Skriptredigerare" to "redigerarskript". That's a totally different meaning. "steering wheel or wheel steering". Why would you do that?

"skriftläges-känslighet", we don't do hyphens unless it's abrevations like TV-stand. It's "Skiftlägeskänslighet" but consider reversing it if words get alarmingly long. "Känslighet för skiftläge" would also be ok to use.

"Ändrat Datum" we don't capitalize nouns in the swedish language, germans do. Stop doing that. It's allover this file.

"This Is Not a Correct Title" Stop capitalizing characters in titles. We don't do that either and and this is elementary. Sweden is so allergic to capitalizing the first letter of words not even government instances get their names capitalized. "My friend works at skatteverket". Only names of people, countries, cities or the first word of a sentence gets to have it's first letter capitalized. Yes, even for titles!

This is very time consuming..
Please understand that you are not making anyone a favour by inventing your own grammatic standards or words. Escpecially when you are replacing perfectly good translations.

**Comment by sdottaka** [comment]
@timint
Thank you for the report.

@pgert
Thank you for continuing the translation.

I don't understand Swedish, so I can't judge the quality of the translation, but a guideline is the following document

https://download.microsoft.com/download/5/0/9/5095f52b-dd67-4951-9afa-c15bb1696a4a/swe-swe-StyleGuide.pdf

For example, capitalization is described in 4.1.5 Capitalization, so I would appreciate it if you could translate with reference to that.

**Comment by timint** [comment]
@pgert I put paid work aside for two days just to do this pro bono. This is done by the book. Please don't wreck it again.

@sdottaka See if you can find someone to quality check my pull request. Otherwise take my word for that anything is far better than what you have right now - a total disaster.

**Comment by sdottaka** [comment]
@timint 

Thank you for the PR.

I have translated the various English words used in WinMerge into Swedish using Poedit's Suggestion feature and the Microsoft Language Portal below.
As a result, I have merged your PullRequest as I feel that your PR uses more appropriate words.

https://www.microsoft.com/en-us/language/Search?&searchTerm=Undo&langID=750&Source=true&productid=undefined

However, you translated the English word folder to katalog, which I believe corresponds to the English word directory, so I felt the previous translation (mapp) was better.

In order to avoid conflicts regarding translation, it would be helpful if you could use a tool like the above for a more general translation.

**Comment by timint** [comment]
@sdottaka Thank you. 👍

Indeed I would literally translate "katalog" to "directory". After rolling back changes I found the use of both and thought I would consistify it by keeping it to one. I would say "mapp/folder" is the less formal, more sloppy used term you hear in spoken language, referring to a one directory level of files as an entity. "Mapp" is more recognized as used in Windows File Explorer. Although the two words are interchangable I am the formal type who would use the word "katalog" when referring to a storage location of multiple levels of folders and files, escpecially when recursively traversing throug a structure. But I would recognize "mapp" for that as well so I think you are safe to go with that.

It's possible there are a few things that can be polished. Or that someone has a better idea for things like "Prediffer" or "MDI child window". But for 98% of it, I think we are ok.

**Comment by timint** [comment]
@sdottaka Hi, I just received the new version 2.16.28.0 via Winget and noticed the translations went back to the old. Was this never added for release?

**Comment by sdottaka** [comment]
Version 2.16.28 is a fix for a bug introduced in version 2.16.26 that had a large impact on folder comparisons.
No translations other than Swedish have been updated too.

The next version, 2.16.29 Beta, will have updated translations.
Please refer to the following URL for the expected release date of the next version

https://github.com/WinMerge/winmerge/milestones
