### ISSUE TITLE
Plugin IgnoreLeadingLineNumbers hangs

### ISSUE THREAD

**Issue by Hansholm** [WinMerge/winmerge#1715]
The plugin IgnoreLeadingLineNumbers hangs since Winmerge v2.16.26

**Comment by sdottaka** [comment]
I have not been able to reproduce this problem.

Are you using the 32-bit version of WinMerge?
Did you install WinMerge using the installer? Or are you using the Zip version?
What version of Windows are you using?
Does this problem occur only with certain files? Or does it occur with any file?
If possible, could you try reinstalling WinMerge and check?

**Comment by sdottaka** [comment]
Thank you for the information.

Unfortunately the files you emailed as attachments don't seem to be visible at https://github.com/WinMerge/winmerge/issues/1715.
Could you please attach the file at https://github.com/WinMerge/winmerge/issues/1715

**Comment by Hansholm** [comment]
Sorry,
here are the files.

[testfiles.zip](https://github.com/WinMerge/winmerge/files/10743406/testfiles.zip)

**Comment by sdottaka** [comment]
Thank you for attaching the file, I have tried it with various versions of WinMerge, including 2.14.0, and all versions took more than a minute to complete the process.
It appears that the problem is not due to the version of WinMerge, but rather that this plugin is not good at handling large files.

Fortunately, this file appears to be a tab-delimited file, so the IgnoreFieldsTab plugin can be used.
As shown in the attached image, you can specify the plugin pipeline `IgnoreFieldsTab 1` to ignore the first column, which should work as expected; if you want to ignore the second column as well, specify `IgnoreFieldsTab 1-2`.

![image](https://user-images.githubusercontent.com/98126/219051999-6ebf4f7f-f00a-4ce1-9505-6100d7fb1f2f.png)

**Comment by Hansholm** [comment]
OK, thanks.

How about including this plugin in the 64-bit WinMerge?

Van: Takashi Sawanaka ***@***.***>
Verzonden: woensdag 15 februari 2023 15:27
Aan: WinMerge/winmerge ***@***.***>
CC: Hans Kessels ***@***.***>; Author ***@***.***>
Onderwerp: Re: [WinMerge/winmerge] Plugin IgnoreLeadingLineNumbers hangs (Issue #1715)


Thank you for attaching the file, I have tried it with various versions of WinMerge, including 2.14.0, and all versions took more than a minute to complete the process.
It appears that the problem is not due to the version of WinMerge, but rather that this plugin is not good at handling large files.

Fortunately, this file appears to be a tab-delimited file, so the IgnoreFieldsTab plugin can be used.
As shown in the attached image, you can specify the plugin pipeline IgnoreFieldsTab 1 to ignore the first column, which should work as expected; if you want to ignore the second column as well, specify IgnoreFieldsTab 1-2.

[Afbeelding verwijderd door afzender. image]<https://user-images.githubusercontent.com/98126/219051999-6ebf4f7f-f00a-4ce1-9505-6100d7fb1f2f.png>

**Comment by sdottaka** [comment]
This plugin has been found to be problematic and may rather be removed from the 32-bit version unless the problem is corrected.

**Comment by sdottaka** [comment]
The IgnoreLeadingLineNumbers plugin was written in Visual Basic 6 and can't be built now, so I rewrote it in VBScript and also improved its performance.

https://raw.githubusercontent.com/WinMerge/winmerge/master/Plugins/dlls/IgnoreLeadingLineNumbers.sct

**Comment by Hansholm** [comment]
Tested it, works perfectly.
Thank you very much.

Van: Takashi Sawanaka ***@***.***>
Verzonden: zondag 19 februari 2023 14:47
Aan: WinMerge/winmerge ***@***.***>
CC: Hans Kessels ***@***.***>; Author ***@***.***>
Onderwerp: Re: [WinMerge/winmerge] Plugin IgnoreLeadingLineNumbers hangs (Issue #1715)


The IgnoreLeadingLineNumbers plugin was written in Visual Basic 6 and can't be built now, so I rewrote it in VBScript and also improved its performance.

https://raw.githubusercontent.com/WinMerge/winmerge/master/Plugins/dlls/IgnoreLeadingLineNumbers.sct
