### ISSUE TITLE
When updating Corsican.isl translation file, GitHub wants to transcode it to UTF-8

### ISSUE THREAD

**Issue by Patriccollu** [WinMerge/winmerge#1716]
Hello,

I'm about to provide you with an update of **Corsican** translation for _InnoSetup_.

When editing [Corsican.isl](https://github.com/WinMerge/winmerge/blob/master/Translations/InnoSetup/Corsican.isl) on GitHub repository using Firefox, the following warning is displayed:

`⚠️ We’ve detected the file encoding as windows-1252. When you commit changes we will transcode it to UTF-8.`

In the meantime, I cancelled the changes.

I read a [comment in issue #1532](https://github.com/WinMerge/winmerge/issues/1532#issuecomment-1295652667 ) saying that this specific encoding was required by an older version of _InnoSetup_, still used by _WinMerge_.

What is you suggestion?

Best regards,
Patriccollu.

**Comment by sdottaka** [comment]
Please commit your changes in UTF-8.
I will later change its file encoding as in commit b461786.
