### ISSUE TITLE
remember the last location where move to happen.

### ISSUE THREAD

**Issue by anirugu** [WinMerge/winmerge#1720]
I use winmerge to compare the folder and copy the file that is missing on right side. I usually  compare and see left unique item, copy them and delete left one.

I was thinking to use move option which is better and doesn't need require. If it can have option where it remember my right location where I move it would be great.

for me It doesn't matter it's remember only for project where and left location and right location match or all the left and right.  Anyone have any idea if it's has been implemented yet.

For me, best place for this is in the context menu where we right click and do move left to and you got a window.

Either that window have a folder with recent icon or heart icon (I don't know win32 API allow this but I see a lot of software on github who do amazing customization).

or just add option in "move to" option.

It will probably save burden for people who are doing move to operation. copy and delete require 2 step and move to require one.

If this option is added, it would allow move in one step for all 1+n times.

**Comment by sdottaka** [comment]
similar FR: #1413

**Comment by sdottaka** [comment]
Added Move->Left to Right and Right to Left menu items to the context menu in PR #1732.

![image](https://user-images.githubusercontent.com/98126/220800298-a1e7b9ca-f630-4e19-8a5b-714c231ca47a.png)
