### ISSUE TITLE
All Files shown as different - but aren't after double click - CRITICAL

### ISSUE THREAD

**Issue by OliverAbraham** [WinMerge/winmerge#1721]
I'm comparing two folders of *.cs files.
All files are shown as different. But when I double click on a file, it says files are identical.
I've tried WinMerge 2.16.28 and 2.16.4. Both are defect. 
2.14.0 is behaving correctly.

THIS ERROR IS ABSOLUTELY CRITICAL - IT BREAKS THE KERNEL FUNCTIONALITY OF THE APP
REASON: when I have to click on every file to see if its different, I don't need a tool.

**Comment by sdottaka** [comment]
What folder compare method have you selected?
The difference between the results of a folder comparison and a file comparison is usually the result of specifying a folder comparison method other than "Full Contents" for compare method.
For example, if you select Modified Date as compare method, the folder comparison will not compare file contents, but only file modification dates.
If the above applies to you, please select Full Contents as shown below.
If not, could you please attach the files to help us reproduce the problem?

![image](https://user-images.githubusercontent.com/98126/219868362-b1b280e1-7bb0-4889-912e-96a9e6e88319.png)

**Comment by OliverAbraham** [comment]
Thank you! Iwasn't aware of compare methods. 
After selecting Full contents, file dates and times are ignored.
