### ISSUE TITLE
Windows 11 Tabs - wrong folder selected from new menu

### ISSUE THREAD

**Issue by KcZer0** [WinMerge/winmerge#1733]
Selecting from background, using Windows 11 menu, in second or more tab, results in the first tab's path being selected 
Selecting as either left or right (from second or third tab), gives same result 

Using normal/old context menu (from second/third tab) compares the correct selected path 

`WinMerge v2.16.28, Windows 11 22H2`

**Comment by sdottaka** [comment]
Thank you for the report.

This problem has been fixed in commit 9e355fcfa454ba113c2ab4fbbb0d3152138159fd.

The fixed WinMergeContextMenu.dll is available for download at
https://github.com/WinMerge/winmerge/releases/tag/ShellExtension-1.18.6.0
