### ISSUE TITLE
Pressing F2 or Rename should not select file extension

### ISSUE THREAD

**Issue by OshidaBCF** [WinMerge/winmerge#1735]
It would be nice if instead of selecting the whole file name it would only select the name leaving the extension.

I guess it's pretty straightforward.

Maybe a setting to change it.

**Comment by sdottaka** [comment]
Implemented in commit 94377c9

**Comment by OshidaBCF** [comment]
Just in case, what happen if you try to rename a file that doesn't have a . in the name ?
i have a few files that are just called "version"

**Comment by sdottaka** [comment]
all characters will be selected

**Comment by OshidaBCF** [comment]
perfect
