### ISSUE TITLE
After I collapse a folder, the arrow next to it stays turned down

### ISSUE THREAD

**Issue by dimailer** [WinMerge/winmerge#1747]
When I expand a folder, the arrow next to it turns down.

When I collapse the folder, the arrow should turn right, but it remains turned down. The folder itself collapses fine.

The arrow only turns right after I expand another folder.

Win 10, WinMerge 2.16.26.0 x64

**Comment by sdottaka** [comment]
Fixed in commit 8d65696.

Thank you for the report.
