### ISSUE TITLE
How do I create a patch from directory

### ISSUE THREAD

**Issue by legovo** [WinMerge/winmerge#1753]
I've seen #331, but I still don't understand how to do it. I've opened the "Patch Generator" menu, but ONLY files can be selected there. I've downloaded the latest version of the program earlier. What should I do?

**Comment by sdottaka** [comment]
Select folders, such as the GIF video below.

You can also generate a patch for folders by selecting folders in the Folder Compare window, then opening the Patch Generator dialog.

![#1753](https://user-images.githubusercontent.com/98126/224580611-c75e933a-eef9-4c2e-8604-ec86355239b4.gif)

**Comment by legovo** [comment]
Ah, now clear. At the time, I didn't understand the message that the patch requires an absolute output path for saving.
