### ISSUE TITLE
Windows 10 shell integration not working

### ISSUE THREAD

**Issue by przet** [WinMerge/winmerge#176]
In Windows10 v1809 (OS build 17763.678) and v1903 (OS build 18362.295), the explorer integration does not work. You can see the WinMerge option in context menu when selecting >=1 files, but WinMerge does not open at all.

For WinMerge version 2.16.4.0 x86

**Comment by przet** [comment]
I would also like to work on this one please :)

I am going to test on a couple other Win10 machines, and also eliminate any anti-virus program issues (which in my experience has created issues in other applications), and then get stuck into the code if needed.

Would be interesting to hear if anyone else has spotted this issue on Win10

**Comment by przet** [comment]
Found this: https://sourceforge.net/p/winmerge/bugs/2195/

**Comment by przet** [comment]
Working in my v1809 windows now. Suspected restart was required, however can't reproduce on my v1903 windows.

**Comment by sdottaka** [comment]
Thank you for the report.

I could reproduce the bug when unchecked 'Launch WinMerge' checkbox in the installer as follows

![image](https://user-images.githubusercontent.com/98126/64214485-ac029e80-ceeb-11e9-9685-25435a4c1294.png)

Did you uncheck the checkbox too?

**Comment by przet** [comment]
@sdottaka yes - when checked on my WinMerge version shell integration works. I am still not sure why it started to work as mentioned in my previous comment, even though I did not check the box.

**Comment by sdottaka** [comment]
The reason WinMerge does not start from ShellExtension is that the WinMege path is not set in the registry key HKEY_CURRENT_USER\Software\Thingamahoochie\WinMerge\Executable.

The above registry key is set once WinMerge is started, so you probably have started WinMerge from something other than ShellExternsion.
