### ISSUE TITLE
CSV / TSV table header row always visible

### ISSUE THREAD

**Issue by SoenkeNickels** [WinMerge/winmerge#1778]
Hello,
it would be easier to scroll through a table file (CSV/TSV) with many lines with the first row always visible for files in which the first line contains table header columns.
Is this possible?

**Comment by sdottaka** [comment]
As of version 2.16.19, the first line can be displayed at the top margin by right-clicking on the top margin and selecting Use First Line as Headers menu item.

![image](https://user-images.githubusercontent.com/98126/227718959-47654689-9716-4fab-9598-8327a4d4d7d1.png)

**Comment by SoenkeNickels** [comment]
Thank you very much, that is the function I was looking for.
