### ISSUE TITLE
Cannot Download

### ISSUE THREAD

**Issue by misterhamm** [WinMerge/winmerge#178]
Download links are redirecting to an error page.

**Comment by bardware** [comment]
Where do you try to download from?

**Comment by bardware** [comment]
These links work: https://github.com/WinMerge/winmerge/releases

**Comment by StoyanDimitrov** [comment]
There were intermittent issues with links on https://winmerge.org/downloads/

**Comment by gerundt** [comment]
It must have been a problem of SF.net. Works now!

Thanks for the report!
