### ISSUE TITLE
Middle Click to close image tab crash

### ISSUE THREAD

**Issue by OshidaBCF** [WinMerge/winmerge#1785]
If i open an image and try to close the tab using middle/wheel click, winmerge instantly crash

**Comment by OshidaBCF** [comment]
[WinMergeU.exe.6216.dmp.txt](https://github.com/WinMerge/winmerge/files/11128801/WinMergeU.exe.6216.dmp.txt)
here is the dmp file (renamed to .txt because github doesn't support dmp files)

**Comment by OshidaBCF** [comment]
Maybe some of the settings i used were the reason of the crash

here is my .ini if you wish to test
[settings.ini.txt](https://github.com/WinMerge/winmerge/files/11129646/settings.ini.txt)

**Comment by sdottaka** [comment]
Thank you for attaching the settings file.
I tried importing the settings file but could not reproduce the problem.
Does the problem occur with any file? Or does it occur in specific files?

I have added a process to avoid this crash in the following commit
https://github.com/WinMerge/winmerge/commit/c0ffdea5d81f4a4031446ba93f492b64eb5e2881

**Comment by OshidaBCF** [comment]
From what i can see it only happen on images, the two folder i'm comparing each have 38k files inside, so even if i'm not "seeing" all of them, that could be the reason it's crashing

right now the crash doesn't happen so i can't tell if it only happen for different images.

**Comment by sdottaka** [comment]
Thank you for the info.
