### ISSUE TITLE
Opening a project fails when a path has environmental variables in it.

### ISSUE THREAD

**Issue by LTusche** [WinMerge/winmerge#1793]
When I save a project with environmental variables it always adds the path to the project file in front of the variable.

For example this project file:
![image](https://user-images.githubusercontent.com/80907593/230378480-23f44fbd-5444-410a-aa7e-b46e9914db84.png)

Turns into this:
![image](https://user-images.githubusercontent.com/80907593/230377520-1c27e489-a00f-4716-ba60-bcca4a7c9b95.png)

Expected behavior: Translate the environmental variable and start the comparison between:
"C:\Users\LTusche\AppData\Roaming\CompareFrom"
and
"C:\CompareTo"

**Comment by sdottaka** [comment]
Fixed in commit 787ac74
Thank you for the report.

The latest binary can be downloaded from the following URL:
https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts
