### ISSUE TITLE
Skipped .FRK files

### ISSUE THREAD

**Issue by MRK6310** [WinMerge/winmerge#1801]
When comparing 2 memory sticks, a number of files with the extension .FRK are skipped. I believe such files are usually associated with Mac computers. I've clicked on Tools > Filters, where I've highlighted "None", but still the FRK files are listed in the comparison results as "Filtered". How can I ensure that no files, including FRK files, are filtered out of the comparison? I'm new to WinMerge, and I can't find a solution in the user's guide.

**Comment by MRK6310** [comment]
@sdottaka

Thanks for your help. The display in [Folder: Filter] when I click the Open icon looks exactly like the image you sent. 
i.e. the "Folder:Filter" box contains *.*, and "Include subfolders" is ticked.

**Comment by MRK6310** [comment]
> @sdottaka
> 
> Thanks for your help. The display in [Folder: Filter] when I click the Open icon looks exactly like the image you sent. i.e. the "Folder:Filter" box contains _._, and "Include subfolders" is ticked.

**Comment by MRK6310** [comment]
CORRECTION
the "Folder:Filter" box contains .,
actually reads:
the "Folder:Filter" box contains *.*,

**Comment by MRK6310** [comment]
I'm even more confused! I'm writing [asterisk] [period] [asterisk] in my 'comment' but when I send it the asterisks disappear!

**Comment by auge8472** [comment]
Asterisks are part of the Markdown syntax. Surrounding a string with one asterisk changes the font style to italic. To make use of asterisks as visible chars you have to mask them with a backslash (`\*` = \*) or to enclose the string including the asteriks with backticks what makes the string inline code (like in the example before).

**Comment by MRK6310** [comment]
@auge8472

Thanks for the information about Markdown syntax. I'd never heard the phrase Markdown syntax before.

Let's try again:   the "Folder:Filter" box contains \*.\*

**Comment by sdottaka** [comment]
What version of WinMerge are you using? If it's 2.16.26, there is a bug where folders with a period at the beginning, such as ".git", are ignored. If that's the case, please use version 2.16.28.

**Comment by MRK6310** [comment]
@sdottaka 
I was using WinMerge 2.16.26. 
Upgrading to version 2.16.28 seems to have fixed the problem.
Thanks for your helpful advice.

**Comment by MRK6310** [comment]
Although using WinMerge 2.16.28 seemed to fix the problem, it re-occurred today when trying to compare two folders on the same drive. At the end of the comparison Winmerge showed about 2 dozen files were skipped. This time it's a mixture of .FRK and .JPG files. No filters have been set, and the WinMerge settings are as recommended by sdottaka earlier.

**Comment by sdottaka** [comment]
Will the same files be skipped for multiple comparisons?
When it is skipped, is it displayed as "File skipped" like the image below?
It would be helpful if you could show me a screenshot if possible.

![image](https://user-images.githubusercontent.com/98126/234427713-0c5d57c3-8269-4a96-be26-4dc4d3122332.png)

**Comment by sdottaka** [comment]
Thanks for putting up the screenshot.
If I create and compare the files shown in that screenshot, only 2.16.26 shows as File skipped, so perhaps 2.16.26 is still in use.

You can view the version information by selecting Help → About menu item.


![image](https://user-images.githubusercontent.com/98126/234719473-a84be554-7a7a-428b-a9a6-8ff95c0c6d6c.png)

**Comment by MRK6310** [comment]
@sdottaka 

WinMerge had reverted to version 2.16.26, despite the installation of version 2.16.28 earlier. I don't know why that happened.
https://winmerge.org/ says a new version (2.16.30) of WinMerge was released today (29-4-2023).
I've installed that and it seems to have fixed the 'skipped files' problem.
Thanks for your help.
