### ISSUE TITLE
Turning off "ignore" doesn't work

### ISSUE THREAD

**Issue by K2M74** [WinMerge/winmerge#1805]
The two "JS" files are different, but the software recognizes them the same, and I've turned off all "ignore" options.
Is there anything wrong with the settings? Version: v2.16.29
![2023-04-15_13-02-10](https://user-images.githubusercontent.com/50667472/232184169-b6ee20a3-802d-4a00-948f-defbd578f416.png)
![2023-04-15_13-02-28](https://user-images.githubusercontent.com/50667472/232184244-a4a193d1-1830-404d-bcd2-215cf2cbf1c1.png)
![2023-04-15_13-02-52](https://user-images.githubusercontent.com/50667472/232184173-205611c8-0ac3-4359-9410-75bc3f0d7ed5.png)

**Comment by sdottaka** [comment]
The IgnoreCommentsC prediffer plugin may be applied, or alternatively, Line filters and Substitution filters may be applied.

If you see "IgnoreCommentsC" displayed in the status bar as shown in the image below, it is likely that the "[Plugins]→[Automatic Prediffer]" menu item is selected. Please choose the "[Plugins]→[Manual Prediffer]" menu item or disable IgnoreCommentsC in the Plugins window.

If not, please check the settings of Line filters and Substitution filters.

![image](https://user-images.githubusercontent.com/98126/232201875-01c81a90-e664-459e-b1ef-4bd04ae50888.png)
