### ISSUE TITLE
[Feature request] New options for displaying comparison results list

### ISSUE THREAD

**Issue by pyetrosafe** [WinMerge/winmerge#181]
Hello ...
I usually work with projects with numerous files. And I always find myself having difficulty finding the different files in a giant list with over 5,000 files normally, having to manually hide the files compared with "identical" results.
It would be very interesting in the program settings under "Options> Compare> Folder" to have an option to hide (or in other words not list) files that are identical in both folders. This would greatly reduce the size of the list to parse, and overall, I just really want to know about the files that had differences, but for the sake of statistics, display in the status bar the number of identical unlisted files.

Thanks a lot!

**Comment by sdottaka** [comment]
I think that the [View]-> [Show Identical Items] menu item that WinMerge has is what you want.
