### ISSUE TITLE
Crash on typing while search is in progress

### ISSUE THREAD

**Issue by the8thavatar** [WinMerge/winmerge#1814]
v2.16.28.0 on Windows Server 2016 
but not v2.16.6.0 on Windows 10
Start a lengthy folder comparison and type any non-directional key quickly and the program crashes without any message. Delay before pressing a key and it can handle it.

**Comment by sdottaka** [comment]
So far I have not been able to reproduce this crash.
I have tried quickly pressing keys while files and folders are displayed as shown in the following image, but have not been able to reproduce it.

![image](https://user-images.githubusercontent.com/98126/233643665-792a3ebc-d9bf-4bee-a395-585750f882f1.png)

**Comment by slambillion** [comment]
Crash occurs in v2.16.44.0 on Windows 11 but not on Windows 7

**Comment by sdottaka** [comment]
This issue has been fixed by PR https://github.com/WinMerge/winmerge/pull/2557
