### ISSUE TITLE
Option "Ignore case" didnt work well

### ISSUE THREAD

**Issue by lelicopter** [WinMerge/winmerge#1816]
For some languages this option are broken.
for example (this is not EN language):
а = А
с = С
х = Х
e.t.c.
WinMerge assume this is not same letters with different case.

**Comment by sdottaka** [comment]
Unfortunately, WinMerge's "Ignore case" option only ignores the case of ASCII characters.
However, if you use the Make Uppercase or Make Lowercase plugin as shown below, you can convert non-ASCII uppercase and lowercase letters to uppercase or lowercase for comparison.

![image](https://user-images.githubusercontent.com/98126/233990793-85753802-5069-41b6-8419-e50f22a09391.png)

related to issue #186
