### ISSUE TITLE
WinMerge toolbar appears too small on UHD and should default to the conforming Windows 10 scaling/DPI accessibility setting

### ISSUE THREAD

**Issue by highlandsguy** [WinMerge/winmerge#182]
This effects systems running resolutions of 3840 x 2160 and higher but also may impact users configuring higher scaling under lower resolutions as well.  Though the WinMerge toolbar can be set to "Huge" manually, it should instead default to the setting which conforms best with the scaling set in the Windows 10 accessibility settings (Ease of Access / Make Everything Bigger).

Windows 10 supports scaling the DPI of monitors by percentage factors ranging from 100% to 350%:  100%, 125%, 150%, 175%, 200%, 225%, 250%, 300%, and 350%  (there is no option to set 225%, 275%, 325%, or higher) (additional levels are supported via custom sizing).   

WinMerge's toolbar supports 3 levels: Small, Big, and Huge

Before the installation of WinMerge, Windows 10 is running a resolution of 3840 x 2160 and has its display scaling set at 300% (level 8 of 9).  After installation of WinMerge on this system, the toolbar defaults to the "Big" setting.  It should default instead to "Huge" 

Microsoft's Windows 10 User Settings "[Accessibility Best Practices](https://docs.microsoft.com/en-us/dotnet/framework/ui-automation/accessibility-best-practices#user-settings)" is concerned "that controls or applications do not override user settings", "[Respect All System-Wide Settings and Do Not Interfere with Accessibility Functions](https://docs.microsoft.com/en-us/dotnet/framework/ui-automation/accessibility-best-practices#respect-all-system-wide-settings-and-do-not-interfere-with-accessibility-functions)".  Namely, applications should "[Ensure All UI Correctly Scales by Any DPI Setting](https://docs.microsoft.com/en-us/dotnet/framework/ui-automation/accessibility-best-practices#ensure-all-ui-correctly-scales-by-any-dpi-setting)"

Pending testing, the default WinMerge toolbar setting should correspond to DPI scaling something like this:
Small: 100%, 125%, 150%
Big:     175%, 200%, 225%
Huge: 250%, 300%, 350%

Screenshots are of WinMerge defaulting to "Big" under UHD w/ high scaling, the Windows 10 "Make Everything Bigger" setting, and WinMerge set to "Huge" under UHD w/ high scaling.
![Winmerge UI Screenshot](https://user-images.githubusercontent.com/10247394/64646121-373bd280-d3cb-11e9-8a8f-5bce5df72fdb.PNG)
![Ease of Access settings](https://user-images.githubusercontent.com/10247394/64646349-c47f2700-d3cb-11e9-9fc8-885a4a951422.PNG)
![Winmerge Huge Toolbar on UHD](https://user-images.githubusercontent.com/10247394/64649163-360da400-d3d1-11e9-83c8-785f7af94c4f.PNG)

**Comment by sdottaka** [comment]
Fixed by commit 9d156fc 
Thank you for the report.
The latest CI build artifacts are available at:
https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts
