### ISSUE TITLE
Can't install Contextual Menu again

### ISSUE THREAD

**Issue by OshidaBCF** [WinMerge/winmerge#1830]
After a fix of a bug was patched i wanted to update my winmerge and decided to switch from the regular "pre-built" version to the git built version, it seems that something broke somewhere, because i cannot install the explorer extension

Trying in winmerge just show two UAC promp then do nothing
And trying with the "built" release on the github give this error
![image](https://user-images.githubusercontent.com/61458287/235539858-4dc4ae90-4a34-4609-8661-8c528b26ec4f.png)

"Failed to install WinMerge"

"Installation failed with error message : "Windows cannot install package WinMergegnegnegne because it doesn't support "external emplacement" (0x80070032)""

**Comment by sdottaka** [comment]
What action did you take that caused this message to appear?

**Comment by OshidaBCF** [comment]
If i'm not wrong : 
i built winmerge from git
i deleted the folder where the old winmerge was installed
i tried to install extension via thz new winmerge but it didn't worked because it seems like it thought it was still installed maybe. 
i tried to reinstall winmerge via the released installer, then removed the extension which worked.
uninstalled winmerge *correctly* with uninstaller

and now the new minmerge can't install extension.

**Comment by OshidaBCF** [comment]
basically i fu**ed up

**Comment by sdottaka** [comment]
Did the error in your attached image occur during installation with the installer? Or was it when you double-clicked `WinMergeContextMenuPackage.msix`?
If the latter, `WinMergeContextMenuPackage.msix` is called a Sparse Package, and double-clicking it will not install the context menu.

Running the installer should install the context menu.
 If the WinMerge context menu is not displayed, check if "Add to context menu" is checked in the Shell Integration category of the Options dialog as shown below.
If it is checked, click the "Unregister shell extension for Windows 11 or later" button and then click the "Register shell extension for Windows 11 or later" button.

![image](https://user-images.githubusercontent.com/98126/235659462-9cf05890-cc54-451d-bb1f-cdde794b72bc.png)

**Comment by OshidaBCF** [comment]
Oh yeah my PC is win 10 so i guess that's normal that the last thing is grey-ed out

**Comment by sdottaka** [comment]
When installing, is "Enable Explorer context menu integration" checked on the "Select Additional Tasks" page?

Also, are the ShellExtensionX64.dll and ShellExtensionU.dll files in the same folder as the installed WinMergeU.exe?
 

![image](https://user-images.githubusercontent.com/98126/235832254-88136da0-151c-4417-b27e-188c17e6bfd9.png)

**Comment by OshidaBCF** [comment]
> Also, are the ShellExtensionX64.dll and ShellExtensionU.dll files in the same folder as the installed WinMergeU.exe?

I will guess no ?
![image](https://user-images.githubusercontent.com/61458287/235861301-624c7d60-abc2-422a-be88-a36bdbef44d0.png)

This is what the installers look like for me because of win 10 i guess
![image](https://user-images.githubusercontent.com/61458287/235861437-71576046-12bc-4b0e-94b0-72703b7a3ade.png)

But i do not want to installed it like this, i wish to keep the github version for whenever a but get fixed

**Comment by OshidaBCF** [comment]
Ohhh, i found some bat files in the project folder
![image](https://user-images.githubusercontent.com/61458287/235861862-307dd55c-1d6c-4ed9-9263-8a179853863a.png)

this is the error that happen when i try to "unregister"

it says that the .dll doesn't exist in the folder, so that's probably why it cannot add the shellextention, it's probably just not spitting out an error

**Comment by OshidaBCF** [comment]
Also running the "register.bat" or "RegisterPerUser.bat" does show a UAC prompt, so i would guess that winmerge run two different bat, which explain the two similar UAC prompt

It seems that the dll weren't "built" or something

**Comment by OshidaBCF** [comment]
YEAHHHH

I found the right bat to build the Dll
now it's working perfection

In my opinion there is too much "steps" to build the app
Maybe a "all in one" bat would be nice ?
