### ISSUE TITLE
End of line diff is a bit wanky

### ISSUE THREAD

**Issue by OshidaBCF** [WinMerge/winmerge#1838]
The setting that allow for different end of line seems a little broken sometimes
![image](https://user-images.githubusercontent.com/61458287/236627846-ec0b86ce-6457-4f41-9895-99d3ed06779d.png)
left file is windows, right is linux, settings is checked so it shouldn't matter but you can see at the end of the line there is the little "missing character" color, as it's technically missing an \r

here i "forced" the text to be roughly the same
![image](https://user-images.githubusercontent.com/61458287/236627831-3da210e3-a9f3-4b5c-8f3f-d5959026a69a.png)
And there is still the missing return on some lines, but not all

**Comment by sdottaka** [comment]
So, if I understand correctly, you are saying that when the "Ignore carriage return differences (Windows/Unix/Mac)" option is enabled, you expect that there will be no color highlighting for differences in end-of-line characters, is that correct? If so, then I agree with you.

![image](https://user-images.githubusercontent.com/98126/236651332-9c1980e5-6728-495c-b25e-724f3c76446b.png)

**Comment by OshidaBCF** [comment]
Indeed, it seem that the setting apply only on "different" line, because when i turn off the setting, all the other lines above are noted as "different"

My guess would be that the "diff-er" doesn't take the setting into account if he see's the line "text" as different, so it doesn't show it if the line is the same, but if it differ it'll list the endl difference as well

**Comment by sdottaka** [comment]
This issue has been fixed in PR #1849. Thank you for your report.

**Comment by OshidaBCF** [comment]
That's a lot of commits, but it's fixed so thanks a lot
