### ISSUE TITLE
Winmerge detect .vb (Visual Basic Text-file) as binary file!!!!

### ISSUE THREAD

**Issue by onnoverschuuren** [WinMerge/winmerge#184]
Winmerge detect .vb (Visual Basic Text-file) as binary!!!!
When comparing a complete directory with a VB.NET project, WinMerge V2.16.4.0 detects some *.vb files a binary. Especially the ones that are only available on one side.

![image](https://user-images.githubusercontent.com/50720800/64677752-7f64fe80-d478-11e9-9320-e4fe02c08a35.png)

Best regards and keep up the good work!

**Comment by sdottaka** [comment]
WinMerge considers files containing NUL characters as binary files. Does the file contain NUL characters?

You can search for NUL characters as follows:
![#184_2](https://user-images.githubusercontent.com/98126/64741828-ee079200-d534-11e9-9fe6-e23ba9ad90a4.gif)

**Comment by mdell-seradex** [comment]
@sdottaka, why does it look like that file has a NULL character, but WinMerge treated it as text by default?

**Comment by sdottaka** [comment]
It's just because the current implementation decides whether to open it in the binary editor or not based on the file extension.

PullRequests that add a configuration option to open a binary editor if the file contains a NUL are welcome.

**Comment by mdell-seradex** [comment]
@sdottaka I was confused by the statement "WinMerge considers files containing NUL characters as binary files".  That made me think that it decides to open those files in a binary editor, but that is not the case in the sample you showed.

**Comment by sdottaka** [comment]
I think this issue is fixed in 4a46291.
This issue is probably a bug where text files are considered binary files, like issue #380.
