### ISSUE TITLE
Display problem with Item totals :

### ISSUE THREAD

**Issue by HiPopSK0004** [WinMerge/winmerge#1840]
I am currently using WinMerge 2.16.30.0 with Japanese fonts on Windows 10 ver. 21H2, but when I change the system font to a non-default font (e.g. Meyrio) and the number of files to compare (items total ) exceeds 1,000,000, the most significant digit is displayed incorrectly.
As you know, the default font of Window 10 is difficult to see and I would like to change it, so please support font change in WinMerge.
I think it is because the display area is not properly allocated when the font is changed.

More information is in the attached file.
[WinMerge display problems.docx](https://github.com/WinMerge/winmerge/files/11416118/WinMerge.display.problems.docx)

**Comment by sdottaka** [comment]
In commit 0e2e9c7, I increased the width of the labels that show the number of totals and compared items.

Thank you for your report.

**Comment by HiPopSK0004** [comment]
sdottaka-san
I'm new to this site, so I'm not sure if I should reply here, but what a quick response, thank you.
WinMerge is a must have for programmers. Thank you very much for providing us with a very nice tool.
We sincerely look forward to your new updates.

**Comment by HiPopSK0004** [comment]
Thank you for your very quick response!

As I mentioned on the forum, WinMerge is a must-have for engineers. Thank you very much for providing such a wonderful tool.

I am glad that this change will make our design environment more comfortable.

 

Best wishes to all!
