### ISSUE TITLE
WinMerge is skipping files when comparing two folders on the same drive?

### ISSUE THREAD

**Issue by chinagreenelvis** [WinMerge/winmerge#1857]
It's working fine if I compare two different drives but if I try to compare two folders from the same drive, it skips every single file.

**Comment by sdottaka** [comment]
What version of WinMerge are you using?
If you are using version 2.16.26, there is a problem with skipping comparisons of folder names containing periods, so please try using the latest version.
If you are using the latest version, could you please show us a screenshot of the comparison results?

**Comment by chinagreenelvis** [comment]
Not sure what version I had before, but there were no periods in the file paths I tried. Either way, updating WinMerge resolved the issue, thanks.
