### ISSUE TITLE
I don't remember how to build winmerge

### ISSUE THREAD

**Issue by OshidaBCF** [WinMerge/winmerge#1860]
Tried following the readme by doing 
`DownloadDeps.cmd`
then `BuildAll.vs2022.cmd x64`

but downloadDeps seems to spit out some errors and some "access denied"
and buildAll give :
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] PropertySystemTest.GetDisplayNames
[  FAILED  ] PropertySystemTest.GetFormattedValues

I remember that i did another steps last time i build, but i don't remember what...

**Comment by sdottaka** [comment]
Maybe the previous build was done with an elevated command prompt and this time it wasn't.
Deleting the Build and BuildTmp directories and building again may help.

Also, the latest build can be downloaded from the following URLs.

https://github.com/WinMerge/winmerge/actions/runs/5029777559
https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts

**Comment by OshidaBCF** [comment]
Oh, i thought that i needed to wait for the "releases" to get updates.

interesting
