### ISSUE TITLE
Some Substitution filter doesn't work

### ISSUE THREAD

**Issue by OshidaBCF** [WinMerge/winmerge#1861]
I'm trying to use substitution filter to hide some changes
But i can't figure out what's wrong
![image](https://github.com/WinMerge/winmerge/assets/61458287/5c87395e-a638-4eb4-8629-54dad1cbc35b)

i tried multiple filters, all of which were working when i tested using regex101.com
`-1000\.0,\r\n          0\.0,` -> `-1\.0,\r\n          -1\.0,`
and `1000\.0,\r\n          0\.0,` -> `1\.0,\r\n          1\.0,` (One for each difference)

or `000\.0,\r\n          0` -> `-?1\.0,\r\n          -?1` (one for both)

Both works on regex101 if i remove the \r, but in Winmerge is doesn't work at all
![image](https://github.com/WinMerge/winmerge/assets/61458287/f129f784-6b43-4e1e-bd75-5588369e642b)

Did i missed any special character ?

**Comment by sdottaka** [comment]
This is because \n and \r in the string specified in the "Replace with" column do not replace them with control characters.

I think the following will work fine.

![image](https://github.com/WinMerge/winmerge/assets/98126/893b3c76-a9d1-4da1-8458-c821730682d5)

**Comment by OshidaBCF** [comment]
If i understand right it's a "two step" filter ?

I replace a string by another, then try to replace another string by anotherother ?

Wouldn't it be simpler to make so that the "replace with" column support control character ?


But thanks for the trick

**Comment by sdottaka** [comment]
Later, I will modify the "Replace With" column to treat \r and \n as control characters only when using regular expressions.

**Comment by OshidaBCF** [comment]
Thank you

**Comment by sdottaka** [comment]
Fixed in commit [3da5ca2](https://github.com/WinMerge/winmerge/commit/3da5ca289e18ac281ab3a53db3e7b2fd4057a7da)
Thank you for your report.
