### ISSUE TITLE
wrong Russian translation in Replace dialog (CTRL+H)

### ISSUE THREAD

**Issue by andry81** [WinMerge/winmerge#1862]
Instead of:

:ballot_box_with_check: `Don't wrap end of file` -> `Не останавливаться в конце файла`

Correctly:

:ballot_box_with_check: `Don't wrap end of file` -> `Останавливаться в конце файла`

**Comment by sdottaka** [comment]
Fixed in commit [b27d440](https://github.com/WinMerge/winmerge/commit/b27d440b52ef5f7e115b93204a3a8293a6611441)
Thank you for your report.
