### ISSUE TITLE
JSON "Orderless" compare mode

### ISSUE THREAD

**Issue by OshidaBCF** [WinMerge/winmerge#1867]
Could it be possible to have a "order less" comparaison for jsons, because most of files i compare are usually lines being moved around, some have changing values and some doesn't but it's slightly overwhelming

What i mean by "order less" is roughly the same thing as this website : http://tlrobinson.net/projects/javascript-fun/jsondiff/

Json isn't "supposed" to have multiple field with the same next next to each other, so it's easy to compare two field using the "path".

I wish to kind of "mix" the website and winmerge, so we can do file comparaison.

Is this possible ?

**Comment by sdottaka** [comment]
Maybe I don't understand exactly what you want, but you can sort by keys by using -S (or --sort-keys) as an argument to WinMerge's PrettifyJSON unpacker plugin .

Set in the Plugins Settings dialog as follows,

![image](https://github.com/WinMerge/winmerge/assets/98126/cdb294bc-2a24-4e5e-bb7a-345bd426a4d3)

Apply the PrettifyJSON unpacker plugin as follows.

![image](https://github.com/WinMerge/winmerge/assets/98126/848104cc-34c2-46fa-a81e-ba870888a514)

**Comment by OshidaBCF** [comment]
That is already helping a lot
But sadly it reorder some of the field which can make it harder to read sometime

What would be perfect is for the plugin to keep the "Order" of the first file, and only reorder the second/third files for the order to match the first file

Is there any "documentation" for the plugin so i can see if it has any other possible arguments ?

**Comment by OshidaBCF** [comment]
Also it would be nice if the plugin didn't changed the color of all the texts, dark red is hard to read on black

**Comment by sdottaka** [comment]
> Is there any "documentation" for the plugin so i can see if it has any other possible arguments ?

This plugin uses jq, so please refer to the jq manual below.

https://stedolan.github.io/jq/manual/

**Comment by OshidaBCF** [comment]
Yeah i found it after posting the message, it doesn't look like there is a way to use a file as a "model", quite a shame

Perhaps i can try to make a Plugin for Winmerge that does what i want instead of trying to modify something that already works...

is there any documentation for that ?

**Comment by sdottaka** [comment]
The documentation for the plugin, although outdated, can be found here:
https://github.com/WinMerge/winmerge/tree/master/Plugins

However, I think that what you want to achieve is probably not possible with the current plug-in mechanism. I think you should either process the files before comparing them with WinMerge, or use some other tool.
