### ISSUE TITLE
Image compare breaks when zoomed too much with large pictures

### ISSUE THREAD

**Issue by ganego** [WinMerge/winmerge#188]
Using Winmerge v2, 2.16.4 x64, when doing an image compare (where you see both images side by side) with large pictures, you cannot fully zoom into the picture. At one point it will simply break and show only a light-blue background.  

An image for testing (8000x8000 px) would be:
https://images-assets.nasa.gov/image/PIA18033/PIA18033~orig.jpg
You have to re-save it to have anything to diff obviously.  

Zoom level that breaks the compare depends on the picture dimensions - for smaller pictures it happens later.

**Comment by sdottaka** [comment]
Fixed by commit b8d01b1

Thank you for the report.
The latest CI build artifacts are available at:
https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts
