### ISSUE TITLE
Pane focusing

### ISSUE THREAD

**Issue by LAPIII** [WinMerge/winmerge#1898]
When opening a new document to compare two texts, is it possible to put the focus on the left pane by keyboard or not open with insertion cursor in the last used pane? If there isn't, I think that either should be programmed.

**Comment by sdottaka** [comment]
What version of WinMerge are you using?
With the latest version, the left pane always has focus when you select the File->New->Text menu item.
You can change the pane focus with F6.

**Comment by LAPIII** [comment]
Version 2.16.24.0
