### ISSUE TITLE
Redundant confirmation "The selected files are identical"

### ISSUE THREAD

**Issue by AlSchemist** [WinMerge/winmerge#1902]
Windows 10 WinMerge version **2**.**16**.**30** 2023-04-27:

1. Open in **WinMerge** the **t**e**xt**ual "File**1**.txt" and the _different_ textual "File**2**.txt".
Their textual contents do **not** matter if the two files are **different**.
2. Open in [Notepad++](https://notepad-plus-plus.org/) the _same_ "File**1**.txt" and "File**2**.txt". Notepad++ and WinMerge should be **side** by **side** _without_ any overlapping.
The text editor does not matter. You can use **Notepad** supplied _by default_ in Windows if you do not wish to install Notepad++.
3. In **Notepad++**, **modify** the text of File**2**.
4. Fully **select** by `Ctrl`+`A` and **copy** by `Ctrl`+`C` the _entire_ text of "File**2**.txt" in the Windows **clipboard**.
5. **Select** the entire text of "File1.txt" and paste by `Ctrl`+`V` the content of File**2** in File**1**. So the two files _become_ **identical**.
6. **Save** _both_ **modified** File**1**.txt and File**2**.txt then **close** **Notepad++**.
7. **WinMerge** asks: "Another application has updated file File**1**.txt since WinMerge scanned it last time."
If WinMerge does **not** show the dialog box, set the focus to WinMerge. There was maybe an overlapping with WinMerge and the text editor.
8. "Do you want to **reload** the file?" **Yes**
9. WinMerge displays a _first_ time since File**1** has been modified: "The selected files are **identical**." Ok
10. WinMerge displays a _2nd_ time since File**2** has been modified: "The selected files are **identical**." Ok

**Optimize** _skipping_ the _second_ **confirmation** because File**1** = File**2** has been _already_ **confirmed**.

The user does **not** wish to check the **checkbox** [ ] "Don't display this message _again_."
Because checking this option leads to **zero** confirmation in the next sessions.

The user would confirm **one** and _only_ one time that the _two_ files are **identical**.

**Comment by sdottaka** [comment]
Fixed in commit [2065bd3](https://github.com/WinMerge/winmerge/commit/2065bd35e3d3a992308b6f5e32d57b8618faa72f)
Thank you for your report.
