### ISSUE TITLE
"Recompare as" menu option doesn't follow current choice

### ISSUE THREAD

**Issue by r-blush** [WinMerge/winmerge#191]
The excellent new feature of "recompare as" seems to have a bug. To reproduce the bug, select "Recompare as XML" and the "Recompare as Text" is greyed out and you cannot revert to comparing as text. To get around this problem, I have found that, if you select "Recompare as Binary" or "Recompare as Image" first, the "Recompare as Text" is enabled again (but the "Recompare as XML" is not).

**Comment by sdottaka** [comment]
Fixed by commit 1162d2f  and 34ac121 

Thank you for the report.

The latest CI build artifacts are available at:
https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts
