### ISSUE TITLE
Treeview scrolls to the wrong position.

### ISSUE THREAD

**Issue by oxosi** [WinMerge/winmerge#1915]
Version

- WinMerge 2.16.30.0 x64
- Windows 10 Pro

Steps to reproduce

1. Folder comparison in tree view between folders with hierarchies and files.
2. Make the vertical scroll bar appear.
3. Scroll to the bottom.
4. Click on a folder at the bottom of the window to view its child items.
5. If the height of the window is exceeded, the window scrolls to the wrong position.

Expected behavior

- No scrolling.
- Or, if there are child items that exceed the height of the window, scroll to the position where the parent item is at the top. like a Windows Explorer.

**Comment by sdottaka** [comment]
As a workaround, you can prevent unexpected scrolling by selecting the folder Item before clicking the ">" icon on the folder item.

**Comment by sdottaka** [comment]
Fixed in commit [e499ac4](https://github.com/WinMerge/winmerge/commit/e499ac47e9665b6b168bc22cbe8e68ff602e2268)
Thank you for your report.
