### ISSUE TITLE
Differences in Replace and Find windows

### ISSUE THREAD

**Issue by Darkums** [WinMerge/winmerge#192]
Find: **Find next** button should be on top and default choice.
Replace: **Find previous** button would be a "nice touch".

![Replace](https://user-images.githubusercontent.com/56113295/66120411-74b70880-e5e3-11e9-8cf9-d4ccc207b4d9.png)
![Find](https://user-images.githubusercontent.com/56113295/66120404-6ff25480-e5e3-11e9-990c-37a8f316f927.png)

**Comment by sdottaka** [comment]
Implemented by PR #201 and by commit 8d34255
