### ISSUE TITLE
Crashes in beta 2.16.31

### ISSUE THREAD

**Issue by 8ctopus** [WinMerge/winmerge#1922]
The [new beta version 2.16.31](https://github.com/WinMerge/winmerge/releases/tag/v2.16.31) keeps crashing (application closes without any error message) when switching between files once right and left are fully in sync and it automatically goes to the next file.

- Windows 10 64 bit.
- I used the [x64 installer](https://github.com/WinMerge/winmerge/releases/download/v2.16.31/WinMerge-2.16.31-x64-Setup.exe)

```
Faulting application name: WinMergeU.exe, version: 2.16.31.0, time stamp: 0x6491a144
Faulting module name: WinMergeU.exe, version: 2.16.31.0, time stamp: 0x6491a144
Exception code: 0xc0000005
Fault offset: 0x000000000012e21c
Faulting process id: 0x3e7c
Faulting application start time: 0x01d9a8ec54172065
Faulting application path: C:\Program Files\WinMerge\WinMergeU.exe
Faulting module path: C:\Program Files\WinMerge\WinMergeU.exe
Report Id: 7e19122a-9ca4-4948-b280-6e486fb0b92d
Faulting package full name: 
Faulting package-relative application ID: 
```

Issue also occurs in version 2.16.30 but way less often.

```
Faulting application name: WinMergeU.exe, version: 2.16.30.0, time stamp: 0x6449225c
Faulting module name: WinMergeU.exe, version: 2.16.30.0, time stamp: 0x6449225c
Exception code: 0xc0000005
Fault offset: 0x000000000012d42c
Faulting process id: 0x3d78
Faulting application start time: 0x01d9a8ecc40a21c1
Faulting application path: C:\Program Files\WinMerge\WinMergeU.exe
Faulting module path: C:\Program Files\WinMerge\WinMergeU.exe
Report Id: 3d86595e-2370-4f89-b334-876e0e6656c7
Faulting package full name: 
Faulting package-relative application ID: 
```

Are there any log files I can attach?

**Comment by sdottaka** [comment]
Are there any dmp files left in the following folders?
`C:\ProgramData\Microsoft\Windows\WER`

I'm trying to reproduce it, but I can't reproduce it.
Could you tell me more about the steps to reproduce?

**Comment by 8ctopus** [comment]
I have some files in `C:\ProgramData\Microsoft\Windows\WER\Temp`

**Comment by 8ctopus** [comment]
All good, I no longer experience this issue in the later versions.
