### ISSUE TITLE
Save function doesn't work if the path length exceeds 248 characters

### ISSUE THREAD

**Issue by nyszilard** [WinMerge/winmerge#1923]
**WinMerge version:** 2.16.30.0 (X64)
**OS**: Win10 1909 (build number: 18363.2274)

The program indicates that the save was successful when I click on the save icon, but in reality, it doesn't actually happen.

Test paths (with 249 characters):
`c:\Test\Test2\Test3\Test4\Test5\Test6\Test7\Test8\Test9\LongerPathName1\LongerPathName2\LongerPathName3\LongerPathName4\LongerPathName5\testFileNameOneTwoThreeFourFiveSixSevenEightNineTenQWERTZUIOPASDFGHJKLYXCVBNMQWERTZUIOPASDFGHJKLYXCVBNMQWSCA.json`

`c:\Test\Test2\Test3\Test4\Test5\Test6\Test7\Test8\Test9\LongerPathName1\LongerPathName2\LongerPathName3\LongerPathName4\LongerPathName5\testFileNameOneTwoThreeFourFiveSixSevenEightNineTenQWERTZUIOPASDFGHJKLYXCVBNMQWERTZUIOPASDFGHJKLYXCVBNMQWSCB.json`

**Comment by sdottaka** [comment]
Fixed in commit [3c2e135](https://github.com/WinMerge/winmerge/commit/3c2e13570fe4c2ae6948674217db624934e5cf4f)
Thank you for your report.
