### ISSUE TITLE
Improved WInMerge interface!

### ISSUE THREAD

**Issue by Need74** [WinMerge/winmerge#1924]
Among the proposals that I would like to submit in terms of software evolution I noted:

- Add in the 'Color Scheme' page of the Preferences, a button allowing to create a personal color scheme under the name 'Custom' and propose to save the personal modifications of one of the color schemes under a different name . This makes it possible not to lose the original color scheme (it is enough to create a Custom.ini file in the C:\Program Files\WinMerge\ColorSchemes folder starting from the ‘default’ template file).

- Add in the Main Preferences page, just above the 'Import...' and 'Export...' buttons, a text 'Backup and Restore configuration:' in order to clearly explain the purpose of these 2 buttons.

- Add a button in the search dialog box (and the same in the replacement dialog box) to count the occurrences of an element contained in the file.

- Add checkboxes in the search dialog box (and the same in the replacement dialog box) to search in the panel where the cursor is or another or in all the open panels.

-Display the search and replace dialog boxes as a single box with two tabs allowing you to switch from a search to a replacement more quickly.

**Comment by sdottaka** [comment]
Since it is the same as #2054, I will close this issue.
