### ISSUE TITLE
Export/Import settings bug with Substitution Filters

### ISSUE THREAD

**Issue by Gitoffthelawn** [WinMerge/winmerge#1925]
WinMerge v2.16.30-x64

When attempting to perform a "roundtrip" export of WinMerge settings followed by an import, I discovered a bug related to Substitution Filters:  If a substitution filter begins with a space, WinMerge will leave out the space character at the beginning of the filter in the settings export file.  Thus, during import, the filter will not match what the user intended to export.

I tested using regex substitution filters, so the workaround was to add a backslash before the space character.

**Comment by sdottaka** [comment]
Fixed in commit [e1dc4ed](https://github.com/WinMerge/winmerge/commit/e1dc4edc8aa5b10ba32f6940810aaa5bb9d9b4e3)

**Comment by sdottaka** [comment]
Thank you for your report!

**Comment by Gitoffthelawn** [comment]
You're welcome.  Thank you for the fix!  And sorry I haven't been around to help as much.
