### ISSUE TITLE
Ignore codepage diffs menu item

### ISSUE THREAD

**Issue by Darkums** [WinMerge/winmerge#193]
It would be nice to have fast access to **Ignore codepage differences
![Compare](https://user-images.githubusercontent.com/56113295/66121128-1ab74280-e5e5-11e9-8c8a-2fff9ad96567.png)
** in menu.
![Menu](https://user-images.githubusercontent.com/56113295/66121136-1e4ac980-e5e5-11e9-80e1-25883520cdc9.png)

**Comment by sdottaka** [comment]
Implemented by PR #197
