### ISSUE TITLE
Microsoft Word .docx Files Not Presenting Accurately

### ISSUE THREAD

**Issue by swbgithub** [WinMerge/winmerge#1943]
Running latest WinMerge version 2.16.30.0 and
Microsoft® Word for Microsoft 365 MSO (Version 2306 Build 16.0.16529.20100) 32-bit 

Microsoft Word .docx files are not importing into WinMerge correctly. Text appears as random letters and symbols. Available Plugin 4.4 'CompareMSWordFiles' is checked under 'Enable Plugins'.  

![WinMerge-Example](https://github.com/WinMerge/winmerge/assets/139923487/5a724929-1607-40a0-83e9-0d0edf3132ec)

**Comment by sdottaka** [comment]
Select Plugin → Unpacker → MS Word menu item to apply the plug-in.
Alternatively, select Plugin → Automatic Unpacking menu item to automatically apply the plug-in the next time you compare.

![image](https://github.com/WinMerge/winmerge/assets/98126/945377e9-4520-41c8-bf33-e3ee7d62310f)

**Comment by swbgithub** [comment]
Applying the plug-in from Plugins\Unpacker\MS-Word worked. Thank you.  However, I also selected Plugins and selected the Automatic Unpacking menu item, but the setting change isn't persistent after I close and reopen WinMerge and try again. I have to manually select Plugins\Unpacker\MS-Word again. I double-checked and the Automatic Unpacking menu item is still selected. Is there someplace else I need to 'apply' changes to make it persistent?

________________________________

**Comment by sdottaka** [comment]
Does it mean that the Automatic Unpacking menu item is selected but the plugin is not automatically applied?
I can't reproduce the problem so far.
How did you open the .docx files? From the "Select Files or Folders" window? From the Explorer context menu?
Or is it open via drag and drop?

**Comment by swbgithub** [comment]
﻿
Correct: The Automatic Unpacking menu item is indeed still selected (even after closing/re-opening WinMerge) but the MS-Word Plugin is not automatically applied.

I tried both drag & drop and also “Select Files or Folders”.  Each method showed the strange characters/symbols until I manually select Plugins\Unpacker\MS-Word again.

Thanks so much for your help on this. I donated last year and will do so again. Excellent customer service.



On Jul 18, 2023, at 19:18, Takashi Sawanaka ***@***.***> wrote:

﻿

Does it mean that the Automatic Unpacking menu item is selected but the plugin is not automatically applied?
I can't reproduce the problem so far.
How did you open the .docx files? From the "Select Files or Folders" window? From the Explorer context menu?
Or is it open via drag and drop?

**Comment by sdottaka** [comment]
Thank you for your donation.

As for the matter that the plug-in is not automatically applied, I can only think of the following causes so far.

- Instead of having the Automatic Unpacking menu item selected, the Automatic Prediffing menu item is selected instead
- The extension .docx is removed in the CompareMSWordFiles plugin settings as shown below, or the "Enable automatic unpacking/prediffing for the plugin" checkbox is unchecked.
![image](https://github.com/WinMerge/winmerge/assets/98126/465e0e58-3bb7-4908-9b0c-b6912ea907f9)

**Comment by swbgithub** [comment]
Thank you.  The extension .docx is indeed present in the file filters you indicated below and the "Enable automatic unpacking/prediffing for the plugin" checkbox is checked (see screenshot).

However, for the other suggestion, I do have the "Automatic Unpacking" menu item selected, but there always is one of the Prediffering menu items selected as well, either "Automatic Prediffer" or "Manual Prediffer". And whichever I select, it still doesn't enable the plug-in to automatically work. (see other screenshot). Is only one Plugin selection supposed to be allowed?  If so, mine doesn't allow that.

________________________________

**Comment by sdottaka** [comment]
I couldn't see your screenshot because images attached to emails don't show up in GitHub issues.

So far I don't know why "Automatic Unpakcing" doesn't work in your environment.

If you have time, I would appreciate it if you could try the following.

1. Download the ZIP version of WinMerge below and extract it to any folder.

https://github.com/WinMerge/winmerge/releases/download/v2.16.30/winmerge-2.16.30-x64-exe.zip

2. Create a winmerge.ini file from in the same folder as WinMergeU.exe in the extracted folder. (Creating a winmerge.ini file saves configuration information in the winmerge.ini file, not in the registry)

3. Launch WinMergeU.exe in the extracted folder and enable "Automatic Unpacking".

4. Compare the .docx files.

**Comment by swbgithub** [comment]
I've posted my screenshot here (I'm online in github.com now) so you can see what I'm referring to. In the screenshot, you can see that Automatic Unpacking *and* Automatic Prediffer are both selected. I am unable to unselect Automatic Prediffer. Is the intention that only one selection is supposed to allowed in the Plugins Settings? If so, then my program is allowing two to be selected at one time and that may be the problem.
![Plugins-Settings](https://github.com/WinMerge/winmerge/assets/139923487/8636d605-b8c2-49dd-a122-12f90c409afd)

**Comment by sdottaka** [comment]
Does it mean that if you choose "Automatic Unpacking" or "Manual Unpacking," "Automatic Prediffing" or "Manual Prediffing" are also automatically selected at the same time?

Which version of WinMerge are you using? You can check it in the Help → About menu item.

**Comment by swbgithub** [comment]
Automatic Prediffer or Manual Prediffer aren’t “automatically” selected, per se. Meaning neither one of those automatically change if/when I toggle between “Automatic Unpacking” or “Manual Unpacking”. I can manually toggle between them, but one or the other always stays selected. 

You wrote in a reply above that one of the reasons I may be having an issue is: “Instead of having the Automatic Unpacking menu item selected, the Automatic Prediffing menu item is selected instead”

Keyword there is “instead”. So if I read what you wrote correctly, the intended behavior is that “Automatic Unpacking” is supposed to be the ONLY one of the 4 choices selected, not “Automatic Unpacking” AND Automatic Prediffer or Manual Prediffer. 

Running latest WinMerge version 2.16.30.0 X64

**Comment by sdottaka** [comment]
It seems that my English expression was strange because I completely rely on translation software.
Note that if you enable Automatic Prediffing, the Prediffing plugin will be automatically applied unexpectedly, so it's usually better to select Manual Prediffing.

**Comment by swbgithub** [comment]
OK, thank you for the translation explanation. Now I understand the communication issue we're having.  I hope the translation software will correctly translate the below. 

Fact 1: Regardless of which Unpacking plugin option I select (Manual or Automatic), one of the Prediffer plugin options (Manual or Automatic) is always selected as well.  

Fact 2: When I select Automatic Unpacking, the MS-Word plugin isn't automatically applied regardless of which Prediffer option is selected (Manual or Automatic).

Summary: There isn't a selection scenario where Automatic Unpacking is successful in automatically applying the MS-Word plugin.

**Comment by sdottaka** [comment]
Thank you for your explanation again.
I do not know why the plugin is not applied at the moment, so I would appreciate it if you could try the following.

https://github.com/WinMerge/winmerge/issues/1943#issuecomment-1643799461

**Comment by swbgithub** [comment]
I tried what you suggested in [https://github.com/WinMerge/winmerge/issues/1943#issuecomment-1643799461](url), exactly how you instructed, loading the files using 'New Documents' then Drag & Drop, but it yielded the same results (random characters appear).  However, then I tried using 'Select Files & Folders' and then Browsed to the files and it was successful (no random characters).

I then tried using 'Select Files & Folders' and then Browsed to the files in my previous instance of WinMerge (where the error was happening) and it was successful there as well.

NOTE 1: When I Drag & Drop, I get a Windows Dialog Box (screenshot attached) and regardless of whether I answer Yes or No to the question prompt, the random characters always appear.  I don't get the Windows Dialog Box when I use 'Select Files & Folders' and then Browse to the files. So it looks like the culprit is indeed Drag & Drop.

NOTE 2: Before I contacted you on 07-18-23, when I tried using 'Select Files & Folders' and then Browsed to the files, the random characters did appear, but I never tried again after you advised to change some of the settings. So it likely has been working after that, but I never tried using 'Select Files & Folders' and then Browse again; I always used Drag & Drop.
![Carriage-Return-Error](https://github.com/WinMerge/winmerge/assets/139923487/9305c368-2987-4815-9507-d26073a80e94)

**Comment by sdottaka** [comment]
Thank you for trying.
Thank you for solving the mystery of this problem.
Unfortunately, Automatic Unpacking does not work with drag and drop after selecting the File->New menu item or clicking the New Documents button on the toolbar.

As a workaround, without pressing the New Documents button, drag and drop one or two files with a gray background as shown below.
If you drag and drop only one file, the "Select Files or Folders" window will appear, drop the second file on it and click the Compare button.

![image](https://github.com/WinMerge/winmerge/assets/98126/5b7fd33c-91cc-4008-a7b9-3068eb3c6c5c)
![image](https://github.com/WinMerge/winmerge/assets/98126/dc94c370-240d-40f8-8303-3808bc5175d2)

**Comment by swbgithub** [comment]
Thank you so much for all of your help. No worries, I don’t have to use Drag & Drop. It’s just what I’ve always used in the past (it used to work). I’m happy to use the ‘Select Files or Folders’ method instead from now on. Much appreciation again. Fantastic customer service.
