### ISSUE TITLE
Binary diff isn't locked to 16 bytes per line

### ISSUE THREAD

**Issue by OshidaBCF** [WinMerge/winmerge#1944]
![image](https://github.com/WinMerge/winmerge/assets/61458287/4e357020-b441-4c6e-b8e2-1853a149f566)
It's very weird to not have a multiple of 4 bytes per line, could it be possible to "limit" the number of bytes per line and just fill the rest with void ?

**Comment by sdottaka** [comment]
Uncheck the "Automatically adjust number of bytes per line ..." checkbox and enter 16 in "Number of bytes to display per line" as shown below.
![image](https://github.com/WinMerge/winmerge/assets/98126/449bfbc0-9702-45e0-9e19-7aec72d8d783)

**Comment by OshidaBCF** [comment]
ohhhh, i didn't saw that

Now what would be nice would be the "position" at the top of the screen
![image](https://github.com/WinMerge/winmerge/assets/61458287/da8610f3-65bd-413d-b2e7-98192da11d5d)
Something like that

**Comment by sdottaka** [comment]
> Now what would be nice would be the "position" at the top of the screen image
Unfortunately, WinMerge cannot display headers like the image above.

**Comment by OshidaBCF** [comment]
Doesn't it do a header when opening csv?
where it show the column "name"?

It could work by just adding a line that say "Offset (h) 00 01 02 ... 0D 0F" no?

**Comment by sdottaka** [comment]
The matter described in the title of this issue has been resolved, so I will close this issue.
Please create a separate issue regarding the display of the header part.

**Comment by OshidaBCF** [comment]
Okay
