### ISSUE TITLE
Empty folders because all files are same but folders are displayed

### ISSUE THREAD

**Issue by Neustradamus** [WinMerge/winmerge#1956]
Dear @WinMerge team,

It is needed to compare several folders but the date of folders are different and all content is same at several levels (several folders in folders).

Folders are empty (all files are same) but folders are displayed.

It is possible to hide folders with different date/time if the content is same?

Note: There are folders in folders.

**Comment by sdottaka** [comment]
If you select the View→Show Identical Items menu item as below, does it not display as you expect?

If the display is not as expected, please provide a screenshot or the actual folder structure to assist further.

![image](https://github.com/WinMerge/winmerge/assets/98126/8d0e757d-7bb9-4f31-b058-3e779571a995)

**Comment by sdottaka** [comment]
Perhaps I'm not understanding this issue.
If you just want to hide empty folders, unfortunately, WinMerge doesn't have that feature.

**Comment by sdottaka** [comment]
When comparing the two folders, folderA and folderB, is the intention of this request to hide subfolder1?

Also, it sounds like you are mentioning empty folders, but you are saying that there are files present in those supposedly empty folders. This is causing me quite a bit of confusion.

If possible, could you please provide a screenshot to see if you have the 'Include subfolders' option enabled or if you have 'Tree mode' enabled, or if you have applied any filters? 

~~~
folderA
  └─ subfolder1: 2023-07-29 
       ├ file1.txt: text=AAAAA
       ├ file2.txt: text=BBBBB


folderB
  └─ subfolder1: 2022-12-31
       ├ file1.txt: text=AAAAA
       ├ file2.txt: text=BBBBB


folderA\subfolder\file1.txt = folderB\subfolder\file1.txt
folderA\subfolder\file2.txt = folderB\subfolder\file2.txt
~~~

**Comment by sdottaka** [comment]
I am still confused.
Why aren't those identical files being displayed?
If the "View → Show Identical Items" menu item is unchecked, the folders containing those files should also not be shown. Perhaps, it's not that the files are not displayed because they match, but rather, a file filter might be applied, preventing them from being shown.

**Comment by sdottaka** [comment]
What is that option?
Also, what version of WinMerge are you using? If you are using version 2.16.26, there might be unexpected filtering issues, so please consider using the latest version.

**Comment by sdottaka** [comment]
Thank you for letting us know.
