### ISSUE TITLE
Cannot compare one-line file

### ISSUE THREAD

**Issue by ujos** [WinMerge/winmerge#1972]
I cannot compare one-line file. Application does not show the line on the Diff pane.

Steps to reproduce:
1. Start the WinMerge app
2. Press Ctrl+N
3. Write for example "1" on the left side and "2" on the right side.
4. Press F5. Both left and Right files are highlighted with Yellow color as they are different.
5. Press Alt+Down

Expected:
The first line is highlighted and the content of the first line had appeared on the Diff pane

In fact:
The Alt+Down shortcut is disabled. No content is displayed on the Diff pane.

WinMerge Version: 2.16.32
Platform: Windows 10

**Comment by sdottaka** [comment]
As a workaround, pressing the Alt+Enter key will display the current differences in the Diff pane.

**Comment by sdottaka** [comment]
Fixed in commit [57cbbaf](https://github.com/WinMerge/winmerge/commit/57cbbafc29e38be9e4d8e526c37d1e7f24e52967)
Thank you for your report.
