### ISSUE TITLE
if i compare 2 folders of symlinks, will Delete-Left affect the linked files?

### ISSUE THREAD

**Issue by blank-teer** [WinMerge/winmerge#1976]

**Comment by sdottaka** [comment]
If it is a symbolic link created with the `mklink /d` command, deleting the symbolic link should not affect the original folder. However, if files within the symbolic link are deleted, the original files will also be deleted.

**Comment by blank-teer** [comment]
okay, thanks. but is it possible to make winmerge delete the original file alongside its symbolic link when symbolic links are compared?

**Comment by blank-teer** [comment]
@sdottaka

**Comment by sdottaka** [comment]
Unfortunately WinMerge doesn't have such a feature.

**Comment by blank-teer** [comment]
okay, but can you at least add the symlinks "following" in order to consider symlinks the same as their target binary files? 

for now, if i compare file A with symlink A (targets to file A), winmerge says they are different files, but double-clicking shows a popup that says that compared files are identical

**Comment by blank-teer** [comment]
@sdottaka <praying>

**Comment by sdottaka** [comment]
> for now, if chosen compare method is Binary Contents (i just don't have hours to compare large file sets with Full Contents) and i compare file A with symlink A (targets to file A), winmerge says they are different files, but double-clicking shows a popup that says that compared files are identical :\

Fixed in commit [dfcaf93](https://github.com/WinMerge/winmerge/commit/dfcaf93a8ad9619debb07f2b9e141586fa34293b)
