### ISSUE TITLE
"Current Difference" specified by double-clicking cannot merge using the "Copy to Right (or Left)" menu.

### ISSUE THREAD

**Issue by oxosi** [WinMerge/winmerge#1980]
Steps to reproduce

1. Open 1.txt and 2.txt.
2. Double-click on "10" on the second line of "1.txt".
3. [Copy to Right/Copy to Left] menu cannot be selected, so [Alt+Right/Alt+Left] cannot be used for merging.

[1.txt](https://github.com/WinMerge/winmerge/files/12327539/1.txt)
[2.txt](https://github.com/WinMerge/winmerge/files/12327540/2.txt)

**Comment by sdottaka** [comment]
Fixed in commit [0e4c6b5](https://github.com/WinMerge/winmerge/commit/0e4c6b50df3dd06ddf1d10471adeab20b2eb8acb)
Thank you for your report.
As a workaround, you can merge by double-clicking and then single-clicking to deselect the text.
