### ISSUE TITLE
how works cache while comparing?

### ISSUE THREAD

**Issue by blank-teer** [WinMerge/winmerge#1981]
is it applied to all compare methods? what is TTL?

**Comment by sdottaka** [comment]
Neither folder comparisons nor file comparisons use application-level caching. Also, no particular cache is specified for the OS.

**Comment by blank-teer** [comment]
but the second comparison (noticed with Binary Contents method) is performed much faster than the first one, id just like to know why

**Comment by sdottaka** [comment]
WinMerge does not control caching, so the OS does it automatically.
Other applications that read and write files will also work faster from the second time onward.
