### ISSUE TITLE
hash-sum - any compare method based on it? is it possible to show it in columns?

### ISSUE THREAD

**Issue by blank-teer** [WinMerge/winmerge#1982]

**Comment by sdottaka** [comment]
The hash value is not calculated unless MD5 etc. is specified in Additional Properties.
Please See the GIF animation below on how to add a hash value to a column.

https://github.com/WinMerge/winmerge/pull/996

**Comment by sdottaka** [comment]
In the gif video #996 above, Dimensions and Size were added in the Additional Properties window instead of the hash value, but MD5, SHA-1, SHA-256 can be added in the same way.

**Comment by blank-teer** [comment]
i tried to reach that Additional Properties button, but it's inactive for some reason

![image](https://github.com/WinMerge/winmerge/assets/40229515/8852ff49-112d-418d-b1fa-4728523d3c41)

**Comment by sdottaka** [comment]
It looks like you are using the 32-bit version of WinMerge which does not support Additional Properties.
To use Additional Properties, uninstall the 32-bit version and install the 64-bit WinMerge below.

https://github.com/WinMerge/winmerge/releases/download/v2.16.32/WinMerge-2.16.32-x64-Setup.exe
