### ISSUE TITLE
how to make filename color more distinguishable in Midnight theme?

### ISSUE THREAD

**Issue by blank-teer** [WinMerge/winmerge#1987]
![image](https://github.com/WinMerge/winmerge/assets/40229515/90feb668-1304-4dc4-90ed-76fbb87770e8)

**Comment by blank-teer** [comment]
that night-at-swamp green on grey is just terrible a little)

**Comment by sdottaka** [comment]
You can change the text color in the Colors/Folder Compare category in the Options window.
![image](https://github.com/WinMerge/winmerge/assets/98126/8d729dc1-bddc-43ea-8fc8-af8654949fc1)

**Comment by blank-teer** [comment]
thank you for pointing to the right color setting, ive tried some without success and gave up fast
