### ISSUE TITLE
What regex version is used on Winmerge

### ISSUE THREAD

**Issue by OshidaBCF** [WinMerge/winmerge#1996]
For "fixing" a difference that couldn't be fixed software wise i wanted to make a regex substitution filter that replace scientific notation floats into "plain" floats (i am really bored)

Surprising i managed to make it works on regex101
![image](https://github.com/WinMerge/winmerge/assets/61458287/f7043678-d640-49f1-83d5-6e9881334403)

Problem, the filter doesn't work on winmerge

I noticed that the filter doesn't work if i select PCRE instead of PCRE2 (Conditional Replacements doesn't exist, nor named groups but that's less a problem)

I was wondering what version of regex winmerge uses

**Comment by sdottaka** [comment]
WinMerge uses the POCO library for regular expression replacement. The POCO library used by WinMerge uses PCRE 8.43 internally.

But it's not a PCRE version issue, the POCO library doesn't support formats like `$sign` and `${4+:+0}`.

Register multiple patterns in the Substitution filter as follows.

~~~
([\d]*)\.?([\d]*)?E-05 → 0.0000$1$2
([\d]*)\.?([\d]*)?E-04 → 0.000$1$2
([\d]*)\.?([\d]*)?E-03 → 0.00$1$2
~~~

**Comment by OshidaBCF** [comment]
I see

very thanks
