### ISSUE TITLE
Filter Optimization ?

### ISSUE THREAD

**Issue by OshidaBCF** [WinMerge/winmerge#1997]
After doing a broke filter that applied to every single digit in which made the app crash, i was wondering if the filter was only being tested when a difference was found

If it was tested on every single lines it may have explained the large amount of ram it tried to use before i had to kill it

The filter was basically `\d*\.?\d*` so it make "some" sense that it crashed

**Comment by sdottaka** [comment]
`\d*\.?\d*` is a pattern that matches even an empty string, so it seems that substitution is being performed infinitely.
Change the pattern so that it doesn't match the empty string.

**Comment by sdottaka** [comment]
Fixed infinite loop in commit [2a34b98](https://github.com/WinMerge/winmerge/commit/2a34b984f1a337cf0aaf34c503b8dbabe347ddbe).

**Comment by OshidaBCF** [comment]
oh yeah i forgot that * also works for 0

thanks
