### ISSUE TITLE
[UX] After Comparison the Window is Flashing Indefinitely

### ISSUE THREAD

**Issue by Kizaemon** [WinMerge/winmerge#200]
Please make the window flash count to be 3 or 5, as this is enough to indicate that a lengthy comparison has finished. Currently the window will flash indefinitely, until clicked. This is a distraction, as this forces to interrupt the flow of my current work. 

File: winmerge/Src/MainFrm.cpp 

Function:
```
/** 
 * @brief Start flashing window if window is inactive.
 */
void CMainFrame::StartFlashing()
{
	CWnd * activeWindow = GetActiveWindow();
	if (activeWindow != this)
---		FlashWindowEx(FLASHW_ALL | FLASHW_TIMERNOFG, 0, 0);
+++		FlashWindowEx(FLASHW_ALL | FLASHW_TIMERNOFG, 3, 0);
}
```

Many thanks!

**Comment by sdottaka** [comment]
Could you make the pull request?
