### ISSUE TITLE
Substitution filters doesn't always apply during folder search

### ISSUE THREAD

**Issue by OshidaBCF** [WinMerge/winmerge#2002]
For some reasons some of the filters i use for substitution apply when i'm doing a folder search, and some others don't.

` *"ricochetTimeToLive": 0\.085,\r\n` -> `` this one doesn't apply

but those two does
`\"[a-zA-Z0-9\+\/]*\=\=\"` -> `diff1`
`\[\r?\n *\d*,\r?\n *\d*,\r?\n *\d*,\r?\n *\d*\r?\n *\]` -> `diff1` (This is for base64 encoded colors

is there anything in the first filter that doesn't work during folder compare, but works while comparing a file ?
Or does the filter doesn't like replacing by "nothing" during folder ?

**Comment by sdottaka** [comment]
I can't reproduce the problem in this issue, could you please attach an example file?

Also, does it work if you change ` *"ricochetTimeToLive": 0\.085,\r\n` to ` *"ricochetTimeToLive": 0\.085,\n`?

**Comment by OshidaBCF** [comment]
HAHAHAHAHAHA


Changing it to \n only works in folder search
but it need \r\n in the file itself

if i replace \r\n by \r?\n it work in the file and in the folder search
but i think that it should still need \r\n in folder search (except if it make the search slower)

[new.txt](https://github.com/WinMerge/winmerge/files/12472298/new.txt)
[old.txt](https://github.com/WinMerge/winmerge/files/12472299/old.txt)

**Comment by sdottaka** [comment]
Thank you for attaching the file.

Oh, you probably have the Diff algorithm set to something other than default?
Currently, folder comparisons always use the default Diff algorithm, so it seems that file comparisons behave differently than folder comparisons.
I don't know the proper fix yet. A workaround is to change the Diff algorithm to default.

**Comment by OshidaBCF** [comment]
i think i changed to "histerical" or "historical"

so if i change to default, will it fix the folder search?

or will it also break the file search?


and for the fix, a while ago i think i made a bug report that substitution filter didn't used control character, and you told me that they did but only used \n, you then changed so they would used /r/n, so this might be the issue


but again, if i put an? for the /r it's happy

**Comment by sdottaka** [comment]
If you set Diff algorithm to default, the same diff algorithm will be used for folder comparison and file comparison, so the results of folder comparison and file comparison will match. Use \n for the pattern.

**Comment by OshidaBCF** [comment]
I switched to Default and only using \n, and it works, sweet

But what each different algo change ?

**Comment by sdottaka** [comment]
With PR #2015, filter results for folder comparison and file comparison now match even if the histogram is selected for the Diff algorithm.
It seems that whether you should use `\r\n` or `\n` depends on the state of the Ignore carriage return differences option.

**Comment by OshidaBCF** [comment]
Thks a lot

Just to know, is there a difference between each algo ?

As all worked the same for me it's hard to tell

**Comment by sdottaka** [comment]
This diff algorithm is the same diff algorithm used by git. (WinMerge uses the library libxdiff that git uses)

For information on git's diff algorithm, please see below.

https://luppeng.wordpress.com/2020/10/10/when-to-use-each-of-the-git-diff-algorithms/

**Comment by OshidaBCF** [comment]
when you say "this diff algo" do you mean "default" or "historical" ?

**Comment by sdottaka** [comment]
The writing doesn't seem to be appropriate.

In git, you can choose from diff algorithms including default (myers), minimal, patience, and histogram.
WinMerge also allows you to choose the same algorithms since it uses Git's diff library.
(To be precise, WinMerge's default algorithm doesn't use Git's diff library, but it's very similar to Git's default (Myers).) 

For details on the differences between each algorithm, please refer to the URL above.

**Comment by OshidaBCF** [comment]
I seeeeee

THks for the info
