### ISSUE TITLE
WinMerge cannot successfully disable some of its Plugins

### ISSUE THREAD

**Issue by Gitoffthelawn** [WinMerge/winmerge#2012]
WinMerge v2.16.32.0 64-bit cannot successfully disable some of its Plugins.

STR:
1. Click `Plugins` -> `Plugin Settings`
2. Make sure `Enable plugins` is checked
3. Uncheck all plugins
4. Click `Okay`
5. Repeat step 1
6. Notice that all the `Prettify` plugins are now checked, as well as the first `ApacheTika` plugin.

**Comment by sdottaka** [comment]
Thank you for your report. This issue is fixed in commit https://github.com/WinMerge/winmerge/commit/ee016769d13cc0960bc11f7a5d849544d8d0fe61, so I am closing it.

**Comment by Gitoffthelawn** [comment]
You're welcome, and thank *you*.  Does that patch also fix the issue with the `Prettify` plugins?

**Comment by sdottaka** [comment]
`Prettify*` plugins can be disabled as well.
