### ISSUE TITLE
Switching between "Find Next" and "Find Prev" need to click twice

### ISSUE THREAD

**Issue by gerundt** [WinMerge/winmerge#202]
When you use *Find Next* to find a string and then click on *Find Prev* WinMerge found the string which is currently selected. So you need click *Find Prev*  again to found the real previos string.

You can test it with this simple text file:

```
a
b
c
a
b
c
a
b
c
```

Type as search term `b` and click *Find Next* twice. The second `b` will be selected. If you now click on *Find Prev* nothing will change. You need to click on *Find Prev* again to select the first 'b'.

**Comment by sdottaka** [comment]
Fixed by commit c5371689c9b54e016929dba504c9001277989de7
