### ISSUE TITLE
Speeling error

### ISSUE THREAD

**Issue by geoffwoodpaf** [WinMerge/winmerge#2042]
Comparison Result should not be "Right only", but should be "Write Only"

**Comment by sdottaka** [comment]
"Right only" indicates that the file or folder exists only on the right side, at least "Write only" is not appropriate.

**Comment by geoffwoodpaf** [comment]
Ahh - OK, I misunderstood the meaning of the Error Code !
I guess 'Right' means 'Destination' ?

**Comment by sdottaka** [comment]
In WinMerge, folder comparison results are displayed in one pane, so it may seem strange to display them as "left" or "right."
"Right" refers to the second folder specified among the folders to be compared or the item within that folder. (However, if you specify and compare three folders, Right will indicate the third folder.)

WinMerge can merge not only the right side but also the left side. Therefore, "Destination" is not limited to the right side.
