### ISSUE TITLE
Folder compare omits unique folders from results if they contain any files and/or subfolders

### ISSUE THREAD

**Issue by vbojan** [WinMerge/winmerge#2046]
When I compare 2 folders and enable "**Show Left Unique Items**" and/or "**Show Right Unique Items**" it's expected to see any and all files and folders, including parent folders, that only exist on the left and/or right side of the compared folders to be listed.

However, some of the related changes unintentionally introduced a bug in https://github.com/WinMerge/winmerge/releases/tag/v2.16.25
so if a unique folder on the left and/or right side contains any files and/or folders it will be omitted from the list. This applies to any parent folders recursively in the upper/parent file path.

The only way to see those unique parent folders it to delete everything inside it and refresh the comparison.
I validated every single version released after v2.16.25 including v2.16.33 pre-release and they all have the same bug.

This is how it used to work:
![image](https://github.com/WinMerge/winmerge/assets/2696314/bb8447b3-1826-4799-af41-8a15d9eee4be)

And this is how it works now:
![image](https://github.com/WinMerge/winmerge/assets/2696314/5c6f6172-a576-4a8d-a926-d0d01219d198)
And how a parent folder shows up in the list after everything inside it gets deleted:
![image](https://github.com/WinMerge/winmerge/assets/2696314/0f2f0076-9565-4fa6-96a9-58aaca29ad8d)

I have a workflow where I need to sync 2 folders every once in a while and then manually resolve all conflicts where most of the time I simply delete all unique files and folders on one side. So with this bug I have to delete leaf nodes, then refresh, delete parents that were omitted in the previous run, refresh again, and keep repeating until I basically reach the top folder and there are no more unique differences on either side.
I tried enabling Tree Mode which does show all folders, so I can then select the parent folder and delete it with all of its content recursively, but it comes with a downside - the top folder has a lot of subfolders with a lots of nested subfolders, so the tree branches a lot and due to indenting even with maximized window it becomes difficult to see enough details to be able to confidently act upon, so I had to disable Tree Mode and hope this issue will get addressed in an upcoming release.

**Comment by sdottaka** [comment]
Fixed by commit [d6f48c4](https://github.com/WinMerge/winmerge/commit/d6f48c4c671c839d8eac84946e97845bfb0db402)
Thank you for your report

**Comment by vbojan** [comment]
Kudos for quick fix.
