### ISSUE TITLE
How to use synchronization points? I think this coudl be very useful!

### ISSUE THREAD

**Issue by treflip** [WinMerge/winmerge#2075]
Hello,

I am comparing code files and they are a bit different due to updates. sometimes teh extra grey lines are based off the first word being the same (in my case the 'if' statements) however the conditional logic is not the same so the sections can be pushed up or down by larger portions than makes comparison easy!

I think the synchronization points will let me set the current horizontal alignment? I am not sure but read the help and it says TBD :(

Figured I could post here and someone could point me in the right direction? I hope this is the right place for this!

Tre

**Comment by sdottaka** [comment]
Please refer to the demo GIF animation at the URL below.

https://github.com/WinMerge/winmerge/discussions/1687#discussioncomment-4777248
