### ISSUE TITLE
Ignoring carriage return differences doesn't work anymore

### ISSUE THREAD

**Issue by rondlh** [WinMerge/winmerge#2080]
Since Winmerge 2.16.33 "ignoring carriage return differences" doesn't work anymore.
The files with only carriage return differences get marked as different, then when clicked the files are reported to be identical. This worked fine for 2.16.32, where the files just didn't get marked as different.

**Comment by sdottaka** [comment]
Could you please try version 2.16.34?
Also, if the folder compare method is other than Full Contents, try comparing with Full Contents.

**Comment by rondlh** [comment]
> Could you please try version 2.16.34? Also, if the folder compare method is other than Full Contents, try comparing with Full Contents.

2.16.34 has the same problem, "compare method" is set to "Full Contents".
Files are marked as "different“, when opened the files are reported to be "identical". 
Left file is "Windows (CRLF)", right file is "Unix (LF)", ignoring carriage return differences is checked.

**Comment by sdottaka** [comment]
Thank you for checking version 2.16.34.
This problem does not currently occur in my environment.
Is it possible for you to attach the files that cause the problem?

**Comment by rondlh** [comment]
In WinMerge 2.16.32 all files are shown to be identical in the file/folder view.
![WinMerge 2 16 32](https://github.com/WinMerge/winmerge/assets/77279634/d1231c68-8a07-441a-8d94-9e7cb24f2948)
In WinMerge 2.16.34 all files are shown to be different in the file/folder view, but when opened they are reported to be identical.
![WinMerge 2 16 34](https://github.com/WinMerge/winmerge/assets/77279634/4643dcf9-303b-430b-91c9-682c5cd235c6)

Here are the files: [TEST.zip](https://github.com/WinMerge/winmerge/files/13211473/TEST.zip)
I also compared the files based on this ZIP-file. It should show the problem, if not then perhaps there is something wrong in my registry.

**Comment by sdottaka** [comment]
Thank you for attaching the file.
I was able to reproduce this issue by clearing the registry data.
This problem can be avoided by enabling the line filter and registering some pattern.
I'll try to fix it later.

**Comment by sdottaka** [comment]
Fixed by commit e1709e5
Thank you for your report.
The latest build artifacts can be downloaded below.

https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts

**Comment by vittoso** [comment]
Hello!
It seems to me there is a very similar bug in 2.16.34.0 if files differ only by Tab or whitespaces indentation. 
Here's the compare options:
![image](https://github.com/WinMerge/winmerge/assets/1496592/3f297a20-0f77-4e60-9e05-7c8ebd7166af)

Here's some example files [TEST_TAB_SPACES.zip](https://github.com/WinMerge/winmerge/files/13250963/TEST_TAB_SPACES.zip) the files are shown to be different in the file/folder view, but when opened they are reported to be identical.

This seems to happen with the "default" Diff algorithm. The "minimal" algorithm seems to recognize that the files are not different also in file/folder view.

**Comment by sdottaka** [comment]
@vittoso
Thank you for your report.
An issue where space differences were not ignored was also fixed in commit e1709e5.
https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts

**Comment by sdottaka** [comment]
We have released version 2.16.36 which includes a fix for this issue.
