### ISSUE TITLE
Diff pane no longer shows coloured differences

### ISSUE THREAD

**Issue by prino** [WinMerge/winmerge#2082]
Whereas the old 2.14 version would show the per-line differences in the bottom diff pane, nicely coloured. Using F4 is not an option, as it would take ages to actually show everything.

**Comment by sdottaka** [comment]
This problem does not occur in my environment.

Is there no change even if you press Alt+Down keys or Next Difference on the toolbar?
Also, is the View → View Line Difference menu item checked?

Could you post a screenshot so we can see how it looks?

**Comment by prino** [comment]
Mea culpa, mea maxima culpa... 

The "View Line Difference" was not checked, but I don't remember ever having to do that for 2.14
