### ISSUE TITLE
Close main window with 'Esc' if there is only one MDI child window

### ISSUE THREAD

**Issue by stanio** [WinMerge/winmerge#2084]
Minor as I compare images less often, still.  I have the following WinMerge setting:

>   Options (General)
>
>   Close windows with 'Esc':
>   Close main window if there is only one MDI child window

It doesn't appear honored in WinIMerge and I have to press <kbd>Esc</kbd> twice to close the main window (the first time it closes the only MDI child).

**Comment by sdottaka** [comment]
Fixed by commit f9b021c
Thank you for your report.
