### ISSUE TITLE
Updated Slovenian language Slovenian_winmerge-2.16.34-2c99494d5

### ISSUE THREAD

**Issue by JadranR** [WinMerge/winmerge#2096]
Updated Slovenian language Slovenian_winmerge-2.16.34-2c99494d5
[Slovenian_winmerge-2.16.34-2c99494d5.zip](https://github.com/WinMerge/winmerge/files/13284103/Slovenian_winmerge-2.16.34-2c99494d5.zip)

With respect
Jadran

**Comment by sdottaka** [comment]
Thank you!

**Comment by JadranR** [comment]
Hi,
I send you now updated Slovenian translation for  Win Merge 2.16.38.
With respect,
Jadran
[Slovenian_Win Merge 2.16.38..zip](https://github.com/WinMerge/winmerge/files/14077631/Slovenian_Win.Merge.2.16.38.zip)

**Comment by sdottaka** [comment]
Thank you!
