### ISSUE TITLE
Ignore EOL changes option is not working as expected in Tree View mode (both GUI and CLI)

### ISSUE THREAD

**Issue by egvijayanand** [WinMerge/winmerge#2099]
Have been using ignore EOL changes for a very long time, but now it is not working in both GUI and CLI (`/ignoreeol`) as expected in v2.16.34

Previously, it worked properly.

Kindly fix this as soon as possible as it is becoming a huge burden to ignore those files.

**Comment by egvijayanand** [comment]
To be precise, this issue is in the **Tree Mode** view, where the file that differs only by EOL is also displayed as a **Modified** file.

The ignore case option is honored when opened as a single file comparison.

This option should also be considered for Tree View mode, if opted-in.

**Comment by sdottaka** [comment]
Duplicate of #2080

**Comment by sdottaka** [comment]
Thank you for your report.
This issue has already been fixed, but has not been released yet.
As a workaround, you can avoid this problem by specifying something other than default for the Diff algorithm as shown below.

![image](https://github.com/WinMerge/winmerge/assets/98126/9c169527-aa5e-49a8-b254-e8b1c2718fe1)

**Comment by egvijayanand** [comment]
Glad to hear that it's already fixed. Hope a fix release is planned in the near future. Will try the workaround for now.

**Comment by sdottaka** [comment]
We have released version 2.16.36 which includes a fix for this issue.
