### ISSUE TITLE
[Image compare] Inconsistent number of differences

### ISSUE THREAD

**Issue by g-mahieux** [WinMerge/winmerge#210]
Hi,
When comparing images which are similar but have significant differences, I see that the number of differences reported at the bottom of the window seems inconsistent.
In particular, when lowering the threshold, the reported number of differences increases, goes to a peaks and then lowers again.
I would expect the number of differences to have a maximal value when the threshold is minimal ; but maybe I am missing something.
See attached screenshots where the number of differences is lower with a lower threshold.
![Winmerge1](https://user-images.githubusercontent.com/37588339/67275768-9b21e280-f4c3-11e9-94dd-5538648ac3f6.png)
![Winmerge2](https://user-images.githubusercontent.com/37588339/67275789-a37a1d80-f4c3-11e9-8001-5c152a17481a.png)
I am expecting that the reported number be consistent with the number of yellow pixels which highlight the differences.
I am working with WinMerge 2.16.4.0 (X64).
Thanks for your feedback.

**Comment by sdottaka** [comment]
The number of differences does not mean the number of difference pixels.

Assuming that there are two difference pixels, if the difference pixels are adjacent, the number of differences is counted as one.

**Comment by g-mahieux** [comment]
Thanks for the clarification.
A nice feature would be to have a setting to enable/disable the merging of adjacent differences in the counting process.
