### ISSUE TITLE
Self-signed certificates support

### ISSUE THREAD

**Issue by germain-italic** [WinMerge/winmerge#2108]
The website I am working on requires HTTPS even on localhost development.

I have a self-signed certificate and a Root CA added to Windows truste store, the certificate is seen as valid in the browser on mysite.localhost (lock icon).

The CA and certs are managed via mkcert: https://github.com/FiloSottile/mkcert

However when opening the URL, WinMerge will complain: _winmerge curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - La fonction de révocation n'a pas pu vérifier la révocation du certificat._

The error message is in French, but you have the error code.

I haven't seen any option to bypass SSL verification (this error could be solved by adding `--ssl-no-revoke` to the cURL command in WinMerge).

**Comment by germain-italic** [comment]
Well, I've found a workaround.
Go to `C:\Program Files\WinMerge\MergePlugins`
Open `Plugins.xml` in Administrator mode

Line 11 replace:
`<command>curl ${*} -o "${DST_FILE}" "${SRC_FILE}"</command>`

With:
`<command>curl ${*} --ssl-no-revoke -o "${DST_FILE}" "${SRC_FILE}"</command>`

Shall I create a pull request, or is it better to keep SSL validation as is?

**Comment by sdottaka** [comment]
The `--ssl-no-revoke` command line option can be specified in the Plugins window as follows.

Considering that curl doesn't enable --ssl-no-revoke by default, it seems better to avoid adding `--ssl-no-revoke`.

![image](https://github.com/WinMerge/winmerge/assets/98126/d7317d5b-5c8d-42c8-a532-743d47a3fbbd)

**Comment by germain-italic** [comment]
Interesting, thanks!
