### ISSUE TITLE
"Register Windows 11 Shell Extension" fails because PowerShell script doesn't escape special chars correctly

### ISSUE THREAD

**Issue by Sgt-Nukem** [WinMerge/winmerge#2109]
Example Windows user name: Kathy with 'k'
%USERPROFILE% dir: C:\Users\Kathy with 'k'

It seems the PowerShell script just wraps it in single quotes so tries to call 'C:\Users\Kathy with ' and gives the rest as argument:
`Add-AppxPackage : A positional parameter cannot be found that accepts argument
'k\AppData\Local\Programs\WinMerge\WinMergeContextMenuPackage.msix'.
At line:1 char:1`

**Comment by sdottaka** [comment]
Fixed by commit [f44c06a](https://github.com/WinMerge/winmerge/commit/f44c06ad89b0f1f44c363ffa3e75c6f27b05d919)
Thank you for your report
