### ISSUE TITLE
[Image compare] Zoom-in focuses on top-left corner instead of cursor position

### ISSUE THREAD

**Issue by g-mahieux** [WinMerge/winmerge#211]
Hi,

This is about the image compare feature.
When zooming in via ctrl+ mouse scroll, WinMerge zooms towards the top-left corner instead of toward the location of the cursor.
This makes it difficult to zoom into a specific area of a big picture.

A related issue:
When you switch back to WinMerge from another program, you first need to click one of the pictures before you can mouse scroll zoom ; even though the WinMerge window is the active window. This is not the case with text files comparison.

I am working with WinMerge 2.16.4.0 (X64).
Thanks for your feedback.

**Comment by sdottaka** [comment]
Fixed by commit 958aee9 

Thank you for the report.

The latest CI build artifacts are available at:
https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts

**Comment by g-mahieux** [comment]
Thanks for the fix!
