### ISSUE TITLE
Can't click and change file line endings with the version 2.16.36.

### ISSUE THREAD

**Issue by Femtometer** [WinMerge/winmerge#2129]
Works fine in 2.16.34.
![截图_2023-12-01_16-26-13](https://github.com/WinMerge/winmerge/assets/5461891/d80f0517-8e36-428b-b648-27b7885b8c2b)

**Comment by sdottaka** [comment]
This bug was fixed in commit [2659c40](https://github.com/WinMerge/winmerge/commit/2659c40db7c1c1abc248bfb2a6446f9bb2ee83ea).
Thank you for your report.
