### ISSUE TITLE
Windows Installer wrong codepage for Russian

### ISSUE THREAD

**Issue by kaftanati** [WinMerge/winmerge#213]
File WinMerge-2.16.4-x64-Setup.exe
When launched, shows broken words.
Windows 10 pro 1903
![WinMerge-2 16 2-x64-Setup exe scr2](https://user-images.githubusercontent.com/11496817/67664074-f77b7b00-f977-11e9-9a2a-4003a27c120c.png)
![WinMerge-2 16 2-x64-Setup exe scr1](https://user-images.githubusercontent.com/11496817/67664077-f8141180-f977-11e9-9438-697da59c30d9.png)

**Comment by sdottaka** [comment]
Thank you for the report.

I think this issue was fixed by https://github.com/WinMerge/winmerge/pull/166.

Could you try the latest installer below?
https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts

**Comment by kaftanati** [comment]
Hello,

Thanks for quick reply.
I checked latest installer - all're working fine.

*С уважением, Борис Кафтанатий.*



вт, 29 окт. 2019 г. в 01:50, Takashi Sawanaka <notifications@github.com>:

**Comment by kaftanati** [comment]
Already fixed at lastest version of installer.
