### ISSUE TITLE
Changing file encoding is not working right

### ISSUE THREAD

**Issue by timint** [WinMerge/winmerge#2174]
Hi. I used v2.16.32.0 and when clicking character encoding at the status bar I found it impossible to make the editor comply to the given settings for character encoding of the modal window.

I then upgraded to v2.16.36.0 and something is fishy here. Now it won't open the modal window when clicked.

![image](https://github.com/WinMerge/winmerge/assets/359192/c1ebf279-4abc-48ab-9a44-3ef7584b39d0)

**Comment by sdottaka** [comment]
Thank you for your report.
The issue where the Codepage window was not displayed has been fixed in version 2.16.37.

Duplicate of #2129

**Comment by timint** [comment]
Thank you for getting back to me. I am delighted to hear that this has been addressed. 👍
