### ISSUE TITLE
unable to "Safely Remove Hardware or eject Media" after a WinMerge

### ISSUE THREAD

**Issue by ganer9** [WinMerge/winmerge#2187]
I connected an external HDD.
I compared the contents using WinMerge. After task completion, I closed WinMerge

I tried to Safely Remove Hardware and Eject Media > Eject "External HDD name"

I get error
![windows error on eject](https://github.com/WinMerge/winmerge/assets/157191091/a9feafe6-e50c-4f1a-ad9e-a495d60505a0)

**Comment by sdottaka** [comment]
Looking at the attached image, it looks like the WinMerge process is still running.
Please terminate all WinMerge processes.
Occasionally, processes may remain even after WinMerge is terminated, so in that case, please terminate the WinMerge process from taskmgr.

**Comment by ganer9** [comment]
There are no Winmerge processes running in the background.Please see screenshot


    On Saturday, 20 January, 2024 at 02:16:32 pm IST, Takashi Sawanaka ***@***.***> wrote:  
 
 


Looking at the attached image, it looks like the WinMerge process is still running.
Please terminate all WinMerge processes.
Occasionally, processes may remain even after WinMerge is terminated, so in that case, please terminate the WinMerge process from taskmgr.

**Comment by sdottaka** [comment]
If the WinMerge process does not exist, I think another process is referencing the external HDD.

**Comment by ganer9** [comment]
I get the error msg whenever I reference the external HDD in WinMerge not otherwise

    On Saturday, 20 January, 2024 at 04:38:01 pm IST, Takashi Sawanaka ***@***.***> wrote:  
 
 


If the WinMerge process does not exist, I think another process is referencing the external HDD.

**Comment by sdottaka** [comment]
Since you replied via email, the second image you probably attached is not visible in the GitHub issue, so we couldn't confirm whether the WinMerge process exists. 
If the WinMerge process is displayed in the task manager as shown in the attached image, forcefully terminate it.
If the external HDD cannot be safely removed even though the WinMerge process does not exist, it is not a WinMerge problem, but an OS problem or another process is referencing it.
![image](https://github.com/WinMerge/winmerge/assets/98126/cb795346-56c1-40d2-bbc4-5d48ed8b358e)

**Comment by ganer9** [comment]
![Taskmgr_ _EjectMedia_screenshot](https://github.com/WinMerge/winmerge/assets/157191091/293b1045-7c46-478c-9dd8-1a59c8df43da)
Herein attached is the screenshot I have mentioned above.

I can confirm there are no WinMerge processes running

When Iam not using Winmerge on the external HDD, I can safely remove it without getting any error msg. This leads me to conclude that Winmerge has a role in the appearance of error msg.

**Comment by sdottaka** [comment]
It seems that you can use Resource Monitor to find out which processes are referencing files and folders on the external HDD.
Could you please try searching by specifying `external HDD drive name:\` in Resource Monitor as shown below?

![image](https://github.com/WinMerge/winmerge/assets/98126/ce1ba8b9-e96d-486c-ac6e-b325a1740e1b)

**Comment by ganer9** [comment]
As if by magic, I'm not able to reproduce the error now

**Comment by pgert** [comment]
I occasionally have this problem, but then it's WinMerge unrelated.
It usually can be solved by pressing the OK button on the message-dialog,
 and then make another reguest for safe removal of the storage-medium, which then is granted.
Annoying Windows bug.

**Comment by ganer9** [comment]
The problem occured again today.

I opened resmon.
Guess what? There is no error after that

**Comment by sdottaka** [comment]
If WinMerge isn't showing up in resmon, at least it's not a WinMerge problem.
If nothing is displayed, the OS itself may be referencing the external HDD, or virus scanning software may be temporarily referencing it.

**Comment by ganer9** [comment]
The problem occurred again (after a WinMerge compare , and closing WinMerge)
I opened resmon.
WinMerge isn't displayed

In Task Manager, Status of Application "Problem Ejecting USB Mass Storage Device" is running

My question: How to track this Application in reston

**Comment by sdottaka** [comment]
I don't know how. Is the following URL helpful for how to safely remove an external HDD?
https://techcult.com/fix-problem-ejecting-usb-mass-storage-device/

**Comment by ganer9** [comment]
Yes
