### ISSUE TITLE
"Copy to right" doesn't work under special circumstances (left nothing, right additonal emtpy line)

### ISSUE THREAD

**Issue by rondlh** [WinMerge/winmerge#2204]
In the image below, the right file has an additional empty line, which I want to mirror to the right (delete the extra line), but the "copy to right function" doesn't do that, nothing seems to happen when I click "Copy to right".

![Copy To Right](https://github.com/WinMerge/winmerge/assets/77279634/f0d353d5-8720-4c60-9258-f01f5bee2161)

I have "Ignore blank lines" enabled, perhaps this is the cause.

**Comment by sdottaka** [comment]
Enabling "Ignore blank lines" will ignore differences in blank lines and make the background a light yellow color. As you might have guessed, the ignored differences are not eligible for copying.
Disable "Ignore blank lines" to copy the differences.

**Comment by rondlh** [comment]
This behavior is a bit odd in my view, WinMerge shows me there is a difference, and give me the option to copy it, but just ignores me when I select it. In my view it would be better to:
1. not show the difference
**OR**
3. copy the difference if I use the copy option.
Showing me a difference, but not letting me copy seems not logical.
I do not like to toggle "Ignore blank lines" the whole time just to copy these blank lines.

**Comment by rondlh** [comment]
OK, I don't agree, but anyway, let's close this issue
