### ISSUE TITLE
Creation of .bak files fails when the original filename starts with a dot

### ISSUE THREAD

**Issue by exoosh** [WinMerge/winmerge#2217]
When making changes to a file from within WinMerge it will create a backup file based on the original filename and then `.bak` appended. This is usually a silent process.

Today I first ran into an issue with a file name that starts with a `.` where this scheme fails.

![image](https://github.com/WinMerge/winmerge/assets/81239903/cb654714-6b6b-4d99-843f-927da687ba38)

Since images cannot be searched as easily: the message says that the backup could not be created and mentions "`C:\Users\oschneider\.bashrc` (-> `C:\Users\oschneider.bashrc.bak`)". Note the missing `\`.

**Comment by sdottaka** [comment]
This issue was fixed with commit efac7e6.
Thank you for your report.

**Comment by exoosh** [comment]
Whoa, that was fast. Thank _you_!
