### ISSUE TITLE
Invalid saving project to existing file (damaged overwriting)

### ISSUE THREAD

**Issue by marsi81** [WinMerge/winmerge#222]
Invalid saving project to existing file (damaged overwriting).
When I save project to existing file which is longer than new content then rest bytes remain in file. New file is not truncated to valid length and generates invalid xml project file.
Reason: save mode in Read/Write mode should set new file size but it doesnt do.
![screenshot](https://user-images.githubusercontent.com/6542838/68683505-2cd2bc00-0567-11ea-8d52-fbd67e51c69e.png)

**Comment by sdottaka** [comment]
I could not reproduce the bug.
There is a similar bug before, and it remembers that it has been fixed.
Which version are you using?

**Comment by marsi81** [comment]
WinMerge 2.14.0 + (3-way merge, image compare/merge) +-jp-137

From here: https://github.com/WinMerge/winmerge/releases/tag/2.14.0%2B-jp-137

**Comment by marsi81** [comment]
Scenario
Make project of comparing two folders with filter: "*.h;*.cpp *.txt,*.ini" and save it to the file.
Next, change filter to shorter text like "*.h" and save again to the same file.
Result file will be like:

<?xml version="1.0" encoding="UTF-8"?>
<project>
	<paths>
		<left>C:\Users\T0234568\Documents\BCB6\</left>
		<right>C:\Users\T0234568\Dropbox\Backup\Programowanie\BCB6\</right>
		<filter>*.h</filter>
		<subfolders>1</subfolders>
		<left-readonly>0</left-readonly>
		<right-readonly>0</right-readonly>
	</paths>
</project>
ect>
</project>


![screen1](https://user-images.githubusercontent.com/6542838/68857567-54e72a00-06e3-11ea-81b0-54018b34b66e.PNG)
![screen2](https://user-images.githubusercontent.com/6542838/68857568-54e72a00-06e3-11ea-865a-dcfa1157d9ad.PNG)
[x.WinMerge.txt](https://github.com/WinMerge/winmerge/files/3846470/x.WinMerge.txt)

**Comment by sdottaka** [comment]
Thank you for the information.

I confirmed that the problem occurred in version 2.14.0+-jp-137. The latest version 2.16.4 does not have this problem, so please use the latest version.

Note that in the latest version, the Save Project dialog is integrated into the [Open] window as shown below.

![image](https://user-images.githubusercontent.com/98126/68903029-2e75cd00-077d-11ea-9cd4-a9eabd8ca25d.png)

**Comment by marsi81** [comment]
Thank you for the information. You alright. I downloaded new version and this bug not exist.
