### ISSUE TITLE
7zip encrypted archives with encrypted file names

### ISSUE THREAD

**Issue by Ugau943** [WinMerge/winmerge#2225]
I don't know if this has anything to do with https://github.com/WinMerge/winmerge/issues/367, but I personally have a problem with the same topic.

Comparing two 7z files with password without encrypted file names works fine, it asks for the password and that's it. 

But, with two 7z files with password **_and_** encrypted file names, I get an error saying "System can't access the file".

It could have something to do with my OS, since I had some trouble with it recently, but I preferred to ask here first, before investigate further for nothing.

**Comment by sdottaka** [comment]
Commit f361646 fixed this issue.

This fix will be included in the next version 2.16.39, but you can also replace Merge7z.dll below with installation folder/Merge7z/Merge7z.dll.

https://github.com/WinMerge/winmerge/releases/tag/Merge7z2301.1

**Comment by Ugau943** [comment]
Work like a charm.
