### ISSUE TITLE
Make event sync settings persistent

### ISSUE THREAD

**Issue by oelgoetz** [WinMerge/winmerge#2248]
Hello,

the synchronized scrolling when using webpage-diff is very good! It's really great that you done it ! 
(https://github.com/WinMerge/winmerge/pull/2111). 

I use it extensively by launching it from a self-written C# application using the following arguments: `file1 file2 /s /u /t Webpage`.

Because of the `/s` option every diff opens in a new tab.
However I found that the settings in the event-sync comboBox are not persistent: One has to activate at least the topmost check box to use the sync feature. 
Is it possible to make these settings persistent - at least in the same session of the WinMerge application?
![image](https://github.com/WinMerge/winmerge/assets/26176276/c6c8a0ae-0c65-4ea9-8c5d-8e018da15472)
IMHO it would be sufficient when every new tab that is started in `/t Webpage` mode uses the same settings as they were used in the last tab opened in that mode.

**Comment by sdottaka** [comment]
Thank you for your report.
It is simply a bug that the selection in the Location Pane's Event Sync dropdown menu is not persistent.
As a workaround, if you set it in the Webpage → Event Sync menu as shown below, it will become a permanent setting, so please set it there.

![image](https://github.com/WinMerge/winmerge/assets/98126/70f0d44c-ac0c-4172-8845-c0d3735b0d7a)

**Comment by sdottaka** [comment]
With commit 8374769, Event Sync settings are now saved when the window is closed.

**Comment by oelgoetz** [comment]
wow! that was quick!
Thank you for the workaround and AFAICS youe even fixed the issue already!
