### ISSUE TITLE
French encoding problem on the end of installation (last dialog box)

### ISSUE THREAD

**Issue by slolo2000** [WinMerge/winmerge#2272]
Hello,

Just to the end of WinMerge installation, there is a dialog box which display a long text.
As you can see on the screenshot below, there is an encoding problem on accented characters.

Reproduce on Windows 11 with "WinMerge-2.16.38-x64-Setup.exe" file.

Can you fix it for the next release please?

![image](https://github.com/WinMerge/winmerge/assets/10075509/156ae50f-cd44-451e-b0e0-098aa943ca20)

**Comment by sdottaka** [comment]
Fixed in commit [69b3bf2](https://github.com/WinMerge/winmerge/commit/69b3bf2407c64f55fa79a50ac40d591fa341b623)

Thank you for your report
