### ISSUE TITLE
[Question] Is it possible to add/submit language file for Merge7z?

### ISSUE THREAD

**Issue by PopuriAO29** [WinMerge/winmerge#2273]
## Question

I'm literally confused, since there are repositories for 7-zip clone, but is it possible to submit the language text file into [this](https://github.com/WinMerge/sevenzip)? Just let me know if there are problem.

Also, you may notice since 7-Zip 24.03 was released. We need wait the source code as well.

## Have you checked that no similar question(s) exist?
* [x] I have searched and didn't find any similar question.

**Comment by sdottaka** [comment]
https://github.com/WinMerge/sevenzip is simply a copy of the 7-Zip source code files. When a new version of 7-Zip is released, its source code files and language files will be overwritten. Therefore, please submit your language files to https://sourceforge.net/projects/sevenzip/.
