### ISSUE TITLE
Replace text issue

### ISSUE THREAD

**Issue by rxa1031** [WinMerge/winmerge#2279]
Hi All,

When replacing text using Replace (CTRL+H), it is observed that the second replace button press results in incorrect data/text replacement.

https://github.com/WinMerge/winmerge/assets/18160755/f7bcdda1-b8e9-4a5e-9de2-c2f5fa30dc6f

Sample test/example below:

Original:
![image](https://github.com/WinMerge/winmerge/assets/18160755/8b7623d0-290e-4048-94b2-09ebd3da881c)

Changed:
![image](https://github.com/WinMerge/winmerge/assets/18160755/b1fbacbe-4af2-4387-a68f-5bffa60c3103)

Please help fix the issue.

Regards,
Rajeev

**Comment by sdottaka** [comment]
I tried to reproduce this issue as shown in the GIF animation below, but was unable to do so.
Which version of WinMerge are you using?
If it is not the latest version, please try the latest version.
![#2279](https://github.com/WinMerge/winmerge/assets/98126/609fec0b-2375-4401-b215-2c34a82c96eb)

**Comment by rxa1031** [comment]
![image](https://github.com/WinMerge/winmerge/assets/18160755/87e43f02-d5d0-4695-8125-92026b05d103)

I highlight the text that needs to be replaced, then press CTRL + H, then change replace in to whole file. Finally I click at least one line above or on the extreme left of the line that has the first occurrence of the text that needs change. Then I press the shown button sequence.

**Comment by rxa1031** [comment]
I confirm the issue is only observed when a part of the text to be searched is highlighted and then CTRL + H is pressed. As the search (and replace) movement is from top to bottom. I need to place the cursor either on the left side of the first word/text/sub-sting/string to be replaced or on any line that is above the first word/text/sub-sting/string to be replaced. I then click the Find Next button. Once the first replace text gets highlighted I start clicking the replace button, until I am done with all replaces.

**Comment by sdottaka** [comment]
Although different from your video, I was able to reproduce the strange behavior shown in the video below.
I'll take a look at it later.

![#2279_2](https://github.com/WinMerge/winmerge/assets/98126/144f4d70-7b0e-4f1e-80e7-2364120f0dbe)

**Comment by rxa1031** [comment]
Since I wanted to replace ndom, I am only highlighting ndom and then pressing CTRL + H

**Comment by rxa1031** [comment]
The size of the captured video would have been greater than 10 MBs and hence could only a part of the whole process. My office laptop does not have an IT approved tool for video compression.

**Comment by sdottaka** [comment]
Finally, I am now able to reproduce this issue as well.
To reproduce this problem, it was necessary to enable Automatic rescan in the Editor category of the Options window.

![image](https://github.com/WinMerge/winmerge/assets/98126/3771703a-9bde-4df9-b68e-e0e1cc1482de)

**Comment by rxa1031** [comment]
Current used settings in my case (Automatic rescan is disabled):
![image](https://github.com/WinMerge/winmerge/assets/18160755/36f0edf8-cc6a-4c8f-8d4f-a51d29ec8e55)

**Comment by rxa1031** [comment]
Used general settings:
![image](https://github.com/WinMerge/winmerge/assets/18160755/ef10a2c7-3c93-40df-be08-eef3c42a2773)

**Comment by rxa1031** [comment]
https://github.com/WinMerge/winmerge/assets/18160755/37007adf-6d78-43e2-9427-f0d764c81fe2

**Comment by sdottaka** [comment]
> I need to place the cursor either on the left side of the first word/text/sub-sting/string to be replaced or on any line that is above the first word/text/sub-sting/string to be replaced

Thank you for attaching the video. I missed the above. I was able to reproduce this issue as well.

I fixed this issue in commit [d3ab50c](https://github.com/WinMerge/winmerge/commit/d3ab50c17250da28ba933435c2434411e1072935).

You can download the latest CI artifacts from the URL below.

https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts
https://github.com/WinMerge/winmerge/actions/runs/8670205946

Thank you for your report.
