### ISSUE TITLE
Program is crashed!

### ISSUE THREAD

**Issue by username1565** [WinMerge/winmerge#229]
When two files are compared in binary mode (File -> recompare as binary, as hex)
and after this, one from this files is deleted (or just renamed),
the program ask to update file. If "No" button is pressed, then everything is OK...

But on press the button "OK",
there is an error "Cann't found the file".
After this - program **IS CRASHED**, and all previous results are - not saved,
and Visual Studio 2010 show an error:
"Unhandled exception at 0x0050f610 in WinMergeU.exe: 0xC0000005: Access violation reading location 0x000000dc."

This error I see on **Windows XP**, using x86 (win32) binary in _portable mode_.
[winmerge-2.16.4-exe.zip](https://downloads.sourceforge.net/winmerge/winmerge-2.16.4-exe.zip) (x86, win32, portable, Windows XP).

Maybe, in some another systems you can see the same behaviour.
So, something need to fix, there.

**Comment by sdottaka** [comment]
Fixed by commit 9c16ef83b2fadfe258d6de03322075d6d4acf423

Thank you for the report.
