### ISSUE TITLE
WinMerge 2.16.40 - Installer - Missing version and archicteure info

### ISSUE THREAD

**Issue by bovirus** [WinMerge/winmerge#2300]
@sdottaka

Pelase check installer exe file (32bit and 64bit).

The installer didn't show version (32bit and 64bit version) and architectire (64bit version)?

32bit installer - Missing version
![image](https://github.com/WinMerge/winmerge/assets/1262554/2d2f1c37-ec86-42e8-a8dd-11e249b7d021)

64bit installer - Mssisng version and architecture info
![image](https://github.com/WinMerge/winmerge/assets/1262554/e63bd871-bf19-4230-b175-895a9b9a6c48)

64bit installer - Missisng copyright info / missing info installer 64bit
![image](https://github.com/WinMerge/winmerge/assets/1262554/9d88a94a-6420-46e8-ad1b-77b92759fa9f)

**Comment by sdottaka** [comment]
I removed the version information and architecture from the installer's title bar for simplicity, but it's bad to not have version information on any page of the installer. . .

I'm either going to change it back or have the version information included on the page somewhere.

**Comment by gitgrub** [comment]
I think the version info is a good thing, just want to know what I do.

**Comment by sdottaka** [comment]
Fixed in commit c4316fe. Thank you for your report.

**Comment by bovirus** [comment]
@sdottaka

Sorry but I didn't unbderstand what "semplicitY" ciould be.

I believe that to have iversioin and architecxture (not x86 - x64 but 32bit/64bit/ARM) info it's very important and suieful.
Not show in x86 version becaiuse that is clear that if is not x64 it's so simple.
 
For me show these info in windows caption and then visible for ALL steps of the installer it's the best place for this scope.

**Comment by sdottaka** [comment]
The version information and architecture are now displayed in the window title.

**Comment by bovirus** [comment]
@sdottaka 

Thanks.

Did you show architecture info also for x86 version (in the apst is not included)?
Did you use in the title "x86"/"x64" or more common and clear for most users "32bit"/"64bit"?
If you use "x86"/"x64" please use "32bit"/"64bit.

**Comment by sdottaka** [comment]
The x86 version will be displayed as x86.

WinMerge supports four architectures: x86, x64, ARM, and ARM64, so 32bit or 64bit is not enough.
(However, the installer is only for three architectures.)

Also, "32bit" and "64bit" require translation, so I avoided them for simplicity.

**Comment by bovirus** [comment]
@sdottaka 

But x86/x66 not help user to udnerstanmd.
ARM ARm64 is clear.

**Comment by gerundt** [comment]
@bovirus If a user is the bitness important he should know that "x86" is the old 32 bit stuff and x64 is 64 bit. 😉

If he don't understand the information, it is not a important for him. Sine the 32 bit version run under x64 too, he should can work with WinMerge.

**Comment by jonadem** [comment]
My 2 cents :
I downloaded the installer from the website and I get `WinMerge-2.16.40-Setup.exe`. When I installed it, I noticed that it wanted to install it in `C:\Program Files (x86)` and it questioned me if the software is in x86 or x64 and I found this issue.
I went to sourceforge to specifically download `WinMerge-2.16.40-x64-Setup.exe` and installed it. he didn't propose me to install Winmerge in `C:\Program Files (x86)` with this installer. Sorry if this is not relevant here.

**Comment by bovirus** [comment]
@gerundt 
@jonadem

For me for the stree user that has no specifc knowledge the info should be clear and identify well 32biit or 64bit installer.

We don't think basing on our knwolkedge but about most user knowledge.

**Comment by sdottaka** [comment]
Ah, we released 2.16.41 which includes this fix, so we closed this issue without really checking the details.
However, at least as the title of this issue says, the version and architecture are now included in the title of the installer window, so we will close this issue for now.
If you are still interested in changing the way the architecture is displayed, please start a new issue.

If we are to think more about users, we should also consider the following in the first place.

- The file name of the x86 installer does not include x86 or 32bit.

- The default on the WinMerge web page is the x86 installer.

- There is no information about whether the file available for download from the download page is the 32-bit, 64-bit, or ARM64 version.

As for the first two points above, I probably did not have the courage to change them because it would affect external sites and existing users.
