### ISSUE TITLE
Invalid compare Result

### ISSUE THREAD

**Issue by swcreate-git** [WinMerge/winmerge#2317]
WinMerge 2.16.40.0 X64, Windows 11

![image](https://github.com/WinMerge/winmerge/assets/58575479/1646fa93-1fcc-41dd-aa2c-cb271f734dd0)

I encountered a strange comparison result.

These two files are actually different files, but they should be treated the same when the option to ignore White Space is turned on.

However, even though there is no real difference in the final line, it is detected as if there is a difference.

The following is the file I compared to the option I set.

![image](https://github.com/WinMerge/winmerge/assets/58575479/dfc47c90-dd73-4fb9-9b02-535c02a74e64)

[Compare.zip](https://github.com/WinMerge/winmerge/files/15233093/Compare.zip)

**Comment by sdottaka** [comment]
Unfortunately, WinMerge does not have an option to ignore differences in line endings when comparing files where one file has no end-of-line (EOL) characters at the end and the other file does have EOL characters at the end.

Duplicates #203 and #989

**Comment by sdottaka** [comment]
PR #2573 allows you to ignore differences where only one of the files does not have a trailing newline.
