### ISSUE TITLE
How to set filter to ignore specific line?

### ISSUE THREAD

**Issue by JStanula** [WinMerge/winmerge#2319]
Hi,
I've got two files to compare. The files are scripts/text in LaTex language. 

In my first file I've got example line:

This house is red. %MOD

In my second file:

This house is blue.

I want to set filter that will ignore every line which contains '%MOD'. Keep in mind the '%MOD' appears only on first file. So if line in first file contains '%MOD' I don't care if there's a change in second one or not. How can be done,??

**Comment by sdottaka** [comment]
WinMerge can use Line filters to ignore differences in lines if the second file also contains %MOD. But unfortunately, I don't think WinMerge can ignore the difference in %MOD lines if one of the files doesn't contain %MOD.
