### ISSUE TITLE
Right click context menu - Compare files or folders in a new tab

### ISSUE THREAD

**Issue by paritosh149** [WinMerge/winmerge#232]
Right Folder Structure:
RightParentFolder
  RightSubFolder
    RightFile.txt

Left Folder Structure:
LeftParentFolder
  LeftSubFolder
    LeftFile.txt

Steps to reproduce:
1. Compare RightParentFolder and LeftParentFolder (include sub-folders)
2. Select RightSubFolder and LeftSubFolder
3. Right click to show context Menu
4. "Compare in new Tab" - option not available

Feature Request : "Compare in new Tab" - should be available

**Comment by sdottaka** [comment]
There is currently no "Compare in new Tab" menu item.
However, when selecting the "Compare" menu item with pressing Ctrl key, it will work as expected.

**Comment by sdottaka** [comment]
Implemented in commit 0e35f71
