### ISSUE TITLE
Comparison Error

### ISSUE THREAD

**Issue by 1John419** [WinMerge/winmerge#2327]
Version 2.16.40.0
Windows 10 Pro 64-bit

Encountered a comparison error. Files are reported as Identical:

![wm01](https://github.com/WinMerge/winmerge/assets/46386951/aecf60e0-2b71-4d5f-84a6-caf2b06f73ba)

They are, in fact, slightly different:

![wm02](https://github.com/WinMerge/winmerge/assets/46386951/9d617304-f1fa-4bf3-8088-96f14996266a)

I have repeatedly hit Refresh and tried close/open WM. Same results.

[src.zip](https://github.com/WinMerge/winmerge/files/15338483/src.zip)

**Comment by 1John419** [comment]
Update:

Options > Compare > Folder > Compare method

  Size (default) ->> error
  
  All other options ->> correctly report 'Files are different'

**Comment by sdottaka** [comment]
As you may have noticed, the Size compare method only compares file sizes, so if the file sizes match, the files
is considered Identical.
The Modified Date and Size compare method compares not only the file size but also the modification date and time of the file.

**Comment by 1John419** [comment]
OK, appears Options > Compare > Folder actually means Compare Folder/File. Thanks for clarifying.
