### ISSUE TITLE
WinMerge not registered as an app in Windows 11

### ISSUE THREAD

**Issue by thernstig** [WinMerge/winmerge#2328]
Previously WinMerge registered as an app in Windows 11, but in my latest installations on new computers it has not.

What I mean by this is that if I use the search field in Windows 11, it should show up as an "app". Compare these two images:

![image](https://github.com/WinMerge/winmerge/assets/30827238/c5f9bc7c-5570-415d-b3d2-e1db52799c67)

![image](https://github.com/WinMerge/winmerge/assets/30827238/3866c84c-879d-46bf-9650-ded9bec77cde)

Notice how for word I just have to type "W" for it to show as it is an app. For WinMerge I have to type the full name and then it is shown as a command.

I just did a plain install with the WinMerge-2.16.40-x64-Setup.exe file.

**Comment by sdottaka** [comment]
You probably installed it by checking "Don't create a Start Menu folder" in the installer.
If you install it with this check removed, I think it will work as you expect.

![image](https://github.com/WinMerge/winmerge/assets/98126/fa861ce5-a922-42fb-b960-a3933097b139)

**Comment by thernstig** [comment]
@sdottaka that is correct, but should that be necessary for this? Is that the exact way Windows 11 finds it as an "App", or is this a quirk of how WinMerge decides to register itself depending on that option?

**Comment by sdottaka** [comment]
To enable searching for an application by name in the Windows 11 Start menu, you need to create a shortcut file for the application in the Start Menu folder (C:\ProgramData\Microsoft\Windows\Start Menu\Programs or C:\Users\username\AppData\Roaming\Microsoft\Windows\Start Menu\Programs).

The checkbox mentioned will create a WinMerge folder in the above directories and within that folder, it will create a shortcut file to WinMergeU.exe.

**Comment by thernstig** [comment]
@sdottaka then this is my mistake, I had no idea Windows 11 was so "dumb" it required it to be in one of the Start Menu directories for it to be considered an app. I mean, consider if someone adds it just to their desktop (or maybe not even that). It is still an "App" for all intents and purposes.

I thought Windows 11 had another concept to define what is an "App" when searching, then for it to just be in the Start Menu.

I suppose I will close this then. Appreciate your patience.
