### ISSUE TITLE
Wrong version

### ISSUE THREAD

**Issue by BenziEilon** [WinMerge/winmerge#2330]
Winmerge title and about show version 2.14.0.0 instead of the current version 2.16.40. I think it was also in previous versions. (System is Windows 10).
![WinMerge title](https://github.com/WinMerge/winmerge/assets/170317183/9a9ec450-0259-4696-91db-36db3dc45e7d)
![Winmerge About](https://github.com/WinMerge/winmerge/assets/170317183/0c23fb92-f2e3-4150-85f9-21c27bd7ffbf)

**Comment by sdottaka** [comment]
The current latest version of WinMerge, 2.16.40, does not display as version 2.14.0, as shown in the following image.

It's likely that you have multiple versions of WinMerge installed.

In such cases, when you launch WinMerge from the Explorer context menu, it will open the version that was most recently closed using the OK button in the Options dialog.

If you have installed WinMerge using an installer, please uninstall all versions of WinMerge and then reinstall the latest version.

![image](https://github.com/WinMerge/winmerge/assets/98126/99101304-005a-4796-9bb2-913affb393b5)

**Comment by BenziEilon** [comment]
Correct answer. Thanks. I had an old 32 bits WinMerge installed aside my X64 version
