### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by harryray33** [WinMerge/winmerge#2332]
Does this work with Win 7?

Thanks

**Comment by sdottaka** [comment]
Although there are some restrictions such as Clipboard compare, WinMerge should basically work on Windows 7.

**Comment by harryray33** [comment]
Thanks, do you know the last version of Winmerge that worked with Win 7 without any restrictions?

**Comment by sdottaka** [comment]
Please refer to the Wiki page below
https://github.com/WinMerge/winmerge/wiki/WinMerge-Supported-Features-by-Architecture

**Comment by sdottaka** [comment]
The above feature uses functionality that is not available in Windows 7, so it has never been usable on Windows 7.
