### ISSUE TITLE
Refresh selected shows wrong file names being compared

### ISSUE THREAD

**Issue by YecineM** [WinMerge/winmerge#2338]
After comparing two folders, when I try to refresh a selected subfolder (Ctrl + F5), the lower pane shows a wrong file name (outside of that subfolder) that is being compared.
I use windows 10 on a 64-bit machine.

**Comment by sdottaka** [comment]
Could you post a screenshot of before and after the refresh?

**Comment by YecineM** [comment]
during initial compare :
![b4](https://github.com/WinMerge/winmerge/assets/45966855/ad36f4c5-4631-4d61-b49a-4dc09d185fd7)
finished initial compare:
![b42](https://github.com/WinMerge/winmerge/assets/45966855/8d62f07d-e8ee-4ea0-b190-0648fa7e16ec)
during subfolder compare:
![after](https://github.com/WinMerge/winmerge/assets/45966855/64a15e3d-d7c4-406b-bffb-a7e81a30b946)

**Comment by sdottaka** [comment]
Ah, I think I've managed to reproduce the issue. I'll take a look at it later. Thank you for attaching the screenshot.

**Comment by sdottaka** [comment]
The issue has been fixed by commit [f62b2e5](https://github.com/WinMerge/winmerge/commit/f62b2e5b8b3e9d415045426e276dfd4d2ed271e6). Thank you for your report.
