### ISSUE TITLE
правка текста

### ISSUE THREAD

**Issue by 5jab** [WinMerge/winmerge#2344]
![win merge](https://github.com/WinMerge/winmerge/assets/58731630/c8d6909f-1973-4990-9cbd-1de4ca3f118a)
Доброго времени! подскажите пожалуйста, как "сделать" текст 2 столбца идентичным первому?

**Comment by auge8472** [comment]
Translation with deepl.com:

Good time! can you please tell me how to ‘make’ the text of 2 columns identical to the first one?

**Comment by 5jab** [comment]
Thanks, I got it. Is there a solution to the problem?

**Comment by sdottaka** [comment]
The file on the right is a JSON file with no line breaks and appears to contain three characters at the beginning that are invalid for a JSON file.
I don't think I understand your question correctly, but if you remove the invalid characters at the beginning of the file on the right, you can prettify it using the PrettifyJSON plugin and compare it, as shown below.

![image](https://github.com/WinMerge/winmerge/assets/98126/41601a06-1b72-405b-8528-38b0359588a8)

**Comment by 5jab** [comment]
Thanks, it helped! it actually looks a little different))
