### ISSUE TITLE
Options - Syntax color settings get reverted when "Customized text colors" settings is touched.

### ISSUE THREAD

**Issue by SinusPi** [WinMerge/winmerge#2355]
HOW TO REPRODUCE:
Change your syntax highlighting colors. Hit OK to see your change take effect.
Now flip the Text - "Use customized text colors" checkbox. And flip it back. And hit "Cancel" to make sure no options change.

WHAT HAPPENS:
The syntax settings will get reverted to defaults.

EXPECTED:
Syntax colors retaining their settings, of course.

**Comment by sdottaka** [comment]
The issue has been fixed in commit fa2bd5a. Thank you for your report.
