### ISSUE TITLE
Comparing a "left only" file complains about different carriage return types

### ISSUE THREAD

**Issue by rondlh** [WinMerge/winmerge#2357]
Comparing a "left only" file complains about different carriage return types.
This doesn't make much sense because there is no right file, so no carriage return type to compare to.
See picture.

<img width="1031" alt="Left file only" src="https://github.com/WinMerge/winmerge/assets/77279634/3a823d0d-7b57-405e-93f9-f6ffaeb2b9f4">

**Comment by sdottaka** [comment]
related to #1702

As a workaround, enable the Ignore carriage return differences (Windows/Unix/Mac) option.

![image](https://github.com/WinMerge/winmerge/assets/98126/bd568393-d1c0-44f2-8e02-3b42b7b4f1b7)

**Comment by rondlh** [comment]
@sdottaka Thanks, closing...
