### ISSUE TITLE
Selected files changes on expanding a folder that is upper on the tree

### ISSUE THREAD

**Issue by PhantomLord72** [WinMerge/winmerge#2359]
This happen with 2.16.40.0 x64
open winmerge for comparing 2 folder with other subfolder each one
expand one of the almost last folder
select 2 or 3 files
expand a folder BEFORE the previous one

the previous selected files loose the selection because they are shifted down and other files are selected

**Comment by sdottaka** [comment]
The issue was fixed in commit [54a19f1](https://github.com/WinMerge/winmerge/commit/54a19f1d126c32e6e7a273b5e29c21ab00c3a951). Thank you for your report.

**Comment by PhantomLord72** [comment]
In 2.16.41 beta the problem is slightly different, but present

**Comment by sdottaka** [comment]
Could you please post a screenshot of the folder before and after expanding?
In my environment, it looks like this:

![image](https://github.com/WinMerge/winmerge/assets/98126/e5cd6f48-d3a1-45e3-bea0-8645af8dbd6d)
![image](https://github.com/WinMerge/winmerge/assets/98126/28512da2-2c0f-45a1-a251-e30c8f8cd0d7)
