### ISSUE TITLE
XML file comparison

### ISSUE THREAD

**Issue by mdell-seradex** [WinMerge/winmerge#2365]
Is there a way (or can it be added) to compare XML files and ignore the order of attributes?
Alternatively, can prettifying the XML have the option to sort the attributes?

I ask, because I am sometimes comparing XML files that are automatically generated by a tool, but it doesn't seem to be consistent in the order the attributes are created.  It may be that the older version generated them in a different order, but I'm not sure.
Because of this, it makes it harder to compare them to determine if there were any actual changes.

Also, would it make sense to do something similar for json?

I appreciate any ideas.
Thank you

**Comment by sdottaka** [comment]
WinMerge has a PretitfyXML plugin that uses tidy-html5 to prettify XML files and sort attributes.

![image](https://github.com/WinMerge/winmerge/assets/98126/2a5001f6-4b35-47b1-b209-16012df1e92d)
![image](https://github.com/WinMerge/winmerge/assets/98126/e6ad5eb2-c78f-437b-a2ce-127fa1104101)

**Comment by mdell-seradex** [comment]
I had no idea it would or could do that!

**Comment by mdell-seradex** [comment]
I had no idea it would or could do that!
