### ISSUE TITLE
Replace - more intelligent choice of replace in (whole file vs selection)

### ISSUE THREAD

**Issue by meteorquake** [WinMerge/winmerge#2368]
Typically I'll double-click a word or small phrase and Ctrl-H to replace it to something else (this sequence prepopulates the replacer). This is common if for example the old and new are code that has a variable name change that is causing a lot of differencing highlights and I quickly want to remove that to see the other differences.
In doing so, because the Replace was called up from a selection, the replace default is "Selection" rather than "Whole File" which isn't sensible because the selection is only a few characters long.
* My recommendation for that is that when Replace is called up from a small selection (e.g. under 100 chars) the default is whole file rather than selection.
* However another - and I think better - solution is not to have the "Replace in" tickboxes at all, but to have both [Replace All] and [In Selection] buttons, as some programs do, and you click the one you want to do the replacement, this is also tidier in the dialog.

Cheers, David

**Comment by sdottaka** [comment]
In commit ba108a9, I modified the behavior so that if a single line or less is selected, "Whole file" will be chosen in the Replace dialog. If multiple lines are selected, "Selection" will be chosen instead. Thank you for your report.

**Comment by meteorquake** [comment]
Super! Look forward to it. Thanks for the speediness!
