### ISSUE TITLE
Image Comparison : In Alpha Animation, dialogs hang winmerge

### ISSUE THREAD

**Issue by meteorquake** [WinMerge/winmerge#2370]
In an image comparison if you have Alpha Animation on and try to pull up Options (clicking the button), winmerge hangs. Also Help - About does, so probably a general problem with dialogs trying to pop up.
Let me know if problem replicating and I'll provide full settings used.
2.16.40.0 W10 X64
David

**Comment by sdottaka** [comment]
I couldn't reproduce the issue with versions 2.16.40 and 2.16.41 either.
Am I comparing very large images or something?

![image](https://github.com/WinMerge/winmerge/assets/98126/743e7f3a-2e71-41c3-b6cf-04c2699eb10b)

**Comment by meteorquake** [comment]
One image is 7.85 Mb JPG, 4896 x 3672, and the other is a 50% JPG version of it that I was comparing for blemishes.
So that would make it large - there wasn't a problem with alpha animation off, just when it was on, and waiting didn't appear to help - the animations themselves were fast enough anyway

**Comment by sdottaka** [comment]
Can you reproduce this with other image files?

**Comment by meteorquake** [comment]
I'll try a very small file and report back.

**Comment by meteorquake** [comment]
Just had a look - I can confirm it wasn't a problem with a small crop from the image, so it is likely related to file size

**Comment by sdottaka** [comment]
Thanks for checking, I think I've managed to reproduce the issue, I'll take a look at it later.

**Comment by sdottaka** [comment]
This issue has been fixed in [commit b29ca0875a29ff3c3114b088d5cf98f3cf7e3777](https://github.com/WinMerge/winimerge/commit/b29ca0875a29ff3c3114b088d5cf98f3cf7e3777). Thank you for your report.
