### ISSUE TITLE
Folder comparison status not accurately reflected in toolbar

### ISSUE THREAD

**Issue by TBugReporter** [WinMerge/winmerge#2374]
Version:
Windows 2.16.40.0

Steps to reproduce:
- duplicate a folder on your PC containing several files to create a test scenario.
- delete two files from one of the folders, and use WinMerge to compare them.
- click the green down arrow button to move to the first difference.
- click the blue left or right arrow to copy the missing file.
- click the green down arrow button again.

Expected result:
- Both green arrows get grayed out, since the focus is now on the _only_ difference, and there is no next or previous difference to move to.

Actual result:
- "Previous difference" lights up.

**Comment by sdottaka** [comment]
This issue has been fixed in commit [acd563f](https://github.com/WinMerge/winmerge/commit/acd563fedce9999415c174fd53ab8309861cccd3). Thank you for your report.
