### ISSUE TITLE
Windows 11 changes date when copying what makes comparing with "Modified Date and Size" obsolet

### ISSUE THREAD

**Issue by Megateaser** [WinMerge/winmerge#2375]
After a Compare "Modified Date and Size" and subsequent copying of the different files to the target drive, the modification date is now changed under Windows 11. This means that all updated files are declared as different during the next "Modified Date and Size" compare. This does not happen under Windows 10 - until recently also not under Windows 11. What can I do to ensure that the modification date is retained when copying?

Thx for helpful comments
Megateaser

**Comment by sdottaka** [comment]
Are you using WinMerge to copy files? Or are you using Explorer to copy files?
Either way, I could not replicate this issue on Windows 11.
Is the destination drive a special file system?

**Comment by Megateaser** [comment]
> Are you using WinMerge to copy files? Or are you using Explorer to copy files? Either way, I could not replicate this issue on Windows 11. Is the destination drive a special file system?

Sorry for my late answer. Yes, I am using WinMerge to copy files. The problem startet recently (on the same hardware it was running before). I use to compare from my NAS (QNAP) to an USB-Stick (NTFS) and copy those files, that have a different "Date and Size". I noticed that copying files to the desktop on Windows 11 does change the date/time as well. Therefore I thought it has to do with Windows 11 (and because on a Windows 10 System using same NAS and USB-Stick it still works fine...

**Comment by sdottaka** [comment]
Is this related to the following FAQ?

https://www.qnap.com/en/how-to/faq/article/why-do-the-timestamps-of-my-shared-files-sometimes-change-after-accessing-them-with-the-apple-filing-protocol-afp

WinMerge uses Win32API IFileOperation(https://learn.microsoft.com/ja-jp/windows/win32/api/shobjidl_core/nn-shobjidl_core-ifileoperation) to copy files.

This is probably what Explorer uses too.

Does the file modification date and time change when you copy a file with Explorer?

If it does change, it may be difficult to take measures on the WinMerge side.

**Comment by Megateaser** [comment]
Thanks for your reply. I checked the actual settings on my QNAP, sending attached pics. 
![20240726 091050](https://github.com/user-attachments/assets/bd0c4e68-256f-4056-a420-9491751550f4)
![20240726 091108](https://github.com/user-attachments/assets/6c557f3e-641e-4cd8-9676-badb4748e4ea)
![20240726 092029](https://github.com/user-attachments/assets/89c162d4-ba4b-4b0c-b17b-5bf982bc1d40)
![20240726 092045](https://github.com/user-attachments/assets/5e7a8581-0b9d-40a5-b930-bbde2883da11)
![20240726 092058](https://github.com/user-attachments/assets/51c38038-f498-4d19-b018-b891e72db43b)

But there were no settings changed on the QNAP since >24 month and this "modificatio date" problem appeared first recently and only on Win11.

Should I change SMB-settings? I only use Windows PCs. Since I need running Win98 on Virtual Machines and I need access to the NAS, SMB1 is activated. Do you suggest turning off SMB1/changing/trying somethink in this settings?

You asked "Does the file modification date and time change when you copy a file with Explorer?" Yes, it does, if I copy eg. a file from the NAS to my desktop. But only on Win11, not on Win10 - Systems. On the Win10 "modification date" remains.

**Comment by sdottaka** [comment]
Unfortunately, I don't have a QNAP NAS so I don't know.
If the last modified date of a file changes even in Explorer, it seems difficult to take any measures within WinMerge.

**Comment by fkbreitl** [comment]
This seems related:
https://answers.microsoft.com/en-us/windows/forum/all/file-explorer-and-date-createdmodified-change-when/e6ad833e-a134-4da8-a9e0-815c92eeecfa

**Comment by Megateaser** [comment]
Thanks a lot Frank! Problem is solved by adding the NAS to the Local Internet Zone as described in the 2nd link you sent:
_"To open IE Options, run "inetcpl.cpl".
Click on the "Security" tab, and click "Local Intranet".
Click "Sites", and click "Advanced".
Add the computer name or the IP address of the computer that hosts the network share to the list.
Click OK, OK, to save your settings."_
