### ISSUE TITLE
creat report by command line

### ISSUE THREAD

**Issue by yuc-sudo** [WinMerge/winmerge#2380]
I want to creat the comparison result html file through the command line. Is there such a command line can creat html reports.

**Comment by sdottaka** [comment]
Although still undocumented, you can specify a destination report file with the /or command line option. See the discussion below for an example of usage.

https://github.com/WinMerge/winmerge/discussions/1760
https://github.com/WinMerge/winmerge/discussions/2117

**Comment by yuc-sudo** [comment]
Thank you very much for your reply
