### ISSUE TITLE
Status of folder comparison not correctly reflected by tab icon after Refresh (F5)

### ISSUE THREAD

**Issue by Hans-Guenter** [WinMerge/winmerge#2383]
If a comparison is repeated or resumed (after a Stopp) via pressing F5 for Refresh this status change is not correctly reflected via the Tab icon.
It shows the icon for a changed folder (![grafik](https://github.com/user-attachments/assets/457faf61-7058-48a2-8f41-33c6a1492e9c)) although the icon for an unfinished folder comparison ![grafik](https://github.com/user-attachments/assets/f49d76a6-2806-4216-99d0-3df3d50a8fb4) would be more appropriate.

**Comment by sdottaka** [comment]
This issue has been fixed in commit [683d5fb](https://github.com/WinMerge/winmerge/commit/683d5fbc427537f9ba0e9d0a9525241cebc7fd9d)
Thank you for your report.
