### ISSUE TITLE
Download Hashtags do not match what is listed...

### ISSUE THREAD

**Issue by NoAIHidingHere** [WinMerge/winmerge#2389]
Per the site it should be -
WinMerge-2.16.40-Setup.exe
d90ee78b59f07651372ec976f0a4da2e860129f04440380df7828c19eb5e1030

I'm getting -
SHA256          C76BCFDD5025059F398E94F97D801A4A6CF52BEF5B86F88209DCDFFB28A141CD 

I won't use it if there's a risk of a hack.

Perhaps it's time to stop hosting on Sourceforge

**Comment by sdottaka** [comment]
The SHA256 value C76BCFDD5025059F398E94F97D801A4A6CF52BEF5B86F88209DCDFFB28A141CD is for WinMerge-2.16.40-x64-Setup.exe, which is a different file. I tried downloading WinMerge-2.16.40-Setup.exe from sourceforge.net, and the SHA-256 value was d90ee78b59f07651372ec976f0a4da2e860129f04440380df7828c19eb5e1030.

If you are worried about downloading from sourceforge.net, you can download it from the following GitHub URL.

https://github.com/WinMerge/winmerge/releases/tag/v2.16.40

**Comment by NoAIHidingHere** [comment]
Dang, this group rocks!  Fast response and great input.  It does match. I was clearly mistaken.  I grabbed from top of download list and then looked at first hashtag in the list.  That was my error.  The version I grabbed is listed 2nd or 3rd in the hashtag list...

Thank you SDOTTKA!
