### ISSUE TITLE
WinMerge does not have Diginal Signature

### ISSUE THREAD

**Issue by DanielDao99** [WinMerge/winmerge#2395]
Hi team,
I have just downloaded the latest installer of WinMerge (version 2.16.42 - Windows)
I found out that the installer does not have the "Digital Signature" tab, which means that this installer is not signed by Windows, while old WinMerge installers still have the "Digital Signature" tab.
Could you please help check this issue?

Thanks and Best regards
--
Some notes:

Image:
![image](https://github.com/user-attachments/assets/c111d6ef-4273-4513-9ecf-3f716c9a186f)
![image](https://github.com/user-attachments/assets/298b4d68-586b-40fd-9753-b66368ee67e5)

Installer download link: https://github.com/WinMerge/winmerge/releases/tag/v2.16.42

**Comment by sdottaka** [comment]
Ah, in 2.16.42, the PC I used to build WinMerge was different from the usual one, so I forgot to add a digital signature.
(The WinMerge build system digitally signs only if the SIGNBAT_PATH environment variable is set, but it seems I didn't set SIGNBAT_PATH.)

**Comment by sdottaka** [comment]
I've released version 2.16.42.1

**Comment by sdottaka** [comment]
Thank you for your report.

**Comment by DanielDao99** [comment]
Thanks for your support!
