### ISSUE TITLE
Esc key closes WinMerge even when "Close windows with 'Esc'" is Disabled

### ISSUE THREAD

**Issue by shirayuki** [WinMerge/winmerge#2398]
When the "Close windows with 'Esc'" option is set to Disabled, pressing the Esc key still causes WinMerge to close. This issue seems to occur specifically when WinMerge is launched as a Git diff or merge tool.

**Steps to Reproduce**:
1. Open WinMerge.
2. Go to Settings and set "Close windows with 'Esc'" to Disabled.
3. Launch WinMerge as a Git diff or merge tool.
4. Press the Esc key.

**Expected Result**:
WinMerge should not close when the Esc key is pressed, given that the "Close windows with 'Esc'" option is Disabled.

**Actual Result**:
WinMerge closes when the Esc key is pressed, despite the "Close windows with 'Esc'" option being Disabled.

**Additional Information**:
This issue does not occur when WinMerge is used for non-Git related purposes. It specifically happens in the context of Git diff or merge operations.

**Comment by sdottaka** [comment]
If you start WinMerge with the command line option /e, it will ignore the `Close windows with 'Esc' option and will close WinMerge when you press the Esc key.

You can check the command line arguments used when starting WinMerge from git by looking at the Command Line: line displayed in the Help → Configuration menu item in WinMerge, as shown below.

![image](https://github.com/user-attachments/assets/444c84ac-077c-426b-bd1f-dc24a719a49c)
![image](https://github.com/user-attachments/assets/37276187-f493-4737-825a-633ced85275d)

**Comment by sdottaka** [comment]
I'll close this issue for now.
If WinMerge closes when you press Esc even though you didn't specify /e or -e in the command line arguments, or if you believe the /e or -e command line options should be ignored, please reopen this issue.
