### ISSUE TITLE
Want to contribute

### ISSUE THREAD

**Issue by mesajflaviu** [WinMerge/winmerge#241]
I have few ideas for this excellent tool and I want to implement it. I know MFC, but I don't know git (just a little). Can you guide me how to made a branch with my ideas ? I want to share it and made this tool even better :)

**Comment by sdottaka** [comment]
Awesome!

Please refer to how to make a pull request below.
https://opensource.com/article/19/7/create-pull-request-github

You may also attach a zip file of the modified source code.

**Comment by H-G-Hristov** [comment]
@mesajflaviu You could use SmartGit (which I recommend), which makes using Git much easier. SourceTree is also free but I haven't used it in a long time. GitHub have their own application too I think.

**Comment by mesajflaviu** [comment]
If you have more tasks to do and I can do it, I can handle it, just write me what. In my time limit of course.
