### ISSUE TITLE
Very high CPU usage by `Antimalware Service Executable` when runing WinMerge scan?

### ISSUE THREAD

**Issue by Ezbaze** [WinMerge/winmerge#2418]
When runing the scan the cpu usage of Antimalware Service Executable spikes by a considerable ammount slowing down the scan items/sec from 3000/sec on average down to 1000/sec on average.

![image](https://github.com/user-attachments/assets/a6ed016d-5771-4836-aa60-bfe3f2a3cc38)

What I tried to stop it from happening:
- Added the `C:\Program Files\WinMerge` to the `Controlled Folder Access` exclusion list
- Added the `C:\Program Files\WinMerge` to the `Virus & Threat Protection` scan exclusion list

I'm not sure what else I could try appart from disabling `Real-time protection` which what brings the items/sec up to 3000

System Info:
os: Windows 11

**Comment by sdottaka** [comment]
I don't know much about the Antimalware Service Executable, but would it have any effect if you added the folders you are trying to compare with WinMerge to the exclusion list?

**Comment by Ezbaze** [comment]
I forgot to mention that this the `Antimalware Service Executable` is part of the `Microsoft Defender Antivirus`, I don't think adding the folders being compared would do anything, as both exclusions are for the program itself that's runing.

From what I could find online, there could be a process that's being used by WinMerge that isn't located in the instalation directory meaning it isn't excluded and is triggering the high CPU usage?

**Comment by sdottaka** [comment]
I don't think there's anything that can be done about this on the WinMerge side.
It's probably not possible to automatically register the folders that WinMerge compares with Microsoft Defender Antivirus, and if it were possible to do so, it might be said that there is a vulnerability.

**Comment by Ezbaze** [comment]
Yes I agree, thanks for your help <3

Looks lke the Microsoft defender exclusion list will be a very close freind of mine from now on :)

**Comment by 0hip** [comment]
> I don't think there's anything that can be done about this on the WinMerge side. It's probably not possible to automatically register the folders that WinMerge compares with Microsoft Defender Antivirus, and if it were possible to do so, it might be said that there is a vulnerability.

Windows 10 Home X64
Winmerge 2.16.46.0
    After removing ". . . \WinMerge\Languages" folder, Microsoft Defender Antivirus stopped  eating resources.
