### ISSUE TITLE
Text replacement result is wrong.

### ISSUE THREAD

**Issue by www1800** [WinMerge/winmerge#2422]
Version: 2.16.42.1 x64

Given text:
"1A1"
"2A2"

Ctrl+H
FInd what:  `("([\s\w]*)A([\s\w]*)")`
Replace with:    `\1, "\2B\3"`
Click "Match case", "Regular expression", "Whole file"
![1](https://github.com/user-attachments/assets/a47d5d78-fb4d-4bfb-8dad-d668575c53e8)

Click "Replace All", result is correct.
![2](https://github.com/user-attachments/assets/18e83510-4cf7-462b-803c-35669448cc83)

Click "Ok" but do NOT close the "Replace" window, just change
Find what:  `C`
Replace with:  `C`

Click "Replace All", result is wrong (nothing should be changed but it gets changed)
![3](https://github.com/user-attachments/assets/06002245-2f89-40c4-9aea-69f693d7e17a)

Thanks.

**Comment by sdottaka** [comment]
Thank you for reporting this issue. It has been resolved in https://github.com/WinMerge/winmerge/commit/7ce38093d9e92adb2cb970472486b4f3f7680bfa
