### ISSUE TITLE
2 mistakes about default values in manual

### ISSUE THREAD

**Issue by thericle** [WinMerge/winmerge#2456]
On https://manual.winmerge.org/en/Configuration.html#Configuration_general under "2.10.  Open-dialog Auto-Completion", the actual default option is "From file system" and not "Disabled", and under "2.11.  Auto-reload modified files", the actual default option is "Only on window activated", instead of "Disabled".

**Comment by sdottaka** [comment]
Thank you for pointing this out. It’s fixed in [this commit](https://github.com/WinMerge/winmerge/commit/17c23c6ab605a518c1f683430c43788574d031e4) and will be in the next release.
