### ISSUE TITLE
Right click - compare - is unclear

### ISSUE THREAD

**Issue by H-G-Hristov** [WinMerge/winmerge#249]
I find the shell extension confusing: Compare, Re-Select Compare, Compare To doesn't seem to work as I would expect. Can we just have:

- Compare Left (or Select Left) - which selects the file to be displayed on the left side
- Compare To - which selects the file to be displayed on the right side

Then we can just have "Compare To" to finish the action and open WinMerge compare tool (if already one file was selected).
For the three way comparison tool we can also have:

- Compare Middle

I think this way will be more intuitive.

**Comment by MailYouLater** [comment]
What you're asking for sounds like the "Compare Non-horizontally" feature, which just got a major update in the fix for #172 which should be in the next stable release.  If you want to try the new interface for it you can download the current Beta version, though as a beta it may have other issues.

**Comment by H-G-Hristov** [comment]
I tried the current release and I still find the extension clunky. 
Compare just opens Winmerge
Compare To doesn't do anything
Then Re-select First appears

**Comment by MailYouLater** [comment]
Oh! I just realized that perhaps you're referring to the shell integration.  I was wondering what you meant by "Compare To" as I've never seen that, but if it's part of the shell integration, that would explain it as I use the PortableApps.com releases and when I tested the Beta build I replaced the App\WinMerge and App\WinMerge64 folders with the contents of their respective zips so I could run the PortableApps.com Launcher to keep it portable while examining the new version.

The "Compare Non-horizontally" feature I referred to is used when comparing folders in WinMerge and it's activated by select two or three files (by Ctrl+click) then right clicking one of them and choosing "Compare Non-horizontally".  In the current stable release "Compare Non-horizontally" is a submenu which looks like this:
![image](https://user-images.githubusercontent.com/1279475/75382113-bc8a4500-588e-11ea-96e9-d03b52c71c46.png) 
In the current beta release "Compare Non-horizontally" brings up a window that looks like this:
![image](https://user-images.githubusercontent.com/1279475/75383338-04aa6700-5891-11ea-8951-aa651456b402.png)
You'll notice that I'm comparing three folders, all containing a "temporary.file" file, and I've selected it and "temporary.file.bak" which is only present in the 'right' folder.  I can now click on up to three of these in any order I please to compare them in WinMerge.

Regarding the shell integration, I don't know how it works or how it should work.  Sorry for the confusion.

**Comment by sdottaka** [comment]
It's a little different from your request, but I changed the context menu as follows.

Compare To → Select Left
                             or
                             Select Middle
Compare ... → Compare ...
Compare → Compare
Re-select First → Re-select Left

**Comment by MailYouLater** [comment]
> Select Middle
> ...
> Re-select First → Re-select Left

No "Re-select Middle"?

Also, now that I have WinMerge installed and can see WinMerge's context menu items as supplied by the shell extension, as much as I appreciate the presence of the WinMerge icon next to these options, it bothers me that the text doesn't tell the user that they are appearing because of WinMerge, which could be confusing for new users who may be unfamiliar with the icon, as well as blind/visually impaired users using a screen reader to improve accessibility.

In deference to WinMerge users who are less familiar with the icon and/or unable to see it, I'd like to suggest that "WinMerge: " be added to the beginning of each of these options.  e.g. "Select Left" -> "WinMerge: Select Left"
