### ISSUE TITLE
Bug Report: Display Issues When Resizing WinMerge Across Dual Monitors

### ISSUE THREAD

**Issue by shirayuki** [WinMerge/winmerge#2514]
When using WinMerge in a dual monitor setup where the secondary display is positioned to the right of the primary display, resizing the WinMerge window by dragging its right edge onto the secondary display causes the content on the secondary display side to become artifacted. The remnants of the previous size remain visible, and the window does not refresh correctly. However, adjusting the height of the window by dragging the top or bottom edge resolves the issue.

**Steps to Reproduce:**

1. Set up a dual monitor display with the primary display on the left and the secondary display on the right.
2. Open WinMerge on the primary display.
3. Drag the right edge of the WinMerge window to extend it onto the secondary display.

**What Happens:**

The content on the secondary display side of WinMerge becomes artifacted, leaving traces of the previous size visible, and the window does not refresh correctly.

**What Should Happen Instead:**

The WinMerge window should refresh properly, and there should be no remnants of the previous size visible after resizing.

**Comment by sdottaka** [comment]
Do you have the View → Lock Pane menu item enabled?
I was able to reproduce this issue in that case.

**Comment by shirayuki** [comment]
> Do you have the View → Lock Pane menu item enabled? I was able to reproduce this issue in that case.

Thank you for your response.

The following old bug report describes a similar phenomenon and also mentions "Lock Panes."
I plan to check the status of that menu item on my PC with dual monitors in the near future.

＃2062 Lock Panes/Dual Monitors: right pane resize problem
https://sourceforge.net/p/winmerge/bugs/2062/

**Comment by shirayuki** [comment]
> Do you have the View → Lock Pane menu item enabled? I was able to reproduce this issue in that case.

Indeed, I confirmed that "Lock Panes" is related to the issue; unchecking it prevents the problem from occurring.

**Comment by sdottaka** [comment]
Thank you for your confirmation. This issue has been resolved in commit 5574efa and will be closed.
