### ISSUE TITLE
Diff renders incorrectly with "Cascadia Mono" variant

### ISSUE THREAD

**Issue by milnak** [WinMerge/winmerge#2525]
Windows 11, WinMerge 2.16.44.0

View >Select Font
Choose "Cascadia Mono", "SemiLight", 10

View doesn't render properly.

Works fine with "Cascadia Mono", "Regular", 10

![image](https://github.com/user-attachments/assets/2d328bd0-d707-4c99-9758-efbed398c1db)

**Comment by sdottaka** [comment]
I tried the following but was not able to reproduce this issue.
Could you please attach a screenshot of the Font dialog?
![image](https://github.com/user-attachments/assets/201fa91b-56a8-49e9-8683-8fff53ba206f)

**Comment by milnak** [comment]
![image](https://github.com/user-attachments/assets/9a6973a3-80b3-47d7-8b0d-8d7aae76ef6c)

**Comment by sdottaka** [comment]
Thank you for attaching the image.
I found the conditions to reproduce this problem.
You can avoid this problem by changing the Rendering Mode in the Editor/General category of the Options window to GDI.
![image](https://github.com/user-attachments/assets/409d40ff-4d23-40b5-bd28-bf4c0ed3d108)

**Comment by milnak** [comment]
that seemed to have fixed it. thanks!

**Comment by sdottaka** [comment]
This issue has been fixed in commit [9ef4cb2](https://github.com/WinMerge/winmerge/commit/9ef4cb2e8b5a0951f4a2dd7a5b8e1a25b00c9625)
Thank you for your report.
