### ISSUE TITLE
Feature Request: Fixed-Width Font in "Find what" and "Replace with" Fields

### ISSUE THREAD

**Issue by shirayuki** [WinMerge/winmerge#2539]
I would like to request an enhancement for the **"Find"** and **"Replace"** dialogs in WinMerge.

**Request:**
Please consider using a fixed-width (monospaced) font for the **"Find what"** and **"Replace with"** fields, or add an option to change the font.

**Reason:**
I often need to replace tab characters with four spaces (or vice versa). However, it's difficult to see exactly how many spaces have been entered in these fields with a proportional font. A fixed-width font would make it much easier to visually distinguish the number of spaces entered, improving accuracy and usability.

**Comment by sdottaka** [comment]
In commit [8d5b2dc](https://github.com/WinMerge/winmerge/commit/8d5b2dcde227b3fd6f045c66df5aa130c7062158) we changed it to use the fixed-width font currently used in the editor.
