### ISSUE TITLE
Feature request: `Open Both With...` option in context menu

### ISSUE THREAD

**Issue by Petewg** [WinMerge/winmerge#2546]
In context  menu we have
 `Open Left -> With` (submenu)
 `Open Right -> With` (submenu)
options used to open files with different application than integrated viewer/editor.
And there are files that can be opened/viewed/investigated, only by their registered application,
(f.e.: .PDFs, where the integrated viewer/editor is practically useless). 
In such a case we have to..
`Open left -> With Registered Application` 
then 
`Open Right -> With Registered Application`

If we add the fact that every time we open a file we lose focus of WinMerge window
and have to regain it, for opening the other-side-file, the entire attempt
becomes unnecessarily time consuming (and in some degree annoying). 
IMHO, the situation could be improved by adding an `Open Both -> With ...` option.

regards,
Pete

**Comment by sdottaka** [comment]
Does the existing "Both Shell menu" menu item not meet your needs as an alternative?
![image](https://github.com/user-attachments/assets/ff69b0ca-6581-4e86-a382-3f3161788983)

**Comment by Petewg** [comment]
>Does the existing "Both Shell menu" menu item not meet your needs as an alternative?

Yes, of course! (I can't believe that I've not spotted that option myself, looks like my eyes were "refusing" to go further down in menu than `Open Left/Right` options.) Thanks for the hint and sorry for the unnecessary post.
