### ISSUE TITLE
Feature Request - Table CSV/Excel/Libreoffice Compare

### ISSUE THREAD

**Issue by asjones987** [WinMerge/winmerge#256]
Would love to see table/Row/Cell comparisons as an option for WinMerge. I have seen some other compare programs offer something like this. Offer a CSV/Excel/Libreoffice compare option. With the ability to select the specific sheet for Excel/Libreoffice.  There are numerous OSS tools for reading Excel files that might help. Unlike other tools Winmerge would only need to read the visible contents of a cell (formula  result not the formula) and NOT the formatting.

It would be a nice feature to consider for the future.

Keep up the good work.

**Comment by Gitoffthelawn** [comment]
FYI, I think (but I'm not sure), that LibreOffice and perhaps some other spreadsheet tools have an option (possibly hidden) to update all cells before saving.  If you don't enable that, your comparisons may be off.  Just an FYI if this gets implemented.

**Comment by asjones987** [comment]
@Gitoffthelawn , most cases Librreoffice/Excel update cells automatically unless one turns that off. That is something on the USER otherwise.

**Comment by sdottaka** [comment]
It may be a bit different from your Feature Request, but we've added Table Compare in 2.16.7 beta version. 

This is a function to display CSV/TSV files in tabular format. There is no ability to directly compare Excel/LibreOffice files, so you'll have to use an existing plugin.

![tblcmp](https://user-images.githubusercontent.com/98126/88985243-acc5cf80-d30a-11ea-9015-2989218ffee5.png)
