### ISSUE TITLE
Looks like v2.16.44.0 is no longer supporting the Open menu Drag/Drop of Folders or Files while Run As Admin.

### ISSUE THREAD

**Issue by WilliamFulk** [WinMerge/winmerge#2565]
Looks like v2.16.44.0 is no longer supporting the Open menu Drag/Drop of Folders or Files while Run As Admin. Windows Screenshot would not let me take a pic of the circle with the slash through it.  Works fine when Run as Non-Admin. The current files security status that I am comparing requires me to use Run As Admin.

![Screenshot 2024-12-01 121210](https://github.com/user-attachments/assets/5acb0fb4-1973-4f74-9ad5-cd796d853a0b)

Great Tool!

PS: Filter question:  How can I change sample "f: ^desktop.ini$" to only block at the Root level while selecting "include subfolders" compare?

**Comment by sdottaka** [comment]
This behavior is not specific to WinMerge versions but is restricted by Windows itself.

When WinMerge is launched with administrator privileges, it can only accept drag-and-drop actions from applications that are also running with administrator privileges.

For example, if you launch Notepad with administrator privileges, open its Open dialog with Ctrl+O, and drag files from there to WinMerge (also running with administrator privileges), the drag-and-drop operation will work.

![image](https://github.com/user-attachments/assets/6f217fb4-b577-4063-b786-289878d73b51)
![image](https://github.com/user-attachments/assets/a9a225cd-25fa-425e-800b-17322b4bdf7d)


> PS: Filter question: How can I change sample "f: ^desktop.ini$" to only block at the Root level while selecting "include subfolders" compare?

Unfortunately, that's not currently possible.

**Comment by WilliamFulk** [comment]
Takashi Sawanaka,Appreciate your nice clarification on both of the items.Thanks,Wm Dale FulkSent from my iPhoneOn Dec 1, 2024, at 6:35 PM, Takashi Sawanaka ***@***.***> wrote:﻿
This behavior is not specific to WinMerge versions but is restricted by Windows itself.
When WinMerge is launched with administrator privileges, it can only accept drag-and-drop actions from applications that are also running with administrator privileges.
For example, if you launch Notepad with administrator privileges, open its Open dialog with Ctrl+O, and drag files from there to WinMerge (also running with administrator privileges), the drag-and-drop operation will work.
image.png (view on web)
image.png (view on web)

PS: Filter question: How can I change sample "f: ^desktop.ini$" to only block at the Root level while selecting "include subfolders" compare?

Unfortunately, that's not currently possible.
