### ISSUE TITLE
WinMerge 2.16.44.0 : CompareMSWordFiles.sct Plugin : Forced Enabled Confirm Conversions Pop-Up

### ISSUE THREAD

**Issue by GeorgeLelik** [WinMerge/winmerge#2566]
I am using WinMerge to compare .rtf files using CompareMSWordFiles plugin. (One can just change .docx extension to .rtf to test the issue.) With an older version (2.16.36.0) it worked just fine. With newer version 2.16.44.0, for every compared .rtf file there pops a Convert File dialog window requiring to confirm the 'Convert file from:' Rich Text Format (RTF). This makes it very inconvenient to compare .rtf files. This is a Word setting that can be found in Word Options > Advanced > General > Confirm  file format conversion on open, which is normally disabled, but is enabled when using the plugin. 

I am not a programmer, but I believe the issue is in WinMerge\MergePlugins\CompareMSWordFiles.sct where it has the following line in two (2) places

var doc = wd.Documents.Open(fileSrc2, -1, -1)

The second parameter is for 'ConfirmConversions' with -1 defaulting to 1/True. I believe it should be as below thus using the current setting, rather than turning it on or off, though I am not able to verify it on the system I use WinMerge on:

var doc = wd.Documents.Open(fileSrc2, , -1)

**Comment by sdottaka** [comment]
This issue has been fixed in commit [eafcde](https://github.com/WinMerge/winmerge/commit/4eafcdedf7a160b4e882ff25ceca77b00d7b56bc).
Thank you for your report.

**Comment by GeorgeLelik** [comment]
Thank you. I see it was changed to var doc = wd.Documents.Open(fileSrc2, 0, -1); It may be more desirable to change it to var doc = wd.Documents.Open(fileSrc2, , -1); so that it uses the current system setting rather than turning on or off that Word setting. The concern is that '0' will disable the confirm conversion Word setting. Some may be using it. It will persist past the WinMerge session, similar to how '1' enabled the setting and it stayed enabled after WinMerge use.

**Comment by sdottaka** [comment]
CompareMSWordFiles.sct is written in JScript, which does not allow arguments to be omitted.
Also, if a dialog box is displayed during comparison, it often appears behind WinMerge, which can lead to the mistaken impression that WinMerge has hung up, so I set it to 0.

**Comment by GeorgeLelik** [comment]
Thank you for the explanation. No concern then.
