### ISSUE TITLE
Unable to exclude desktop.ini

### ISSUE THREAD

**Issue by chemelli74** [WinMerge/winmerge#2579]
I tried several syntax, but all fails.

Here the extract of my filter:

```
## Filter for filename
f: \thumbs.db$ 
f: \desktop.ini$
```

The first is excluded correctly, the second is not.

**Comment by sdottaka** [comment]
The current file filter only extracts the file name from the file path to be compared when filtering files, so \ is not necessary. If you do not want it to match adesktop.ini, etc., please add ^ as follows.
~~~
## Filter for filename
f: ^thumbs.db$ 
f: ^desktop.ini$
~~~

**Comment by chemelli74** [comment]
Thx a lot, didn't find the right syntax in the manual.
