### ISSUE TITLE
WinMerge 2.16.4.0 crashes after de-selecting Split Vertically

### ISSUE THREAD

**Issue by CodingKidd** [WinMerge/winmerge#259]
Today I opted to change the view to stacked rather "Split Vertically" when comparing two files and within a couple seconds of de-selecting "Split Vertically" WinMerge simply quit. I re-launched WinMerge then dropped the two folders I was comparing onto the main WinMerge window; no issues. When I selected a file to view both versions appeared for just a few seconds then WinMerge quit. I went through this process a couple more times with the intent of reselecting "Split Vertically" but the menu would not be displayed before it quit. I then re-launched WinMerge but this time I selected "New Documents" from the menu bar but again, after a few seconds WinMerge quit. 
I decided to uninstall/reinstall WinMerge which worked as long as I did not de-select "Split Vertically". I ended up having to reinstall again in order to continue my work today.

WinMerge: 2.16.4.0
Windows 10 Pro: 1903

**Comment by sdottaka** [comment]
Thank you for the report.
I think this bug was fixed by commit https://github.com/WinMerge/winmerge/commit/b74625386f37a9fe8ec59f034ab1f08e607d47d4

The latest installer(not stable version) is here:
https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts
