### ISSUE TITLE
Third tgz doesn't get fully extracted (first two do)

### ISSUE THREAD

**Issue by MailYouLater** [WinMerge/winmerge#263]
If I do a comparison of three `.tar.gz` or `.tgz` files, the two in the 'left' and 'middle' positions get double extracted so the files/folders they contain appear in the WinMerge interface, but the one in the 'right' position is only extracted once, so WinMerge sees it as only containing a single `.tar` file.

![image](https://user-images.githubusercontent.com/1279475/74067224-966b3680-49ad-11ea-91d7-f5c19dd8771a.png)

If I use 7-Zip to extract the `.tar` from each of these `.tgz` files, I can compare them more appropriately, but it would be nice if the third item would be treated the same way that the first two are.
![image](https://user-images.githubusercontent.com/1279475/74067384-ff52ae80-49ad-11ea-99a7-26fc09c692df.png)

**Comment by sdottaka** [comment]
Fixed by commit 9f99285 

Thank you for the report.

The latest installer is available at:
https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts

**Comment by MailYouLater** [comment]
Fixed! Thanks.
