### ISSUE TITLE
how to show white space with linebreak hidden?

### ISSUE THREAD

**Issue by renpujun** [WinMerge/winmerge#265]
Hi there!
     Is there any way to show the white space with linebreak mark hidden? In the current version of Winmerge, the whitespace and linebreak mark must be show or hidden together...Could you seprate the configs?

**Comment by sdottaka** [comment]
Sorry for the delay in answering.
Unfortunately, there is no such setting in WinMerge right now, but the editor component itself allows us to control the display of spaces and line breaks separately, which may be implemented in a future version.
PR is welcome.

**Comment by sdottaka** [comment]
Implemented by commit 923423c
