### ISSUE TITLE
[Feature Request] GoTo Moved Line

### ISSUE THREAD

**Issue by quangkieu** [WinMerge/winmerge#278]
I saw that we already have the map of where the current lines were moved to/from. Could we have a context option to jump to the moved from/to of current diff on the other panel.
As for big file comparation, the map on the location panel is very hard to pinpoint where the line moved from/to on the other panel.

**Comment by MailYouLater** [comment]
A keyboard shortcut for this option would also be extremely helpful.

**Comment by sdottaka** [comment]
Implemented by Pull Request #484
