### ISSUE TITLE
Create a patch file from directories

### ISSUE THREAD

**Issue by jonadem** [WinMerge/winmerge#283]
When the "Generate patch" is pressed (under "Tools") with a directories diff, WinMerge returns a dialog "Cannot create a patch file from directories". Could you implement this ?

**Comment by sdottaka** [comment]
I don't think it will be implemented unless someone makes a PullRequest.

Currently, WinMerge does not allow you to create a patch by specifying a folder. However, you can select multiple files to create a patch.

If there are subfolders in the folder, it may help to enable the 'Include Subfolders' option or disable tree mode.

**Comment by sdottaka** [comment]
implemented by PR #331
