### ISSUE TITLE
Src\Common\MyCom.h unused?

### ISSUE THREAD

**Issue by gerundt** [WinMerge/winmerge#284]
Is the file `Src\Common\MyCom.h` unused? Seems not included in some outer source file.

**Comment by sdottaka** [comment]
This file seems to have been used in the Visual Source Safe support code.
This support has been removed and can be removed.
I will delete it later.

**Comment by sdottaka** [comment]
MyCom.h was removed  by commit e2b4bcfb4d2b42173a1d3d09f577988c955ae0da
