### ISSUE TITLE
I mapped a solarized dark theme

### ISSUE THREAD

**Issue by keeleyt83** [WinMerge/winmerge#287]
Hey, **not** an issue but a heads up, in case you're interested. I created a custom solarized theme for WinMerge and dropped the ini file here:

https://github.com/keeleyt83/winmerge-solarized-dark

Keep up the good work!

**Comment by gerundt** [comment]
By trying the theme I found a bug in WinMerge too. When you are on a *color* option page and import the INI file, WinMerge don't change the colors on the page. First after closing/reopening the options shows WinMerge the new colors.

**Comment by gerundt** [comment]
@sdottaka Instead the "Defaults" buttons to reset the colors, would be a Dropdown list maybe an alternative?

In this case it would be easier to a selectable theme for the user. If we look for example to the *differences colors*: Instead a `GitHub/Bitbucket` and a `Defaults` button we could have a Dropdown list with these entries:

* Defaults
* GitHub/Bitbucket
* Solarized
* Custom

If a user change a color WinMerge should change the selected entry to *Custom*.

**Comment by sdottaka** [comment]
@gerundt I added ColorSchemes folder at f22eca00fd386c1c53fd3faa3e9a4ebfd634e67d.
I want to make the files in this folder selectable in a combo box.

**Comment by sdottaka** [comment]
@keeleyt83  I've added color schemes to WinMerge with a few modifications based on your solarized dark theme. 1d238d6b318f8e4ccc5341591900a8197407f0b1
