### ISSUE TITLE
Error on git repository cloning

### ISSUE THREAD

**Issue by qosobrin** [WinMerge/winmerge#288]
Hi, there:

trying to clone this repository to my local computer using GitHub desktop client but every time I try I get the following error: 

> A submodule points to commit which does not exist

I even forked the repository, but cloning from my personal fork provides the same error.

Thank you very much.
Best regards,
Luis A.

**Comment by sdottaka** [comment]
Thank you for the report.

It seems that the push of frhed of the submodule did not go well.
I think you can clone normally now.
