### ISSUE TITLE
Generating report after comparing local and network folders crashes

### ISSUE THREAD

**Issue by earthsound** [WinMerge/winmerge#295]
Running version 2.16.6 in Windows Server Standard 2012 64-bit

When I compare two folders (including subfolders), one local and the other a mapped shared folder, the comparison is fine. 

If I expand all folders & generate an HTML report, it crashes. (It also crashes if I don't expand all.) 

I know it isn't tremendously helpful, but here are the details from Windows (folders expanded):

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	WinMergeU.exe
  Application Version:	2.16.6.0
  Application Timestamp:	5e527bf0
  Fault Module Name:	WinMergeU.exe
  Fault Module Version:	2.16.6.0
  Fault Module Timestamp:	5e527bf0
  Exception Code:	c0000005
  Exception Offset:	001a9a00
  OS Version:	6.2.9200.2.0.0.272.7
  Locale ID:	1033
  Additional Information 1:	a3bc
  Additional Information 2:	a3bc2515beb7490765c2de70b50c31a0
  Additional Information 3:	800b
  Additional Information 4:	800b8a106ed288b83d021b9fc2eaa9c0

Different crash details are reported if I leave the folders not expanded (default settings):

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	WinMergeU.exe
  Application Version:	2.16.6.0
  Application Timestamp:	5e527bf0
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.2.9200.22997
  Fault Module Timestamp:	5e475c30
  Exception Code:	c0000005
  Exception Offset:	00080e3b
  OS Version:	6.2.9200.2.0.0.272.7
  Locale ID:	1033
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	6c8a
  Additional Information 4:	6c8a505eb56210a312a5fa1e47545073

Interestingly, the partial reports generated before it crashes stop at the same folder.

**Comment by sdottaka** [comment]
I haven't been able to get this bug to reproduce.

Please let me know if you know the conditions for the reproduction of this bug.

**Comment by sdottaka** [comment]
PR #1319 fixed a crash when creating an HTML report. This fix will be included in 2.16.21, which will be released on 2022-06-20.
So I close this issue.
If you still have problems with this version, please reopen this issue.
