### ISSUE TITLE
Allow specifying default for EOL warning checkbox

### ISSUE THREAD

**Issue by Gitoffthelawn** [WinMerge/winmerge#297]
I frequently compare files that have different EOL indicators.

I appreciate how WinMerge provides a notification each time to let me know the text content may be the same, but the files are not truly identical.  I don't want to turn the message off.  But the checkbox is always auto-checked to turn this message off.  Can you make the default to have the checkbox unchecked, or add a setting so the user can set the default for this checkbox?

Thanks!

**Comment by Gitoffthelawn** [comment]
Reviewing the code, it appears that the applicable call is here: https://github.com/WinMerge/winmerge/blob/9132c3069d65d3651e068a822bff68fb9f656723/Src/MergeDoc.cpp#L2703

`MB_DEFAULT_CHECKED` probably needs to be *not* applied to that ShowMessageBox call.  I'm not 100% certain of how to accomplish this for this specific message box, since that parameter is not explicitly passed.

Actually, thinking about this on a global sclae, how about we no longer have `MB_DEFAULT_CHECKED` be the default for all warnings?  It's best for UX to not hide things without explicit user direction.

**Comment by sdottaka** [comment]
> Can you make the default to have the checkbox unchecked
In commit 394722f766887017c0a299fcce7148c7febb8b3f I made that checkbox default to unchecked.

**Comment by Gitoffthelawn** [comment]
@sdottaka Thank you so much!  I really appreciate it. :)
