### ISSUE TITLE
DST causes incorrect dates shown in Date column

### ISSUE THREAD

**Issue by onnoverschuuren** [WinMerge/winmerge#299]
Daylight Saving Time (DST) causes wrong dates displayed in Date columns
There is a 1 Hour difference, please check.

**Comment by sdottaka** [comment]
I don't live in an area where DST is applied, so I'm not familiar with DST, but I couldn't reproduce this bug when I set Timezone to an area with DST.

Could you attach a screenshot of the WinMerge folder comparison and the Explorer properties of the file?

**Comment by onnoverschuuren** [comment]
See attached picture.

________________________________
Van: Takashi Sawanaka <notifications@github.com>
Verzonden: woensdag 1 april 2020 15:08
Aan: WinMerge/winmerge <winmerge@noreply.github.com>
CC: onnoverschuuren <info@onnoverschuuren.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [WinMerge/winmerge] DST causes incorrect dates shown in Date column (#299)


I don't live in an area where DST is applied, so I'm not familiar with DST, but I couldn't reproduce this bug when I set Timezone to an area with DST.

Could you attach a screenshot of the WinMerge folder comparison and the Explorer properties of the file?

**Comment by sdottaka** [comment]
Thank you for the reply. But the picture seems to be not attached on GitHub issues.

**Comment by onnoverschuuren** [comment]
![DSTproblem](https://user-images.githubusercontent.com/50720800/78291197-40d28680-7525-11ea-9fd2-5eb6318fb3fa.PNG)

**Comment by sdottaka** [comment]
Now I was able to reproduce the bug.
commit 0c72b2f fixes this issue.
Thank you for the report.
