### ISSUE TITLE
Loading Diff project won't enable "Compare" button

### ISSUE THREAD

**Issue by Baertram** [WinMerge/winmerge#301]
WinMerge Version 2.16.6.0

I have saved a diff project file with 3 files.
If I right click any file in my explorer, choose "WinMerge" and then load the saved diff project file the 3 filenames to compare + save new (3rd file) are correctly loaded into the edit fields.

But the compare button is not active!
I need to manually click into one of the 3 file edit fields buttons to expand the dropdown, select the already selected filename again. Or click on the "Search" button. 
After that the compare button updates / get's enabled.

Please activate the compare button automatically if a diff project was loaded and all 3 files in the project still exist.

Thank you

**Comment by sdottaka** [comment]
I was unable to reproduce that bug.

Could you check the <left>, <middle>, and <right> tags in the project file (.WinMerge) for any extra whitespace or non-existent paths?

**Comment by Baertram** [comment]
I'm using the German language.
The button is named "Vergleichen" and it keeps being disabled until I click into the filename dropdowns and open the dropdown or change the filename characters.

Here is the project file contents (does not contain whitespaces).
Maybe it's a problem because of admin rightsd as I access a file from the c:\users folder and did not start WinMerge with priviledged rights?
But as soon as I click into the file 1 edit box and then open the dropdown of this edit fieldd the button "Compare" get's enabled.

`
<?xml version="1.0" encoding="UTF-8"?>
<project>
	<paths>
		<left>C:\Users\xxx\Documents\Elder Scrolls Online\live\AddOns\pChat\Settings_old.lua</left>
		<middle>C:\Users\xxx\Documents\Elder Scrolls Online\live\AddOns\pChat\Settings.lua</middle>
		<right>C:\Users\xxx\Documents\Elder Scrolls Online\live\AddOns\pChat\Settings_new.lua</right>
		<filter>*.*</filter>
		<subfolders>1</subfolders>
		<left-readonly>1</left-readonly>
		<middle-readonly>1</middle-readonly>
		<right-readonly>0</right-readonly>
	</paths>
</project>
`

**Comment by Baertram** [comment]
> <?xml version="1.0" encoding="UTF-8"?>
> <project>
> 	<paths>
> 		<left>C:\Users\xxx\Documents\Elder Scrolls Online\live\AddOns\pChat\Settings_old.lua</left>
> 		<middle>C:\Users\xxx\Documents\Elder Scrolls Online\live\AddOns\pChat\Settings.lua</middle>
> 		<right>C:\Users\xxx\Documents\Elder Scrolls Online\live\AddOns\pChat\Settings_new.lua</right>
> 		<filter>*.*</filter>
> 		<subfolders>1</subfolders>
> 		<left-readonly>1</left-readonly>
> 		<middle-readonly>1</middle-readonly>
> 		<right-readonly>0</right-readonly>
> 	</paths>
> </project>

**Comment by Baertram** [comment]
After recreating the files I'm currently not able to reproduce the issue. Weird.
Maybe the filenames were somehow bugged.

Will try again and reopen the bug report, for now I'll close it.
