### ISSUE TITLE
Strings starting with space

### ISSUE THREAD

**Issue by qosobrin** [WinMerge/winmerge#309]
Maybe I'm wrong but there are three strings in https://github.com/WinMerge/winmerge/blob/master/Translations/WinMerge/English.pot that should be corrected because they start with a space. 

```
msgid " Folder: Filter"
msgid " File: Unpacker Plugin"
msgid " Categories"
```

If I am wrong and that was on purpose, please, discard this issue. If not, please, correct them.

Best regards.

**Comment by qosobrin** [comment]
There are also one string that ends with a space:

`msgid "[F] "`

May this one should be corrected too.

**Comment by sdottaka** [comment]
It's not a good thing, but I think these whitespace has been added to adjust the position, so let's leave it for now.

**Comment by qosobrin** [comment]
OK for me then. I close the issue.
