### ISSUE TITLE
Suggest new Compare Option "Ignore Numbers"

### ISSUE THREAD

**Issue by CarlTBarnes** [WinMerge/winmerge#310]
I would suggest on the Options dialog under Compare General you add a new Checkbox "Ignore Numbers".  

A more flexible alternative would be to add an "Ignore Characters" checkbox and next to that an Edit control to list up to 16 characters to ignore. With that I would check the box then type 0123456789 and probably period and comma. I would suggest 3 of these to allow multiple character sets.

My source contains window declarations that specify the Position AT(X, Y, Width, Height). When those windows are changed normally I do not care to see it highlighted that a control AT(X,Y,W,H) was changed (it's a cosmetic change), that is just distracting clutter so I would check the Ignore numbers box and refresh. This would then highlight signification changes.

Example:
```
Window WINDOW('Dim Config'),AT(1,1,91,110),MDI,SYSTEM,FONT('Segoe UI',9,,FONT:regular)
    PROMPT('Dim Alpha:'),AT(3,4),USE(?Pmt:DimAlpha)
    SPIN(@n3),AT(41,3,39),USE(DimAlpha),RANGE(0,255),STEP(5)
    PROMPT('Dim Color:'),AT(3,25),USE(?Pmt:DimColor)
    SPIN(@n-11),AT(4,35,61),USE(DimColor)
    BUTTON('...'),AT(69,35,14,13),USE(?PickColorBtn),TIP('ColorDialog()')
    BUTTON('Equate...'),AT(3,50,37,13),USE(?ColorEquatesBtn),TIP('Color Equates')
    BUTTON('System...'),AT(43,50,37,13),USE(?ColorSystemBtn),TIP('System Color Equates')
    BOX,AT(42,20,14,13),USE(?ColorBox),COLOR(COLOR:Black),FILL(COLOR:Black),LINEWIDTH(1)
    CHECK('Disable Dim (inactive)'),AT(3,69),USE(DimDisable)
    END

```

**Comment by sdottaka** [comment]
The 'Ignore Numbers' option was implemented by PR #1025.
