### ISSUE TITLE
Several issues regarding i18n

### ISSUE THREAD

**Issue by qosobrin** [WinMerge/winmerge#314]
Here I provide several issues related to strings and i18n that I have just came across.

- When closing a project with unsaved files an alert window comes up. The string "Discard changes" appears untranslated. There are two similar strings like this to be translated in   https://github.com/WinMerge/winmerge/blob/master/Translations/WinMerge/English.pot but this particular one is not included:
![discard](https://user-images.githubusercontent.com/6613431/79598203-d3595500-80e3-11ea-9644-4cc0d323a829.png)

- Frhed settings are not internationalized:
![frhed](https://user-images.githubusercontent.com/6613431/79599604-11f00f00-80e6-11ea-8a67-d7c3af63a213.png)

- Hex viewer pane information baseline is not internationalized:
![binary](https://user-images.githubusercontent.com/6613431/79599586-07357a00-80e6-11ea-8347-7f8497555ed5.png)

- The Location Pane for image comparison is not internationalized:
![location_pane](https://user-images.githubusercontent.com/6613431/79600176-03562780-80e7-11ea-9b89-21b24764fc24.png)

- The pane information baseline, when comparing images, is not internationalized:
![image](https://user-images.githubusercontent.com/6613431/79600544-998a4d80-80e7-11ea-8f76-fa0036fcbaf2.png)

- Options > Colors > Syntax: The main part of the window should be moved to the right to allow more space to the internationalized string.
![colors_syntax](https://user-images.githubusercontent.com/6613431/79601172-aeb3ac00-80e8-11ea-89e3-0ac3b0cd456d.png)

- Something similar for Options > Color > Text: There is more separation between the text and the color items but is not used.
![colors_text](https://user-images.githubusercontent.com/6613431/79601733-955f2f80-80e9-11ea-9c12-82aab6421535.png)

- Something similar for Options > Color > Markers: There is more separation between the text and the color items but is not used.
![colors_markers](https://user-images.githubusercontent.com/6613431/79601957-ee2ec800-80e9-11ea-9c3c-4b9cd8e846b9.png)

- zoom levels subwindow contains two items with the same underlined character (<ins>2</ins>00% and <ins>2</ins>5%):
![zoom](https://user-images.githubusercontent.com/6613431/79602406-b411f600-80ea-11ea-8c63-d39c747e7ee7.png)

- The markers utility has a drop-down menu that is not internationalized:
![markers](https://user-images.githubusercontent.com/6613431/79602935-add04980-80eb-11ea-94c7-ce5b74c462f3.png)

- msgid "O&pen-dialog Auto-Completion:"
This string is used in the options Window and it does not show the underlined letter. The & symbol should be removed.

- msgid "From MRU list"
Maybe MRU is an very used acronym but I had to look it up to understand it. I understand that "From Most Recently Used List" is more appropriate.

- msgid "Whitespace"
This string is used in the Options window and I think it should be in a plural form "Whitespaces".

**Comment by sdottaka** [comment]
>When closing a project with unsaved files an alert window comes up. The string "Discard changes" appears untranslated. There are two similar strings like this to be translated in https://github.com/WinMerge/winmerge/blob/master/Translations/WinMerge/English.pot but this particular one is not included:

It seems to have been translated in the latest CI build artifact.

https://github.com/WinMerge/winmerge/actions/runs/80696512

![image](https://user-images.githubusercontent.com/98126/79621252-a3469c00-814d-11ea-8332-5f6228629c2a.png)

> Frhed settings are not internationalized:

Please translate the following URL:
https://github.com/WinMerge/frhed/tree/github/3way-diff-gplv2/Translations/Frhed

> msgid "O&pen-dialog Auto-Completion:"

Pressing the Alt key will display an underline.

![image](https://user-images.githubusercontent.com/98126/79621545-c1f96280-814e-11ea-9438-54bbe1fe1070.png)

**Comment by sdottaka** [comment]
The following issues has been fixed:
> The Location Pane for image comparison is not internationalized:
> zoom levels subwindow contains two items with the same underlined character (200% and 25%):
> The markers utility has a drop-down menu that is not internationalized:

**Comment by qosobrin** [comment]
> Please translate the following URL:
> https://github.com/WinMerge/frhed/tree/github/3way-diff-gplv2/Translations/Frhed

If so, then I think that this path should be included in the Translation instructions: https://github.com/WinMerge/winmerge/blob/master/Translations/README.md

Thank you.
Regards.

**Comment by sdottaka** [comment]
I think commit 5ebf89a will fix the remaining issues.
