### ISSUE TITLE
Compile WinMerge with ASLR and CFG enabled

### ISSUE THREAD

**Issue by asvc** [WinMerge/winmerge#315]
As WinMerge is already being built with MS Visual Studio, would it be possible to enable [/DYNAMICBASE](https://docs.microsoft.com/en-us/cpp/build/reference/dynamicbase-use-address-space-layout-randomization) and [/guard:cf](https://docs.microsoft.com/en-us/cpp/build/reference/guard-enable-control-flow-guard?view=vs-2019) ?

```ps
> Get-PESecurity -File "C:\Program Files\WinMerge\WinMergeU.exe"

ARCH             : AMD64
DotNET           : False
ASLR             : False
DEP              : True
Authenticode     : False
StrongNaming     : N/A
SafeSEH          : N/A
ControlFlowGuard : False
HighentropyVA    : True
```

Interestingly, [/HIGHENTROPYVA](https://docs.microsoft.com/en-us/cpp/build/reference/highentropyva?view=vs-2019) reports as being enabled, while ASLR is not used at all. Maybe I am missing something here.

**Comment by sdottaka** [comment]
I'm not sure yet, but I want the WinMerge 32bit version to work with WindowsXP, so I may not be able to turn them on.
The WinMerge 64bit version may be able to enable them, as long as the binary size doesn't get too big and the performance doesn't suffer.

**Comment by asvc** [comment]
@sdottaka , I do not have compelling evidence that CFG would produce any perceptually observable slowness, especially in case of an application that does not operate on large amount of data.

Binary size increase is negligible, there is an addition of `.reloc` for ASLR and some small extra for CFG.

I doubt these will work on Windows XP which has had its support ended in April 2014 (in other words - 7 years ago)

**Comment by sdottaka** [comment]
I enabled ASLR and GuardCF in commit 5c318cb only for 64bit version.

**Comment by asvc** [comment]
@sdottaka , seems like something went off the track. I have updated to the latest v2.16.6.0 (shasum of `WinMergeU.exe` is `BCC3AFB722B2D4A7410FCB4B99DEC4678F7F786F`) and see not only CFG, but ASLR disabled altogether:
```powershell
Get-PESecurity -File .\WinMergeU.exe

ARCH             : AMD64
DotNET           : False
ASLR             : False
DEP              : True
Authenticode     : False
StrongNaming     : N/A
SafeSEH          : N/A
ControlFlowGuard : False
HighentropyVA    : True
```

Running process:
![image](https://user-images.githubusercontent.com/300146/82168824-d623b180-98fe-11ea-9864-9a02beea259e.png)

Could you please check on your end?

**Comment by sdottaka** [comment]
The version you tried was version 2.16.6, which was released before your report.

The one with ASLR and CFG enabled hasn't been released yet, the CI Build version below has both enabled.

https://github.com/WinMerge/winmerge/actions/runs/107339816
