### ISSUE TITLE
Error popup if errors parsing an xml file

### ISSUE THREAD

**Issue by JosepMaJAZ** [WinMerge/winmerge#329]
I've updated from winmerge 2.16.4 to 2.16.6 and now i get a popup error when comparing xml files that have some sort of parsing error  (be it a format or an encoding error).
It happens on both,  file compare and folder compare.

He easiest way to reproduce it is create two files file1.xml and file2.xml with some non-xml content (like "hello world")
Compare them and the popup appears.
This is an example of the popup with an encoding problem
![WinMerge-2 16 6-error-on-xmlfiles](https://user-images.githubusercontent.com/9913727/80714575-6091a600-8af5-11ea-8dae-5d1d127cba3f.png)

**Comment by sdottaka** [comment]
The message box above appears to be displayed by the DisplayXMLFiles.dll plugin.
However, as of version 2.16.6, the above plugins are not bundled.

To avoid the above error, delete DisplayXMLFiles.dll in the MergePlugins folder.

Instead of the above plugin, please use [File]->[Recompare As]->[XML] menu item.

**Comment by JosepMaJAZ** [comment]
Oh ok. I have removed it right now and the error has gone.
I used the installer and updated the current version. Maybe the installer should have warned or removed it.

I also see teo other dll with an older date: watchbeginningoflog.dll and watchendoflog.dll.
Are they also obsolete?

**Comment by sdottaka** [comment]
I've stopped bundling plugins that are easy to get into trouble.
In particular, watchbeginningoflog.dll and watchendoflog.dll should be deleted because they can give unexpected results when comparing *.log files.

**Comment by JosepMaJAZ** [comment]
Ok. Then you can close this issue or keep it and add some type of information during the installation process.
