### ISSUE TITLE
A File within a missing Folder, is not listed as missing file

### ISSUE THREAD

**Issue by Jaxx005** [WinMerge/winmerge#330]
Example:

**Left folder only:**  
\#recycle 
\#recycle  \ desktop.ini

WinMerge lists the Folder as "Left only" (Correct)
But the file within that folder (desktop.ini) is not listed.
This causes the file totals to differ by 1.

Could not find this issue raised already.
Have not tested any further, sorry.
Could it be that its named "#recycle" (system folder?), and is skipped?

If it's a wider issue, it could cause some head-scratching.
Very useful utility. Many thanks.
//Jaxx

**Comment by sdottaka** [comment]
Please enable the "Include unique subfolder contents" option. 
It might be better to default to this option.

![image](https://user-images.githubusercontent.com/98126/80770297-db58d080-8b8a-11ea-89cb-91438d43533c.png)

**Comment by Jaxx005** [comment]
Fab. Sorted. File-counts tally now.  

Yes, default as enabled seems more logical, so that it includes such files and totals match etc.

Many thanks

Regards

**Comment by Jaxx005** [comment]
Solved. See Option to include files in unique folders.
