### ISSUE TITLE
Long filename issue

### ISSUE THREAD

**Issue by pbucolo** [WinMerge/winmerge#339]
I'm using 2.16.6 x64 WinMerge to compare files between two network paths (Samba share on Linux Server) to find duplicates.
Winmerge compare two folders and subfolders with 50-100K files at one time.

In the result window are showned only identical files. 
I select all files (CTRL+A) then I select Delete Left Files.

The normal behaviour is that Winmerge open the process window to prepare files for deletion and when ready another windows ask for confirmation before proceed.

But, if in the selected files there are at least one file with long name (248 chars), the process to prepare for deletion, stops without any warning or error. 
Winmerge goes back in the main windows and no operation is made.

To find the file with long name is difficoult due the fact that any warning or error is showned.
BTW, i suppose that it's possible in a future release correct this issue to delete correctly all files including the ones with long name.

Regards,
- Pierluigi

**Comment by sdottaka** [comment]
I've fixed this bug with this commit bbee7c9441d45187b21926d70fcb32f85bc713dc.
Thank you for the report.
