### ISSUE TITLE
Browse button in the file/dir selection show wrong path

### ISSUE THREAD

**Issue by pbucolo** [WinMerge/winmerge#346]
I understand the real behaviour related my previous issue #341 opened few days ago.

Preface:
I'm using often Winmerge to compare folders contents, the dirs to compare have the same name but are stored in two different servers and accessible like Network share.

For example:
Dir 1:  \\Production_Server\home\user\dir_A_to_compare
Dir 2:  \\Backup_Server\home\user\dir_A_to_compare

Often the folders are equal and I delete all same files and the folder in the Backup_Server.
In this example I delete Dir 2 and its content.

In the same way I proceed to compare other two folders:
Dir 3: \\Production_Server\home\user\dir_B_to_compare
Dir 4:  \\Backup_Server\home\user\dir_B_to_compare

New Dir choice:
To select Dir 3, I use the Browse button and I go up one dir and select the new Dir 3. 
To select Dir 4, I use the Browse button, but in the text box is present an not existing path because I've delete the Dir 2.

For Dir 4 winmerge has two different behaviour.
1 - The browse window is opend with a "neutral path" set, like "This PC" (if I remeber weel)
2 - The Browse window is opened using the path of Dir 3.

The first behaviour is preferable, because in the second case......due the fact that the network path are almost the same, (change only the server name) it's easy to select again Dir 3.....
So I compare the folder with itself....and I can make a big damage deleting the ORIGINAL files I've got.....
Expecially if the network path is long the Server name is not showned due the limited text box size.

I suggest to correct the Winmerge behaviour with two improvements:
1 - If the same file/folder is selected to compare itself, show an ALERT and not allow this operation.
(Why I must compare file /folder with itself ? )

2 - When the path in the textbox is invalid or inaccesible) set the path of browse window to a "neutral path" and NOT to a path existing in other text box of the Winmerge selection window.

I hope that my description is clear and the issue is reproducible .

- Pierluigi

**Comment by pbucolo** [comment]
Good work, 
I compiled using Visual Studio latest branch 2.16.7 x64.
Now is opened the parent folder if the folder doesn't exist.

I suppose the bug could be closed.

- Pierluigi

**Comment by sdottaka** [comment]
Thank you for the confirmation.

**Comment by pbucolo** [comment]
Nothing…. It’s a little contribute…

BTW Using Winmerge I note some improvements.
Please, tell me which is the best way to describe it.

I’ll write in the Discussion Forum ?
Or in the ISSUE ?

Let me know

Regards,

  *   Pierluigi








Da: Takashi Sawanaka
Inviato: mercoledì 20 maggio 2020 12:36
A: WinMerge/winmerge <winmerge@noreply.github.com>
Cc: pbucolo <pbucolo@gmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [WinMerge/winmerge] Browse button in the file/dir selection show wrong path (#346)


Thank you for the confirmation.

**Comment by sdottaka** [comment]
Please write about it on GitHub issues.
