### ISSUE TITLE
Assertion failed Message Box form MSVC Runtime Library

### ISSUE THREAD

**Issue by Thomas-Haase** [WinMerge/winmerge#347]
I'm using 2.16.0.0 Unicode x64. When comparing a file with whitespace compare enabled, and ignore empty lines enabled, I get this message box:
![grafik](https://user-images.githubusercontent.com/20301226/82216872-dbdac080-9919-11ea-9a8c-489296846c0a.png)

**Comment by sdottaka** [comment]
Could you please see if the assertion message box shows up in the latest version 2.16.6?
If shown, could you attach the files you compared?

**Comment by Thomas-Haase** [comment]
This issue does not occur in 2.16.6. Thx.

FYI: all three indicated compare settings must be enabled, to reproduce the issue in 2.16.0

![grafik](https://user-images.githubusercontent.com/20301226/82220237-aa182880-991e-11ea-8807-43060137baa0.png)

**Comment by sdottaka** [comment]
Thank you for the info.
