### ISSUE TITLE
Winmerge Freeze if large number of  files are listed in Window View

### ISSUE THREAD

**Issue by pbucolo** [WinMerge/winmerge#348]
When a large number of files are listed in Window View it's impossible to use WinMerge, because each operation (click on menu items, click in the Window View, scrolling) is executed after several second or minutes, depending how is higher the number of files listed.

I tested this issue when comparing identical folders with more then a millon files.

- Pierluigi 
Winmerge 2.16.7 x64

**Comment by sdottaka** [comment]
This fix (d5eaccc) should improve this problem a bit.

**Comment by pbucolo** [comment]
Hi,

to test this patch can I clone It from git ?

Pierluigi


Da: Takashi Sawanaka <notifications@github.com>
Inviato: giovedì 21 maggio 2020 14:00
A: WinMerge/winmerge <winmerge@noreply.github.com>
Cc: pbucolo <pbucolo@gmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [WinMerge/winmerge] Winmerge Freeze if large number of files are listed in Window View (#348)


This fix (d5eaccc<https://github.com/WinMerge/winmerge/commit/d5eaccce4a112eacd19888131eea848daa5b78dc>) should improve this problem a bit.

**Comment by sdottaka** [comment]
git pull & build or you can download the latest binaries from https://github.com/WinMerge/winmerge/actions/runs/111396634

**Comment by pbucolo** [comment]
Patch tested, now is really very responsive, no more freeze.

Good work.
