### ISSUE TITLE
Crush-report.

### ISSUE THREAD

**Issue by username1565** [WinMerge/winmerge#351]
1. Compare two files.
2. Rename one file, then.
3. Open second file, as text, change this second file, and save it.
4. Back to WinMerge, see the window about some program updated the second file, and try to reload it in WinMerge.
5. See crush of WinMerge, because first file was been renamed.

**Comment by sdottaka** [comment]
This bug has been fixed with commit 39dc6b3e599231ac63a854db8959d34504f75410

Thank you for the report.

**Comment by username1565** [comment]
Hello, @sdottaka !
I see one more crush, when file is busy by another process.

1. Compare two files.
2. Rewrite one file by some program, and do not close file.
3. Back to WinMerge, and see some file was been updated.
4. Try re-compare files.
5. See crush of WinMerge, while one file is busy by another process (opened in the some program).

**Comment by sdottaka** [comment]
I was able to reproduce the crash in 2.16.6, but the latest master branch doesn't crash and I get a "Cannot open file ..." message box instead. The latest master branch seems to have fixed this issue.

**Comment by username1565** [comment]
Just I saw this crush, in [`winmerge-2.16.4-exe.zip`](https://github.com/WinMerge/winmerge/releases/tag/2.16.4)

**Comment by sdottaka** [comment]
Could you try https://github.com/WinMerge/winmerge/releases/tag/2.16.7 ?

**Comment by username1565** [comment]
@sdottaka, yes, of course. This works without any crash. Thanks! I will use it, now.
