### ISSUE TITLE
Difference does not highlighed in Diff Pane sometimes

### ISSUE THREAD

**Issue by vinixwu** [WinMerge/winmerge#355]
WinMerge Version: 2.16.6.0 X64
OS: Win10 2004

When I opened a file for version compare, I noticed that some differences didn't highlighed in Diff Pane:
![image](https://user-images.githubusercontent.com/20789695/83834840-e078e480-a721-11ea-99ca-b3b4a0f03ac0.png)

But some of the differences in the same file displayed correctly:
![image](https://user-images.githubusercontent.com/20789695/83834929-1027ec80-a722-11ea-9f14-3939a987aadd.png)

I opened a new WinMerge window and pasted just the line in question, it displayed correctly:
![image](https://user-images.githubusercontent.com/20789695/83835064-685eee80-a722-11ea-8b63-b8224bd3693d.png)

I've quoted a small part of the original files which can also reproduce the problem:
[Left.txt](https://github.com/WinMerge/winmerge/files/4733839/Left.txt)
[Right.txt](https://github.com/WinMerge/winmerge/files/4733840/Right.txt)

**Comment by sdottaka** [comment]
The reason the differences are not highlighted is that the line is not a difference line, but a moved block line.

Disable the moved block detection or to make it easier to recognize that it is a move block, the following settings are recommended.

![image](https://user-images.githubusercontent.com/98126/83881906-50b45400-a77c-11ea-98ff-0e4bf3b89757.png)

**Comment by babanga** [comment]
I've just installed winmerge and have a similar sounding issue. To see the differences in Diff pane you have to use the next/prev/last diff buttons or hotkeys. Is this a bug or is there an option to see the differences by simply clicking on the line with a mouse?

**Comment by vinixwu** [comment]
> The reason the differences are not highlighted is that the line is not a difference line, but a moved block line.

In 1st image, the number in the URL is different. So you mean that similar (but not the same) line is detected as moved block?

**Comment by sdottaka** [comment]
> I've just installed winmerge and have a similar sounding issue. To see the differences in Diff pane you have to use the next/prev/last diff buttons or hotkeys. Is this a bug or is there an option to see the differences by simply clicking on the line with a mouse?

It is not a bug. If you double click on a line with a difference, you will see that difference line in the Diff Pane.

**Comment by sdottaka** [comment]
> > The reason the differences are not highlighted is that the line is not a difference line, but a moved block line.
> 
> In 1st image, the number in the URL is different. So you mean that similar (but not the same) line is detected as moved block?

I'm not sure what "the number in the URL" means, but WinMerge treats lines with the same content as moving blocks, like this:

![image](https://github.com/WinMerge/winmerge/assets/98126/9e635bb7-6174-4f03-93f7-36a72696ee8c)

**Comment by vinixwu** [comment]
Thank you for your response. :)

I suggest these matched lines should also be displayed in the Diff Pane.
For example, line 67 of Left.txt and line 54 of Right.txt.

Takashi Sawanaka ***@***.***> 於 2023年5月30日 週二 下午8:25寫道：
