### ISSUE TITLE
Only indent existing lines

### ISSUE THREAD

**Issue by jdm3** [WinMerge/winmerge#356]
Block indent of a selection that includes a 'delete' difference will currently add lines for each deleted line.

Could you instead only indent existing content?

![wm1](https://user-images.githubusercontent.com/1189768/83905349-5e36f300-a716-11ea-8eb1-cf3af6f23310.gif)

**Comment by sdottaka** [comment]
This issue has been fixed with commit 660e989
Thank you for the report.

**Comment by jdm3** [comment]
Thank-you for the quick response!  And keep up the great work, love the tool!!!

**Comment by michael-mayes** [comment]
Thanks to @jdm3 for reported and to @sdottaka for the fix

This issue had been bugging me from time to time, but have only realised today that development and developer interaction is very active here on GitHub
