### ISSUE TITLE
Moved ghost lines are shown in the wrong color

### ISSUE THREAD

**Issue by taoyue** [WinMerge/winmerge#358]
Repro steps
-----------
1. Go to Edit-Options, Compare > General.
2. Check "Enable moved block detection."
3. Go to Colors > Differences.
4. Set the Difference Deleted color to a distinctive color (purple).
5. Click OK.
6. Diff the attached files, moved1.txt and moved2.txt.
    *  [moved1.txt](https://github.com/WinMerge/winmerge/files/4741293/moved1.txt)
    *  [moved2.txt](https://github.com/WinMerge/winmerge/files/4741294/moved2.txt)

Expected behavior
-----------------
* The moved line should display in the Moved Background color.
* The moved ghost line should display in the Moved Deleted color.

Actual behavior
---------------
* The moved ghost line displays in the Difference Deleted color.

![moved-ghost-wrong-color](https://user-images.githubusercontent.com/3683818/83958435-a867c380-a83f-11ea-9324-ff97a6b60b2b.png)

More information
----------------

The problem is caused by the fact that `CMergeDoc::FlagMovedLines` only sets `LF_MOVED` on the lines that actually moved.  The flags are not set on the moved ghost lines in the other file.

`CMergeEditView::GetLineColors2` expects moved ghost lines to have `dwLineFlags` of `LF_DIFF | LF_MOVED | LF_GHOST`.  If all three flags are set, then it will take the branches on lines 755, 776, and 778, ending up on line 779 where `crBkgnd` gets set to `m_cachedColors.clrMovedDeleted`.

However, a moved ghost line has `dwLineFlags` of only `LF_GHOST`, since the code never set `LF_DIFF` and `LF_MOVED`.  So it goes to the else if block at line 803, then the else at 807, ending up on line 808 where `crBkgnd` gets set to `m_cachedColors.clrDiffDeleted`.

Here is the relevant code that shows the control flow:

```C++
  755   else if (dwLineFlags & LF_DIFF)
  756   {
  757       if (lineInCurrentDiff)
        ...
  774       else
  775       {
  776           if (dwLineFlags & LF_MOVED)
  777           {
  778               if (dwLineFlags & LF_GHOST)
  779                   crBkgnd = m_cachedColors.clrMovedDeleted;
        ...
  791   }
        ...
  803   else if (dwLineFlags & LF_GHOST)
  804   {
  805       if (lineInCurrentDiff)
  806           crBkgnd = m_cachedColors.clrSelDiffDeleted;
  807       else
  808           crBkgnd = m_cachedColors.clrDiffDeleted;
```

**Comment by sdottaka** [comment]
This bug has been fixed with commit 5b16f3d
Thank you for the report.
