### ISSUE TITLE
Size of folder not displayed

### ISSUE THREAD

**Issue by lucmonte** [WinMerge/winmerge#361]
I'm using Winmerge 2.16.6.0. Very good program! It helps me everyday. I notice that when I run a folder comparison and a subfolder doesn't exist in either left or right side, size of subfolder that exists is not displayed. Is it possible to add an option for scanning the subfolders that exists in either side and showing the size of that subfolder?

Thank you

Luca

**Comment by sdottaka** [comment]
Please enable the "Include unique subfolder contents" option.
![image](https://user-images.githubusercontent.com/98126/84264416-1ec83680-ab5c-11ea-98e9-28eecc78e7f9.png)

**Comment by sdottaka** [comment]
If enabling the "Include unique subfolder contents" option does not resolve the issue, please re-open this issue.
