### ISSUE TITLE
opening same file

### ISSUE THREAD

**Issue by megido** [WinMerge/winmerge#362]
2.16.6.0 doesn't some warning when open same file, in early version it does but I do not remember which one

**Comment by sdottaka** [comment]
2.16.6 will also display the following message box

Perhaps you have checked the "Don't display this message again" checkbox and the message box is no longer visible.

![image](https://user-images.githubusercontent.com/98126/84557487-a1bcdd00-ad66-11ea-93fc-c8e6468797a2.png)

To display the message box again, press the Reset button below in the Options dialog.

![image](https://user-images.githubusercontent.com/98126/84557530-024c1a00-ad67-11ea-8625-948742363049.png)

**Comment by megido** [comment]
firstly it's information box and in this case it fine
like this
![two-files](https://user-images.githubusercontent.com/5677342/84572805-83f17700-ad6a-11ea-9a60-e6672bc90f07.png)

but in this case must be warning because user trying compare same file
![same-file](https://user-images.githubusercontent.com/5677342/84572820-a6839000-ad6a-11ea-9c08-492ee6b655ef.png)

**Comment by sdottaka** [comment]
Sorry, I misunderstood this issue.
I've fixed this issue with commit 988b817.
(https://github.com/WinMerge/winmerge/actions/runs/134821747)
