### ISSUE TITLE
Comparing 2 XML templates.  WinMerge shows no difference after 1st comparison.

### ISSUE THREAD

**Issue by kcombs12** [WinMerge/winmerge#363]
Hi,
Using WinMerge version 2.14.1.1 Unicode
Lenovo Laptop, 16.0 GB RAM, 64-bit operating system

I've used WinMerge for years and love it.  Recently I'm experiencing something that is unusual.  When I compare 2 XML files the FIRST time, it works great, as expected.  When I then change and browse to two DIFFERENT XML templates to compare, then it shows no difference.  I've had to unload WinMerge from my laptop and reload and then it works.  If I move XML coding over to the right, for example, I do not save the changes.  I close the product down and start over, same thing.  I delete the files from the browse windows, start fresh and pull the XML templates again, no change.  I compare yet another two different files that I know for a fact are different, still same result.  ALL yellow, showing no differences or to me, yellow means different, so it's not recognizing anything.

So, I unload WinMerge and re-install it.  There's got to be something I'm doing incorrectly, but can't figure it out.  How do I erase the memory of the first comparison, so the 2nd, 3rd, 4th, etc., comparisons will work?  
Thank you!
Kcombs12

**Comment by sdottaka** [comment]
Could you attach the XML files?

**Comment by kcombs12** [comment]
[Well, I'd love to, but when I drag and drop my XML file here I get a message that says, "We don't support that file type."  Ideas?

](url)

**Comment by kcombs12** [comment]
[NotePad_SunPower-Contractors or Non US Req_061520_1256.txt](https://github.com/WinMerge/winmerge/files/4802155/NotePad_SunPower-Contractors.or.Non.US.Req_061520_1256.txt)
[Notepad_SunPowerTest-Contractors or Non US Req_061520_1252.txt](https://github.com/WinMerge/winmerge/files/4802157/Notepad_SunPowerTest-Contractors.or.Non.US.Req_061520_1252.txt)

**Comment by kcombs12** [comment]
Ok, I was able to place the XML files in Notepad.  Dragged and dropped them in above file.

**Comment by kcombs12** [comment]
Hi,
I did attach the XML files in Notepad to the website, but there are here too.
Thank you!
Karin

Out of Office:  July 3rd – USA Holiday

**Comment by sdottaka** [comment]
Thank you for attaching the file.
I've confirmed that the issue can be reproduced with version 2.14.0 and not with the latest 2.16.6.
Therefore, please use the latest version.

**Comment by kcombs12** [comment]
THANK YOU!!!
