### ISSUE TITLE
Crash when comparing encrypted 7z files

### ISSUE THREAD

**Issue by gbInArY** [WinMerge/winmerge#367]
If you try to compare a 7z file with password **and encrypted names**, WinMerge will crash instead of asking for a password.

How to reproduce the issue:
1- Unzip the file: [The test.zip](https://github.com/WinMerge/winmerge/files/4851977/The.test.zip)
2- Try to compare: _Some 7z encrypted - 1.7z_ with _Some 7z encrypted - 2.7z_

Note: the password for these files is: test

**Comment by sdottaka** [comment]
This bug has been fixed with commit cd1371a (https://github.com/WinMerge/winmerge/releases/tag/Merge7z1900.2)
Thank you for the report.
