### ISSUE TITLE
Find dialog sometimes remembers old text to start a new find instead of the new text.

### ISSUE THREAD

**Issue by mdell-seradex** [WinMerge/winmerge#368]
I often use Ctrl-F3 to find without using the dialog, however when I want to use a Find Option (e.g. Match whole words, Regular Exp) I use Ctrl-F to open the Find dialog (Or Ctrl-H for Find & Replace) with the selected text as the value to find.

What sometimes occurs is that instead of the selected text being displayed in the dialog, a previous find value is shown.  Often the text displayed starts with the selected text (e.g. "str" was selected, but "string" is displayed in the Find Dialog - I had searched for "string" previously and have searched for other things since).
It seems that sometimes the text is not related at all.

Please change it so that if text is selected (highlighted) when the Find or Find & Replace dialog is opened, only the selected text is displayed for the find value.

**Comment by sdottaka** [comment]
This bug has been fixed with commit 6cfb49c 
Thank you for the report.
