### ISSUE TITLE
Allow for better word boundaries when navigating text

### ISSUE THREAD

**Issue by mdell-seradex** [WinMerge/winmerge#369]
I often use Ctrl-Left Arrow or Ctrl-Right Arrow to navigate text and combine it with Shift to highlight.
When navigating text like "System.Windows.Forms.TextBox", it does not stop at the periods and instead goes on to the next white space, bracket or other similar character.
I would like to have the ability to allow that navigation to stop at characters like periods as well as this aids in navigating code and adjusting when trying to compare if to code files are actually the same

e.g. one has "System.Windows.Forms.TextBox" and the second has "TextBox" with an imports statement at the top of the file "Imports System.Windows.Forms", thus they are actually the same.  In that case I strip out "System.Windows.Forms." from the first file to match them more closely to find what real differences they have, if any.

**Comment by mdell-seradex** [comment]
I also forgot that it does this when double clicking on text as well (not using the "." as a work break).
Please add that as well as any other naturally related actions.
e.g. If I double click on "Windows" within "System.Windows.Forms.TextBox", only "Windows" should be automatically highlighted instead of the whole string.

Thank you

**Comment by sdottaka** [comment]
This issue has been fixed with commit cdb3b2272616484b5e0019f81b8c6d0baccb30b9
