### ISSUE TITLE
App crash due to deleted file

### ISSUE THREAD

**Issue by gal20040** [WinMerge/winmerge#371]
Hi!

I've encountered with app crash due to deleted file (one of the compared).
I use v.2.16.6.0, x86.

WinMerge configuration file attached:
[WinMerge_conf.txt](https://github.com/WinMerge/winmerge/files/4872789/WinMerge_conf.txt)

Steps:
1. Create new two files comparison (Ctrl + N)
2. Drag and drop one file on the left pane and the second one on the right pane.
3. Delete one of the files.
4. Edit the second one in another application (e.g. notepad).
5. Switch back in WinMerge.
6. You will get notification that one of the files was edited. Click YES to response for reload it.
**Expected:**
7. Edited file view should be updated and some notification about deletion the second file should be presented.

**Actual:**
7. App crash is presented.

**Error in event viewer:**
Faulting application name: WinMergeU.exe, version: 2.16.6.0, time stamp: 0x5e527bf0
Faulting module name: WinMergeU.exe, version: 2.16.6.0, time stamp: 0x5e527bf0
Exception code: 0xc0000005
Fault offset: 0x00113cbb
Faulting process id: 0x414c
Faulting application start time: 0x01d651f9b3e55f4f
Faulting application path: C:\Program Files (x86)\WinMerge\WinMergeU.exe
Faulting module path: C:\Program Files (x86)\WinMerge\WinMergeU.exe
Report Id: c24bc5d5-d2e7-45df-893a-8b0f6a271e1f
Faulting package full name: 
Faulting package-relative application ID: 

**Information in event viewer:**
Fault bucket 1824272151656830123, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0
Problem signature:
P1: WinMergeU.exe
P2: 2.16.6.0
P3: 5e527bf0
P4: WinMergeU.exe
P5: 2.16.6.0
P6: 5e527bf0
P7: c0000005
P8: 00113cbb
P9: 
P10: 
Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER708B.tmp.WERInternalMetadata.xml
These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_WinMergeU.exe_9e35e5a14f2ec741e275be1e301b3f5f61f6474_7e1385d5_531a7463\Report.txt
[Report.txt](https://github.com/WinMerge/winmerge/files/4872797/Report.txt)
Analysis symbol: 
Rechecking for solution: 0
Report Id: c24bc5d5-d2e7-45df-893a-8b0f6a271e1f
Report Status: 1
Hashed bucket: 893096aa3b15154259511ddb452494ab

**Comment by sdottaka** [comment]
It looks like the same bug as https://github.com/WinMerge/winmerge/issues/351.
The bug has been fixed in commit 39dc6b3
