### ISSUE TITLE
compare methods "Full Contents" and "Quick Content" drop unique items

### ISSUE THREAD

**Issue by 8ctopus** [WinMerge/winmerge#380]
WinMerge 2.16.6.0 x64 - Windows 10 Pro x64 1909

First of all thanks for making such a useful tool!

**Please read the update at the end of the post**

I've recently noticed that the latest version of WinMerge drops some of the unique items when using compare mode "Full Contents" and "Quick Contents". This does not happen with other modes such as "Binary Contents" or "Size".

### Full Contents compare screenshot
![Full Contents compare](https://user-images.githubusercontent.com/13252042/88369988-a2578300-cdaa-11ea-82b3-89d2fec53638.png)

### Binary Contents compare screenshot
![Binary Contents compare](https://user-images.githubusercontent.com/13252042/88370037-b307f900-cdaa-11ea-83c9-dd506a59bb02.png)

**UPDATE**: The missing files are actually not dropped but incorrectly categorized as binary files when using compare modes "Full Contents" and "Quick Contents".

**Comment by sdottaka** [comment]
I think this issue is fixed in 4a46291977af8101d3fb9636287e663912f87131.
The Beta version will be released soon.

**Comment by 8ctopus** [comment]
@sdottaka OK, I'll be glad to test it when the beta is released unless there are nightly builds?

**Comment by sdottaka** [comment]
Here is the CI build version: https://github.com/WinMerge/winmerge/actions/runs/180732527

**Comment by 8ctopus** [comment]
Hello @sdottaka, pre-release 2.16.7 fixes the issue I reported.
