### ISSUE TITLE
Bug: Line Filters aren't applied when using a 3rd file

### ISSUE THREAD

**Issue by cnotin** [WinMerge/winmerge#395]
I'm using a line filter which works fine when comparing 2 files, but if I add a 3rd file (which is similar to the first 2 so I should see similar filtering), then I see no filtering at all in any of the 3.
Maybe Line Filters aren't supported on 3-files diff mode?

Version: 2.16.6.0

**Comment by cnotin** [comment]
Filtering works fine with 2 files:
![image](https://user-images.githubusercontent.com/550823/89645759-cb076e80-d8ba-11ea-843c-4c24db578155.png)

Filtering fails when adding a 3rd file:
![image](https://user-images.githubusercontent.com/550823/89645769-d195e600-d8ba-11ea-89e4-3e50e7edc7f1.png)

**Comment by sdottaka** [comment]
I completely forgot about that, but as you pointed out, line and comment filters are not yet implemented in 3-way compare.
Thank you for reminding me.

**Comment by cnotin** [comment]
No worries! It'd be nice to have it though.
I let you keep this open as a reminder if you want.

By the way, WinMerge is really an awesome tool thank you very much! 👏

**Comment by sdottaka** [comment]
Fixed by commit fbf58d3

**Comment by cnotin** [comment]
Awesome thank you!
