### ISSUE TITLE
More space for some internationalized strings

### ISSUE THREAD

**Issue by Mr-Update** [WinMerge/winmerge#402]
![Suchen](https://user-images.githubusercontent.com/37781396/89829397-cc56c680-db5a-11ea-91fe-c54d7ee4584a.png)

![Ersetzen](https://user-images.githubusercontent.com/37781396/89829406-d082e400-db5a-11ea-8707-635e5a5d2610.png)

![Patch-Generator](https://user-images.githubusercontent.com/37781396/89829416-d4af0180-db5a-11ea-9306-c88be0bf08f5.png)

After widening the location pane there is still some space missing.
![Positionsleiste](https://user-images.githubusercontent.com/37781396/89829428-d8db1f00-db5a-11ea-8ad6-9e00748f0b19.png)

**Comment by sdottaka** [comment]
Fixed by commit 27fd934

Thank you for the report.
