### ISSUE TITLE
WinMerge unexpectedly quits: access violation reading location

### ISSUE THREAD

**Issue by annazolkieve** [WinMerge/winmerge#409]
WinMerge has started unexpectedly quitting after:
- 2-3 seconds after selecting files and clicking "Compare";
- 2-3 seconds after clicking "New Documents".
No idea what's the reason.
I've tried to debug with VS (at least to try to see what's the root cause).
VS shows this:
![image](https://user-images.githubusercontent.com/46918093/90442910-0dfbea00-e0e4-11ea-97f8-d24f5d8c515c.png)
Please integrate (if not yet integrated) some "App crashed, send crash log" handler.

**Comment by annazolkieve** [comment]
UPD. Upgrading to 2.16.6.0 has solved the problem.

**Comment by sdottaka** [comment]
It may be the same as issue #259.

**Comment by annazolkieve** [comment]
@sdottaka Yes, I remember that before I've de-selected Split Vertically.

**Comment by sdottaka** [comment]
Thank you for the info.
