### ISSUE TITLE
Wrong merging

### ISSUE THREAD

**Issue by DrunkAnalytics** [WinMerge/winmerge#420]
Hello. Starting from ver. 2.16.4 merging files work wrong on x32 XP SP3. Different files are not different. I tested that issue on ver. 2.16.4, 2.16.6 and 2.16.2. On 2.16.2 problem is absent.
[WinMerge.txt](https://github.com/WinMerge/winmerge/files/5142084/WinMerge.txt)

**Comment by sdottaka** [comment]
Could you attach a screenshot?

**Comment by sdottaka** [comment]
Probably now I can reproduce this problem.
It seems that you specified patience for the Diff algorithm on the Compare/General page of the Options dialog.
I think it works if you change from patience to default.

**Comment by sdottaka** [comment]
I've fixed this issue by commit ef01a1c and released version 2.16.8. https://github.com/WinMerge/winmerge/releases/tag/2.16.8
Thank you for the report.

**Comment by DrunkAnalytics** [comment]
Thnx! I tested it on ver. 2.16.8 and now it's good.
