### ISSUE TITLE
Include Filter does not filter out specific file?

### ISSUE THREAD

**Issue by andrewteg** [WinMerge/winmerge#428]
I have an include filter with a bunch of lines to filter out extensions like:
`f: \.tmp  ## temporary files`
`f: \.bak  ## back up files`
I added this line thinking it would filter out a specific file:
`f: map\\index_test.php`
However, I still get that when comparing 
D:\apps\temp\htdocs\
D:\apps\live\htdocs\

The file I want to filter out is directly at:
D:\apps\temp\htdocs\map\index_test.php
D:\apps\live\htdocs\map\index_test.php

Shouldn't this file filter ignore that file?

Thanks.

**Comment by sdottaka** [comment]
Unfortunately, for now, you can only specify the filename on the 'f:' line, like this:

f: index_test.php

I'd like to support a .gitignore format file filter that can do that, but I'm not sure when.
