### ISSUE TITLE
unused variable

### ISSUE THREAD

**Issue by maddin200** [WinMerge/winmerge#434]
Externals/poco/Foundation/src/DirectoryIteratorStrategy.cpp line 64

	std::stack<DirectoryIterator> it;  // <-- unused

	//_depthDeterminer(it);

**Comment by sdottaka** [comment]
Fixed by commit 3b86ca5.

However, WinMerge does not use Externals/poco/Foundation/src/DirectoryIteratorStrategy.cpp.

Also, this source is from the following project, so I think you should report it here.

https://github.com/pocoproject/poco

**Comment by maddin200** [comment]
thanks - done here:
https://github.com/pocoproject/poco/issues/3107
