### ISSUE TITLE
Image compare doesn't hightlight some differences

### ISSUE THREAD

**Issue by stanio** [WinMerge/winmerge#436]
WinMerge 2.6.18.0 X64
Windows 10

It appears the image compare doesn't highlight (Block Size / Block Alpha) some differences comparing these two images:

![gbamockup@2x](https://user-images.githubusercontent.com/1247730/93976739-1cdc5900-fd82-11ea-968c-0064dfbdf0d8.png)
![gbamockup@2xbrz](https://user-images.githubusercontent.com/1247730/93976742-1e0d8600-fd82-11ea-96d4-5f08e1ffd0e9.png)

See a sample surrounded with a red line:

![overlay-none](https://user-images.githubusercontent.com/1247730/93977179-c7547c00-fd82-11ea-98be-ab26db740e12.png)

It is easier spotted using a XOR overlay:

![overlay-xor](https://user-images.githubusercontent.com/1247730/93977487-3cc04c80-fd83-11ea-9b1d-664461366e58.png)

One may see more non-highlighted differences zooming out and panning the images.

**Comment by sdottaka** [comment]
You have set the "CD Threshold" (Color Distance Threshold) to 20, so subtle color differences are ignored.

What if I try setting CD Threshold to 0?

**Comment by stanio** [comment]
Oh, right.  Missed that setting completely.  Thank you for pointing it out!

Setting "CD Threshold" to 0 highlights all differences as expected.  Seems like I didn't understand what this setting does – now I know CD stands for Color Distance.
