### ISSUE TITLE
"Don't ask again" checkbox for the Confirm Copy dialog

### ISSUE THREAD

**Issue by tchesftw** [WinMerge/winmerge#444]
The Confirm Copy dialog ("are you sure you want to copy xxxx from left ...") would probably benefit from a "Don't ask again" checkbox. I use that feature quite a lot and it's annoying to answer Yes every time.

I can do it and open a pull request.

**Comment by sdottaka** [comment]
I agree with the idea. The pull request is welcome.

**Comment by tchesftw** [comment]
Done.
