### ISSUE TITLE
[Feature Request]:  Add syntax highlights for languages

### ISSUE THREAD

**Issue by mlipok** [WinMerge/winmerge#446]
Please add syntax highlights for AutoIt languages

**Comment by mlipok** [comment]
I just saw that Basic is fine for me.
Could "Basic" became a default Syntax Highlighting for "AutoIt"
?

![2020-10-18 173851 - WinMerge - GitHub - AutoIt Syntax Highlighting](https://user-images.githubusercontent.com/11089482/96372937-b6244280-1169-11eb-98ca-31715691653a.png)

**Comment by mlipok** [comment]
For reference:

Further work will be done here:
https://github.com/WinMerge/winmerge/commit/c5a124c23d027aad72c807093d9d330e730b642f

**Comment by sdottaka** [comment]
AutoIt syntax highlighting has been implemented at commit 99f95ab

**Comment by mlipok** [comment]
AutoIt syntax highlighting has been implemented at commit https://github.com/WinMerge/winmerge/commit/08ab2142e4155f70607e739cb7d343a6cbed3998

**Comment by mlipok** [comment]
why this change is not enlisted here:
https://github.com/WinMerge/winmerge/releases/tag/v2.16.10

**Comment by sdottaka** [comment]
> 
> 
> Why this change is not enlisted here:
> https://github.com/WinMerge/winmerge/releases/tag/v2.16.10
> 
> ?

It is not listed because there is a corresponding Pull Request (#543,#584) for the issue.
