### ISSUE TITLE
"Ignore blank lines" does not work in 3-way compare

### ISSUE THREAD

**Issue by jki21** [WinMerge/winmerge#450]
"Identical" when 2-way compare:
![image](https://user-images.githubusercontent.com/32349750/95723138-62b47f00-0ca7-11eb-896c-807bf2cb06e4.png)
"Text files are different" when 3-way compare: 
![image](https://user-images.githubusercontent.com/32349750/95722396-757a8400-0ca6-11eb-96c4-90aa4ec46e65.png)
file content:
![image](https://user-images.githubusercontent.com/32349750/95722501-99d66080-0ca6-11eb-99cf-d832a3dda944.png)

**Comment by sdottaka** [comment]
Fixed by commit fbf58d3
