### ISSUE TITLE
Winmerge Compare button disabled

### ISSUE THREAD

**Issue by gbejiway** [WinMerge/winmerge#451]
Hello,

Sometimes when I want to compare two files the Compare button is disabled. Both files exist and are selected through the Browse function. Sometimes the Compare button is active, sometimes (about 10% of all attempts), even for the same files. it is disabled. I am unable to see any pattern or understand why this happens. By closing the application and starting again the Compare button becomes available, so there is a solution but it is not really ideal.

[](url
![Compare](https://user-images.githubusercontent.com/72803080/95861749-2c880580-0d62-11eb-91e7-f1f70bec3fe8.JPG)
)
![Compare2](https://user-images.githubusercontent.com/72803080/95862336-0e6ed500-0d63-11eb-8344-272c4b1efee4.JPG)

**Comment by sdottaka** [comment]
Thank you for the report.

Is Y drive a network drive?

**Comment by gbejiway** [comment]
Hello,

 

Yes, the Y is a connection to the IFS of our iSeries machine.

 

Best Regards

Graham Belton

**Comment by sdottaka** [comment]
After all I couldn't reproduce this issue, but I fixed it to retry if the file or folder existence check failed. This may solve this problem.

**Comment by sdottaka** [comment]
Please reopen after reproducing with the latest version.
