### ISSUE TITLE
Scrolling binary files

### ISSUE THREAD

**Issue by mrLithe** [WinMerge/winmerge#456]
Scrolling of binaries with the mouse wheel does not work. If the cursor is on one side, it works. If the cursor is on the other side, it does not work. It just twitches.

![WinMergeScroll](https://user-images.githubusercontent.com/19571942/96261771-8b02ed00-0fc9-11eb-8872-1d17e1e02047.gif)

**Comment by mrLithe** [comment]
WinMerge opens from TortoiseSVN

**Comment by sdottaka** [comment]
Fixed by commit bb8e1ab

Thank you for the report.
