### ISSUE TITLE
Cannot save merged files. XLS in Manual Predifier/Unpacking mode. JAVA in Automatic Predifier/Unpacking mode.

### ISSUE THREAD

**Issue by Artur51** [WinMerge/winmerge#461]
It not comfortable to use application while working with java and xls files. Because it is required to manually setup Automatic or Manual Predifier/Unpacking mode. Both menu at the same time must to be changed depend on file type you are working on. It would be nice if application can automatically made a required setup for file type. And allow resave merged files  to original location without error prompt.
Please have it fixed.

Step to reproduce: 

1) Open two java files and setup in menu
Automatic Predifier and Automatic Unpacking 
restart the application 
open the same or others java/text files to merge.
it is not possible to save files after merge.

2) Open two xls files and setup in menu
setup Manual Predifier and Manual Unpacking 
restart the application 
open the same or others xls files to merge.
it is not possible to save files after merge.

**Comment by sdottaka** [comment]
Sorry for the late response.

So far I have not been able to reproduce both issues.

Do you have the same problem with the latest version?

**Comment by Artur51** [comment]
Hello dear Takashi Sawanaka!
Yes, I still have these issues. It would be nice to have those fixed.
Please fix the issues.

I just downloaded version 2.16.14 and it behaves the same way. In Plugins -
Manual Unpacking + Manual Predifier it works perfectly for java files.
 But it does not merge xls files. I believe users should avoid changing
settings. All should work fine in a regular setup. Those settings seem to
me odd, too complicated to test different combinations for each file type.
Hope it is can be code in your unit testing to have all issues resolved
once.

Have a good day.
Artur Zuravljov.



вс, 19 сент. 2021 г., 7:59 Takashi Sawanaka ***@***.***>:

**Comment by sdottaka** [comment]
When comparing java files, does the name of the plugin appear in the status bar in the following location?

![image](https://user-images.githubusercontent.com/98126/134156767-aeb72564-455f-42d4-a8e5-06df1324e01e.png)

If you see the name of a plugin, what is the extension setting for that plugin?

This can be found in the 'File filters' section of the Plugins dialog that appears when you select the Plugins → Plugin Settings menu item.

![image](https://user-images.githubusercontent.com/98126/134156884-542e0839-cbb1-415c-8407-46845c774731.png)

When you say 'Cannot save merged files', do you mean that the following message box appears when saving?

![image](https://user-images.githubusercontent.com/98126/134157312-26292b44-2ea9-4aa9-85aa-a5370e51cb73.png)

I think the XLS file you were comparing is an Excel workbook file, is this correct?

Note that the plug-in that extracts the text part from the Excel workbook file and compares it does not support saving (Unpacking), so it cannot be written back.

**Comment by Artur51** [comment]
With the latest version and with the version I had reported issue for the
java files were processed fine.
For the version, I had reported an issue for I was able to use
packing/saving back with the manual mode.
It seems the solution I used before is described here.
https://sourceforge.net/p/winmerge/bugs/1745/
it says that there was a workaround to have save when settings are set to
manual.
Now with the latest version, I cannot save xls files with any settings.
If it is possible, please, point me what should be adjusted to have merge
save working for xls.
Or if there is an issue, please fix it on your end.

Thank you a lot!


вт, 21 сент. 2021 г. в 13:55, Takashi Sawanaka ***@***.***>:

**Comment by Artur51** [comment]
maybe it is possible to implement custom packing with some library
https://libxlsxwriter.github.io/
Hope it helps.

ср, 22 сент. 2021 г. в 13:00, Artur Zuravljov ***@***.***>:

**Comment by sdottaka** [comment]
As mentioned earlier, the plug-in for .xls files that comes with WinMerge does not support packing, so you cannot write back to it. This is the same for older versions. 

It can, however, be saved as a text file, as indicated by the dialog on saving. (I assume you don't want that...)

I'm glad that the problem of not being able to save java files in Automatic Predifier/Unpacking mode has been solved. 
There is a duplicate issue #770 on packing support for .xls files, so I close this issue.
