### ISSUE TITLE
Feature request: Add "Copy current [line/individual change] [to/from] [Left/Right]" in Merge functions

### ISSUE THREAD

**Issue by dmz73vu** [WinMerge/winmerge#463]
Currently Merge functions exist to Copy [from/to] [left/right] but those functions operate on the whole block of changes.
Often there are individual lines or changes that should be copied and the rest of the changed block should be ignored.
It would be nice to be able to copy those changes without manually editing the file.

**Comment by sdottaka** [comment]
Implemented by PR #642
