### ISSUE TITLE
Files are not being filtered properply

### ISSUE THREAD

**Issue by zxa4fd** [WinMerge/winmerge#471]
I am trying to only view xml files, but it is showing [other](https://imgur.com/OKJsCqi) filetypes - folders to be exact -  as well. How can I fix this?

**Comment by sdottaka** [comment]
Specify "*.xml" for "Folder: Filter" in the "Select Files or Folders" window and compare folders as shown below.

![image](https://user-images.githubusercontent.com/98126/98536223-c5129680-22ca-11eb-82ea-89df5212bd27.png)

If you see a lot of subfolders, you may want to disable Tree Mode as follows.

![image](https://user-images.githubusercontent.com/98126/98536260-d9569380-22ca-11eb-97b9-e26fbe8fcaa0.png)

**Comment by zxa4fd** [comment]
Hello, I am filtering with java but it still [showing other files ](https://imgur.com/qW5JTNC)

**Comment by sdottaka** [comment]
If you use the "Exclude Souce Control" filter as shown below, the contents of the .git directory will be ignored.
However, with the above method, only * .java files or * .xml files cannot be displayed, but if you sort by extension as shown below, the file extensions you are interested in will be aggregated and displayed. 

![issue471](https://user-images.githubusercontent.com/98126/98552744-2db93d80-22e2-11eb-84f4-01ca91c365ce.gif)

If you want to ignore the .git directory and see only the * .java files, you need to create a new file filter.

**Comment by zxa4fd** [comment]
> If you use the "Exclude Souce Control" filter as shown below, the contents of the .git directory will be ignored.
> However, with the above method, only * .java files or * .xml files cannot be displayed, but if you sort by extension as shown below, the file extensions you are interested in will be aggregated and displayed.
> 
> ![issue471](https://user-images.githubusercontent.com/98126/98552744-2db93d80-22e2-11eb-84f4-01ca91c365ce.gif)
> 
> If you want to ignore the .git directory and see only the * .java files, you need to create a new file filter.

It doesn't seem to work:

![8p7sxCpwm1](https://user-images.githubusercontent.com/16448415/98649314-6d2f6a80-2372-11eb-92fe-a52081525bad.gif)

**Comment by sdottaka** [comment]
The "Exclude Source Control" filter is a filter that ignores .git directories. I think applying this has significantly reduced the number of folders you see, but haven't you achieved your goal yet?

If so, please create a filter.

Click [Too]-> [Filters ..] menu item and click the [New] button to create a filter with the following contents and try using this filter.

~~~
name: Java loose filter
desc: Java loose filter

def: include

f: \.class$

d: target$
d: \.git$
d: \.settings$
~~~

This filter ignores * .class files and ignores the target, .git, .settings folders.

If this setting is not enough, edit this filter to adjust it.


![image](https://user-images.githubusercontent.com/98126/98691328-45abc280-23b1-11eb-8c0b-cb10ef313ed4.png)

**Comment by zxa4fd** [comment]
Thanks
