### ISSUE TITLE
Ctrl+Alt+Right shortcut not working

### ISSUE THREAD

**Issue by stealthier** [WinMerge/winmerge#473]
The Copy to Right and Advance Ctrl+Alt+Right shortcut keyboard doesn't seem to work anymore.

The Alt+Right shortcut works, but doesn't advance of course.  The Copy to Right and Advance menu item works.  But Ctrl+Alt+Right does nothing.

Bug?  It's been this way for a while.

**Comment by sdottaka** [comment]
I couldn't reproduce this issue.

Are you using Intel Graphics?
If so, it may be the following problem.

https://stackoverflow.com/questions/33801165/navigation-back-and-forward-not-working-at-intellij-idea

https://intellij-support.jetbrains.com/hc/en-us/community/posts/207031055-ctrl-alt-left-suddenly-not-working-?page=1#community_comment_360002201359

**Comment by stealthier** [comment]
I do have Intel Graphics and this is a new dev machine, I didn't notice the issue only affects the new machine.  It works on my home computer.

Shortcuts can't be remapped in WinMerge.  The hotkeys are disabled in the Intel Graphics control panel but it still seems to intercept them as reported here https://superuser.com/questions/373832/disable-alt-arrow-display-flip-keyboard-shortcut and in a lot of other posts (bad).  I've tried remapping the Intel hotkeys but it still seems to intercept the old ones, but I'll try that again.

Thanks for the help, I wouldn't have figured this out.
