### ISSUE TITLE
Feature Request: Move To Next File option while comparing files

### ISSUE THREAD

**Issue by jschof** [WinMerge/winmerge#475]
While comparing files when you reach the last difference and try to go to the next difference you are prompted with the option to move to the next file. This is fantastic but I would like to go to the next file at any time.

I don't see a menu item for this feature. It would be nice if it could be added there and optimally a button added as well.

To complete the feature it would be nice to also be able to navigate to the 1st, previous, last file similar to what you can do with differences.

Thanks!

**Comment by sdottaka** [comment]
If you don't want to see the message box, please check the [Don't ask this question again] checkbox above the message box and click [Yes] button.

![image](https://user-images.githubusercontent.com/98126/99136311-859bcf80-2667-11eb-9737-9db4811aa364.png)

**Comment by jschof** [comment]
Thanks but I have no problem with the prompt. I just want to be able to skip to the next file without having to go to the bottom of the file first and then going to the next difference. 

I understand that I can get the result i want with the click of 2 buttons but it would be much friendlier to just have to click on a single button to achieve this.

**Comment by sdottaka** [comment]
sorry. I misread it.

**Comment by jschof** [comment]
Np, I appreciate you trying to help nonetheless.

**Comment by sdottaka** [comment]
Implemented by PR #561
