### ISSUE TITLE
feature request / info

### ISSUE THREAD

**Issue by HartLarsson** [WinMerge/winmerge#477]
Hi,

is there a way to compare 2 folders and subfolders and create a 3rd folder with only the structre necessary (folders & files) that are different?

for example:

```
Folder1
   folderA
      file1.txt
      file2.txt
   folderB
      file3.txt
      file4.txt
```

```
Folder2
   folderA
      file1.txt
      file2.txt
   folderB
      file3.txt
      file4.txt
```

file2.txt and file4.txt are different so i need a output diff folder like:

```
Folder_diff
   folderA
      file2.txt
   folderB
      file4.txt
```

I've tried to find a solution but i was not able to understand if winmege is able to do that.

thanks

**Comment by sdottaka** [comment]
Unfortunately, it doesn't have the exact features, but please try the following:

- Compare folders.
- Uncheck View → Tree Mode menu item
- Sort by Comparison result column
- Select different files
- Right-click → Click Copy →'Left to ... or' Right to ...' menu item


![issue477](https://user-images.githubusercontent.com/98126/99160577-3370b200-272c-11eb-9ab1-e131f4207e1f.gif)

**Comment by HartLarsson** [comment]
@sdottaka your way is perfect! is exactly the result i need! thank you so much!
