### ISSUE TITLE
Sorting on Comparison Result being done incorectly

### ISSUE THREAD

**Issue by click-click** [WinMerge/winmerge#483]
When I sort on the comparison result column, the entries are not being grouped together. Winmerge2011 does it correctly. 
![winmerge](https://user-images.githubusercontent.com/8570365/99824060-73cd9700-2b55-11eb-9c8f-96f7a80dbc5d.png)

**Comment by sdottaka** [comment]
Fixed by commit 96c1d3e

Thank you for the report.

**Comment by Thorin-M** [comment]
This problem has returned in version 2.16.10 and 2.16.12.

**Comment by sdottaka** [comment]
I couldn't confirm that the problem started to occur again.

Could you elaborate a little more?

**Comment by Thorin-M** [comment]
Hi!
I'm sorry about the delay...
I use WinMerge v2.16.16.0 x64 Swedish language.
When I'm diffing three folders I get this problem.
The files that differs between the folders are separated by files that isn't different:
![image](https://user-images.githubusercontent.com/40067359/148236888-6a28cb28-d2f8-4d09-9a94-008cc1b4df80.png)
Older versions of WinMerge kept the diffing files together, putting them either on top of or beneath the files that is equal.

**Comment by sdottaka** [comment]
Thank you for your report.
I have confirmed that there is a problem when comparing three folders.
I have fixed this issue in commit 0e55f09.

**Comment by Thorin-M** [comment]
Thank you!
Built and tested latest revision, and it looks good!
![image](https://user-images.githubusercontent.com/40067359/148519480-eff90410-c9b6-41a9-8883-2168cf6324b0.png)
