### ISSUE TITLE
Save compare options in project file

### ISSUE THREAD

**Issue by bkisdi** [WinMerge/winmerge#489]
The `Save Project...` operation should save the compare options set by the top right `Options...` button into the project file (`.WinMerge`) - and the  `Open Project...` should restore them, of course.

(This is a feature request, but I can't label it :(. )

**Comment by ranjwarrior** [comment]
Looking for additional comments/clarifications - Based on my understanding of current WinMerge behavior, this is how most IDEs/Editors work. Project settings are saved separately from global settings. Some issues in combining both and implementing this feature are:
1. When opening multiple project files global settings will be overwritten by the last opened project
2. If an existing compare was completed with current global settings and a new project that overwrites current settings are opened, user will not know options used in the first compare

If this is to be implemented, should the project file (xml format) and the settings file (ini format) be combined into xml format when saving? Or, these can be saved separately together into a zip format (with the xml and ini files independently) and upon open, imported separately.

**Comment by sdottaka** [comment]
Implemented by PR #915
