### ISSUE TITLE
Winmerge crashes consistently when deleting files

### ISSUE THREAD

**Issue by jrmain** [WinMerge/winmerge#491]
Up until the last couple of weeks, I never had problems like this with Winmerge; it's always been very reliable. Thanks for that!

But recently, when comparing folders, if I select several that are 'only on the right side', right click, and choose to delete them on the right side, Winmerge crashes.

After this happened earlier today, I compared the same folders and again tried to delete those same folders, and again Winmerge crashed.

When this happens, the selected folders are not deleted.

Not sure if it matters, but I usually perform comparisons like this by right-clicking a folder in Explorer and choosing 'Compare To' , then right-clicking the other folder and choosing 'Compare'.

I'm running Winmerge 2.16.8.0, currently the latest version. According to my notes, the last time I updated Winmerge was September 4, 2020, but it's possible I failed to record subsequent updates.

I've attached the configuration log as requested.
[WinMerge.txt](https://github.com/WinMerge/winmerge/files/5604655/WinMerge.txt)

I also tested this by comparing two folders that were identical except for a small text file in a new folder in one of the folders. When I right-clicked the 'right side only' folder in Winmerge and selected 'Delete on right side', I got a message: 'Out of Memory'. After clicking the OK button on the error dialog, Winmerge became unresponsive and started using 100% of one CPU core. I had to terminate it.

**Comment by sdottaka** [comment]
I haven't been able to reproduce this bug yet.

I would appreciate it if you could let me know the conditions for reproducing the bug.

**Comment by jrmain** [comment]
What kind of additional information are you looking for? Running processes? A screencast of the sequence of steps leading up to the problem?

**Comment by jrmain** [comment]
Here's the app crash report for the most recent crash.
[WinmergeAppcrashReport.txt](https://github.com/WinMerge/winmerge/files/5610446/WinmergeAppcrashReport.txt)

**Comment by sdottaka** [comment]
Thank you for the information.

I tried to reproduce the bug in Windows 8.1 on a virtual machine using your WinMerge.txt settings, but the bug could not be reproduced.

Can you tell me if you have the following information?

-　WinMergeU.exe.*.dmp file in %appdata%\local\CrashDumps 
-　The name of the compared folders and the path name of the file you were trying to delete

**Comment by jrmain** [comment]
I attached a ZIP file containing three dump files.
[WinMergeU.exe.13716.zip](https://github.com/WinMerge/winmerge/files/5611986/WinMergeU.exe.13716.zip)

Folders I'm comparing:
F:\Download\ISS\Bazar_Wordpress_Theme_3.15.0\bazar\bazar-child
F:\Download\ISS\_bazar-child_from_dev_site

Folder (and the file it contains) that I'm trying to delete:
F:\Download\ISS\_bazar-child_from_dev_site\test
F:\Download\ISS\_bazar-child_from_dev_site\test\test.txt

**Comment by sdottaka** [comment]
Now I can reproduce the problem with your information.
There was a problem under the following conditions.

- Enable Include Subfolders option
- Non-tree mode
- When a folder containing a file is deleted

I've fixed the bug with commit 44dd52a.

Thank you for the report!

**Comment by jrmain** [comment]
Excellent! Happy to help. Looking forward to the next release.
