### ISSUE TITLE
Line length formatted manual source (DocBook XML) is not convenient to update Japanese manual

### ISSUE THREAD

**Issue by Shun-Tsukamoto** [WinMerge/winmerge#499]
Currently, the manual source (ex. Docs\Manual\EN\Compare_files.xml) is formatted based on the line length limit. 

I just thought to update the Japanese manual and I found it is not convenient to do because of the following two reasons.
- It's hard to compare languages because line breaks prevent from doing the paragraph-to-paragraph comparison.
- Line breaks cause unnecessary whitespaces shown in the result html (Japanese words are not separated by whitespaces)

This style was introduced by the very early commit 3240ecbe but I don't find a clear reason. Is there any problem to change this style?

Suggestion
One paragraph is in one line.

BTW, what xml editor do you use? Is there any recommended editor that is compatible with the current formatting style?

**Comment by sdottaka** [comment]
I don't disagree with "One paragraph is in one line.", But I welcome the Pull Request because I couldn't find a good XML formatter.

> BTW, what xml editor do you use? Is there any recommended editor that is compatible with the current formatting style?

I'm not using an XML editor. I, too, want to know an editor or formatter that is compatible with the current formatting style.

**Comment by Shun-Tsukamoto** [comment]
I just wrote a small perl script to format it and tried to translate it. But using text-editor was still inefficient. 

Do you have plans to introduce .pot file or something for the manual source xml files?

Now we may want to move this from Issues to Discussions but I don't know how to.

**Comment by sdottaka** [comment]
Unfortunately, we have no plans to do so at this time.
There seem to be some tools to convert XML files to pot files, but I haven't tried them yet.

https://github.com/tomschr/xml2po-ng
https://github.com/KDE/poxml

I'll try it if I have time, but of course, pull requests are welcome.

**Comment by sdottaka** [comment]
In PR #1994 user manual translations can be managed in PO files.
