### ISSUE TITLE
swap panes not working for 3 file comparison....

### ISSUE THREAD

**Issue by 4evermaat** [WinMerge/winmerge#507]
The swap panes feature only works properly with 2-file comparisons.   3 file comparisons, the middle file always remains the same when trying to swap.   I cannot swap middle file.   

The problem is that I cannot customize the middle file when initiating the comparison from windows explorer (selecting 3 files in windows explorer, and then using context menu to launch in WinMerge).

Would be nice to drag/drop OR to pop up (drop-down) a menu that would allow user to customize which file goes into which pane, without having to start over with new manual comparison.

Please fix this.

**Comment by ranjwarrior** [comment]
I can work on this and submit a PR, unless someone is already working on this. My proposal is:
1. Modify the View -> Swap Panes to View -> Swap Panes -> <3 new menus Swap 1-2, Swap 2-3 and Swap1-3>
2. The Swap Pane functionality (currently only swaps first and last) will account for the file index and swap the panes between fromIndex and ToIndex as long as ToIndex >2
Will wait for confirmation before proceeding (sorry am new here)
![SwapPanes](https://user-images.githubusercontent.com/43297179/103427328-edf63000-4b85-11eb-9c2a-41b0d2fbe28a.png)

**Comment by sdottaka** [comment]
Great! We welcome your pull requests.

**Comment by ranjwarrior** [comment]
Created the PR - sorry if I missed anything. Also I don't seem to have the permission to link the PR to this issue. Thx.

**Comment by sdottaka** [comment]
Fixed by PR #533

**Comment by ranjwarrior** [comment]
Thank you. I see I missed some changes (the translation files, and also
some code - sorry). Appreciate it if you can provide some guidelines to
follow in each commit, and I can try to get a better commit next time.
Thx.

**Comment by sdottaka** [comment]
There was nothing wrong with it.
I had to update the .po file because some strings that needed to be translated were added, but the .po files are updated automatically at build time, so it's not a hassle.
