### ISSUE TITLE
Windows XP Pro SP0 vs Requirements

### ISSUE THREAD

**Issue by ILW000** [WinMerge/winmerge#515]
Non-compliance with current "requirements", posted on [main site](https://winmerge.org/downloads/?lang=en) (_"32-bit installer: Microsoft Windows XP or newer"_). 

2.16.8 x86 installer gave an error about registration of some dll. WinMerge did not start correctly after installation.

2.12.2 installer worked perfectly. And WinMerge did start correctly after installation.

**Comment by sdottaka** [comment]
I've tested it using modern.ie's Windows XP SP3 virtual VM, which was distributed by Microsoft a long time ago, so I think it should have been written as Windows XP SP3.

**Comment by sdottaka** [comment]
Fixed by commit https://github.com/WinMerge/website/pull/22/commits/f57c059ea5e643a1a1498e9ed63c8545c869019e
