### ISSUE TITLE
Crash when generating patch

### ISSUE THREAD

**Issue by wblondel** [WinMerge/winmerge#521]
Hello,

I am using WinMerge 2.16.8.0 on Windows 10 v1809 build 17763.1637.

I can't generate a patch, it crashes every time with no error.
My two files are on my local disk and are relatively small, only 2.35MB.
The paths to the files don't have any accented characters.

Below are the two files (I zipped them to reduce the size, but I compare the unzipped files)
[Deces-1970-source.zip](https://github.com/WinMerge/winmerge/files/5740381/Deces-1970-source.zip)
[Deces-1970-corrected.zip](https://github.com/WinMerge/winmerge/files/5740382/Deces-1970-corrected.zip)

Is there a log file I can check?

Thank you

[WinMerge.txt](https://github.com/WinMerge/winmerge/files/5740388/WinMerge.txt)

**Comment by sdottaka** [comment]
Fixed by commit 41ec039

It seems to crash when the "Ignore carriage return differences (Windows/Unix/Mac)" option in the Patch Generator dialog is enabled.

Thank you for your report.
