### ISSUE TITLE
Compare by Bitrate

### ISSUE THREAD

**Issue by MoistGaming** [WinMerge/winmerge#525]
I feel like this would be an amazing improvement to get added. 
i am a modder for a game, and one of the things that i have to deal with is that i have to make sure the Audio files are in the correct bitrate with the games audio files. but its such a pain having to manually compare every audio file's bitrate, some ranging from 352, 705, 1411 bitrates.

I looked for a bit at other File/Folder compare/merger applications, and so far none of them offer a Bitrate tab to compare the file's bitrates between files.

If this was added, it would be seriously helpful to anyone dealing with Audio files, Voice Packs, etc.

**Comment by sdottaka** [comment]
In WinMerge version 2.16.16, file properties provided by the Windows Property System can now be added as columns in the folder comparison window.

Bit rates for audio files can also be compared using the above.


![image](https://user-images.githubusercontent.com/98126/142758933-e39d2486-74db-497c-ac72-e2bd8263f219.png)

![image](https://user-images.githubusercontent.com/98126/142758924-741f246f-15a9-4b12-8c76-f0cc6069c2fe.png)

![image](https://user-images.githubusercontent.com/98126/142758874-6df3f148-d9c9-4305-a0e2-8975b2673842.png)

![image](https://user-images.githubusercontent.com/98126/142758913-a18690b5-5085-4b6d-a085-cafca6d0d4c7.png)

![image](https://user-images.githubusercontent.com/98126/142759025-7c870b5e-47ec-4aa1-9ce7-739ad8a28405.png)
