### ISSUE TITLE
[feature request] Add options to command line to change "compare methods" 

### ISSUE THREAD

**Issue by glhez** [WinMerge/winmerge#530]
Hello,

In the WinMerge 2011 fork, I had requested an option to provide a compare method on the command line : https://github.com/datadiode/winmerge2011/commit/97438d7067b36317b60a7fb545fa0dbe1567d47b (I put the commit for reference, but I don't think the commit can simply be cherry picked).

My use case is simple : I've got heavy file (>200M) that I don't want to fully compare, only to determine if there are missing files. 

If I want to do that with WinMerge 2.16.8.0, I must select the folder I want to compare, then select the comparison method. 

The same could be done for other options (whitespaces, carriage returns, ...).

**Comment by sdottaka** [comment]
I think this option should be added, but even with WinMerge 2.16.8, you can specify it in a way that is not described in the manual.
The following is an example of comparing with the Modified Date and Size compare method.

`"c:\Program Files\WinMerge\WinMergeU.exe" /r /cfg CompMethod2=4 path1 path2`

**Comment by glhez** [comment]
That's fine as a workaround for me.

What's the values for CompMethod2 ? 
Or perhaps the index is the same than one in the UI under Compare method? (and 5=Size).

**Comment by sdottaka** [comment]
>What's the values for CompMethod2 ?
>Or perhaps the index is the same than one in the UI under Compare method? (and 5=Size).

 CompMethod2=0: Full Contents
 CompMethod2=1: Quick Contents
 CompMethod2=2: Binary Contents
 CompMethod2=3: Modified Date
 CompMethod2=4: Modified Date and Size
 CompMethod2=5: Size

**Comment by sdottaka** [comment]
Implemented by commit 99aaa68
