### ISSUE TITLE
WinMerge crashes with mouse double click

### ISSUE THREAD

**Issue by Mr-Update** [WinMerge/winmerge#531]
- WinMerge crashes with mouse double click in the red box (1.)
Requirements: 2 panes, window size or full screen 
No crash with 3 panes.

![Crash](https://user-images.githubusercontent.com/37781396/103426549-98884600-4bba-11eb-8377-a56470c6b656.png)

- There are also minor problems with double-clicking under the status bar:
Requirements: 2 or 3 panes, window size or full screen 
2. Go to (for left file)
3. Codepage
4. Convert Line Endings to (for left file)
5. RO (for left file)
6. Go to (for right file, for middle file with 3 panes)
7. Codepage (without file modification) resp. Save modified files? (after file modification)
8. Convert Line Endings to (for right file, for middle file with 3 panes)

![RO](https://user-images.githubusercontent.com/37781396/103426600-f2890b80-4bba-11eb-9d63-a6cd7dcd257b.png)
- Without "Split Vertically", there is not enough room for RO.

Thank you for your great work! Have a great and happy new year!

**Comment by sdottaka** [comment]
Fixed by commit 364cb99 and ea1179f

Thank you for the report.
