### ISSUE TITLE
Button scaling not working on high res monitors

### ISSUE THREAD

**Issue by eykamp** [WinMerge/winmerge#534]
Button icons are not scaling properly on a high res monitor, as shown in the following pic:

![image](https://user-images.githubusercontent.com/1133323/103447202-c7df9700-4c3c-11eb-9479-5186457420f8.png)

From version 2.16.8.0 X64
On Win10, obviously.

**Comment by sdottaka** [comment]
This issue has been fixed in version 2.16.9.

https://github.com/WinMerge/winmerge/releases/tag/2.16.9
