### ISSUE TITLE
Copy Folder does not copy subfolders and I don't see any option for it

### ISSUE THREAD

**Issue by LetsGoIslanders** [WinMerge/winmerge#537]
I did a folder comparison and wanted to copy a Left Only folder to the Right by using Copy Right on the toolbar.  It only copied the first level folder, but not the subfolder.  I couldn't find any option to copy subfolders.  Am I missing something?

**Comment by sdottaka** [comment]
If the subfolders of the copied folder are not copied, it is a bug. However, in the current implementation, after copying, it may appear uncopied. Isn't it displayed correctly when I press F5 to redisplay it?

**Comment by LetsGoIslanders** [comment]
Oh, I didn't check.  I assumed the GUI was correct.  Next time I will check if it actually copied the subfolders.
Will the GUI issue be fixed?

    On Sunday, January 3, 2021, 06:09:21 AM EST, Takashi Sawanaka <notifications@github.com> wrote:  
 
 


If the subfolders of the copied folder are not copied, it is a bug. However, in the current implementation, after copying, it may appear uncopied. Isn't it displayed correctly when I press F5 to redisplay it?

**Comment by sdottaka** [comment]
The GUI issue has been fixed with commit 4e39527.
