### ISSUE TITLE
Substiturions vs. Substitutions

### ISSUE THREAD

**Issue by Mr-Update** [WinMerge/winmerge#551]
![Filter](https://user-images.githubusercontent.com/37781396/104376761-c6a84700-5525-11eb-914f-645cc29d45bc.png)

With the original German.po (`Substiturions`)

`msgid "The pair is already present in the list of Ignored Substiturions"`
`msgstr "Das Paar ist bereits in der Liste der ignorierten Ersetzungen vorhanden."`

I see:

![already1](https://user-images.githubusercontent.com/37781396/104376823-d889ea00-5525-11eb-8f10-8a7313c31eea.png)

With the modified German.po (`Substitutions`)

`msgid "The pair is already present in the list of Ignored Substitutions"`
`msgstr "Das Paar ist bereits in der Liste der ignorierten Ersetzungen vorhanden."`

I see:

![already2](https://user-images.githubusercontent.com/37781396/104376857-e2abe880-5525-11eb-9882-7ebbd1420420.png)

**Comment by sdottaka** [comment]
Fixed by commit 03c3499 

Thank you for the report.
