### ISSUE TITLE
Update Slovenian translation

### ISSUE THREAD

**Issue by JadranR** [WinMerge/winmerge#553]
Please, allow Me to update Slovenian translation of WinMerge

Best regards,
Jadran

**Comment by JadranR** [comment]
Never Mind. here is updated Slovenian.PO file, per date 13.01.2021.

Best Regards,
Jadran Rudec

[Slovenian.zip](https://github.com/WinMerge/winmerge/files/5806599/Slovenian.zip)

**Comment by sdottaka** [comment]
Applied by commit 4d0f225

Thank you!
