### ISSUE TITLE
 Link error when building VCPP plugin DisplayXMLFiles with Visual Studio 2019 16.7.7

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [WinMerge/winmerge#555]
I get the following linker error
LINK : fatal error LNK1104: cannot open file 'PocoFoundationmtd.lib'
when building the project Plugins\src_VCPP\DisplayXMLFiles from the solution VCPPPlugins.vs2017.sln (In all solution configurations e.g. Unicode Debug x64) with Visual Studio 2019 16.7.7
Seems that the Project\Linker\General\Additional Library Directories are wrong.

**Comment by sdottaka** [comment]
Fixed by commit 8d140c7
Thank you for the report
