### ISSUE TITLE
Link warnings when building VCPP plugin DisplayXMLFiles with Visual Studio 2019 16.7.7

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [WinMerge/winmerge#558]
I get the following warnings when building VCPP plugin DisplayXMLFiles with Visual Studio 2019 16.7.7
DisplayXMLFiles.def : warning LNK4222: exported symbol 'DllCanUnloadNow' should not be assigned an ordinal
DisplayXMLFiles.def : warning LNK4222: exported symbol 'DllGetClassObject' should not be assigned an ordinal
DisplayXMLFiles.def : warning LNK4222: exported symbol 'DllRegisterServer' should not be assigned an ordinal
DisplayXMLFiles.def : warning LNK4222: exported symbol 'DllUnregisterServer' should not be assigned an ordinal
These functions should not be exported by ordinal, see [Linker Tools Warning LNK4222](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-warning-lnk4222?view=msvc-160)

**Comment by sdottaka** [comment]
Fixed by commit 7fab57d
Thank you for the report.
