### ISSUE TITLE
Some more files should be added to the .gitignore file

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [WinMerge/winmerge#559]
*.exp
*.lib
*_i.c
*_p.c
dlldata.c
DisplayBinaryFiles.h
DisplayXMLFiles.h
EditBinaryFiles.h
HideFirstLetter.h
IgnoreColumns.h
IgnoreCommentsC.h
IgnoreFieldsComma.h
IgnoreFieldsTab.h
WatchBeginningOfLog.h
WatchEndOfLog.h

Maybe with path and maybe ShellExtension_i.c and ShellExtension_i.p can be reomoved, because of *_i.c *_p.c.
And *.asm exists twice, so one can be removed.

**Comment by sdottaka** [comment]
Fixed by commit 398b30b
Thank you for the report.

**Comment by Andreas-Schniertshauer** [comment]
Now the following files are in the list of Not Versioned Files that should be ignored also:
Plugins/src_VCPP/DisplayXMLFiles/x64/Release MinSize/DisplayXMLFiles.dll.recipe
Plugins/src_VCPP/DisplayXMLFiles/x64/Release MinSize/DisplayXMLFiles.vs2017.vcxproj.FileListAbsolute.txt
Plugins/src_VCPP/HideFirstLetter/ReleaseMinSize/HideFirstLetter.exp
Plugins/src_VCPP/HideFirstLetter/ReleaseMinSize/HideFirstLetter.lib
Plugins/src_VCPP/HideFirstLetter/x64/Release MinSize/HideFirstLetter.dll.recipe
Plugins/src_VCPP/HideFirstLetter/x64/Release MinSize/HideFirstLetter.vs2017.vcxproj.FileListAbsolute.txt
Plugins/src_VCPP/IgnoreColumns/ReleaseMinSize/IgnoreColumns.exp
Plugins/src_VCPP/IgnoreColumns/ReleaseMinSize/IgnoreColumns.lib
Plugins/src_VCPP/IgnoreColumns/x64/Release MinSize/IgnoreColumns.dll.recipe
Plugins/src_VCPP/IgnoreColumns/x64/Release MinSize/IgnoreColumns.vs2017.vcxproj.FileListAbsolute.txt
Plugins/src_VCPP/IgnoreCommentsC/ReleaseMinSize/IgnoreCommentsC.exp
Plugins/src_VCPP/IgnoreCommentsC/ReleaseMinSize/IgnoreCommentsC.lib
Plugins/src_VCPP/IgnoreCommentsC/x64/Release MinSize/IgnoreCommentsC.dll.recipe
Plugins/src_VCPP/IgnoreCommentsC/x64/Release MinSize/IgnoreCommentsC.vs2017.vcxproj.FileListAbsolute.txt
Plugins/src_VCPP/WatchBeginningOfLog/x64/Release MinSize/WatchBeginningOfLog.dll.recipe
Plugins/src_VCPP/WatchBeginningOfLog/x64/Release MinSize/WatchBeginningOfLog.vs2017.vcxproj.FileListAbsolute.txt
Plugins/src_VCPP/WatchEndOfLog/x64/Release MinSize/WatchEndOfLog.dll.recipe
Plugins/src_VCPP/WatchEndOfLog/x64/Release MinSize/WatchEndOfLog.vs2017.vcxproj.FileListAbsolute.txt

May be by using
```
Plugins/**/x64/
Plugins/**/Release*
Plugins/**/Debug*
```

**Comment by sdottaka** [comment]
Oops! Fixed by commit 91db705
