### ISSUE TITLE
Updated Slovenian translation of WinMerge, per date 19.01.2021

### ISSUE THREAD

**Issue by JadranR** [WinMerge/winmerge#565]
Updated Slovenian translation of WinMerge, per date 19.01.2021

[Slovenian WinMerge 2.16.9_20210119.zip](https://github.com/WinMerge/winmerge/files/5834485/Slovenian.WinMerge.2.16.9_20210119.zip)

Best Regards,
Jadran

**Comment by sdottaka** [comment]
Committed at 0ebc9ef9e8418e43d6e0bcbfeea6292beebc4e85

Thank you!
