### ISSUE TITLE
BUG: Doesn't respect "Don't ask this question again" checkbox when comparing large files

### ISSUE THREAD

**Issue by vertigo220** [WinMerge/winmerge#574]
When comparing large files, it says showing the contents requires a very large amount of memory and asks if you want to just show the comparison results. When checking the box to not ask again, instead of not showing this warning anymore, it still shows every time a comparison is done. I keep checking the box, and it keeps showing.

W10x64
2.16.8.0x64

**Comment by sdottaka** [comment]
Fixed by commit 87b7dc3

Thank you for the report.
