### ISSUE TITLE
How to close a project?

### ISSUE THREAD

**Issue by jayjupdhig** [WinMerge/winmerge#575]
Can't see any entries in "File" menu list. I.m.o, the only one way seems to be to exit an restart.

Thx for feedback.

**Comment by sdottaka** [comment]
I may not understand the meaning of your question exactly, but if you just want to close the child window, select the Window-> Close menu.

**Comment by jayjupdhig** [comment]
Oh, thx, i was thinking the "close project" must be in in the "File" menu... but it isn't ;-)
