### ISSUE TITLE
TrendMicro identified as a virus WinMerge-2.16.10-x64-Setup.exe

### ISSUE THREAD

**Issue by ericharris76** [WinMerge/winmerge#604]
TrendMicro identified WinMerge-2.16.10-x64-Setup.exe as a virus.

Attached is the export from TrendMicro, renamed so the .csv file ends in .txt:
[Viruses.csv.txt](https://github.com/WinMerge/winmerge/files/5922647/Viruses.csv.txt)

**Comment by sdottaka** [comment]
Where did you download the file?

virustotal.com shows that TrendMicro's scan engine reported the file as Undetected.

https://www.virustotal.com/gui/file/6e9cd0d92eb721bd40974de4cc1cfb0b69e497dcfffbbc50638cf931603247cb/detection

**Comment by ericharris76** [comment]
Got it from sourceforge.net.Don't recall the date, but it was fairly recently.  If the attachment is to be believed, it was 1/30/2021 12:52 AM.  That might be CDT, or UTC.   -Eric-----Original Message-----

**Comment by sdottaka** [comment]
I reported it as a False Positive at the URL below.

https://www.trendmicro.com/en_us/about/legal/detection-reevaluation.html

Just in case, could you download WinMerge-2.16.10-x64-Setup.exe from the following URL and compare it with the file downloaded from sourceforge.net?

https://github.com/WinMerge/winmerge/releases/tag/v2.16.10

**Comment by ericharris76** [comment]
Thank you for reporting it.I would compare it to the one I downloaded, but TrendMicro deleted it, rather than quarantining it.  (I probably ought to change that setting.)  Or maybe I selected that, when prompted.-----Original Message-----

**Comment by sdottaka** [comment]
I will close this issue for now. If TrendMicro still detects the WinMerge installer as a virus, please reopen it.

**Comment by ericharris76** [comment]
Thank you for following up on this.

TrendMicro is fine with this file now.    -Eric


Alternate e-mail: ***@***.***
-----Original Message-----

**Comment by sdottaka** [comment]
Thank you for confirming!
