### ISSUE TITLE
typeinfoex.h(189): warning C4701: potentially uninitialized local variable 'pTypeLib' used

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [WinMerge/winmerge#606]
You can resolve this by initializing ITypeLib* pTypeLib = nullptr; in function CComTypeInfoHolderModule<nObtainMethod>::GetTI

**Comment by sdottaka** [comment]
Fixed by commit 94567c6 

Thank you for the report. Pull requests are also welcome :)
