### ISSUE TITLE
File is corrupted while saving differences in changed file (Ctrl+S)

### ISSUE THREAD

**Issue by Darkums** [WinMerge/winmerge#607]
In .sql file saved WinMerge replaces:

- % with +ACU-
- " with +ACI-
-  ; with +ADs-
- _ with +AF8-
- = with +AD0-

If corrupted file is opened to check for differences those differences are not showed.

**Comment by Darkazas** [comment]
File is corrupted the same on 2.16.9-x64 and 2.16.10-x64 versions.

**Comment by sdottaka** [comment]
Could you show me a file that can reproduce the bug?

**Comment by Darkums** [comment]
[BarcodeParser_H.sql.txt](https://github.com/WinMerge/winmerge/files/5932550/BarcodeParser_H.sql.txt)

**Comment by Darkums** [comment]
Remove .txt and you got the original.

**Comment by Darkums** [comment]
[BarcodeParser_H.sql.corrupted.txt](https://github.com/WinMerge/winmerge/files/5932562/BarcodeParser_H.sql.corrupted.txt)

**Comment by sdottaka** [comment]
Thank you for attaching the file.

WinMerge uses mlang.dll by default to attempt automatic detection of file encoding.

mlang.dll seems to think that the file encoding of the file is UTF-7 (codepage = 65000).

![image](https://user-images.githubusercontent.com/98126/107039447-43ff6880-6801-11eb-8e99-31fce5d2a7cb.png)

Saving the file as UTF-7 will replace the characters as you reported.

For this reason, the behavior has been fixed at commit d869af4  to replace it with the default encoding if it determines UTF-7.

As a workaround, uncheck the checkboxes listed below in the Codepage category of the Options dialog.


![image](https://user-images.githubusercontent.com/98126/107040895-2a5f2080-6803-11eb-8be6-b7a41fb6ebe7.png)


A file saved in UTF-7 should be able to be recovered by opening the file with WinMerge and saving it in a different encoding as shown below in the File-> File Encoding menu.

![image](https://user-images.githubusercontent.com/98126/107040375-7cec0d00-6802-11eb-9cd8-1668e75b1b6c.png)

Thank you for your report.

**Comment by Darkazas** [comment]
I'm turning this option on\off from time to time (because it works life alpha product). Just didn't check the status bar this time.

**Comment by Darkazas** [comment]
Maybe optional confirmation yes\no message box with detected code page would be appropriate ?

**Comment by sdottaka** [comment]
Most people don't expect the files to be opened in UTF-7. I don't like the message box that appears when I open the files. You can reopen the file in UTF-7 by specifying code page 65000 (UTF-7) from the File-> File Encoding menu item.
