### ISSUE TITLE
[FeatureRequest] README.md + Information about: AppVeyor 

### ISSUE THREAD

**Issue by mlipok** [WinMerge/winmerge#630]
After todays talks which was started here:
https://github.com/WinMerge/winmerge/pull/627#issuecomment-778619471

Please consider to add information about AppVeyor something like this:
"
Installers will be created automatically by AppVeyor when pushing commits to GitHub.
Recent Installer you can find here:
https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts
"

to:
https://github.com/WinMerge/winmerge/blob/master/README.md

**Comment by sdottaka** [comment]
I changed it to go to https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts when clicking the status badge below.

![image](https://user-images.githubusercontent.com/98126/107876715-fffc1a00-6f0a-11eb-80ea-51d8d178bd81.png)
