### ISSUE TITLE
Binary Files reported as different, when identical

### ISSUE THREAD

**Issue by CodeF53** [WinMerge/winmerge#635]
When comparing the textures of minecraft versions 21w06a and 21w07a, many images are flagged as different:
![image](https://user-images.githubusercontent.com/37855219/108291557-afc1c980-714f-11eb-8782-a98faf3bdef4.png)
But, when one clicks into one these images, the program states that the files are identical
![image](https://user-images.githubusercontent.com/37855219/108291665-d2ec7900-714f-11eb-98ec-ded17135bd22.png)

**Comment by sdottaka** [comment]
Perhaps these images are not visually different, but they are different in metadata or compression ratio.

You can see the difference by comparing them as binary files as shown below.

![image](https://user-images.githubusercontent.com/98126/108438169-0800e480-7292-11eb-8c96-348bc86a24bd.png)

If the files are visually the same, and you want them to be considered the same, check the options below and compare.

![image](https://user-images.githubusercontent.com/98126/108438307-5b733280-7292-11eb-8782-78a39c04ae8c.png)
