### ISSUE TITLE
Issue - Syntax Highlighment - AutoIt - variables / operators

### ISSUE THREAD

**Issue by mlipok** [WinMerge/winmerge#641]
I see that dolar sign $ is taken as an operator (for example $QPDF_EXT_PARAM4) 

![image](https://user-images.githubusercontent.com/11089482/108622755-21916000-743b-11eb-8e5e-60455c038a0a.png)

But in AutoIt all strings starting from dolar sign are VARIABLES and ENUM and CONSTANTS .

As far as I understand I think that in:
winmerge/Externals/crystaledit/editlib/parsers/autoit.cpp
before this part:
```
                {
                  DEFINE_BLOCK (nPos, COLORINDEX_OPERATOR);
                  bRedefineBlock = true;
                  bDecIndex = true;
                  goto out;
                }
```
should be added an exception for this case.

**Would somebody add special checking if a string/tokens starts from dolar sign then entire string (for example $QPDF_EXT_ENUMCOUNTER) should use color for User1 ?**

btw. 
I think that the simplest RegExp for catching such strings ( variables in AutoIt ) should start from $ sign and end before any white characters or dot or comma.

EDIT:
I found better way to catching such strings .... tested with PCRE     
`(?i)(\$[\w]+)`
or even better/shorter:
`\$\w+`

![image](https://user-images.githubusercontent.com/11089482/108689717-b78bc000-74f9-11eb-97cb-1cf2d26a3a86.png)

Hope this will be helpfull in solving this issue.

**Comment by mlipok** [comment]
testing data:

```
$QPDF_EXT_121313,
$QPDF_EXT_121313 ,
$QPDF_EXT-121313
$QPDF_ext_121313
some other string

```

**Comment by mlipok** [comment]
Any chance for this little fix?

**Comment by sdottaka** [comment]
Instead of just fixing AutoIt, I would like to add a new color category called Variables and fix other languages as well.

Or I would like to use a library for many languages like https://github.com/ScintillaOrg/lexilla.

**Comment by mlipok** [comment]
https://github.com/WinMerge/winmerge/pull/749
