### ISSUE TITLE
Rar5 support

### ISSUE THREAD

**Issue by vyv03354** [WinMerge/winmerge#644]
Although 7z.dll 19.00 supports Rar5, WinMerge cannot decompress Rar5.
1. Rar5 has a different [signature](https://www.rarlab.com/technote.htm#rarsign) from Rar4:
 RAR 5.0: 0x52 0x61 0x72 0x21 0x1A 0x07 0x01 0x00
 RAR 4.x: 0x52 0x61 0x72 0x21 0x1A 0x07 0x00
2. 7z.dll has distinct CLSIDs for Rar4 (xx=03) and Rar5 (xx=CC) according to `CPP\7zip\Guid.txt`.

But Merge7z only has an [entry for Rar4](https://github.com/WinMerge/winmerge/blob/21f76716f5a84c128910dbc6c23aa8b8e4696143/ArchiveSupport/Merge7z/Merge7zCommon.cpp#L705). It will have to add an entry for Rar5 such as:
```
DEFINE_FORMAT(CRar5Handler,		CC, "rar", "Rar!\x1a\x07\x01\x00");
```

**Comment by sdottaka** [comment]
Fixed by commit 6dc0456

Thank you for the report.
