### ISSUE TITLE
Option to show "picture identical" column in main window

### ISSUE THREAD

**Issue by ganego** [WinMerge/winmerge#65]
jpeg pictures can be different when you compare them byte-by-byte thanks to different EXIF. Yet the picture itself can be identical when compared without exif. The picture compare shows this information in the statusbar when you open two files.  

I propose also adding an option to show a column in the main window, that will show this information directly for all pictures (maybe also with an option in the "View" menu to toggle showing only/no picture identical files).
Example: https://imgur.com/a/gC115

Thank you.

**Comment by sdottaka** [comment]
Thank you for the request.

A different person had similar requests. Instead of displaying the image comparison result in a new column, it displays the image comparison result in the existing comparison result. I'll think about it.

**Comment by ganego** [comment]
> Instead of displaying the image comparison result in a new column, it displays the image comparison result in the existing comparison result  

This might lead to a problem when you want to actually get a real byte-compare though (too). Having a separate column will give you more information - byte-identical *and* pic-identical - at the same time, which can be beneficial.

>  I'll think about it.  

Thank you.

**Comment by sdottaka** [comment]
I'm sorry it's not the implementation you wanted, but I added the "Enable image compare in folder compare" option to the [Compare/Image] category in the Options dialog. (9230173a0e0a75e7521acaa02ba33f7aa332c84a)

If this option is enabled, the folder comparison will compare image files as images.

If you want to make sure that they are an exact match, disable this option.
