### ISSUE TITLE
Three way merge

### ISSUE THREAD

**Issue by dalexand** [WinMerge/winmerge#66]
Is there a way to start a three way merge with a Meld-like window placement (output results in the middle window)? I have not found a way to do it with a command line.

**Comment by sdottaka** [comment]
# Merge at startup
If you want to merge automatically at startup, please use /am option like below:
~~~
C:\Program Files\WinMerge\WinMergeU.exe /e /ub /fm /am /wl /wr theirs_filepath base_filepath mine_filepath /o merged_file
~~~~
if you want to save merged result to base_filepath, please remove "/o merged_filepath" from above. 

# Merge manually

If you want to merge manually, open three files with WinMerge, set focus to the middle pane and click "Auto Merge" icon on the toolbar.

**Comment by timofonic** [comment]
## **_What about something like the following apps?_**

# Beyond Compare
![image](https://user-images.githubusercontent.com/49494/39092919-3606f798-4617-11e8-8bac-8bc800b843fa.png) ![image](https://user-images.githubusercontent.com/49494/39092936-6b51afa6-4617-11e8-8ad5-6226da97029b.png)


# Diffmerge
![image](https://user-images.githubusercontent.com/49494/39092883-dab84bee-4616-11e8-89d5-096598054543.png) ![image](https://user-images.githubusercontent.com/49494/39092889-f3fefd00-4616-11e8-8398-fda87e2121da.png)

# ECMerge
![image](https://user-images.githubusercontent.com/49494/39092973-0d787800-4618-11e8-8a45-e4411ff50f9f.png) ![image](https://user-images.githubusercontent.com/49494/39092997-56660bcc-4618-11e8-987d-18e326d88f80.png) ![image](https://user-images.githubusercontent.com/49494/39093000-71f8ea58-4618-11e8-970d-695e27b71aa7.png)
![image](https://user-images.githubusercontent.com/49494/39093024-11a4c7ca-4619-11e8-8ddb-6ee647be8e88.png)

# ExamDiff Pro
![image](https://user-images.githubusercontent.com/49494/39093079-b4bf3a62-4619-11e8-88a9-8008f410fce7.png) 
![image](https://user-images.githubusercontent.com/49494/39093091-05b18b96-461a-11e8-9410-242822201ca8.png)

# UltraCompare Professional
![image](https://user-images.githubusercontent.com/49494/39093122-8a7d1b74-461a-11e8-9c2c-f93cd01b3de5.png)
![image](https://user-images.githubusercontent.com/49494/39093156-2581e230-461b-11e8-8453-5228e342e34c.png)

# Araxis Merge Professional Edition
![image](https://user-images.githubusercontent.com/49494/39093173-7e36dcdc-461b-11e8-9009-badee4400a98.png)
![image](https://user-images.githubusercontent.com/49494/39093183-b8e996bc-461b-11e8-849d-cee6b17d35d6.png)

# P4Merge
![image](https://user-images.githubusercontent.com/49494/39093376-2dc8169a-461f-11e8-8286-26523d07445d.png)
![image](https://user-images.githubusercontent.com/49494/39093645-08771db0-4623-11e8-890f-46bc7d89c4dd.png)
![image](https://user-images.githubusercontent.com/49494/39093669-8fe99bb0-4623-11e8-9fbc-9565baf96867.png)

# KDiff3
![image](https://user-images.githubusercontent.com/49494/39093619-78a0e504-4622-11e8-887a-a8d641f2e5e1.png)
![image](https://user-images.githubusercontent.com/49494/39093762-1375c458-4625-11e8-84dc-cee8be404d70.png)

# Meld
![image](https://user-images.githubusercontent.com/49494/39093701-f0424296-4623-11e8-9322-7912e91d2800.png)
![image](https://user-images.githubusercontent.com/49494/39093717-3ebc5592-4624-11e8-8d07-d176c2233c07.png)
![image](https://user-images.githubusercontent.com/49494/39093722-4f29178a-4624-11e8-81d7-56b5985418f1.png)
![image](https://user-images.githubusercontent.com/49494/39093726-5ad62d5c-4624-11e8-8b3f-ec3c0c492889.png)


# DeltaWalker
![image](https://user-images.githubusercontent.com/49494/39093650-2432bdca-4623-11e8-969d-bb97bfcb9495.png)
![image](https://user-images.githubusercontent.com/49494/39093734-8a4787e8-4624-11e8-9985-baccef19b0bb.png)
