### ISSUE TITLE
New Plugin for JSON File Comparation

### ISSUE THREAD

**Issue by CharlesMengCA** [WinMerge/winmerge#662]
Hi,

I created a new plugin for JSON file comparation.  You can find the code here. 

https://github.com/CharlesMengCA/DisplayJSONFiles

Regards,

**Comment by sdottaka** [comment]
Thank you. I have added a link to your plugin on the Wiki page.
https://github.com/WinMerge/winmerge/wiki/External-plugin-links

By the way, for formatting JSON and XML files, I am planning a new type of Formatter plugin.
It will be able to format the file without saving it or only the selected range.

**Comment by Niko2909** [comment]
Hey,

thank you for developing on that tool.

For my purposes, I'm missing a compare as JSON function. 

One solution is, the two files should be compared as JSON objects and not as text files.
The other solution is to format the files in the cache and compare like text files. Here, the position change will also be marked.

Can I do that task with the plugin above? Or is it only for displaying the files?

**Comment by sdottaka** [comment]
> Can I do that task with the plugin above? Or is it only for displaying the files?

This plugin is a plugin that formats and displays JSON files.
