### ISSUE TITLE
Report only differences exclude matches

### ISSUE THREAD

**Issue by zsbook11** [WinMerge/winmerge#665]
I think this a great tool and will be using exclusively for file compare. I would like to have a report that show the line that are different and not the entire file content.

**Comment by sdottaka** [comment]
Select View → Diff Context → 0 lines menu item as shown below to generate the report.

![image](https://user-images.githubusercontent.com/98126/110208996-7cac6380-7ecd-11eb-8b0e-b05e2f54bd8f.png)
