### ISSUE TITLE
UI stops responding when comparing files through context menu

### ISSUE THREAD

**Issue by smfukaya** [WinMerge/winmerge#684]
When I compare 02 (two) simple files through Windows context menu, 9 out 10 times Winmerge UI hangs (even with "Ignore carriage return differences (Windows/Unix/Mac)" option checked). Looks like some kind of looping error (CPU stays at 12% usage).

Winmerge 2.16.10.0 (64 bits)
Windows 10 (64 bits) Version 20H2 Compilação 19042.867

https://user-images.githubusercontent.com/29984055/111149290-753f2700-856b-11eb-9666-ba6b3f8f7a77.mp4

**Comment by sdottaka** [comment]
I couldn't reproduce this bug.

Would you please attach the files used for the comparison and the settings that are displayed when you click [Help] → [Configuration] menu item?

**Comment by smfukaya** [comment]
Please find attached the requested files. It seems that comparing them through the Windows context menu (i.e., right click) triggers the problem. When opening WinMerge first, selecting Open and comparing doesn't seem to trigger the issue.

[WinMerge.txt](https://github.com/WinMerge/winmerge/files/6142857/WinMerge.txt)
[new 7.txt](https://github.com/WinMerge/winmerge/files/6142859/new.7.txt)
[new 8.txt](https://github.com/WinMerge/winmerge/files/6142860/new.8.txt)

I'm also attaching some videos, Windows crash reporting (Werfault) files, and Sysinternals procmon event logs.

https://user-images.githubusercontent.com/29984055/111187573-dfb78d80-8592-11eb-92d8-bf3444bd9548.mp4
https://user-images.githubusercontent.com/29984055/111187578-e0e8ba80-8592-11eb-9d03-0287cedd4217.mp4

https://user-images.githubusercontent.com/29984055/111187603-e7773200-8592-11eb-9d4b-952de4e34481.mp4


[Report.zip](https://github.com/WinMerge/winmerge/files/6142983/Report.zip)
[WinMergeU - procmon.zip](https://github.com/WinMerge/winmerge/files/6142988/WinMergeU.-.procmon.zip)

**Comment by smfukaya** [comment]
Hi @sdottaka,

I renamed this issue and the description. It seems that the problem is related to context menu integration (not with the files EOL difference).

**Comment by sdottaka** [comment]
Thank you for information.
I tried it with the attached files and settings, but I haven't been able to reproduce it yet.

By the way, isn't this bug eliminated by checking "Don't display this message again" in the "The selected files are identical" message box?

**Comment by smfukaya** [comment]
Hi @sdottaka ,

Unfortunately, that option "Don't display this message again" doesn't fix the problem. I tried to attach VS2019 to the process, but TBH, I don't know what I doing (I'm Java programmer, not C++). Think somehow need to hook to the ShellExtensionX64.dll context menu handler because attaching to the process must be to late to catch anything.

If you could give me instructions (for newbies) I may try to attach something useful.

![2021-03-16_13-43-30-VS2019 - attached to process](https://user-images.githubusercontent.com/29984055/111347657-2e7e2980-865e-11eb-995f-3e07fb84f47e.png)

**Comment by smfukaya** [comment]
Hi  @sdottaka ,

Sorry for all the trouble. It was something local to my machine / OS.

I ran `sfc /scannow` and the problem got fixed.

**Comment by sdottaka** [comment]
I would be happy if the problem was solved.

If the bug reappears again, could you please unzip the following file and place the WinMergeU.pdb file created in the same folder as WinMergeU.exe and take the above screenshot again?

https://github.com/WinMerge/winmerge/releases/download/v2.16.10/WinMergeU-2.16.0-x64-pdb.7z

If you use a PDB file, we can know the name of the function that is having the problem, not just the address.

**Comment by smfukaya** [comment]
Sure, will do! Thank you very much!

Best!
