### ISSUE TITLE
Using variable "subcode" in plugins fails

### ISSUE THREAD

**Issue by jrathlev** [WinMerge/winmerge#686]
I could not find any documentation about the variable _subcode_  used in the functions _UnpackFile_ and _PackFile_ but I assume that this is intended to pass a value from unpacking to packing.

Unfortunately this does not work in the current version 2.16.10. Setting it to any fix value, e.g. 0 or 1, in _UnpackFile_ will return an absurd number in _Packfile_. I found different values like 94556916 or 94553484.

**Comment by sdottaka** [comment]
I couldn't reproduce this problem.

I tried changing the source of DisplayXMLFiles.dll as follows, but when PackFile was called, it was displayed as "123".

![image](https://user-images.githubusercontent.com/98126/111326240-be988f00-86af-11eb-8ef4-772899f707cb.png)

![image](https://user-images.githubusercontent.com/98126/111326668-1636fa80-86b0-11eb-9adb-aba96d8630bc.png)

**Comment by jrathlev** [comment]
**Solved!** - This is not an issue of WinMerge.

I am writing a plugin in Delphi and used the interface section of the provided sample _UnpackDFM_.  The declaration of the _PackFile_ function used in this code has a bug:
`function PackFile(const fileSrc, fileDst : WideString;  var pChanged : WordBool; 
  Subcode : Integer) : WordBool; safecall;`

The correct call is
`function PackFile(const fileSrc,fileDst: WideString; var pChanged: WordBool; 
  var SubCode: Integer): WordBool; safecall;`
The parameter _SubCode_ must be declared as _var_.

**Comment by sdottaka** [comment]
Hmm? I changed the source of UnpackDFM without changing the subcode argument as below, I couldn't reproduce the problem.

![image](https://user-images.githubusercontent.com/98126/111472174-0f21f200-876d-11eb-860a-9829de4bbd09.png)

![image](https://user-images.githubusercontent.com/98126/111472047-ef8ac980-876c-11eb-87e3-68cf8480397e.png)

**Comment by jrathlev** [comment]
I found a bug in my _ridl_ file. This file is similar to an _idl_ file in VCPP and is required by Delphi to create a new _tlb_ file. I don't know why this happened, but the declaration for the _pack_ function was wrong concerning the parameter _SubCode_. 
I fixed this and now everything works as it should be.
