### ISSUE TITLE
XML miscompare

### ISSUE THREAD

**Issue by IEales** [WinMerge/winmerge#704]
Sometimes an XML file may have identical sections, but a value swap between them.
WinMerge insists on shifting sections instead of just highlight changes within the lines.
Essentially, a character by character comparison with no section offset is required
![XMLmiscompare](https://user-images.githubusercontent.com/81490069/112734432-ecc56c80-8f02-11eb-8ca2-e02da3cef925.png)

**Comment by sdottaka** [comment]
I think you have enabled the 'Match similar lines' option in the Compare/General category in the Options dialog.
If so, when disabling that option, you'll get what you expect.
Unfortunately, the 'Match similar lines' option often doesn't seem to give the expected comparison results.

**Comment by sdottaka** [comment]
The following fixes have fixed this issue. 

4ddcac25dc4bc0451339ff5816d0d80177223ba9
6da30cdeab4de9a4b5e70e4ca1d59fc2612d0843
98cc2c2e69b627f093be8a2d281a09e12757765a

**Comment by IEales** [comment]
Problem is back in 2.16.18
XML needs a line by line compare and don't search for matching. It's irrelevant in an XML structure

![XMLmiscompare220407_Match](https://user-images.githubusercontent.com/81490069/162251111-c49c9207-56dc-4c56-a11b-817bc276b2c2.png)
![XMLmiscompare220407_NoMatch](https://user-images.githubusercontent.com/81490069/162251135-54c99dcc-2404-4f6d-8248-f7fc1c7f7d34.png)
.

**Comment by sdottaka** [comment]
The same results are obtained with older versions.
WinMerge currently does not understand the structure of XML files and compares them as just a collection of lines of text, which is why it gives such results.
A diff tool such as graphtage would give better results.

https://github.com/trailofbits/graphtage

**Comment by IEales** [comment]
With Match Similar disabled, why not just line by line? - IanOn Apr 7, 2022 16:19, Takashi Sawanaka ***@***.***> wrote:
The same results are obtained with older versions.
WinMerge currently does not understand the structure of XML files and compares them as just a collection of lines of text, which is why it gives such results.
A diff tool such as graphtage would give better results.
https://github.com/trailofbits/graphtage

**Comment by sdottaka** [comment]
The 'Match similar lines' option is a function to match lines in a Diff block after calculating the Diff with the specified Diff algorithm.

Thus, in our example, there are no lines to match in the Diff block, so the Diff result is not affected by the value of the 'Match similar lines' option.

To get good results in this example, we would need to add a tree diff algorithm to WinMerge that understands the structure of the document, or a straightforward algorithm that does not detect inserts and deletes.
