### ISSUE TITLE
Refresh (F5) in WinMerge 2.16.10.0 has no effect when an unpacker plugin is automatically applied

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [WinMerge/winmerge#710]
I have a problem with my unpacker plugin in WinMerge 2.16.10.0:
When the Refresh (F5) button is clicked I did not come across any of the WinMergeScript functions e.g. UnpackFile, UnpackBufferA, ...
I have my plugin activated and I have Plugins → Automatic Unpacking mode enabled.
Pressing Refresh (F5) has no effect.
I need to select "Plugins\Edit with Unpacker" and change "File unpacker" to my plugin and then hit OK, in this case e.g. UnpackFile is called.

**Comment by sdottaka** [comment]
Does Ctrl+F5(Reload) not work?

**Comment by Andreas-Schniertshauer** [comment]
Yes, this works - thanks for the help, I didn't know about Ctrl+F5 it is mot mentioned in the WinMerge Help, in section Plugins there is only F5 mentioned, aha I see in the Appendix A. Shortcut keys Ctrl+F5 is for Reload F5 for Refresh only.
