### ISSUE TITLE
Specify file extensions to compare as XML

### ISSUE THREAD

**Issue by Gitoffthelawn** [WinMerge/winmerge#730]
WinMerge has options that allow the user to specify extensions for CSV, TSV, binary, and images.

How about adding a similar option for specifying XML files?

I have a bunch of files that aren't true XML (they are actually more or less JSON with XML components, but they aren't 100% pure JSON-compliant) that WinMerge really has trouble comparing as they have no CRs or LFs.  But when I use the "Recompare as..." -> "XML" menuitem, the comparison is a bit better as all the XML blocks get recognized.

The files don't have an XML extension (or JSON, for that matter), so having the ability to assign file extensions to XML comparison functionality would be a big help.

Thanks!

**Comment by sdottaka** [comment]
I don't know if the XML data in the JSON file can be formatted well, but in the latest version, the target extension of the PrettyfyXML plugin for formatting XML can be specified as follows

![image](https://user-images.githubusercontent.com/98126/133922157-6547e7df-1b2f-46d5-8c8a-dbf30a08ad8a.png)
