### ISSUE TITLE
Copy confirmation dialog has overlapped Yes/No Button

### ISSUE THREAD

**Issue by yuakihiro** [WinMerge/winmerge#739]
Version 2.16.10 (Locale: ja)
![image](https://user-images.githubusercontent.com/66588792/115194612-a55c8580-a128-11eb-897a-2408759ea2cf.png)
![image](https://user-images.githubusercontent.com/66588792/115194768-de94f580-a128-11eb-8004-94f91b467886.png)
はいbutton and いいえbutton is overlapped

**Comment by sdottaka** [comment]
Fixed by commit 780283e
Thank you for the report.
