### ISSUE TITLE
Highlight moved lines and working with colon-separated text

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [WinMerge/winmerge#740]
Based on the attached image I have 2 questions for correct usage:

a) With Settings "Enable moved block detection" and " Match similar lines" I have this result. How to configure it that e.g. "Compression" and "DateTimeOriginal" are highlighted in the sense "after moving these parts are the same"?
b) Is there a handy way to use files like this - with colon ":" as separator - like CSV tables, to compare parts before the colon and after the colon?
![winmerge_similar](https://user-images.githubusercontent.com/13277944/115273199-8c130380-a13f-11eb-855d-3fc225fbbb34.png)

**Comment by sdottaka** [comment]
Unfortunately, there is no good way to do both.
You can re-compare as a Table as below, but you won't get the results you expect.

![image](https://user-images.githubusercontent.com/98126/115317488-a0461780-a1b6-11eb-8100-15dff35b7574.png)

![image](https://user-images.githubusercontent.com/98126/115317497-a3d99e80-a1b6-11eb-9794-c8f6f1787c7d.png)

**Comment by Pierre-de-la-Verre** [comment]
Thanks.
