### ISSUE TITLE
Icon size

### ISSUE THREAD

**Issue by HeberonYT** [WinMerge/winmerge#746]
Hello. I have searched the documentation, but found no answer.
I would like to increase the size of the toolbar icons, they are very small and sometimes I press buttons that I do not want.
If you could tell me how, I would appreciate it.
![Screenshot_4](https://user-images.githubusercontent.com/13698597/115764294-01165100-a36b-11eb-8e2e-582ea2b2bc9f.png)

**Comment by sdottaka** [comment]
Select the View->Toolbar->Big menu item.

![image](https://user-images.githubusercontent.com/98126/115793539-3ec8b780-a407-11eb-9295-6364251d0a68.png)

**Comment by HeberonYT** [comment]
Muchas gracias, buen hombre!.
