### ISSUE TITLE
ATL: QIThunk - 2 LEAK in plugins e.g. DisplayBinaryFiles and DisplayXMLFiles

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [WinMerge/winmerge#755]
Hello, I get a `ATL: QIThunk - 2         	LEAK    :	Object = 0x0000028A1847D3D0	Refcount = 1	MaxRefCount = 1	CComClassFactory - IClassFactory` reported in the plugins e.g. DisplayBinaryFiles, DisplayXMLFiles after I add 
`
#ifdef _DEBUG
#define _ATL_DEBUG_INTERFACES
#define _ATL_DEBUG_QI
#endif
`
in `StdAfx.h` before `#include <atlbase.h>`
I added these because I was looking for a memory leak in my own plugin, but couldn't find it. It seems that WinMerge did not release all references because one is left in each plugin when `_Module.Term()` is called in `DllMain`. The other plugins I have not tested but I think they have the same problem.
When I add the ATL_DEBUG... code in both plugins I get the following output:
`
QIThunk - 1         	Release :	Object = 0x0000028A1847CA40	Refcount = 0	CComClassFactory - IUnknown
ATL: QIThunk - 2         	LEAK    :	Object = 0x0000028A1847CA40	Refcount = 1	MaxRefCount = 1	CComClassFactory - IClassFactory
Detected memory leaks!
Dumping objects ->
{81} normal block at 0x0000028A1847CA40, 72 bytes long.
 Data: <  o             > 00 D2 6F 19 8A 02 00 00 01 00 00 00 CD CD CD CD 
Object dump complete.
QIThunk - 1         	Release :	Object = 0x0000028A1847D3D0	Refcount = 0	CComClassFactory - IUnknown
ATL: QIThunk - 2         	LEAK    :	Object = 0x0000028A1847D3D0	Refcount = 1	MaxRefCount = 1	CComClassFactory - IClassFactory
The program '[22296] WinMergeU.exe' has exited with code 0 (0x0).
`
I used the the current version 7f07ef11670d3b9d24d9edda53960dc978deae22 for debugging.

**Comment by Andreas-Schniertshauer** [comment]
I found the leak, it is in WinMerge Src\Common\lwdisp.c in function CreateDispatchBySourceAndCLSID, here is missing a call to Release after `if (SUCCEEDED(sc = DllGetClassObject ...:  `piClassFactory->lpVtbl->Release(piClassFactory);`

**Comment by sdottaka** [comment]
Fixed by commit 27bd0d8

Thank you for the report!
