### ISSUE TITLE
Add preference option to clear "Don't ask this question again" CompareLargeFiles choice

### ISSUE THREAD

**Issue by christopher-ursich** [WinMerge/winmerge#772]
When comparing large files, I mistakenly clicked the wrong choice after setting "Don't ask this question again."  I cannot find anywhere in WinMerge's UI to change this preference option.  Please add the ability to do so.

(For myself, I did track down the relevant registry key using the release notes and the commit: https://github.com/WinMerge/winmerge/issues/574.  Deleting `HKCU\SOFTWARE\Thingamahoochie\WinMerge\MessageBoxes\CompareLargeFiles` caused the prompt to appear again.)

**Comment by TBSenseo** [comment]
I would like that the decision from this dialog should go into the regular Options, so that it can be modified later, maybe under a section "Message boxes".

**Comment by sdottaka** [comment]
Implemented in commit 0efa3ba
