### ISSUE TITLE
Line Numbers option

### ISSUE THREAD

**Issue by JonnoWonno** [WinMerge/winmerge#776]
As an _enhancement_, the ability to add line numbers would be great. Clearly as an **option** - so that you could switch it on and off if you so choose. I'm not sure, visually, how this would best be accomplished for each of the compare windows (while also remaining compact).... maybe even something like a watermark behind the content? Otherwise, to demonstrate the concept of my request, consider the line number 'layout' used in MS SSMS 18, or an even better example in Visual Studio 2019's Diff (where the presence of unmatched new lines are also indicated by hatch fill).

**Comment by sdottaka** [comment]
Does View → View Line Numbers menu item meet your requirements?

![image](https://user-images.githubusercontent.com/98126/117025849-3a20cf00-ad36-11eb-9f1d-c91a039a8ae0.png)

**Comment by JonnoWonno** [comment]
It does. Thank you for highlighting where to find that option (both the examples I provided - have the setting under Options).
