### ISSUE TITLE
Error on try to show differences between two different gif

### ISSUE THREAD

**Issue by username1565** [WinMerge/winmerge#784]
1. v2.16.12. Version https://github.com/WinMerge/winmerge/releases/tag/v2.16.12

2. File: winmerge-2.16.12-exe.zip (x86, win32, portable exe).

3. Two folders with different .gif - images.

4. Try to compare this, and see:
![image](https://user-images.githubusercontent.com/39200328/117657742-749cc880-b189-11eb-8098-f636b970faf4.png)

5. Try to open the differences, and see:
![image](https://user-images.githubusercontent.com/39200328/117657805-88e0c580-b189-11eb-8a67-369418f0e5ca.png)

Then, I did try to do this in WinMerge v2.12.4.0
And I see the following thing:
![image](https://user-images.githubusercontent.com/39200328/117658070-d78e5f80-b189-11eb-9171-73142e2304e6.png)
And when this as binary, then comparison is good:
![image](https://user-images.githubusercontent.com/39200328/117658193-fab90f00-b189-11eb-9fa7-94ae9c6844e5.png)

**Comment by sdottaka** [comment]
I could not reproduce this issue.
Would you please attach the contents displayed by clicking the Help → Configuration menu item?

![image](https://user-images.githubusercontent.com/98126/117659809-5cec3100-b1d7-11eb-8ffb-95fb31a55527.png)

**Comment by sdottaka** [comment]
Also, does the problem reproduce with another gif files? If it only reproduces with a specific gif file, could you attach that file?

**Comment by username1565** [comment]
@sdottaka, I did try to compare [this](https://system.data.sqlite.org/downloads/1.0.113.0/sqlite-netFx-full-source-1.0.113.0.zip), and [this](https://github.com/moneymanagerex/System.Data.SQLite/archive/refs/heads/master.zip), according [this issue](https://github.com/username1565/System.Data.SQLite/issues/1),
and I see the some differences in `.gif`-files, there. I do not know what format this have, but this files too old (about 2016-th year), and I see `appcrush` of WinMerge.
So need to switch `.gif`-files, and another images to `binary-format`, as you can see on image, on previous post, and need to do this just to prevent `AppCrush`.

**Comment by username1565** [comment]
@sdottaka , I used portable version of `v2.16.12` from file [winmerge-2.16.12-exe.zip](https://github.com/WinMerge/winmerge/releases/download/v2.16.12/winmerge-2.16.12-exe.zip) (x86, win32, portable exe) from [this release](https://github.com/WinMerge/winmerge/releases/tag/v2.16.12). Maybe problem here.
I runned this on windows x86 (as win32 application).

**Comment by sdottaka** [comment]
- C:\Windows\NOTEPAD.exe does not exist? (Is Windows installed on a drive other than C?)
- What version of OS are you using?
- Does the "disk:Documents and settings/User/My Documents" folder exist?
- If you delete WinMerge\WinIMerge\WinIMergeLib.dll, the gif files will not be compared as an image, so I think it will not crash.

**Comment by username1565** [comment]
@sdottaka 
> `C:\Windows\NOTEPAD.exe` does not exist? (Is Windows installed on a drive other than C?)

Yeap. Another drive.
You can use an environment variables in pathway, something like this `%WINDIR%/notepad.exe`,
or this `%SYSTEMROOT%\notepad.exe` instead of `C:\Windows\NOTEPAD.exe`.
Just try to run: `Win+R` -> `%WINDIR%/notepad.exe`.
Winmerge already can display the text-interpretter, and maybe,
you can run the comparison of this file with empty file, or with the same,
just to show the text, inside winmerge,
and to make the portable-version independent from `notepad.exe`,
or just include this in `zip-file` (this have a small size, and seems, like portable.exe too).
`disk:\WINDOWS\system32\notepad.exe`.

> What version of OS are you using?

Windows XP SP3 (x86). 

> Does the `"disk:/Documents and settings/User/My Documents"` folder exist?

I have `cyrillic symbols` in pathway. Something like this:
`D:\Documents and Settings\РандомныйВасян\Мои документы`
Maybe here is a some problem too.
You can use `%userprofile%` or something like `%appdata%\..\` to open the folder `my documents`.
Maybe you can use the same folder, where zip was been unpacked, or another folder `..blahblah\WinMerge\AppData\`
and get this `folder-path`, as some internal method, like `std::filesystem::current_path`,
even if some another chars contains in pathway, there ( `X:\Documents and settings\ЮзeR少天𓃠\Мои документы\downloads\WinMerge\WinIMerge\WinImerge.dll` ).
And use that folder in `current folder`, instead of using %userprofile%, inside the system,
just to make portable-version, really portable.

> If you delete `WinMerge\WinIMerge\WinIMergeLib.dll`, the `gif` files will not be compared `as an image`, so I think it will not crash.

Yeap. There is some problem, in that dll.
After rename this file, and after I did try to compare two gifs,
I see the differences for this binary files compared as text:
![image](https://user-images.githubusercontent.com/39200328/118927602-94728000-b931-11eb-833b-35a56f5ff587.png)

Maybe you can disable comparison for gif files, and compare this as text, or as hex, inside the recompiled `WinIMergeLib.dll`.

I see the following exception, in `Visual Studio 2010`, on try to compare two gifs, with `WinIMergeLib.dll`:
![image](https://user-images.githubusercontent.com/39200328/118927308-1ca45580-b931-11eb-99d4-ad91f4da6dd7.png)
And this seems, like some problem, in the pathway, that contains `cyrillic symbols`.

**Comment by sdottaka** [comment]
Thank you for the information.

I found that the crash only occurred under the Windows XP SP3 environment.

I fixed the FreeImage library with the following commit so that it wouldn't crash.

https://github.com/WinMerge/freeimage/commit/52117fb2aa29c362860739e998572317f9fbd34d

The rebuilt WinIMergeLib.dll can be downloaded from the following URL.

**Comment by username1565** [comment]
@sdottaka
After replace `WinMergePortable\2.16.12\WinMerge\WinIMerge\WinIMerge.dll`, (`1.0.27.0`) to (`1.0.29.0`) from new `zip`,
I do not see any crush on try to compare `gifs`.

Do not forget to add `this dll` in the `next release` (portable x86 zip),
also you can test and maybe fix the `pathways`,
and make `Portable WinMerge` independent from `notepad.exe` in `%windir%\WINDOWS\system32`-folder,
and independent from `Documents and settings`-folder too, as I said earlier.

Thanks.

**Comment by sdottaka** [comment]
In commit https://github.com/WinMerge/winmerge/commit/d9a6b5d8a72c282f5a04ae2ea960535a0ad1ac0f, I allowed environment variables in the path of the external editor and set the initial value of the external editor to %windir%\NOTEPAD.EXE.

In your environment, the path of the external editor is already registered in the registry as C:\Windows\NOTEPAD.exe, so in the next version, set the environment variable to this path as follows.

![image](https://user-images.githubusercontent.com/98126/119153864-93a23100-ba8c-11eb-8ddc-99ba19eacc4c.png)

For the My Document folder, WinMerge already gets the path to that folder using the Win32 API, so it should be portable.
