### ISSUE TITLE
Up/Down keys don't work as expected in editor

### ISSUE THREAD

**Issue by hugmyndakassi** [WinMerge/winmerge#787]
Hi,

the <kbd>Up</kbd>/<kbd>Down</kbd> arrow keys don't work in the editor (they used to at some point, but I couldn't tell when this got changed). Instead they assume the functionality of the <kbd>Alt</kbd>+<kbd>Up</kbd> and <kbd>Alt</kbd>+<kbd>Down</kbd> shortcuts respectively (i.e. navigate to previous or next difference).

However, this makes it nigh impossible and very impractical to use the built-in editor. It leaves the mouse as the only option to navigate the editor window.

I'm using version 2.16.12.0 X64.

**Comment by sdottaka** [comment]
It is in merge mode.

To cancel the merge mode, uncheck File → Merge Mode menu item.

![image](https://user-images.githubusercontent.com/98126/118271593-730e3000-b4fc-11eb-95b2-bdf431ac1f89.png)

**Comment by hugmyndakassi** [comment]
Many thanks, I didn't realize.
