### ISSUE TITLE
Fast encoding switching.

### ISSUE THREAD

**Issue by lit-uriy** [WinMerge/winmerge#793]
Often you have to compare pairs of files, then in one encoding, then in another.
It is very inconvenient to go to the settings every time and change the encoding there.

I will be glad if you make the encoding switch in the main window.

For example, in the status bar, where the current file encoding is specified.

**Comment by sdottaka** [comment]
In WinMerge 2.16.10 and later, double-clicking on encoding in the status bar will bring up a Codepage dialog where you can specify the encoding to use for loading or saving.

It is not yet released, but in commit 9d8de80, only the double-clicked pane will reflect the selected encoding
![switch_encoding](https://user-images.githubusercontent.com/98126/149622957-d692067f-307c-4213-9069-839b2b6f98b6.gif)
.
