### ISSUE TITLE
Allow specifying "compare as" from the command line

### ISSUE THREAD

**Issue by Gitoffthelawn** [WinMerge/winmerge#794]
In the File menu, the user can perform "Recompare as" to specify how the comparison should be performed.

It would be very helpful to be able to specify this for the command line.  Specifically, I would like to compare some files that do not have an XML extension as XML.  Adding the extension to the new `Options` > `Editor` > `Syntax` UI only changes how the file is displayed in the editor, but does not affect how the files are compared.

Perhaps, in addition to command line support, the user could specify how to compare files with certain extensions.

**Comment by sdottaka** [comment]
In version 2.16.14, the built-in XML plugin has been removed and a PrettifyXML plugin that uses the tidy-html5 command has been added.

This plugin can be specified on the command line as follows

~~~
"C:\Program Files\WinMerge\WinMergeU.exe" file1 file2 /unpacker PrettifyXML
~~~

The type of syntax highlighting can be specified as follows.

~~~
"C:\Program Files\WinMerge\WinMergeU.exe" file1 file2 /FileExt XML
~~~

In addition, the window types (Table, Binary, Image) that can be specified in the Compare As menu item can be specified as follows

"C:\Program Files\WinMerge\WinMergeU.exe" file1 file2 /t table /table-delimiter ,
"C:\Program Files\WinMerge\WinMergeU.exe" file1 file2 /t binary
"C:\Program Files\WinMerge\WinMergeU.exe" file1 file2 /t image

**Comment by Gitoffthelawn** [comment]
@sdottaka Thank you Takashi.  I'll experiment with your suggestions.
