### ISSUE TITLE
Long lines with small changes show most of line as changed

### ISSUE THREAD

**Issue by Gitoffthelawn** [WinMerge/winmerge#795]
I often want to compare files >100KB with no line breaks (no CR or LF).  Even changing just a few characters in such a file causes WinMerge to think large swaths of the file have been changed, when only a few characters have been changed.  The issue seems to be that WinMerge does not recognize that characters between two changes are all identical when there are no line breaks.

Test version: WinMerge v2.16.12.0 x64

**Comment by sdottaka** [comment]
Sorry for the slow response.

In order to speed up the response, WinMerge gives up calculating differences within a line if the line is very long, and considers the entire line to be different.

If you are comparing XML or JSON files with long lines, you can use the PrettifyXML or PretifyJSON plug-ins to format the contents of the file to make a single line into multiple lines.

**Comment by Gitoffthelawn** [comment]
> Sorry for the slow response.

No problem. :)

> In order to speed up the response, WinMerge gives up calculating differences within a line if the line is very long, and considers the entire line to be different.

Hmmm... could this value be exposed so the user can modify it via the setting UI or the `ini` file?

> If you are comparing XML or JSON files with long lines, you can use the PrettifyXML or PretifyJSON plug-ins to format the contents of the file to make a single line into multiple lines.

I need to experiment with those plugins some more.  I *very* often have the need to compare large blocks of text that are almost-XML or almost-JSON but don't quite conform to those standards.  This is sometimes because they are pre-processed subsets of XML or JSON data that have chunks of the data removed by software that doesn't know about XML or JSON (it processes everything as byte strings).

**Comment by Konoakapen** [comment]
Is there any workaround for this issue? I often need to compare long lines and I'm reduced to doing pre- and post-processing of the code where I insert a newline every time there's a space, or something silly. It's time-consuming and messy.

A checkbox in the settings or even an INI edit would be amazing. WinMerge's response time is definitely not an issue for me but not being able to compare long lines is.
