### ISSUE TITLE
Substitution filters not working in WinMerge v2.16.12.0

### ISSUE THREAD

**Issue by Gitoffthelawn** [WinMerge/winmerge#796]
I tried substitution filters in WinMerge v2.16.12.0 x64 and could not get them to do anything.  They take a long time to process, so they act like they are doing something, but there was no visible change in the output in either pane.  To test, I simply tried changing all occurrences of `a` to `test`.  I also tried a regex substitution of changing `,` (a comma) to `,\r\n`, and that also didn't work.

See also: Problems with Substitution Filters #790 (I saw that issue report after writing this one, but it sounds like that issue is related, but may not be identical.  I want to carefully read the reply from @sdottaka a couple more times and perform more testing.)

**Comment by sdottaka** [comment]
Could you tell me the contents of the compared files?

I compared files with the following content, and the Substitution Filters seem to work as they should.

![image](https://user-images.githubusercontent.com/98126/119145496-a9abf380-ba84-11eb-9e21-d7dfddf7b6a4.png)

**Comment by Gitoffthelawn** [comment]
@sdottaka What your screenshot shows is exactly what I was expecting.  Besides creating the filter, and clicking "Enable" in the `Filters` dialog box, did you have to do anything else special to get it to work?

Regarding the contents of the files I compared... ooh, um, that was 4 days ago, and I've probably used WinMerge at least 200 times since then. :)  I don't remember which files I was comparing, but I know I was comparing scores of modified JSON files (not quite JSON syntax, but very close).  Most of those files did not have any CR or LF characters; perhaps that's a helpful clue.

**Comment by sdottaka** [comment]
> did you have to do anything else special to get it to work?

The Substitution filters settings I have made are only those shown in the screenshot above.

**Comment by allwi** [comment]
I have the same issue: the filter doesn't seem to work.
I use a regex as shown below
![image](https://user-images.githubusercontent.com/22267500/143377749-1405542c-ab3d-44e9-ad6c-5e69d81c7ab1.png)
The regex should remove all descriptions from an XML document.
But when I compare two XML files, I get
![image](https://user-images.githubusercontent.com/22267500/143378204-b803ee9e-4d99-4053-a6bc-e48e77b00baa.png)
I would expect that the line <SomethingElse> is highlighted as a difference but that the <Param1> line is not marked,

**Comment by sdottaka** [comment]
Unfortunately, there is a limitation in the substitution filters that are applied after the diff calculation.

I hope to fix this eventually, but it is unlikely to happen soon.

Instead, try using the PrediffLineFilter.sct plugin, which provides similar functionality.

This plugin is applied before the diff calculation, so you will get the expected results.

![image](https://user-images.githubusercontent.com/98126/143432376-24326baf-906a-4317-8131-10daa3bf294a.png)
![image](https://user-images.githubusercontent.com/98126/143432456-83c40611-41e0-4dc5-9a0d-d77e463189b6.png)
![image](https://user-images.githubusercontent.com/98126/143432552-371afc7d-b16f-47ca-86b7-383ed8e58b02.png)
![image](https://user-images.githubusercontent.com/98126/143432786-5baa810d-dc84-4533-b1c4-7376e9da16fd.png)
![image](https://user-images.githubusercontent.com/98126/143431650-7cebafb6-e203-4ca1-b6fe-0efd2a9dca88.png)

**Comment by Gitoffthelawn** [comment]
@sdottaka I was never able to get the PrediffLineFilter plugin to work... the settings page never appears.

So I was experimenting with substitution filters again, and now have a pair of files that demonstrate very odd behaviour.  The substitutions are never displayed in the output, but for a portion of the files, WinMerge correctly identifies that the substituted changes are to be ignored.  Yet partway through the files, the substitution filter simply stops having any effect.

**Comment by sdottaka** [comment]
This issue was resolved with improvement in PR #2032.
