### ISSUE TITLE
FeatureRequest - Ignoring options - lack in "button menu"

### ISSUE THREAD

**Issue by mlipok** [WinMerge/winmerge#804]
in menu:
![image](https://user-images.githubusercontent.com/11089482/119627340-621ec200-be0c-11eb-9f33-549ad7d47c58.png)

there are only 3+3 options for ignoring

in configuration:
![image](https://user-images.githubusercontent.com/11089482/119627375-6b0f9380-be0c-11eb-91c9-577eddcbd596.png)

there are 3+5 options for ignoring.

Please add the 2 missing options to the menu. I mean the one marked with red felt-tip pen (on the last screenshot).

**Comment by mlipok** [comment]
Please also consider to add hint/tip, to this button
![image](https://user-images.githubusercontent.com/11089482/119627868-dd807380-be0c-11eb-9c9e-05397f747064.png)

something like "Comparition options"

**Comment by sdottaka** [comment]
Commit 5332924546aa180d4304360ac2b9146aa9d07226 added those menu items.

For tooltips, the tooltip is a description of the icon rather than the drop-down menu. I didn't want to change the translation either, so I left it as it was.
