### ISSUE TITLE
Basic Parser seems to not work properly

### ISSUE THREAD

**Issue by Mo-Gul** [WinMerge/winmerge#816]
A lot of keywords defined in [basic.cpp](https://github.com/WinMerge/winmerge/blob/master/Externals/crystaledit/editlib/parsers/basic.cpp) don't seem to be highlighted, see as examples the yellow marked works in the screenshot.

![Basic](https://user-images.githubusercontent.com/17992976/121147472-2ee32680-c841-11eb-9763-235ef4c51534.png)

**Comment by sdottaka** [comment]
Which version are you using?
This issue should have been fixed in the latest release 2.16.12.

**Comment by Mo-Gul** [comment]
Sorry, my fault. I *did* update to the current version only on one of my machines and of course stumbled upon this problem on the other. With the above stated version it works perfectly fine.
