### ISSUE TITLE
Incorrect comparison

### ISSUE THREAD

**Issue by janniesoftycomp** [WinMerge/winmerge#834]
Winmerge is not comparing correctly. 
I've noticed this over the past month or two.
I've checked on TotalCommander comparison, which seems to be doing this correctly - please see attachments.
I've also included the 2 files being compared.

![Winmerge version](https://user-images.githubusercontent.com/37791553/122723995-d3b72800-d273-11eb-94ac-a6b50e72d6b9.png)
![Winmerge settings](https://user-images.githubusercontent.com/37791553/122724054-dca7f980-d273-11eb-81c3-6683bf7552de.png)
![Totalcommand correct compare](https://user-images.githubusercontent.com/37791553/122724188-fcd7b880-d273-11eb-959a-7e7c35dbdd58.png)
![Winmerge error compare](https://user-images.githubusercontent.com/37791553/122724372-25f84900-d274-11eb-8fa8-6cf9a58c572c.png)
[Data.txt](https://github.com/WinMerge/winimerge/files/6684903/Data.txt)
[IMPL_P_SUSPEND_ABANDONED_INCOMPLETES.txt](https://github.com/WinMerge/winimerge/files/6684904/IMPL_P_SUSPEND_ABANDONED_INCOMPLETES.txt)

**Comment by sdottaka** [comment]
Thank you for the report. This bug has been fixed in commit 6be8fc3569f4698f22e0bbaf6af27cee8b060072.

**Comment by janniesoftycomp** [comment]
Wow! That’s an amazing response time.

Good job, and thanks.



Regards,
Jannie Engelbrecht
Software Developer
Office: 012 664 2745
Mobile: 083 3939 207

***@***.***D766A2.3A66F500]
Website: www.softycomp.co.za<http://www.softycomp.co.za/>
For more info follow us on ***@***.***D766A2.3A539410] <https://www.linkedin.com/company/softy-comp> ***@***.***D766A2.3A539410] <https://www.facebook.com/SoftyCompPtyLtd/>
