### ISSUE TITLE
WinMerge doesn't build under Visual Studio 16.10.2

### ISSUE THREAD

**Issue by OpenShooter** [WinMerge/winmerge#841]
Using the WinMerge master downloaded 2021-6-18, attempting to build solution ALLvs2019 Debug Win32 fails with these errors:

`Severity	Code	Description	Project	File	Line	Suppression State`
**Error	C1083**	`Cannot open include file: '../../Externals/sevenzip/CPP/Common/Common.h': No such file or directory	Merge7z	C:\Miscellaneous\WinMerge\winmerge-master\ArchiveSupport\Merge7z\stdafx.h	10	`
**Error	MSB3073**	`The command "if exist dlldata.c goto :END`
`echo エラー: MIDL は、主要なプロジェクトにインターフェイスを少なくとも 1 つ持っていない限り DLLDATA.C を生成しません。`
`Exit 1`
`:END`

`:VCEnd" exited with code 1.	WinMerge32BitPluginProxyPS	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	145	`
**Error	C1001**	`Internal compiler error.	FolderCompare	C:\Miscellaneous\WinMerge\winmerge-master\Externals\boost\boost\operators.hpp	154`

There is no file `Common.h`, but there is a file `operators.hpp` in the specified location. As the second is a compiler error, it may be a VS issue.

Win32 rebuild also has 81+ warnings. I can supply a file with these for both Debug and Release builds, but I don't know how to attach it to this message.

Building Release Win32 gives only the C1083 error (`Common.h` missing). Debug and Release x64 builds also have only the same error, but many additional warnings, mostly conversions from `long long` to `long` possibly losing data.

**Comment by sdottaka** [comment]
It looks like git submodules haven't been downloaded.

If you downloaded the WinMerge source code with git clone command, please execute the following command in the WinMerge source code folder.

~~~
git submodule init
git submodule update
DownloadDeps
~~~

The following compressed file contains all the sources.

https://github.com/WinMerge/winmerge/releases/download/v2.16.13/winmerge-2.16.13-full-src.7z

**Comment by OpenShooter** [comment]
Thanks again for your help. FYI, I downloaded the source code originally from the zip file, not using git, so the file sent with DOWNLOAD ZIP is incomplete.

This time I used the compressed file v2.16.13 you referenced above, decompressed it using 7zip, and attempted a Debug Win32 build using VS2019 and the solution ALLvs2019.

This gives 11 errors:
`Severity	Code	Description	Project	File	Line	Suppression State`
**Error	C1001**	`Internal compiler error.	FolderCompare	C:\Miscellaneous\WinMerge\2.16.13 sources\Externals\boost\boost\operators.hpp	154`	
**Error	MSB3191**	`Unable to create directory "C:\Miscellaneous\WinMerge\2.16.13 sources\Build\frhed\Win32\Debug\Languages\". Cannot create "C:\Miscellaneous\WinMerge\2.16.13 sources\Build\frhed\Win32\Debug\Languages" because a file or directory with the same name already exists.	frhed (Externals\Frhed\frhed)	C:\Miscellaneous\WinMerge\2.16.13 sources\Externals\frhed\FRHED\Frhed.targets	162	`
**Error	MSB3073**	`The command "PreLink.bat "C:\Miscellaneous\WinMerge\2.16.13 sources\BuildTmp\heksedit\Win32\Debug\" "C:\Miscellaneous\WinMerge\2.16.13 sources\Build\frhed\Win32\Debug\hekseditU.dll"
:VCEnd" exited with code -1.	heksedit	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	150	`
**Error	LNK1149**	`output filename matches input filename 'C:\Miscellaneous\WinMerge\2.16.13'	heksedit	C:\Miscellaneous\WinMerge\2.16.13 sources\Externals\frhed\FRHED\LINK	1`	
**Error	RC1107**	`invalid usage; use RC /? for Help	heksedit	C:\Miscellaneous\WinMerge\2.16.13 sources\Externals\frhed\FRHED\EXEC	1`	
**Error	LNK1342**	`failed to save a backup copy of the binary file to be edited	heksedit	C:\Miscellaneous\WinMerge\2.16.13 sources\Build\frhed\Win32\Debug\Languages\heksedit.lng	1`	
**Error	MSB8011**	`Failed to register output. Please try enabling Per-user Redirection or register the component from a command prompt with elevated permissions.	WinMerge32BitPluginProxyPS	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	2301	`
**Error	LNK1104**	`cannot open file 'WinIMergeLib.lib'	cidiff	C:\Miscellaneous\WinMerge\2.16.13 sources\Externals\winimerge\src\LINK	1	`
**Error	LNK1104**	`cannot open file 'WinIMergeLib.lib'	WinIMerge (Externals\WinIMerge\WinIMerge)	C:\Miscellaneous\WinMerge\2.16.13 sources\Externals\winimerge\src\LINK	1`
**Error	LNK1104**	`cannot open file 'FreeImageLibd.lib'	WinIMergeLib	C:\Miscellaneous\WinMerge\2.16.13 sources\Externals\winimerge\src\LINK	1	`
**Error	MSB6006**	`"link.exe" exited with code 1104.	cidiff	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	1075`	

It looks like `boost` isn't building properly due to a compiler error (I will submit this to MS), and the `frhed` build commands have some errors. There are also 859 warnings, including many the warn that common directories are being used, e g:
`warning MSB8028: The intermediate directory (Debug\) contains files shared from another project (WinMerge32BitPluginProxy.vcxproj).  This can lead to incorrect clean and rebuild behavior.`
I can say from experience that this warning should be heeded.

**Comment by sdottaka** [comment]
Most of the above errors seem to occur when the folder name contains whitespace characters.
I was able to reproduce the Internal Compiler error with Win32 Debug build. It did not occur in x64 Debug build.

I will fix some warnings and errors when the folder name contains whitespace when I have time.

**Comment by sdottaka** [comment]
Some commits should fix this issue.
