### ISSUE TITLE
Project: WinIMergeLib WinIMergeLib.vcxproj.filters warning winmerge\externals\winimerge\.git\fetch_head" does not exist

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [WinMerge/winmerge#852]
This warning occurs, because of the line `<CustomBuild Include="..\.git\FETCH_HEAD" />` in WinIMergeLib.vcxproj.filters. The path seems not to be correct, maybe it must be `..\..\..\.git\FETCH_HEAD`, maybe the line is no more necessary?

**Comment by sdottaka** [comment]
This issue has been fixed with the following commit. You're probably referring to a slightly older version of the source code

https://github.com/WinMerge/winimerge/commit/478cdb8b004f9783caed57b4c936579bc3cebf68

**Comment by Andreas-Schniertshauer** [comment]
Thanks, my fault forget to update submodules.
