### ISSUE TITLE
CString rangestr = (argc > 0) ? argv[0] : GetColumnRangeString();

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [WinMerge/winmerge#853]
`
	wchar_t **argv = CommandLineToArgvW(m_bstrArguments.m_str, &argc);
	CString rangestr = (argc > 0) ? argv[0] : GetColumnRangeString();
`
seems to be not correct, when m_bstrArguments.m_str is empty, argc  is 1 because it contains the path to the current executable file as first parameter and this is then used for the rangestr.
This code is used in IgnoreColumns, IgnoreFieldsComma and IgnoreFieldsTab.

**Comment by sdottaka** [comment]
Fixed by commit d6e9833
Thank you for the report!
