### ISSUE TITLE
x64: LINK : warning LNK4010: invalid subsystem version number 5.01; default subsystem version assumed

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [WinMerge/winmerge#855]
This warning occurs, because of Testing\FolderCompare project setting (Debug+Release): Linker\System\Minimal Required Version 5.01.
Must be 5.02 for x64 and 6.02 for ARM according to: https://docs.microsoft.com/en-us/cpp/build/reference/subsystem-specify-subsystem?view=msvc-160

See also frhed ARM and FolderCompare ARM

**Comment by sdottaka** [comment]
Fixed by commit a1eb447
Thank you for the report.
