### ISSUE TITLE
Updated Slovenian translation Winmerge v.2.16.13 

### ISSUE THREAD

**Issue by JadranR** [WinMerge/winmerge#858]
Updated Slovenian translation of Winmerge-2.16.13 per date 04.07.2021

Note: I’m late because I was on vacation, without the Internet. 

[Translated 4.7.2021.zip](https://github.com/WinMerge/winmerge/files/6759771/Translated.4.7.2021.zip)

Best Regards,
Jadran

**Comment by sdottaka** [comment]
Merged at commit a98b2b7
Thank you!

**Comment by JadranR** [comment]
Updated Slovenian translation of Winmerge-2.16.143 per date 25.07.2021

Note: Link on https://sourceforge.net/projects/winmerge/files/stable/2.16.14/winmerge-2.16.14-full-src.7z/download isn't download correct version WinMerge :-((((

[Translated 25.05.2021.zip](https://github.com/WinMerge/winmerge/files/6874472/Translated.25.05.2021.zip)

Best Regards,
Jadran

**Comment by sdottaka** [comment]
Applied in commit fdd6d08edc429e04af6d7893d40db186706eba60

> Note: Link on https://sourceforge.net/projects/winmerge/files/stable/2.16.14/winmerge-2.16.14-full-src.7z/download isn't download correct version WinMerge :-((((

winmerge.org hasn't been updated yet.

**Comment by JadranR** [comment]
Hi,

I send you now ZIP archive with updated Slovenian translation for WinMerge and ShellExtension, per Date 16.12.2021

Merry Christmas and Happy New Year 2022 .

Jadra
[Slovenian translation 20121216.zip](https://github.com/WinMerge/winmerge/files/7730230/Slovenian.translation.20121216.zip)
n

**Comment by sdottaka** [comment]
Thank you!

**Comment by JadranR** [comment]
Hi,
Please, include exe file for last versionWinMerge into Master.ZIP file because this way I know which is the latest version to translate or add somewhere separately on the website a separate latest version of the .EXE working file to download. 

Big thanks,
Jadran

**Comment by JadranR** [comment]
Hi,
I hope so that is this release Slovenian language file is correct (English.POT file have old Date (25.07.2021)????
I suggest you use the style: Version_Build_Date (Eg.: 2.16.16._912_20211216) .

I send attached updated translation. NOTE: The POT file date is suspiciously out of date. 
[20211217_Slovenian translation.zip](https://github.com/WinMerge/winmerge/files/7732314/20211217_Slovenian.translation.zip)

**Comment by sdottaka** [comment]
Master.Zip is the file that is downloaded when you click on the "Download ZIP" link in the attached image?

![image](https://user-images.githubusercontent.com/98126/146532361-0dff608f-ea42-4181-8b10-028fa2ff9a29.png)

If so, this file is automatically generated from the git repository by GitHub, so I can't include the EXE in this.

You can download the ZIP and installer containing the EXE generated from the latest source code from the following URL.

https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts

You can also move to this URL by clicking the button below. 

![image](https://user-images.githubusercontent.com/98126/146534056-13d8d402-da5e-400e-b3ac-93fd67cf7217.png)
![image](https://user-images.githubusercontent.com/98126/146533382-e1a6a2b0-65f2-4bb7-9549-673f95b4adbc.png)

This URL is also linked from winmerge.org.

![image](https://user-images.githubusercontent.com/98126/146533109-50ac223a-f007-4e49-90b5-b2734acba087.png)


> I send attached updated translation. NOTE: The POT file date is suspiciously out of date. 20211217_Slovenian translation.zip

As you point out, the translation is based on the old English.pot, so this cannot be adopted.

The previous ZIP file looked good. Did something go wrong with the previous ZIP file?

**Comment by JadranR** [comment]
Hi,

Big thanks for this e-mail :-)))

Be  healthly.

Jadran

V V pet., 17. dec. 2021 ob 12:01 je oseba Takashi Sawanaka <
***@***.***> napisala:

**Comment by JadranR** [comment]
Hi,

I send you Now updated Slovenian translation for WinMerge 2.16.17 X64, per date 
[Last Slovenian translation.zip](https://github.com/WinMerge/winmerge/files/7800715/Last.Slovenian.translation.zip)
03.01.2022 (see attached screenshot).
![sshot-01](https://user-images.githubusercontent.com/53031490/147906308-b9139e82-afa6-4c5e-adf7-6f9dbd1f2f74.jpg)


Best Regards,
Jadran

**Comment by sdottaka** [comment]
Thank you!

**Comment by JadranR** [comment]
Updated Slovenian translation, per Date 21.02.2022
[Slovenian.zip](https://github.com/WinMerge/winmerge/files/8112076/Slovenian.zip)

**Comment by JadranR** [comment]
Updated Slovenian translation for Frhed, per Date 21.02.2022.
[Frhed_si.zip](https://github.com/WinMerge/winmerge/files/8112079/Frhed_si.zip)

Best Regards,
Jadran

**Comment by sdottaka** [comment]
Thank you!
