### ISSUE TITLE
ALL.vs2019.sln cl : command line warning D9035: option 'Gm' has been deprecated and will be removed in a future release

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [WinMerge/winmerge#862]
This warning occurs in various projects because of /Gm (Enable Minimal Rebuild)  `<MinimalRebuild>true</MinimalRebuild>` switch that is deprecated since 11/12/2018 see https://docs.microsoft.com/en-us/cpp/build/reference/gm-enable-minimal-rebuild?view=msvc-160&viewFallbackFrom=vs-2017
It can be safely removed.

**Comment by sdottaka** [comment]
Fixed in commit 2bb8f3f and 1942441
Thank you for the report.
