### ISSUE TITLE
Option to (re)Enable `Confirm copy` dialog

### ISSUE THREAD

**Issue by Petewg** [WinMerge/winmerge#873]
`Confirm copy` dialog which opens  when a file copy is attempted, has a `Don't ask this question again` checkbox. 
What it does when checked is quite self-explanatory...
The "problem" is that once you check it (intentionally or not) there is no option to reset it back
and this inability can be proved a real problem at some particular case where you need enhanced
attention and explicit warning about what is going to be copied. An option to enable / disable this confirm dialog,
would greatly help to be avoided potential "accidents".

regards,
Pete

**Comment by sdottaka** [comment]
Pressing the Reset button in the General category of the Options dialog will re-enable the confirm copy dialog

![image](https://user-images.githubusercontent.com/98126/125444421-ec4024fe-8895-4396-8be1-abcb08ee54de.png)

**Comment by Petewg** [comment]
Yes, You're right! 
I had to have spotted the option to reset the visibility of the dialogs.
Please just let me explain (not seeking an excuse) why I failed to discover (and use) this `Reset` button: well, every time I open the `Options` dialog I get what is shown on the below image.
![opt](https://user-images.githubusercontent.com/3877210/125495092-6b087283-f8f7-4ce9-bc86-4ae1297a50bb.jpg)
That is, the left panel with the options tree is already scrolled down (I guess it is restoring the position of the last close) so you have to scroll up to reveal that `General` options item. I think, this is a little bit unusual UI behavior (I'm not sure that I had ever scrolled the panel up and had seen this option), but again this not an excuse for my oversight! Anyway I'm glad that what I asked, is already implemented. Many thanks for the hint and my apologies for the unnecessary "noise"!

regards,
Pete
