### ISSUE TITLE
Duplicate menu shortcut in translations

### ISSUE THREAD

**Issue by massic80** [WinMerge/winmerge#905]
Hi!
I just began translating WinMerge, since Italian translation is missing some labels.
I just noticed that also in the original English labels there is a conflict on the keyboard shortcuts on Image Compare (thise labels with the "&" which become underlined letters in the menu item):
<ins>V</ins>ertical Wipe
<ins>H</ins>orizontal Wipe
Flip <ins>V</ins>ertically
Flip <ins>H</ins>orizontally

Have the same H and V shortcut. Shall we replace them? :)
Meanwhile, could you please explain what the Wipe is? ;)

**Comment by sdottaka** [comment]
The conflict was fixed with commit 7c0977f

For the Wipe, please see the gif animation and Wikipedia articles below.

![905](https://user-images.githubusercontent.com/98126/127648841-6a30f786-94be-42d5-a4b4-8e2800922517.gif)

https://en.wikipedia.org/wiki/Wipe_(transition)

**Comment by massic80** [comment]
Veeery precious, thank you!

**Comment by massic80** [comment]
Sorry, got to reopen.
I also noticed
Rotate<ins>R</ins>ight
and
<ins>R</ins>ectangle select

**Comment by sdottaka** [comment]
Thank you for pointing it out again.

I fixed the conflict with commit b3e0a54.

**Comment by massic80** [comment]
I know that I'm off-topic, but I have a question for you: poEdit splits the strings (even the original strings) when it finds a \n:
"hello\ndear"
becomes
"hello\n"
"dear"

Is it a problem? Can I push my file this way or better if i reset the original situation?

**Comment by sdottaka** [comment]
I've never had a problem with a po file edited with poEdit, so I don't think it's necessary to reset to the original situation.
