### ISSUE TITLE
The translation file can't be opened

### ISSUE THREAD

**Issue by Felipefpl** [WinMerge/winmerge#909]
Poedit 3 reports the file as being corrupted or in a unknown format, the english .pot file is reported as "this isn't a valid .pot file" - this problem hardly happens with other .po/.pot files i have here.

**Comment by sdottaka** [comment]
I opened the latest po file I got with git and the po file contained in winmerge-2.16.14-full-src.7z, but I couldn't reproduce this issue.

Which file did you open?

![image](https://user-images.githubusercontent.com/98126/128648696-a41974c9-2bf2-4dfe-bfe4-631d8b87ee3e.png)

**Comment by Felipefpl** [comment]
brazilian.po

**Comment by sdottaka** [comment]
Would you please attach the file here?

**Comment by Felipefpl** [comment]
I downloaded the file from github, i also had a copy from when i translated the file for the last time, both didnt work.

[Brazilian.zip](https://github.com/WinMerge/winmerge/files/6954629/Brazilian.zip)

**Comment by sdottaka** [comment]
Thank you for attaching.
The attached Brazilian.po opened without any problems with poEdit in my environment.

![image](https://user-images.githubusercontent.com/98126/128710338-e8e79971-747b-4f69-a0b8-cf6c0da7e7d1.png)

When I tried emptying the contents of the English.pot file and clicking the "Update from POT file ..." menu item, the following error occurred. Perhaps your English.pot is corrupted?
Would you please attach English.pot as well?

![image](https://user-images.githubusercontent.com/98126/128710839-c2e63567-64b0-423a-a606-487c778c12f2.png)

**Comment by Felipefpl** [comment]
Downloaded it from winmerge.org

[English.zip](https://github.com/WinMerge/winmerge/files/6954789/English.zip)

**Comment by sdottaka** [comment]
Looking at the contents of the English.pot file, it was HTML. I think this is the cause.

![image](https://user-images.githubusercontent.com/98126/128720070-41297d8f-bbc5-46ae-a705-a8225667b10d.png)

Please save and use English.pot with the following URL

https://raw.githubusercontent.com/WinMerge/winmerge/master/Translations/WinMerge/English.pot

**Comment by Felipefpl** [comment]
It worked, thank you very much for taking care of this. Btw, can you check to see if there are other files with the problem? In winmerge.org i mean. ;)

**Comment by sdottaka** [comment]
?

Originally there was no problem with the po and pot files on github.com.

I renamed your attached english.pot to english.html and opened it, and it became the screen of github.

I think there was a problem with how to get the English.pot file.

To get the file from github.com, press the Raw button below and save what you see, or download the zip file.

![image](https://user-images.githubusercontent.com/98126/128786484-08009e1a-06ee-4dce-bb8b-3e887e05ecad.png)

**Comment by Felipefpl** [comment]
> To get the file from github.com, press the Raw button below and save what you see, or download the zip file.

Strange, i also did that before you fixed the file and even so i got the error msg saying that the .pot file was a bad one. Anyway, it's fixed so i'm satisfied. :)
