### ISSUE TITLE
Unicode SMP chars misrendered after performing a find

### ISSUE THREAD

**Issue by danny0838** [WinMerge/winmerge#914]
Steps to reproduce:

1. Prepare files and start a comparison. Chars seems correctly rendered:
   file1.txt: `䒜𧀬123𠀀𠀀456`
   file2.txt: `䒜𧀬123𠀁𠀁456`
   ![2021-08-13 17_26_06-WinMerge -  file1 txt - file2 txt](https://user-images.githubusercontent.com/531417/129336803-c5d85c09-6ceb-4919-9e28-ba9e1985d756.png)

2. Perform a find:
   ![2021-08-13 17_26_28-Find](https://user-images.githubusercontent.com/531417/129336808-67bd9501-3b37-4d3a-a049-ccd63f67eb27.png)

3. Now chars are no more rendered correctly:
   ![2021-08-13 17_26_40-WinMerge -  file1 txt - file2 txt](https://user-images.githubusercontent.com/531417/129336815-8d94a9af-e0cc-47d6-8565-e5805f4c47ed.png)

Refreshing with F5 or Ctrl+F5 doesn't fix. Restarting of WinMerge is required to make it render well again.

Note: Installing a font (e.g. [HanaMin](http://fonts.jp/hanazono/)) may be required to get related Ext-B chars render correctly.

---
Tested on WinMerge 2.16.14.0 X64 on Windows 7 SP1.

**Comment by sdottaka** [comment]
Fixed in 40d70ca

Thank you for the report.

You can avoid this problem by unchecking the `Regular expression` checkbox.
