### ISSUE TITLE
Put the diff patch to the clipboard rather than to files

### ISSUE THREAD

**Issue by halmai** [WinMerge/winmerge#923]
I would like to get the generated patches on the clipboard in order to paste them into emails, slack, etc. 

Now I can save it only into a file that I need to attach to the mail or the slack message but otherwise, I never need it in the future. I wouldn't like to contaminate my file system with these files, thus such a tool would be useful. 

Saving the diff into a file is also useful, I just would like to have an extra option.

Thanks.

**Comment by sdottaka** [comment]
With commit xxx, a "Copy To Clipboard" checkbox has been added to the Patch Generator dialog.
After checking this checkbox, click the OK button to copy the contents of the patch to the clipboard.

![image](https://user-images.githubusercontent.com/98126/142762436-3c884088-4974-4c09-81f3-8084894873e4.png)
