### ISSUE TITLE
Replace slow

### ISSUE THREAD

**Issue by Btimes2** [WinMerge/winmerge#940]
Replace is slow on Windows 10, WinMerge 2.14.6.
For example, when I compared two texts of 18.000 words, each word in different rows. 
The older version of the file used a slightly different spelling in many thousands of rows. I only noticed that after loading it in WinMerge, so I tried to replace the old spelling with the new one in WinMerge, to compare the actual content and not the spelling. 

Replacing one word in 18.000 rows takes about 1 second in most text editors on my computer, but for WinMerge it took a full minute. 

Could it be that WinMerge tries to compare the texts each time any change occures, including every steps of a replace all command? If so, then this could be optimized.

**Comment by sdottaka** [comment]
Fixes to commit fed6672, 7a7050e, 593cbbb, and f73ddf7 allow replacement operations that used to take about 20 seconds to complete to be completed in less than a second.
