### ISSUE TITLE
Make "Do not close this box" checkbox in search window On by default

### ISSUE THREAD

**Issue by Btimes2** [WinMerge/winmerge#941]
I tried to use WinMerge text search for many times when I noticed that there is a "Do not close this box" checkbox in the search window.

While this option is very useful, it is also uncommon, and I think most common users just like me will not think of it, one can only think that the program is bad to close the search window each time it finds a new occurence. 

Please make this checkbox on by default. That way, beginners get the behavior they expect based on other text editors, while advanced users can get the behavior they want just by one single click.

**Comment by sdottaka** [comment]
Fixed with commit 115ec70

Thank you for the report.
