### ISSUE TITLE
Calling WinMerge from Windows context menu: how WinMerge determines which of the selected files will be displayed on the left pane?

### ISSUE THREAD

**Issue by annazolkieve** [WinMerge/winmerge#950]
1. Calling WinMerge from Windows context menu: how exactly WinMerge determines which of the selected files will be displayed on the left pane?
2. For files named before.txt and after.txt: how to select them in a such way that WinMerge will show before.txt on the left pane? If it is impossible, then what is the sorting algorithm (of any) Windows is using when supplying arguments to WinMerge?
3. In which order file names before.txt and after.txt are passed to WinMerge?
4. Does WinMerge always open the 1st filename on the left pane?

**Comment by sdottaka** [comment]
WinMerge accepts the order of the paths passed from Explorer as is and does not control the order.

It's not intuitive, but to place the 'before.txt' file on the left, right-click on it at the end, as shown below.

![950](https://user-images.githubusercontent.com/98126/131930909-75dbf67a-f7ce-46e0-b4c6-08f5efa6a42d.gif)
