### ISSUE TITLE
Reloading a file that was changed by another application does not preserve column widths

### ISSUE THREAD

**Issue by brianberns** [WinMerge/winmerge#951]
Comparing two .tsv files in table mode (version 2.16.14.0 X64). When one of the .tsv files is modified externally, WinMerge will reload it, but column widths are reset. Would be much more usable if the columns widths were preserved during a reload. (Note: A manual F5 refresh does preserve columns widths. I'm just suggesting that reload should work the same way.)

P.S. I love WinMerge! Great program.

**Comment by sdottaka** [comment]
Fixed with commit 6da109b

This behavior may change in the future.

This is because I have not yet decided whether to keep all column widths on reload or only the widths of manually modified columns on reload.

Commit 6da109b is the former behavior.

**Comment by brianberns** [comment]
Thank you! Either of those behaviors would be fine with me.
