### ISSUE TITLE
3-Way File Merge: No Keyboard / hot keys available for Merging from Left Pane to right pane and vice versa

### ISSUE THREAD

**Issue by rxa1031** [WinMerge/winmerge#957]
Hello,

3-Way File Merge: No Keyboard / hot keys available for Merging from Left Pane to right pane and vice versa

Although there are three panes, user is only able to copy between the adjacent panes.

Also when the Left-most pane is selected and user presses ALT+RIGHT, and then CTRL+Z the Middle pane becomes selected.

I am comparing File 1, File 2, and File 3. File 2 is displayed in middle pane. I have to manually copy and past changes that I want to move from File 1 to File 3 or vice versa.

Please help with Hot Keys / Shortcut keys for the same.

Thanks,
Rajeev

**Comment by sdottaka** [comment]
Unfortunately, there is no menu item or shortcut key for that function in WinMerge right now.

**Comment by sdottaka** [comment]
commit 207457b3b2ee051bb6c71cbf1371aa80f8553660 now allows you to copy from left to right and vice versa.

It is not yet assigned to a shortcut key, so to copy from left to right using only the keyboard, you need to press Alt+M, D, L, and R in that order.

![image](https://user-images.githubusercontent.com/98126/147253880-295a201d-32b9-4db1-a70e-b66bff940e0c.png)
![image](https://user-images.githubusercontent.com/98126/147254056-46f71096-c093-42fa-ade4-300e5404218d.png)
