### ISSUE TITLE
When moving in the scroll pane, the selected position is incorrect

### ISSUE THREAD

**Issue by project-flower** [WinMerge/winmerge#970]
1. Click anywhere in the left pane and hold down the Shift key.
2. Click the location pane and scroll to a position where the clicked location disappears.
3. I shouldn't have selected the right pane, but the strange part is selected.

Also, if you move with the scroll pane while selected in the left pane, the selected part will be canceled.

[WinMerge.txt](https://github.com/WinMerge/winmerge/files/7154914/WinMerge.txt)

**Comment by sdottaka** [comment]
Fixed with commit 70d2ea7

Thank you for the report.

Note: If you want to select text in the left pane, hold down the Shift key and click on the left bar of the location pane.
If you want to select text in the right pane, Shift-click on the right bar of the location pane.
