### ISSUE TITLE
Plugin unpacked file extension problem (get_PluginUnpackedFileExtension)

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [WinMerge/winmerge#983]
WinMerge 2.16.14 and 2.16.15: I am using the get_PluginUnpackedFileExtension and return .yaml when comparing zip files that contain xml files, the plugin does a xml to yaml transformation, the fileDst name in the UnpackFile function is _WM886C.tmp.yaml, and the file is written correctly to the Temp\WinMerge folder. In the yaml I use '#' as comments and I want to use the WinMerge option 'Ignore comment differences'  and 'Complete unhighlight the ignored differences'. For this to work I added to the WinMerge\Edit\Options\Editor\Sysntax\Shell ;yaml.
But this does not work, may be because in the comparison window the xml files names are shown at the top.
Thanks for the help.

**Comment by Andreas-Schniertshauer** [comment]
It was fixed here https://github.com/WinMerge/winmerge/issues/820, but did not work in all cases.
I found that pressing F5 when in the comparison window it works. but not when the comparison window is opened initially, because in this case in MergeDoc(354) in function CMergeDoc::Rescan ```GetView(0, 0)->m_CurSourceDef->type != 0```  is false and m_filePaths is used that has the xml extension.

**Comment by sdottaka** [comment]
Fixed in commit 89c7a86

Thank you for the report.

**Comment by Andreas-Schniertshauer** [comment]
Now it works when the comparison window is opened initially, but when changing the ```Edit\Options\Ignore comment differences``` from OFF to ON while the comparison window is open it does not work, pressing F5 or Ctrl-F5 does not help. When changing the ```Edit\Options\Ignore comment differences``` from ON to OFF while the comparison window is open it works.

**Comment by sdottaka** [comment]
Oh! Thank you for reporting again.
I've fixed the problem with commit acbbd15.
