### ISSUE TITLE
Linebreak, 0d0a, as a last character is not ignored as a difference.

### ISSUE THREAD

**Issue by PicayuneOne** [WinMerge/winmerge#989]
If one file has a final linebreak and another does not, it always gets flagged as a difference even if "Ignore Whitespace" and "Ignore Blank Lines" are chosen.

**Comment by sdottaka** [comment]
Duplicate of #203

**Comment by sdottaka** [comment]
PR #2573 allows you to ignore differences where only one of the files does not have a trailing newline.
