### ISSUE TITLE
Cannot resize last column with UI

### ISSUE THREAD

**Issue by Dani21** [WinMerge/winmerge#998]
When files are compared in table mode and you're using word wrap, it makes it incredibly useful to be able to resize columns and still see all the data. For that reason, resizing the last column is just as useful as resizing any other column (and appears to be the only column that behavior isn't working for).

It doesn't appear that there's an option to do so as my mouse cursor never changes its icon to the horizontal "resizer" at the end of the last column. There doesn't appear to be a way to resize every column to the same width either (which would let me work around the issue) or right click the column to resize it. The only workaround appears to be to hit the tab key in the last column to cause more to appear, and then resizing the last column.

**Comment by sdottaka** [comment]
Currently, WinMerge allows you to change the size of the last column, as shown below. Is there a problem that prevents you from resizing the last column only when comparing certain files?

![998](https://user-images.githubusercontent.com/98126/136638999-fe413ff9-367f-42cb-9960-ff0d7b2507fd.gif)

**Comment by sdottaka** [comment]
Thank you for your explanation. Now I can reproduce this problem.

**Comment by sdottaka** [comment]
Fixed with commit 7a9a056

Thank you for the report.
