### ISSUE TITLE
Pinning first row of file

### ISSUE THREAD

**Issue by Dani21** [WinMerge/winmerge#999]
When comparing files in table mode, I'm requesting a feature that can be turned on where instead of showing A, B, C, etc as the text of the pinned/frozen/hovering row, the first row can be the first row of data so that it always shows (ie. column headers). This could be an option named "Freeze first N rows" and "Freeze first N columns" if you want to be the most flexible, or to keep it simple "Always show data header line". I would've used this feature today if it was available or I could find it (ie. I'm not just thinking of ideas and posting them here).

**Comment by sdottaka** [comment]
Slightly different from your request, but I have added the ability to display the first line as headers.
![image](https://user-images.githubusercontent.com/98126/158491985-8735636b-6088-4641-8d55-74ee875cbd87.png)

**Comment by endo64** [comment]
I'm using v2.16.32 and I can't find this option anywhere, and nothing in the documentation. Is it removed?

**Comment by sdottaka** [comment]
> I'm using v2.16.32 and I can't find this option anywhere, and nothing in the documentation. Is it removed?

The "Use First Line as Headers" option is available in WinMerge 2.16.32 as well.

Open the CSV or TSV file in Table mode, then right-click the top margin of the editor pane (just below the header bar, where the row numbers are displayed). The context menu will include "Use First Line as Headers".

If you don't see the menu, you may have multiple versions of WinMerge installed on the same computer. Please check the version of the running WinMerge via Help → About.

**Comment by endo64** [comment]
Thank you for your response.
I use table mode, disabled/enabled all plugins, reloaded/restarted, unfortunately, I still cannot see it.


<img width="395" height="208" alt="Image" src="https://github.com/user-attachments/assets/51851d02-5077-4ba4-951c-61c7ddae15f8" />

<img width="551" height="417" alt="Image" src="https://github.com/user-attachments/assets/fa3812e9-3d79-4e1a-a2ec-904220853ee0" />

<img width="869" height="360" alt="Image" src="https://github.com/user-attachments/assets/d4b4e8be-1201-4a9f-91c9-f0a2452e34db" />

**Comment by sdottaka** [comment]
Thanks for checking.

Looking at the screenshot, it seems that the Top Margin is currently hidden. Please enable it from View → View Top Margin.

After enabling it, right-click the Top Margin area of the editor pane . You should then see the "Use First Line as Headers" option in the context menu.

<img width="362" height="574" alt="Image" src="https://github.com/user-attachments/assets/d4f505c0-e55a-422e-aa37-ec3abbbf39a4" />

**Comment by endo64** [comment]
Thank you for your time to help me!
I confirm that I'm able to access "Use First Line as Headers" menu when I enable Top Margin.
